/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_ZULSJE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZULSJE(PROPERTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_892O3Q INT DEFAULT 0;
    DECLARE MYSQL_VAR_RZCG27 INT DEFAULT 0;
    DECLARE MYSQL_VAR_L5XXHH INT DEFAULT 0;
    DECLARE MYSQL_VAR_LSTHDP INT DEFAULT 0;
    DECLARE MYSQL_VAR_N3Z5PU INT DEFAULT 0;
    DECLARE MYSQL_VAR_8CA2JW INT DEFAULT 0;
    DECLARE MYSQL_VAR_X7HLT8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JBTGHE INT DEFAULT 0;

    SELECT COALESCE(LIST_PRICE, 0), COALESCE(AREA_SQFT, 0), COALESCE(BEDROOMS, 0), COALESCE(BATHROOMS, 0), COALESCE(YEAR_BUILT, 2000)
    INTO MYSQL_VAR_892O3Q, MYSQL_VAR_RZCG27, MYSQL_VAR_L5XXHH, MYSQL_VAR_LSTHDP, MYSQL_VAR_N3Z5PU
    FROM REAL_ESTATE_PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SET MYSQL_VAR_8CA2JW = YEAR(CURDATE()) - MYSQL_VAR_N3Z5PU;
    SET MYSQL_VAR_X7HLT8 = MYSQL_VAR_892O3Q / NULLIF(MYSQL_VAR_RZCG27, 0);

    SET MYSQL_VAR_JBTGHE = MYSQL_VAR_892O3Q;

    IF MYSQL_VAR_8CA2JW > 30 THEN
        SET MYSQL_VAR_JBTGHE = MYSQL_VAR_JBTGHE - (MYSQL_VAR_JBTGHE * 10 / 100);
    END IF;

    SET MYSQL_VAR_JBTGHE = MYSQL_VAR_JBTGHE + (MYSQL_VAR_L5XXHH * 5000) + (MYSQL_VAR_LSTHDP * 3000);

    RETURN CAST(MYSQL_VAR_JBTGHE AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_41B7HC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_41B7HC(ACCOUNT_ID_PARAM INT, MIN_AMOUNT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EOV6ZK INT DEFAULT 0;
    DECLARE MYSQL_VAR_46RDFZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_UGV6FH INT DEFAULT 0;
    DECLARE MYSQL_VAR_U1LNJX INT DEFAULT 0;
    DECLARE MYSQL_VAR_NQ4YDM INT DEFAULT 0;

    SELECT COALESCE(SUM(AMOUNT), 0), COUNT(*)
    INTO MYSQL_VAR_46RDFZ, MYSQL_VAR_U1LNJX
    FROM TRANSACTIONS
    WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM
      AND TRANSACTION_TYPE = 'CREDIT'
      AND AMOUNT >= MIN_AMOUNT;

    SELECT COALESCE(SUM(AMOUNT), 0)
    INTO MYSQL_VAR_EOV6ZK
    FROM TRANSACTIONS
    WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM
      AND TRANSACTION_TYPE = 'DEBIT';

    SELECT BALANCE INTO MYSQL_VAR_NQ4YDM FROM ACCOUNTS WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM;

    SET MYSQL_VAR_UGV6FH = MYSQL_VAR_46RDFZ - MYSQL_VAR_EOV6ZK;

    RETURN COALESCE(MYSQL_VAR_NQ4YDM, 0) + MYSQL_VAR_UGV6FH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3EWCOM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3EWCOM(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LM8TRL INT DEFAULT 0;
    DECLARE MYSQL_VAR_WXKV68 INT DEFAULT 1;

    SELECT MYSQL_FUNC_ZULSJE(20)
    INTO MYSQL_VAR_LM8TRL, MYSQL_VAR_WXKV68
    FROM ORDERS O
    WHERE O.CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_WXKV68 <= 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_41B7HC(10, 11);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EERRQA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EERRQA(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V8XNB0 INT DEFAULT 0;

    SELECT CUSTOMER_ID
    INTO MYSQL_VAR_V8XNB0
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_V8XNB0 % 1000;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_B1MDMA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_B1MDMA(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DZ8OAW INT DEFAULT 0;
    DECLARE MYSQL_VAR_L80A2F INT DEFAULT 0;
    DECLARE MYSQL_VAR_JHUZJY INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_DZ8OAW
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_L80A2F
    FROM CUSTOMERS;

    IF MYSQL_VAR_L80A2F = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_JHUZJY = (MYSQL_VAR_DZ8OAW * 100) / MYSQL_VAR_L80A2F;

    RETURN MYSQL_VAR_JHUZJY;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BUFBMO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BUFBMO(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PI7MU8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_354KGX INT DEFAULT 0;
    DECLARE MYSQL_VAR_7IIPC4 INT DEFAULT 0;

    SELECT MYSQL_FUNC_B1MDMA('test_1_0')
    INTO MYSQL_VAR_PI7MU8
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(REFUND_AMOUNT), 0)
    INTO MYSQL_VAR_354KGX
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_7IIPC4 = MYSQL_FUNC_EERRQA(20);

    RETURN MYSQL_VAR_7IIPC4;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DM0UCA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DM0UCA(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5KOOK0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_AXODJC INT DEFAULT 0;

    SELECT MONTH(ORDER_DATE), YEAR(ORDER_DATE)
    INTO MYSQL_VAR_5KOOK0, MYSQL_VAR_AXODJC
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN (MYSQL_VAR_AXODJC * 12) + MYSQL_VAR_5KOOK0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_G6DEGX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_G6DEGX(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AQDH11 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MFEGWM INT DEFAULT 0;
    DECLARE MYSQL_VAR_HB2BFR DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_AQDH11
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(OI.QUANTITY), 0)
    INTO MYSQL_VAR_MFEGWM
    FROM ORDER_ITEMS OI
    JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
    WHERE OI.PRODUCT_ID = PRODUCT_ID_PARAM
    AND O.ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    IF MYSQL_VAR_MFEGWM = 0 THEN
        RETURN MYSQL_VAR_AQDH11;
    END IF;

    SET MYSQL_VAR_HB2BFR = MYSQL_VAR_AQDH11 / MYSQL_VAR_MFEGWM;

    RETURN FLOOR(MYSQL_VAR_HB2BFR);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GYRWLW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GYRWLW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PYIAN7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_WJ4AQ4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_A9YT2Y INT DEFAULT 0;
    DECLARE MYSQL_VAR_E8JT5J VARCHAR(20) DEFAULT 'BRONZE';
    DECLARE MYSQL_VAR_5SAM09 INT DEFAULT 1;
    DECLARE MYSQL_VAR_JKMGYJ INT DEFAULT 0;

    SELECT MYSQL_FUNC_DM0UCA(30)
    INTO MYSQL_VAR_WJ4AQ4, MYSQL_VAR_PYIAN7
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT MYSQL_FUNC_G6DEGX(10) INTO MYSQL_VAR_E8JT5J
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_5SAM09 = CASE MYSQL_VAR_E8JT5J
        WHEN 'PLATINUM' THEN 4
        WHEN 'GOLD' THEN 3
        WHEN 'SILVER' THEN 2
        ELSE 1
    END;

    IF MYSQL_VAR_WJ4AQ4 > 0 THEN
        SET MYSQL_VAR_A9YT2Y = MYSQL_VAR_PYIAN7 / MYSQL_VAR_WJ4AQ4;
        SET MYSQL_VAR_JKMGYJ = MYSQL_VAR_A9YT2Y * MYSQL_VAR_WJ4AQ4 * MYSQL_VAR_5SAM09;
    END IF;

    RETURN MYSQL_FUNC_BUFBMO(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P0ZIHI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P0ZIHI(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UKWO26 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(PRICE, 0)
    INTO MYSQL_VAR_UKWO26
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_UKWO26 * 0.3) / 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8VIS2N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8VIS2N(STORE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XG8FLF INT DEFAULT 0;
    DECLARE MYSQL_VAR_PIFH7D INT DEFAULT 0;
    DECLARE MYSQL_VAR_LXSCL8 INT DEFAULT 0;

    SELECT MYSQL_FUNC_GYRWLW(20) INTO MYSQL_VAR_XG8FLF
    FROM TRANSACTIONS
    WHERE STORE_ID = STORE_ID_PARAM
      AND TRANSACTION_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SELECT COUNT(*) INTO MYSQL_VAR_PIFH7D
    FROM RETAIL_RETURNS R
    JOIN TRANSACTIONS T ON R.TRANSACTION_ID = T.TRANSACTION_ID
    WHERE T.STORE_ID = STORE_ID_PARAM
      AND R.RETURN_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    IF MYSQL_VAR_XG8FLF = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_LXSCL8 = (MYSQL_VAR_PIFH7D * 100) / MYSQL_VAR_XG8FLF;

    RETURN MYSQL_FUNC_P0ZIHI(30);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KZHOS1(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9ZMQ49 INT DEFAULT 0;

    SELECT MYSQL_FUNC_3EWCOM(10)
    INTO MYSQL_VAR_9ZMQ49
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_FUNC_8VIS2N(30);
END//

DELIMITER ;