/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_DVE6U6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DVE6U6(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
RETURN SUPPLIER_ID_PARAM % 100;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EOWVPD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EOWVPD() RETURNS INT
BEGIN
RETURN MYSQL_FUNC_DVE6U6(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_38Q8EG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_38Q8EG(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_S897Z1 INT DEFAULT 40;
    DECLARE MYSQL_VAR_7FL77E INT DEFAULT 0;
    DECLARE MYSQL_VAR_JXDRA4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_M42I89 INT DEFAULT 0;
    DECLARE MYSQL_VAR_LF3TDB INT DEFAULT 0;

    SELECT COALESCE(SESSION_RATE, 40), COALESCE(SCHOLARSHIP_PERCENT, 0)
    INTO MYSQL_VAR_S897Z1, MYSQL_VAR_7FL77E
    FROM TUTORING_STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_JXDRA4
    FROM TUTORING_SESSIONS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_M42I89 = MYSQL_VAR_JXDRA4 * MYSQL_VAR_S897Z1;
    SET MYSQL_VAR_LF3TDB = MYSQL_VAR_M42I89 - (MYSQL_VAR_M42I89 * MYSQL_VAR_7FL77E / 100);

    RETURN CAST(MYSQL_VAR_LF3TDB AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TYAU77(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_B24S87 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_YGY7S6 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_V9P6J8 INT DEFAULT 0;

    SELECT COALESCE(SHIPPING_COST, 0), COALESCE(TOTAL_AMOUNT, 1)
    INTO MYSQL_VAR_B24S87, MYSQL_VAR_YGY7S6
    FROM ORDERS O
    LEFT JOIN SHIPMENTS S ON O.ORDER_ID = S.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_V9P6J8 = MYSQL_FUNC_38Q8EG(30);

    RETURN MYSQL_FUNC_EOWVPD();
END//

DELIMITER ;