/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_03sl93 (
    id INT,
    name VARCHAR(100)
);
INSERT INTO table_03sl93 (id, name) VALUES (1, 'Client A');
INSERT INTO table_03sl93 (id, name) VALUES (2, 'Client B');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_G1IY3W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_G1IY3W(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DH2A0L INT DEFAULT 2;
    DECLARE MYSQL_VAR_0MPKNI INT DEFAULT 0;

    IF N <= 1 THEN
        RETURN 0;
    END IF;

    IF N % 2 = 0 THEN
        RETURN 2;
    END IF;

    SET MYSQL_VAR_0MPKNI = FLOOR(SQRT(N));
    SET MYSQL_VAR_DH2A0L = 3;

    WHILE MYSQL_VAR_DH2A0L <= MYSQL_VAR_0MPKNI DO
        IF N % MYSQL_VAR_DH2A0L = 0 THEN
            RETURN MYSQL_VAR_DH2A0L;
        END IF;
        SET MYSQL_VAR_DH2A0L = MYSQL_VAR_DH2A0L + 2;
    END WHILE;

    RETURN N;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1GOY23----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1GOY23() RETURNS INT
BEGIN
SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = 'THIS IS A WARNING MESSAGE';
    RETURN 44;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_F08RO9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_F08RO9(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KERXK0 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_G1IY3W(10) - (0) + COALESCE(WEEK(START_DATE), 0))
    INTO MYSQL_VAR_KERXK0
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_1GOY23() - (0) + COALESCE(MYSQL_VAR_KERXK0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FEDMQN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FEDMQN() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8L0FBD INT;
    
    SELECT COUNT(*) INTO MYSQL_VAR_8L0FBD FROM TABLE_03SL93;
    
    RETURN MYSQL_VAR_8L0FBD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QZOPAX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QZOPAX(LEASE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_J9PY6B INT DEFAULT 0;
    DECLARE MYSQL_VAR_LEHYTM INT DEFAULT 50;
    DECLARE MYSQL_VAR_C6YAP7 INT DEFAULT 12;
    DECLARE MYSQL_VAR_LUD8AU INT DEFAULT 0;

    SELECT COALESCE(SPACE_SQFT, 100), COALESCE(MONTHLY_RATE, 50), COALESCE(LEASE_TERM_MONTHS, 12)
    INTO MYSQL_VAR_J9PY6B, MYSQL_VAR_LEHYTM, MYSQL_VAR_C6YAP7
    FROM OFFICE_SPACE_LEASES
    WHERE LEASE_ID = LEASE_ID_PARAM;

    SET MYSQL_VAR_LUD8AU = MYSQL_FUNC_FEDMQN();

    IF MYSQL_VAR_J9PY6B > 5000 THEN
        SET MYSQL_VAR_LUD8AU = MYSQL_VAR_LUD8AU - (MYSQL_VAR_LUD8AU * 5 / 100);
    END IF;

    RETURN CAST(MYSQL_VAR_LUD8AU AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EE5BIO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EE5BIO(CLASS_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EQVE08 INT DEFAULT 0;
    DECLARE MYSQL_VAR_EY4ALY INT DEFAULT 0;
    DECLARE MYSQL_VAR_CTU2TS INT DEFAULT 0;
    DECLARE MYSQL_VAR_LMLHBM INT DEFAULT 0;
    DECLARE MYSQL_VAR_1Z41ZW INT DEFAULT 0;
    DECLARE MYSQL_VAR_L2GEUN INT DEFAULT 0;

    SELECT COALESCE(CAPACITY, 20), COALESCE(CURRENT_ENROLLMENT, 0), COALESCE(DURATION_MINUTES, 60)
    INTO MYSQL_VAR_EQVE08, MYSQL_VAR_EY4ALY, MYSQL_VAR_CTU2TS
    FROM FITNESS_CLASSES
    WHERE CLASS_ID = CLASS_ID_PARAM;

    SELECT COUNT(*), COALESCE(AVG(CASE ATTENDANCE_STATUS WHEN 'ATTENDED' THEN 1 ELSE 0 END) * 100, 0)
    INTO MYSQL_VAR_LMLHBM, MYSQL_VAR_1Z41ZW
    FROM BOOKINGS
    WHERE CLASS_ID = CLASS_ID_PARAM;

    SET MYSQL_VAR_L2GEUN = ((MYSQL_VAR_EY4ALY * 100) / MYSQL_VAR_EQVE08) + (MYSQL_VAR_LMLHBM * 2) + (MYSQL_VAR_1Z41ZW / 2);

    RETURN MYSQL_VAR_L2GEUN;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VIOBK8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VIOBK8(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3SIJ67 INT DEFAULT 0;
    DECLARE MYSQL_VAR_TZUDY5 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COUNT(*), COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_3SIJ67, MYSQL_VAR_TZUDY5
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN (MYSQL_FUNC_EE5BIO(20) - (0) + COALESCE(FLOOR((MYSQL_VAR_3SIJ67 * MYSQL_VAR_TZUDY5) / 10), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0D7931----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0D7931(VIOLATION_ID_PARAM INT, DAYS_EARLY INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UOIFKJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_H0KX37 INT DEFAULT 0;
    DECLARE MYSQL_VAR_D7CHOW INT DEFAULT 0;

    SELECT (MYSQL_FUNC_QZOPAX(20) - (0) + COALESCE(COALESCE(FINE_AMOUNT, 50), 0))
    INTO MYSQL_VAR_UOIFKJ
    FROM PARKING_VIOLATIONS
    WHERE VIOLATION_ID = VIOLATION_ID_PARAM;

    IF DAYS_EARLY >= 30 THEN
        SET MYSQL_VAR_H0KX37 = 40;
    ELSEIF DAYS_EARLY >= 14 THEN
        SET MYSQL_VAR_H0KX37 = 25;
    ELSEIF DAYS_EARLY >= 7 THEN
        SET MYSQL_VAR_H0KX37 = 15;
    END IF;

    SET MYSQL_VAR_D7CHOW = MYSQL_FUNC_VIOBK8(20);

    RETURN (MYSQL_FUNC_F08RO9(20) - (0) + COALESCE(CAST(MYSQL_VAR_D7CHOW AS SIGNED), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8LUT9O----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8LUT9O(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_62WUSE INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y5ZIL9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_PQKBUU INT DEFAULT 0;

    SELECT COALESCE(TUITION_BALANCE, 0)
    INTO MYSQL_VAR_62WUSE
    FROM SCHOOL_STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT), 0) INTO MYSQL_VAR_Y5ZIL9
    FROM PAYMENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_PQKBUU = MYSQL_VAR_62WUSE - MYSQL_VAR_Y5ZIL9;

    IF MYSQL_VAR_PQKBUU < 0 THEN
        SET MYSQL_VAR_PQKBUU = 0;
    END IF;

    RETURN CAST(MYSQL_VAR_PQKBUU AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EERRQA(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V8XNB0 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_0D7931(10, 11) - (0) + COALESCE(CUSTOMER_ID, 0))
    INTO MYSQL_VAR_V8XNB0
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN (MYSQL_FUNC_8LUT9O(10) - (0) + COALESCE(MYSQL_VAR_V8XNB0 % 1000, 0));
END//

DELIMITER ;