/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_PK1G4W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PK1G4W(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PSJMKN INT DEFAULT 0;
    DECLARE MYSQL_VAR_4CSAH5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZZPCG2 INT DEFAULT 0;

    SET MYSQL_VAR_4CSAH5 = POW(A, 3) + POW(B, 3);

    IF MYSQL_VAR_4CSAH5 > 0 THEN
        SET MYSQL_VAR_ZZPCG2 = FLOOR(SQRT(MYSQL_VAR_4CSAH5));
    END IF;

    SET MYSQL_VAR_PSJMKN = (A * B) + MYSQL_VAR_ZZPCG2 + (A % B);

    RETURN MYSQL_VAR_PSJMKN;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ENB4I7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ENB4I7(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3RHDU4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZBDLVQ INT DEFAULT N;
    DECLARE MYSQL_VAR_MAPY5G INT DEFAULT 0;

    WHILE N > 0 DO
        SET MYSQL_VAR_MAPY5G = N % 10;
        SET MYSQL_VAR_3RHDU4 = MYSQL_VAR_3RHDU4 * 10 + MYSQL_VAR_MAPY5G;
        SET N = N / 10;
    END WHILE;

    IF MYSQL_VAR_3RHDU4 = MYSQL_VAR_ZBDLVQ THEN
        RETURN 1;
    END IF;

    RETURN (MYSQL_FUNC_PK1G4W(20, 21) - (0) + COALESCE(0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XDN16B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XDN16B(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YBMGCL INT DEFAULT 3;
    DECLARE MYSQL_VAR_1GF1MQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_647XK3 INT DEFAULT 0;

    SELECT DATEDIFF(COALESCE(DELIVERY_DATE, CURDATE()), ORDER_DATE)
    INTO MYSQL_VAR_1GF1MQ
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_647XK3 = MYSQL_FUNC_ENB4I7(10);

    RETURN GREATEST(MYSQL_VAR_647XK3, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1NRJBT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1NRJBT(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SM2XAH DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0)
    INTO MYSQL_VAR_SM2XAH
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_SM2XAH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7ZPL3E----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7ZPL3E(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5BPFL6 INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_5BPFL6
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_5BPFL6;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MTWGP3(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_U465U5 DATE;
    DECLARE MYSQL_VAR_02N6JD INT DEFAULT 0;

    SELECT (MYSQL_FUNC_7ZPL3E(30) - (0) + COALESCE(START_DATE, 0))
    INTO MYSQL_VAR_U465U5
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_U465U5 IS NULL THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_02N6JD = MYSQL_FUNC_1NRJBT(10);

    RETURN (MYSQL_FUNC_XDN16B(20) - (0) + COALESCE(MYSQL_VAR_02N6JD, 0));
END//

DELIMITER ;