/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_F4WX69----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_F4WX69(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_K8S0N2 INT DEFAULT 0;

    SELECT DAY(ORDER_DATE)
    INTO MYSQL_VAR_K8S0N2
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_K8S0N2;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_STNAGE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_STNAGE(X INT) RETURNS INT
BEGIN
RETURN MYSQL_FUNC_F4WX69(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P310KY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P310KY(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GOT9ZA DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_GW766I DECIMAL(10,2) DEFAULT 1.00;

    SELECT COALESCE(AVG(PRICE), 0), COALESCE(AVG(PRICE), 1)
    INTO MYSQL_VAR_GOT9ZA, MYSQL_VAR_GW766I
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_GOT9ZA * 100) / MYSQL_VAR_GW766I);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GVB9YE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GVB9YE(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_899W6O DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_899W6O
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_899W6O / 2080) / 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GCMS42----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GCMS42(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_F1G5XQ VARCHAR(20) DEFAULT 'DRAFT';

    SELECT STATUS
    INTO MYSQL_VAR_F1G5XQ
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN CASE WHEN MYSQL_VAR_F1G5XQ = 'ACTIVE' THEN 1 ELSE 0 END;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6SSNLE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6SSNLE(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UK703B INT DEFAULT 0;
    DECLARE MYSQL_VAR_8J2N81 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_GL9CWR INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_UK703B
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT MYSQL_FUNC_GVB9YE(10)
    INTO MYSQL_VAR_8J2N81
    FROM PRODUCTS
    WHERE CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    IF MYSQL_VAR_UK703B < MYSQL_VAR_8J2N81 * 0.5 THEN
        SET MYSQL_VAR_GL9CWR = 100;
    ELSEIF MYSQL_VAR_UK703B > MYSQL_VAR_8J2N81 * 1.5 THEN
        SET MYSQL_VAR_GL9CWR = 50;
    ELSE
        SET MYSQL_VAR_GL9CWR = 25;
    END IF;

    RETURN MYSQL_FUNC_GCMS42(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FG6CYO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FG6CYO(CS_ID INT, CLUSTER_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3QAN2L BIGINT UNSIGNED DEFAULT 1;
    DECLARE MYSQL_VAR_3O4UJH VARCHAR(36);
    DECLARE MYSQL_VAR_YIVDB9 VARCHAR(36);
    
    SET MYSQL_VAR_3O4UJH = CONCAT('CS', CS_ID);
    SET MYSQL_VAR_YIVDB9 = CONCAT('CLUSTER', CLUSTER_ID);
    
    DELETE FROM MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS
    WHERE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTERSET_ID = MYSQL_VAR_3O4UJH
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTER_ID = MYSQL_VAR_YIVDB9
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.VIEW_ID = MYSQL_VAR_3QAN2L;

    UPDATE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERS C
    SET C.CLUSTERSET_ID = NULL
    WHERE C.CLUSTER_ID = MYSQL_VAR_YIVDB9;

    RETURN 1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0BVFHQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0BVFHQ(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HEHOUW DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_BAGU3U DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_PYSNT7 INT DEFAULT 0;

    SELECT COALESCE(SHIPPING_COST, 0), COALESCE(TOTAL_AMOUNT, 1)
    INTO MYSQL_VAR_HEHOUW, MYSQL_VAR_BAGU3U
    FROM ORDERS O
    LEFT JOIN SHIPMENTS S ON O.ORDER_ID = S.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_PYSNT7 = (MYSQL_VAR_HEHOUW * 100) / MYSQL_VAR_BAGU3U;

    RETURN MYSQL_VAR_PYSNT7;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8M49UQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8M49UQ(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N9JN2K INT DEFAULT 0;
    DECLARE MYSQL_VAR_OYR6O1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_DW0Z3E INT DEFAULT 0;

    SELECT MYSQL_FUNC_FG6CYO(20, 21)
    INTO MYSQL_VAR_N9JN2K
    FROM CAMPAIGNS
    WHERE YEAR(START_DATE) = YEAR(CURDATE());

    SELECT MYSQL_FUNC_6SSNLE(30)
    INTO MYSQL_VAR_OYR6O1
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM
    AND YEAR(REGISTRATION_DATE) = YEAR(CURDATE());

    IF MYSQL_VAR_OYR6O1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_DW0Z3E = MYSQL_FUNC_0BVFHQ(30);

    RETURN MYSQL_FUNC_P310KY(10);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z73713(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_E9L4BW INT DEFAULT 0;
    DECLARE MYSQL_VAR_GHB3AO INT DEFAULT 0;
    DECLARE MYSQL_VAR_WB4TQB INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COUNT(*)
    INTO MYSQL_VAR_E9L4BW, MYSQL_VAR_GHB3AO
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_WB4TQB = MYSQL_FUNC_8M49UQ('test_0_0');

    RETURN MYSQL_FUNC_STNAGE(20);
END//

DELIMITER ;