/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_K6NVNW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_K6NVNW(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JXS5AU DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_G8PI28 INT DEFAULT 0;
    DECLARE MYSQL_VAR_X1OY69 INT DEFAULT 0;
    DECLARE MYSQL_VAR_HIGZ52 INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_JXS5AU
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*), COALESCE(SUM(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_G8PI28, MYSQL_VAR_X1OY69
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_HIGZ52 = (MYSQL_VAR_G8PI28 * 10) + (MYSQL_VAR_X1OY69 / 100) + (MYSQL_VAR_JXS5AU * 5);

    RETURN MYSQL_VAR_HIGZ52;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HVABBX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HVABBX(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N7JFGF INT DEFAULT 0;
    DECLARE MYSQL_VAR_DLFY8S DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_N7JFGF
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_DLFY8S
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_N7JFGF = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_DLFY8S * 100) / MYSQL_VAR_N7JFGF);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SR5O0T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SR5O0T(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OSD3CN INT DEFAULT 0;
    DECLARE MYSQL_VAR_VKL9ZO INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_OSD3CN
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_VKL9ZO
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_VKL9ZO = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_OSD3CN / MYSQL_VAR_VKL9ZO;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_R0IO0R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_R0IO0R() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RR9KUH INT DEFAULT 0;
    SELECT CBIN INTO MYSQL_VAR_RR9KUH FROM TABLE_BEPX1F.`TABLE3` LIMIT 1;
    RETURN MYSQL_VAR_RR9KUH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OQO8UB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OQO8UB(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_64F5FK INT DEFAULT 0;

    SELECT MYSQL_FUNC_SR5O0T(10)
    INTO MYSQL_VAR_64F5FK
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_R0IO0R();
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GTHB8L----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GTHB8L(NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6UOLNJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_7XV12P INT;

    SET MYSQL_VAR_7XV12P = MYSQL_FUNC_HVABBX(10);

    COUNT_LOOP: WHILE MYSQL_VAR_7XV12P > 0 DO
        IF MYSQL_VAR_7XV12P MOD 2 = 1 THEN
            SET MYSQL_VAR_6UOLNJ = MYSQL_VAR_6UOLNJ + 1;
        END IF;
        SET MYSQL_VAR_7XV12P = MYSQL_VAR_7XV12P DIV 2;
    END WHILE COUNT_LOOP;

    RETURN MYSQL_FUNC_OQO8UB(30);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_27O7KS(DEPT_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_R5ZHUK INT DEFAULT 0;
    DECLARE MYSQL_VAR_COJBYF INT DEFAULT 0;
    DECLARE MYSQL_VAR_WJANZW INT DEFAULT 0;
    DECLARE MYSQL_VAR_1W0K38 INT DEFAULT 0;
    DECLARE MYSQL_VAR_22C0T1 INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(AVG(SALARY), 0), COALESCE(MAX(SALARY), 0), COALESCE(MIN(SALARY), 0)
    INTO MYSQL_VAR_1W0K38, MYSQL_VAR_R5ZHUK, MYSQL_VAR_COJBYF, MYSQL_VAR_WJANZW
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPT_ID;

    SET MYSQL_VAR_22C0T1 = MYSQL_VAR_COJBYF - MYSQL_VAR_WJANZW;

    CASE
        WHEN MYSQL_VAR_1W0K38 = 0 THEN RETURN MYSQL_FUNC_GTHB8L(20);
        WHEN MYSQL_VAR_R5ZHUK < 3000 THEN SET MYSQL_VAR_22C0T1 = MYSQL_VAR_22C0T1 * 8 / 10;
        WHEN MYSQL_VAR_R5ZHUK > 10000 THEN SET MYSQL_VAR_22C0T1 = MYSQL_VAR_22C0T1 * 12 / 10;
        ELSE SET MYSQL_VAR_22C0T1 = MYSQL_FUNC_K6NVNW(30);
    END CASE;

    RETURN MYSQL_VAR_22C0T1;
END//

DELIMITER ;