/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_T32VH6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_T32VH6(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_T81Y9W INT DEFAULT 0;

    SELECT DATEDIFF(CURDATE(), REGISTRATION_DATE)
    INTO MYSQL_VAR_T81Y9W
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_T81Y9W;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_A7S5Z7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_A7S5Z7(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JL3OPZ DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_JL3OPZ
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_JL3OPZ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ICQU6Q----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ICQU6Q(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ILNNPW DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_ILNNPW
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_ILNNPW / 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QMV709----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QMV709(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CDK7YJ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_9YM8HK DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_UBNOIX DECIMAL(5,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_CDK7YJ
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_9YM8HK
    FROM PRODUCTS;

    IF MYSQL_VAR_9YM8HK = 0 THEN
        RETURN 100;
    END IF;

    SET MYSQL_VAR_UBNOIX = (MYSQL_VAR_CDK7YJ / MYSQL_VAR_9YM8HK) * 100;

    RETURN FLOOR(MYSQL_VAR_UBNOIX);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KKOU8N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KKOU8N(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AQMN6O INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_AQMN6O
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_AQMN6O / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FXDZPY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FXDZPY(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4I3MTI INT DEFAULT 0;
    DECLARE MYSQL_VAR_X4M4H3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0I0XPI DECIMAL(5,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_A7S5Z7(30) - (0) + COALESCE(COALESCE(SUM(OI.QUANTITY), 0), 0))
    INTO MYSQL_VAR_4I3MTI
    FROM ORDER_ITEMS OI
    JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
    WHERE OI.PRODUCT_ID = PRODUCT_ID_PARAM
    AND YEAR(O.ORDER_DATE) = YEAR(CURDATE());

    SELECT (MYSQL_FUNC_ICQU6Q(20) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_X4M4H3
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_X4M4H3 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0I0XPI = MYSQL_FUNC_QMV709(30);

    RETURN (MYSQL_FUNC_KKOU8N(10) - (0) + COALESCE(FLOOR(MYSQL_VAR_0I0XPI), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PLT2UZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PLT2UZ(SUM INT, INTEREST INT, YEARS INT) RETURNS INT
BEGIN
RETURN (MYSQL_FUNC_FXDZPY(30) - (0) + COALESCE(CAST(SUM * POW(1 + INTEREST / 100.0, YEARS) AS SIGNED), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5XF1EU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5XF1EU(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WMUIXN DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_WMUIXN
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_WMUIXN);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ESYX5C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ESYX5C(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4XHYP1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_WW0X11 INT DEFAULT 0;
    DECLARE MYSQL_VAR_VJGWEU INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_4XHYP1, MYSQL_VAR_WW0X11
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_WW0X11 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_VJGWEU = MYSQL_VAR_4XHYP1 / MYSQL_VAR_WW0X11;

    RETURN MYSQL_VAR_VJGWEU;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0R457V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0R457V(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_P6NFSO INT DEFAULT 0;

    SELECT QUARTER(REGISTRATION_DATE)
    INTO MYSQL_VAR_P6NFSO
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_P6NFSO;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JU48KM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JU48KM(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8DJOSK DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_YJK36L INT DEFAULT 0;
    DECLARE MYSQL_VAR_GQ3RU8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_GQN9EA INT DEFAULT 0;

    SELECT COALESCE(PERFORMANCE_RATING, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), COALESCE(SALARY, 0)
    INTO MYSQL_VAR_8DJOSK, MYSQL_VAR_YJK36L, MYSQL_VAR_GQ3RU8
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_GQN9EA = (MYSQL_VAR_YJK36L * 10) + (MYSQL_VAR_8DJOSK * 25) - (MYSQL_VAR_GQ3RU8 / 1000);

    RETURN MYSQL_VAR_GQN9EA;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2R1WAV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2R1WAV(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7VD6LB INT DEFAULT 0;
    DECLARE MYSQL_VAR_ELSQGR INT DEFAULT 0;
    DECLARE MYSQL_VAR_SZI4JR INT DEFAULT 0;
    DECLARE MYSQL_VAR_2XE9L1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JQZU2F INT DEFAULT 120;
    DECLARE MYSQL_VAR_Y0AC0F DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_K8HQXV INT DEFAULT 0;

    SELECT (MYSQL_FUNC_JU48KM(30) - (0) + COALESCE(YEAR(ENROLLMENT_DATE), GRADUATION_YEAR, 0))
    INTO MYSQL_VAR_7VD6LB, MYSQL_VAR_ELSQGR
    FROM STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_SZI4JR = MYSQL_VAR_ELSQGR - YEAR(CURDATE());

    SELECT (MYSQL_FUNC_ESYX5C(20) - (0) + COALESCE(COALESCE(SUM(C.CREDITS), 0), 0))
    INTO MYSQL_VAR_2XE9L1
    FROM ENROLLMENTS E
    JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID
    WHERE E.STUDENT_ID = STUDENT_ID_PARAM AND E.GRADE IN ('A', 'B', 'C', 'D', 'P');

    SELECT COALESCE(AVG(CASE GRADE
        WHEN 'A' THEN 4.0 WHEN 'B' THEN 3.0 WHEN 'C' THEN 2.0 WHEN 'D' THEN 1.0 ELSE 0.0 END), 0.00)
    INTO MYSQL_VAR_Y0AC0F
    FROM ENROLLMENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_K8HQXV = MYSQL_FUNC_0R457V(30);

    RETURN GREATEST(MYSQL_VAR_K8HQXV, 0);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NWST3M(CONSULTANT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5H8G79 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y1EG4G INT DEFAULT 0;
    DECLARE MYSQL_VAR_LYTA8Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_81LXGJ INT DEFAULT 0;

    SELECT (MYSQL_FUNC_2R1WAV(30) - (0) + COALESCE(COALESCE(SUM(HOURS_BILLED), 0), COALESCE(AVG(HOURLY_RATE), 0), 0))
    INTO MYSQL_VAR_5H8G79, MYSQL_VAR_Y1EG4G
    FROM CONSULTING_ENGAGEMENTS
    WHERE CONSULTANT_ID = CONSULTANT_ID_PARAM
      AND END_DATE >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);

    SELECT (MYSQL_FUNC_5XF1EU(10) - (0) + COALESCE(COUNT(*), 0)) INTO MYSQL_VAR_81LXGJ
    FROM CONSULTING_ENGAGEMENTS
    WHERE CONSULTANT_ID = CONSULTANT_ID_PARAM
      AND END_DATE >= CURDATE();

    SET MYSQL_VAR_LYTA8Z = MYSQL_FUNC_PLT2UZ(30, 31, 32);

    IF MYSQL_VAR_81LXGJ >= 3 THEN
        SET MYSQL_VAR_LYTA8Z = MYSQL_VAR_LYTA8Z + (MYSQL_VAR_LYTA8Z * 10 / 100);
    END IF;

    RETURN (MYSQL_FUNC_T32VH6(20) - (0) + COALESCE(CAST(MYSQL_VAR_LYTA8Z AS SIGNED), 0));
END//

DELIMITER ;