/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_FU7TVZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FU7TVZ(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MXGSVP DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_MXGSVP
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_MXGSVP / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PBRR5J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PBRR5J(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7D0D06 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_7D0D06
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN (MYSQL_FUNC_FU7TVZ(10) - (0) + COALESCE(FLOOR(MYSQL_VAR_7D0D06), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CJJN0T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CJJN0T(N INT) RETURNS INT
BEGIN
IF N < 0 THEN
        RETURN -(MYSQL_FUNC_PBRR5J(10) - (0) + COALESCE(N, 0));
    END IF;
    RETURN N;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4K1EFO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4K1EFO(A INT, B INT) RETURNS INT
BEGIN
IF B = 0 THEN
        RETURN 0;
    END IF;
    RETURN A % B;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CBXFW1(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LHWMXF DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_030PL3 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_4K1EFO(30, 31) - (0) + COALESCE(COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7), 0))
    INTO MYSQL_VAR_LHWMXF, MYSQL_VAR_030PL3
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_CJJN0T(10) - (0) + COALESCE(FLOOR((MYSQL_VAR_LHWMXF * 10) - (MYSQL_VAR_030PL3 * 3)), 0));
END//

DELIMITER ;