/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_XGQ0PJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XGQ0PJ(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1MJJJU INT DEFAULT 2;
    DECLARE MYSQL_VAR_F6ISFQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_L6RSCK INT DEFAULT 0;
    DECLARE MYSQL_VAR_O4L81Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_V88748 INT DEFAULT 0;

    SELECT COALESCE(WARRANTY_YEARS, 2), COALESCE(COVERAGE_AMOUNT, 1000), COALESCE(DEDUCTIBLE, 100)
    INTO MYSQL_VAR_1MJJJU, MYSQL_VAR_F6ISFQ, MYSQL_VAR_L6RSCK
    FROM INSURANCE_WARRANTY
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(REPAIR_COST), 0) INTO MYSQL_VAR_O4L81Z
    FROM WARRANTY_CLAIMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM AND STATUS = 'APPROVED';

    SET MYSQL_VAR_V88748 = (MYSQL_VAR_1MJJJU * 20) + (MYSQL_VAR_F6ISFQ / 100) - (MYSQL_VAR_L6RSCK / 10);

    IF MYSQL_VAR_O4L81Z > 500 THEN
        SET MYSQL_VAR_V88748 = MYSQL_VAR_V88748 - 30;
    END IF;

    RETURN CAST(MYSQL_VAR_V88748 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XN9NC8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XN9NC8(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2MU5F0 INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_2MU5F0
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN GREATEST(100 - (MYSQL_VAR_2MU5F0 * 5), 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_D6GAUI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_D6GAUI(SHIPMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6Q0E6B DATE;
    DECLARE MYSQL_VAR_FPPC55 DATE;
    DECLARE MYSQL_VAR_XVH695 DATE;
    DECLARE MYSQL_VAR_KM0BZE INT DEFAULT 0;

    SELECT SHIPPING_DATE, DELIVERY_DATE
    INTO MYSQL_VAR_6Q0E6B, MYSQL_VAR_XVH695
    FROM SHIPPING_SHIPMENTS
    WHERE SHIPMENT_ID = SHIPMENT_ID_PARAM;

    IF MYSQL_VAR_6Q0E6B IS NULL THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_FPPC55 = DATE_ADD(MYSQL_VAR_6Q0E6B, INTERVAL 7 DAY);

    IF MYSQL_VAR_XVH695 IS NULL THEN
        SET MYSQL_VAR_KM0BZE = DATEDIFF(CURDATE(), MYSQL_VAR_FPPC55);
    ELSE
        SET MYSQL_VAR_KM0BZE = DATEDIFF(MYSQL_VAR_XVH695, MYSQL_VAR_FPPC55);
    END IF;

    IF MYSQL_VAR_KM0BZE < 0 THEN
        SET MYSQL_VAR_KM0BZE = 0;
    END IF;

    RETURN MYSQL_VAR_KM0BZE;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NAJZE8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NAJZE8(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WN6BC3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZBCZOR INT DEFAULT 0;
    DECLARE MYSQL_VAR_454IQW INT DEFAULT 0;
    DECLARE MYSQL_VAR_8ZXQHF DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_IBGUOW INT DEFAULT 0;

    SELECT MYSQL_FUNC_XN9NC8(30)
    INTO MYSQL_VAR_WN6BC3, MYSQL_VAR_ZBCZOR
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COUNT(DISTINCT PRODUCT_ID)
    INTO MYSQL_VAR_454IQW
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_ZBCZOR > 0 THEN
        SET MYSQL_VAR_8ZXQHF = MYSQL_VAR_WN6BC3 / MYSQL_VAR_ZBCZOR;
    END IF;

    IF MYSQL_VAR_WN6BC3 > 10000 THEN
        SET MYSQL_VAR_IBGUOW = MYSQL_VAR_IBGUOW + 30;
    END IF;

    IF MYSQL_VAR_454IQW < MYSQL_VAR_ZBCZOR / 2 THEN
        SET MYSQL_VAR_IBGUOW = MYSQL_VAR_IBGUOW + 20;
    END IF;

    IF MYSQL_VAR_8ZXQHF > 5000 THEN
        SET MYSQL_VAR_IBGUOW = MYSQL_VAR_IBGUOW + 25;
    END IF;

    RETURN MYSQL_FUNC_D6GAUI(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LRNBMI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LRNBMI(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_33X2YS INT DEFAULT 0;
    DECLARE MYSQL_VAR_AXMZ4X DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_MGNO7C INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_33X2YS, MYSQL_VAR_AXMZ4X
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_MGNO7C = MYSQL_FUNC_NAJZE8(20);

    RETURN MYSQL_VAR_MGNO7C;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6FFIYL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6FFIYL() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KJU462 INT DEFAULT 0;
    SELECT COUNT(*) INTO MYSQL_VAR_KJU462 FROM TABLE_9AEQOO.`TABLE3`;
    RETURN MYSQL_VAR_KJU462;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7SWC2B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7SWC2B(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UAF4YK INT DEFAULT 0;
    DECLARE MYSQL_VAR_7QNKXG INT DEFAULT 1;
    DECLARE MYSQL_VAR_BIUS89 INT DEFAULT 1;
    DECLARE MYSQL_VAR_NYBK00 INT DEFAULT 0;

    IF N <= 0 OR N > 100 THEN
        RETURN 0;
    END IF;

    OUTER_LOOP: WHILE MYSQL_VAR_7QNKXG <= N DO
        INNER_LOOP: WHILE MYSQL_VAR_BIUS89 <= N DO
            IF MYSQL_VAR_7QNKXG = MYSQL_VAR_BIUS89 THEN
                SET MYSQL_VAR_NYBK00 = MYSQL_VAR_NYBK00 + (MYSQL_VAR_7QNKXG * MYSQL_VAR_BIUS89);
            END IF;
            SET MYSQL_VAR_BIUS89 = MYSQL_VAR_BIUS89 + 1;
        END WHILE INNER_LOOP;
        SET MYSQL_VAR_BIUS89 = 1;
        SET MYSQL_VAR_7QNKXG = MYSQL_VAR_7QNKXG + 1;
    END WHILE OUTER_LOOP;

    RETURN MYSQL_VAR_NYBK00;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QZOPAX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QZOPAX(LEASE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_J9PY6B INT DEFAULT 0;
    DECLARE MYSQL_VAR_LEHYTM INT DEFAULT 50;
    DECLARE MYSQL_VAR_C6YAP7 INT DEFAULT 12;
    DECLARE MYSQL_VAR_LUD8AU INT DEFAULT 0;

    SELECT MYSQL_FUNC_7SWC2B(30)
    INTO MYSQL_VAR_J9PY6B, MYSQL_VAR_LEHYTM, MYSQL_VAR_C6YAP7
    FROM OFFICE_SPACE_LEASES
    WHERE LEASE_ID = LEASE_ID_PARAM;

    SET MYSQL_VAR_LUD8AU = MYSQL_VAR_J9PY6B * MYSQL_VAR_LEHYTM * MYSQL_VAR_C6YAP7;

    IF MYSQL_VAR_J9PY6B > 5000 THEN
        SET MYSQL_VAR_LUD8AU = MYSQL_VAR_LUD8AU - (MYSQL_VAR_LUD8AU * 5 / 100);
    END IF;

    RETURN CAST(MYSQL_VAR_LUD8AU AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NJ1XB9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NJ1XB9(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_L448TZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_PEI0PD DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_6FFIYL()
    INTO MYSQL_VAR_L448TZ
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_PEI0PD = (YEAR(CURDATE()) - MYSQL_VAR_L448TZ) * 0.03 * 100;

    RETURN MYSQL_FUNC_QZOPAX(30);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8LUT9O(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_62WUSE INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y5ZIL9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_PQKBUU INT DEFAULT 0;

    SELECT MYSQL_FUNC_NJ1XB9(20)
    INTO MYSQL_VAR_62WUSE
    FROM SCHOOL_STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT), 0) INTO MYSQL_VAR_Y5ZIL9
    FROM PAYMENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_PQKBUU = MYSQL_FUNC_LRNBMI(20);

    IF MYSQL_VAR_PQKBUU < 0 THEN
        SET MYSQL_VAR_PQKBUU = 0;
    END IF;

    RETURN MYSQL_FUNC_XGQ0PJ(30);
END//

DELIMITER ;