/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_BHC0I8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BHC0I8(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LL5I67 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_LL5I67
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_LL5I67);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZOU44V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZOU44V(WARRANTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HAKN9G DATE;
    DECLARE MYSQL_VAR_ZNCB2Y INT DEFAULT 0;
    DECLARE MYSQL_VAR_NPC6HS DATE;
    DECLARE MYSQL_VAR_WCBOZX INT DEFAULT 0;
    DECLARE MYSQL_VAR_04PS9D INT DEFAULT 0;

    SELECT PURCHASE_DATE, WARRANTY_MONTHS
    INTO MYSQL_VAR_HAKN9G, MYSQL_VAR_ZNCB2Y
    FROM WARRANTIES
    WHERE WARRANTY_ID = WARRANTY_ID_PARAM;

    IF MYSQL_VAR_HAKN9G IS NULL THEN
        RETURN -1;
    END IF;

    SET MYSQL_VAR_NPC6HS = DATE_ADD(MYSQL_VAR_HAKN9G, INTERVAL MYSQL_VAR_ZNCB2Y MONTH);
    SET MYSQL_VAR_WCBOZX = DATEDIFF(MYSQL_VAR_NPC6HS, CURDATE());

    IF MYSQL_VAR_WCBOZX < 0 THEN
        SET MYSQL_VAR_04PS9D = 0;
    ELSEIF MYSQL_VAR_WCBOZX <= 30 THEN
        SET MYSQL_VAR_04PS9D = 1;
    ELSE
        SET MYSQL_VAR_04PS9D = 2;
    END IF;

    RETURN MYSQL_VAR_04PS9D;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MM0IKF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MM0IKF(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6DGIJT INT DEFAULT 0;
    DECLARE MYSQL_VAR_DIKRBY INT DEFAULT 1;

    SELECT COUNT(DISTINCT S.CUSTOMER_ID), COUNT(*)
    INTO MYSQL_VAR_6DGIJT, MYSQL_VAR_DIKRBY
    FROM CUSTOMERS C
    LEFT JOIN SUBSCRIPTIONS S ON C.CUSTOMER_ID = S.CUSTOMER_ID AND S.STATUS = 'ACTIVE'
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN (MYSQL_VAR_6DGIJT * 100) / MYSQL_VAR_DIKRBY;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_86AGHU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_86AGHU(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BHVHNT VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_CKVYM3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_6SI0EN DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_BTWVAN INT DEFAULT 0;

    SELECT CHANNEL, COUNT(*), COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_BHVHNT, MYSQL_VAR_CKVYM3, MYSQL_VAR_6SI0EN
    FROM CAMPAIGNS C
    LEFT JOIN CONVERSIONS CV ON C.CAMPAIGN_ID = CV.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM
    GROUP BY C.CAMPAIGN_ID;

    CASE MYSQL_VAR_BHVHNT
        WHEN 'PAID' THEN SET MYSQL_VAR_BTWVAN = MYSQL_VAR_CKVYM3 * 3 + FLOOR(MYSQL_VAR_6SI0EN / 50);
        WHEN 'ORGANIC' THEN SET MYSQL_VAR_BTWVAN = MYSQL_VAR_CKVYM3 * 5 + FLOOR(MYSQL_VAR_6SI0EN / 50);
        WHEN 'SOCIAL' THEN SET MYSQL_VAR_BTWVAN = MYSQL_VAR_CKVYM3 * 4 + FLOOR(MYSQL_VAR_6SI0EN / 50);
        ELSE SET MYSQL_VAR_BTWVAN = MYSQL_VAR_CKVYM3 * 2 + FLOOR(MYSQL_VAR_6SI0EN / 50);
    END CASE;

    RETURN MYSQL_VAR_BTWVAN;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_V8SY4N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_V8SY4N(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8NH9RR DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_CG5DX2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_9GETDM INT DEFAULT 0;

    SELECT COALESCE(MAX(SALARY), 0), COALESCE(MIN(SALARY), 0)
    INTO MYSQL_VAR_CG5DX2, MYSQL_VAR_9GETDM
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_8NH9RR = MYSQL_FUNC_86AGHU(20);

    RETURN (MYSQL_FUNC_MM0IKF('test_1_0') - (0) + COALESCE(FLOOR(MYSQL_VAR_8NH9RR), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KD934Z----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KD934Z(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UGR1O6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_2MH1HH INT DEFAULT 0;
    DECLARE MYSQL_VAR_YRH2P0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_DT7CQM INT DEFAULT 0;

    SELECT (MYSQL_FUNC_ZOU44V(20) - (0) + COALESCE(COALESCE(SALARY, 50000), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), 0))
    INTO MYSQL_VAR_UGR1O6, MYSQL_VAR_2MH1HH
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT (MYSQL_FUNC_BHC0I8(20) - (0) + COALESCE(COALESCE(IS_REMOTE_FRIENDLY, 0), 0))
    INTO MYSQL_VAR_YRH2P0
    FROM DEPARTMENTS D
    JOIN EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
    WHERE E.EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_DT7CQM = MYSQL_FUNC_V8SY4N(10);

    IF MYSQL_VAR_YRH2P0 = 1 THEN
        SET MYSQL_VAR_DT7CQM = MYSQL_VAR_DT7CQM + 15;
    END IF;

    RETURN MYSQL_VAR_DT7CQM;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OQH1OB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OQH1OB(A INT, B INT) RETURNS INT
BEGIN
IF A < B THEN
        RETURN A;
    END IF;
    RETURN B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_42HTXO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_42HTXO(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_44CV7R INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_44CV7R
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_OQH1OB(20, 21) - (0) + COALESCE(MYSQL_VAR_44CV7R, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7YMH98----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7YMH98(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XZ550I DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_Q0SE34 INT DEFAULT 0;

    SELECT COALESCE(AVG(DATEDIFF(CONVERSION_DATE, START_DATE)), 0)
    INTO MYSQL_VAR_XZ550I
    FROM CONVERSIONS C
    JOIN CAMPAIGNS CAMP ON C.CAMPAIGN_ID = CAMP.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SET MYSQL_VAR_Q0SE34 = GREATEST(100 - (MYSQL_VAR_XZ550I * 5), 0);

    RETURN (MYSQL_FUNC_42HTXO(10) - (0) + COALESCE(MYSQL_VAR_Q0SE34, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_20BRDV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_20BRDV(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M5OFYZ INT DEFAULT 0;

    SELECT (MYSQL_FUNC_7YMH98(10) - (0) + COALESCE(WEEK(REGISTRATION_DATE), 0))
    INTO MYSQL_VAR_M5OFYZ
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_M5OFYZ;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8L6EUR(AD_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CNZ07O INT DEFAULT 5000;
    DECLARE MYSQL_VAR_VFMN25 INT DEFAULT 0;
    DECLARE MYSQL_VAR_QIACLW INT DEFAULT 0;
    DECLARE MYSQL_VAR_XH5600 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_RENT, 5000), COALESCE(IMPRESSIONS_EXPECTED, 100000)
    INTO MYSQL_VAR_CNZ07O, MYSQL_VAR_VFMN25
    FROM BILLBOARD_ADVERTISEMENTS
    WHERE AD_ID = AD_ID_PARAM;

    SELECT (MYSQL_FUNC_20BRDV(10) - (0) + COALESCE(COALESCE(TRAFFIC_COUNT, 50000), 0))
    INTO MYSQL_VAR_QIACLW
    FROM BILLBOARD_ADVERTISEMENTS BA
    JOIN BILLBOARD_LOCATIONS BL ON BA.LOCATION_ID = BL.LOCATION_ID
    WHERE BA.AD_ID = AD_ID_PARAM;

    SET MYSQL_VAR_XH5600 = (MYSQL_VAR_VFMN25 * MYSQL_VAR_QIACLW) / MYSQL_VAR_CNZ07O;

    RETURN (MYSQL_FUNC_KD934Z(10) - (0) + COALESCE(CAST(MYSQL_VAR_XH5600 AS SIGNED), 0));
END//

DELIMITER ;