/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_UI6FD0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UI6FD0(BOOK_ID_PARAM INT, DAYS_LATE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PWU99X INT DEFAULT 5;
    DECLARE MYSQL_VAR_NH4YZ7 INT DEFAULT 100;
    DECLARE MYSQL_VAR_O6I4DL INT DEFAULT 0;
    DECLARE MYSQL_VAR_6TJ299 INT DEFAULT 0;

    IF DAYS_LATE <= 0 THEN
        RETURN 0;
    END IF;

    SELECT COUNT(*) INTO MYSQL_VAR_6TJ299
    FROM BOOK_LOANS
    WHERE BOOK_ID = BOOK_ID_PARAM AND RETURN_DATE IS NULL;

    SET MYSQL_VAR_O6I4DL = DAYS_LATE * MYSQL_VAR_PWU99X;

    IF MYSQL_VAR_6TJ299 > 3 THEN
        SET MYSQL_VAR_O6I4DL = MYSQL_VAR_O6I4DL * 2;
    END IF;

    IF MYSQL_VAR_O6I4DL > MYSQL_VAR_NH4YZ7 THEN
        SET MYSQL_VAR_O6I4DL = MYSQL_VAR_NH4YZ7;
    END IF;

    RETURN MYSQL_VAR_O6I4DL;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z73713----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z73713(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_E9L4BW INT DEFAULT 0;
    DECLARE MYSQL_VAR_GHB3AO INT DEFAULT 0;
    DECLARE MYSQL_VAR_WB4TQB INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COUNT(*)
    INTO MYSQL_VAR_E9L4BW, MYSQL_VAR_GHB3AO
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_WB4TQB = (MYSQL_VAR_E9L4BW / 100) + (MYSQL_VAR_GHB3AO * 5);

    RETURN MYSQL_FUNC_UI6FD0(20, 21);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WTOM4W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WTOM4W(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XVDZJ1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_LSAXX6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_86K3GU INT DEFAULT 0;
    DECLARE MYSQL_VAR_IJVG1M INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0), COALESCE(SPENT_AMOUNT, 0)
    INTO MYSQL_VAR_XVDZJ1, MYSQL_VAR_LSAXX6
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_XVDZJ1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_86K3GU = MYSQL_VAR_XVDZJ1 - MYSQL_VAR_LSAXX6;
    SET MYSQL_VAR_IJVG1M = (MYSQL_VAR_LSAXX6 * 100) / MYSQL_VAR_XVDZJ1;

    RETURN CAST(MYSQL_VAR_IJVG1M AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PVPOWA(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V72520 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_JAKCJC INT DEFAULT 0;

    SELECT MYSQL_FUNC_Z73713(10)
    INTO MYSQL_VAR_V72520, MYSQL_VAR_JAKCJC
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_JAKCJC = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_WTOM4W(20);
END//

DELIMITER ;