/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_LJ4FXY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LJ4FXY(SUBSCRIPTION_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6P68MS VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_AGTFG0 INT DEFAULT 30;
    DECLARE MYSQL_VAR_VWE7NU INT DEFAULT 5;
    DECLARE MYSQL_VAR_1EUANI INT DEFAULT 500;
    DECLARE MYSQL_VAR_1F1A55 INT DEFAULT 0;
    DECLARE MYSQL_VAR_G1C16G INT DEFAULT 0;
    DECLARE MYSQL_VAR_QIFV6E INT DEFAULT 0;

    SELECT PLAN_TYPE, MONTHLY_FEE
    INTO MYSQL_VAR_6P68MS, MYSQL_VAR_AGTFG0
    FROM SUBSCRIPTIONS
    WHERE SUBSCRIPTION_ID = SUBSCRIPTION_ID_PARAM;

    SET MYSQL_VAR_VWE7NU = CASE MYSQL_VAR_6P68MS
        WHEN 'PREMIUM' THEN 50
        WHEN 'GOLD' THEN 20
        WHEN 'SILVER' THEN 10
        ELSE 5
    END;

    SET MYSQL_VAR_1EUANI = CASE MYSQL_VAR_6P68MS
        WHEN 'PREMIUM' THEN 2000
        WHEN 'GOLD' THEN 1000
        WHEN 'SILVER' THEN 500
        ELSE 200
    END;

    SELECT COALESCE(SUM(MB_USED), 0), COALESCE(SUM(CALL_MINUTES), 0)
    INTO MYSQL_VAR_1F1A55, MYSQL_VAR_G1C16G
    FROM USAGE_RECORDS
    WHERE SUBSCRIPTION_ID = SUBSCRIPTION_ID_PARAM
      AND USAGE_DATE >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH);

    IF MYSQL_VAR_1F1A55 > MYSQL_VAR_VWE7NU * 1024 THEN
        SET MYSQL_VAR_QIFV6E = MYSQL_VAR_QIFV6E + ((MYSQL_VAR_1F1A55 - MYSQL_VAR_VWE7NU * 1024) / 1024) * 10;
    END IF;

    IF MYSQL_VAR_G1C16G > MYSQL_VAR_1EUANI THEN
        SET MYSQL_VAR_QIFV6E = MYSQL_VAR_QIFV6E + ((MYSQL_VAR_G1C16G - MYSQL_VAR_1EUANI) / 100) * 5;
    END IF;

    RETURN MYSQL_VAR_QIFV6E;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_66V3GM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_66V3GM(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5WLDWE DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_5WLDWE
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_5WLDWE);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_255SSF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_255SSF(RES_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8VX5E4 DATE;
    DECLARE MYSQL_VAR_QUP87M DATE;
    DECLARE MYSQL_VAR_IZE4ZC INT DEFAULT 0;

    SELECT (MYSQL_FUNC_66V3GM(30) - (0) + COALESCE(CHECK_IN_DATE, CHECK_OUT_DATE, 0))
    INTO MYSQL_VAR_8VX5E4, MYSQL_VAR_QUP87M
    FROM RESERVATIONS
    WHERE RES_ID = RES_ID_PARAM;

    IF MYSQL_VAR_8VX5E4 IS NULL OR MYSQL_VAR_QUP87M IS NULL THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_IZE4ZC = MYSQL_FUNC_LJ4FXY(10);

    IF MYSQL_VAR_IZE4ZC < 0 THEN
        SET MYSQL_VAR_IZE4ZC = 0;
    END IF;

    RETURN MYSQL_VAR_IZE4ZC;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0ZK3C6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0ZK3C6() RETURNS INT
BEGIN
RETURN (MYSQL_FUNC_255SSF(10) - (0) + COALESCE(0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IVVX4J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IVVX4J(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DRLO8Y DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_DRLO8Y
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_DRLO8Y / 50);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_V4Z76I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_V4Z76I(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2D7XB1 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_IVVX4J(10) - (0) + COALESCE(COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0), 0))
    INTO MYSQL_VAR_2D7XB1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_2D7XB1 * 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_D1P1JS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_D1P1JS(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WVWSY7 VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_FVA3JA INT DEFAULT 0;
    DECLARE MYSQL_VAR_UX5PZ9 INT DEFAULT 0;

    SELECT STATUS, COALESCE(BUDGET, 0), DATEDIFF(CURDATE(), START_DATE)
    INTO MYSQL_VAR_WVWSY7, MYSQL_VAR_FVA3JA, MYSQL_VAR_UX5PZ9
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_WVWSY7 != 'ACTIVE' OR MYSQL_VAR_UX5PZ9 = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_FVA3JA / MYSQL_VAR_UX5PZ9;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PK1G4W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PK1G4W(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PSJMKN INT DEFAULT 0;
    DECLARE MYSQL_VAR_4CSAH5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZZPCG2 INT DEFAULT 0;

    SET MYSQL_VAR_4CSAH5 = POW(A, 3) + POW(B, 3);

    IF MYSQL_VAR_4CSAH5 > 0 THEN
        SET MYSQL_VAR_ZZPCG2 = FLOOR(SQRT(MYSQL_VAR_4CSAH5));
    END IF;

    SET MYSQL_VAR_PSJMKN = (A * B) + MYSQL_VAR_ZZPCG2 + (A % B);

    RETURN MYSQL_VAR_PSJMKN;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4CZBJU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4CZBJU(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KG9NFH INT DEFAULT 0;

    SELECT (MYSQL_FUNC_PK1G4W(30, 31) - (0) + COALESCE(COALESCE(LEAD_TIME_DAYS, 7), 0))
    INTO MYSQL_VAR_KG9NFH
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_D1P1JS(10) - (0) + COALESCE(GREATEST(100 - (MYSQL_VAR_KG9NFH * 7), 0), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LK34S6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LK34S6(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CG9N8K INT DEFAULT 0;
    DECLARE MYSQL_VAR_MGE75V INT DEFAULT 0;
    DECLARE MYSQL_VAR_AQ2C9G INT DEFAULT 0;
    DECLARE MYSQL_VAR_MYL7ZJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_8QRP9P INT DEFAULT 0;

    SELECT COALESCE(SALARY, 50000), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_CG9N8K, MYSQL_VAR_MGE75V
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_AQ2C9G
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_MYL7ZJ
    FROM EMPLOYEES E
    JOIN DEPARTMENTS D ON E.DEPT_ID = D.DEPT_ID
    WHERE D.DEPT_ID = (SELECT DEPT_ID FROM EMPLOYEES WHERE EMP_ID = EMP_ID_PARAM);

    SET MYSQL_VAR_8QRP9P = (MYSQL_VAR_MGE75V * 10) + (MYSQL_VAR_AQ2C9G * 15) + ((MYSQL_VAR_MYL7ZJ * 100) / 1000);

    IF MYSQL_VAR_CG9N8K > 100000 THEN
        SET MYSQL_VAR_8QRP9P = MYSQL_VAR_8QRP9P + 20;
    END IF;

    RETURN MYSQL_VAR_8QRP9P;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0BVFHQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0BVFHQ(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HEHOUW DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_BAGU3U DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_PYSNT7 INT DEFAULT 0;

    SELECT COALESCE(SHIPPING_COST, 0), COALESCE(TOTAL_AMOUNT, 1)
    INTO MYSQL_VAR_HEHOUW, MYSQL_VAR_BAGU3U
    FROM ORDERS O
    LEFT JOIN SHIPMENTS S ON O.ORDER_ID = S.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_PYSNT7 = (MYSQL_VAR_HEHOUW * 100) / MYSQL_VAR_BAGU3U;

    RETURN MYSQL_VAR_PYSNT7;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PLD579----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PLD579(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FBK5LD DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_R17YYA DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4JWU41 INT DEFAULT 0;

    SELECT COALESCE(AVG(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_FBK5LD
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
    AND ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 90 DAY);

    SELECT COALESCE(AVG(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_R17YYA
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
    AND ORDER_DATE < DATE_SUB(CURDATE(), INTERVAL 90 DAY);

    IF MYSQL_VAR_R17YYA = 0 THEN
        RETURN 100;
    END IF;

    SET MYSQL_VAR_4JWU41 = ((MYSQL_VAR_FBK5LD - MYSQL_VAR_R17YYA) * 100) / MYSQL_VAR_R17YYA;

    RETURN MYSQL_VAR_4JWU41;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1Z5WIN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1Z5WIN(METER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4G0B7X INT DEFAULT 5;
    DECLARE MYSQL_VAR_XH1JAY INT DEFAULT 80;
    DECLARE MYSQL_VAR_5BIFDA INT DEFAULT 0;
    DECLARE MYSQL_VAR_JNEAZV INT DEFAULT 0;

    SELECT (MYSQL_FUNC_4CZBJU(30) - (0) + COALESCE(COALESCE(CAPACITY_KW, 5), COALESCE(EFFICIENCY_PERCENT, 80), 0))
    INTO MYSQL_VAR_4G0B7X, MYSQL_VAR_XH1JAY
    FROM SOLAR_PANELS
    WHERE METER_ID = METER_ID_PARAM;

    SELECT (MYSQL_FUNC_PLD579(30) - (0) + COALESCE(COALESCE(CURRENT_READING, 0), 0)) INTO MYSQL_VAR_5BIFDA
    FROM ELECTRICITY_METERS
    WHERE METER_ID = METER_ID_PARAM;

    SET MYSQL_VAR_JNEAZV = MYSQL_FUNC_LK34S6(10);

    RETURN (MYSQL_FUNC_0BVFHQ(30) - (0) + COALESCE(CAST(MYSQL_VAR_JNEAZV AS SIGNED), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S7A9RG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S7A9RG(NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2E76FD INT DEFAULT 0;
    DECLARE MYSQL_VAR_RO6869 INT;
    DECLARE MYSQL_VAR_4VQQRL INT;

    SET MYSQL_VAR_4VQQRL = ABS(NUM);

    SUM_LOOP: WHILE MYSQL_VAR_4VQQRL > 0 DO
        SET MYSQL_VAR_RO6869 = MYSQL_VAR_4VQQRL MOD 10;
        SET MYSQL_VAR_2E76FD = MYSQL_VAR_2E76FD + MYSQL_VAR_RO6869;
        SET MYSQL_VAR_4VQQRL = MYSQL_VAR_4VQQRL DIV 10;
    END WHILE SUM_LOOP;

    RETURN MYSQL_VAR_2E76FD;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9JOOKN(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3OFBI1 INT DEFAULT 10;
    DECLARE MYSQL_VAR_NMDJMV DECIMAL(6,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_7LQP6W DECIMAL(6,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_LBAN9J DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_KTYO98 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_S7A9RG(30) - (0) + COALESCE(COALESCE(DATA_LIMIT_GB, 10), 0))
    INTO MYSQL_VAR_3OFBI1
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_1Z5WIN(20) - (0) + COALESCE(COALESCE(AVG(BANDWIDTH_MBPS), 0), COALESCE(MAX(BANDWIDTH_MBPS), 0), 0))
    INTO MYSQL_VAR_NMDJMV, MYSQL_VAR_7LQP6W
    FROM USAGE_LOGS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND USAGE_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SELECT (MYSQL_FUNC_V4Z76I(20) - (0) + COALESCE(COALESCE(SUM(DATA_USED_GB), 0) / 30, 0))
    INTO MYSQL_VAR_LBAN9J
    FROM USAGE_LOGS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND USAGE_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SET MYSQL_VAR_KTYO98 = (MYSQL_VAR_NMDJMV * 10) + ((MYSQL_VAR_3OFBI1 - MYSQL_VAR_LBAN9J) * 5);

    IF MYSQL_VAR_7LQP6W > 100 THEN
        SET MYSQL_VAR_KTYO98 = MYSQL_VAR_KTYO98 + 15;
    END IF;

    RETURN (MYSQL_FUNC_0ZK3C6() - (0) + COALESCE(MYSQL_VAR_KTYO98, 0));
END//

DELIMITER ;