/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_ZXZAL3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZXZAL3(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OQOAIJ DATE;
    DECLARE MYSQL_VAR_AGD2WH INT DEFAULT 0;

    SELECT HIRE_DATE
    INTO MYSQL_VAR_OQOAIJ
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_AGD2WH = TIMESTAMPDIFF(YEAR, MYSQL_VAR_OQOAIJ, CURDATE());

    RETURN MYSQL_VAR_AGD2WH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RGNYV8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RGNYV8(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SSYYRT INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_SSYYRT
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_ZXZAL3(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IDH4E2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IDH4E2(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3LL683 INT DEFAULT 0;
    DECLARE MYSQL_VAR_CWCHS2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_DEEDER INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_3LL683
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_CWCHS2
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_3LL683 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_DEEDER = ((MYSQL_VAR_3LL683 - MYSQL_VAR_CWCHS2) * 100) / MYSQL_VAR_3LL683;

    RETURN MYSQL_VAR_DEEDER;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_N0F9GL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_N0F9GL(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2K3QWZ DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(PRICE, 0)
    INTO MYSQL_VAR_2K3QWZ
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_2K3QWZ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XU3QPQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XU3QPQ(DEPARTMENT_ID_PARAM INT, PERFORMANCE_RATING INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3DLSQC INT DEFAULT 0;
    DECLARE MYSQL_VAR_VP4G4I INT DEFAULT 1000;
    DECLARE MYSQL_VAR_F1UZQQ INT DEFAULT 0;

    SELECT COALESCE(AVG(SALARY), 0) INTO MYSQL_VAR_3DLSQC
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    CASE PERFORMANCE_RATING
        WHEN 5 THEN SET MYSQL_VAR_F1UZQQ = MYSQL_VAR_VP4G4I * 3;
        WHEN 4 THEN SET MYSQL_VAR_F1UZQQ = MYSQL_VAR_VP4G4I * 2;
        WHEN 3 THEN SET MYSQL_VAR_F1UZQQ = MYSQL_VAR_VP4G4I;
        WHEN 2 THEN SET MYSQL_VAR_F1UZQQ = MYSQL_VAR_VP4G4I / 2;
        ELSE SET MYSQL_VAR_F1UZQQ = 0;
    END CASE;

    RETURN MYSQL_VAR_F1UZQQ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NWST3M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NWST3M(CONSULTANT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5H8G79 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y1EG4G INT DEFAULT 0;
    DECLARE MYSQL_VAR_LYTA8Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_81LXGJ INT DEFAULT 0;

    SELECT MYSQL_FUNC_N0F9GL(30)
    INTO MYSQL_VAR_5H8G79, MYSQL_VAR_Y1EG4G
    FROM CONSULTING_ENGAGEMENTS
    WHERE CONSULTANT_ID = CONSULTANT_ID_PARAM
      AND END_DATE >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);

    SELECT COUNT(*) INTO MYSQL_VAR_81LXGJ
    FROM CONSULTING_ENGAGEMENTS
    WHERE CONSULTANT_ID = CONSULTANT_ID_PARAM
      AND END_DATE >= CURDATE();

    SET MYSQL_VAR_LYTA8Z = MYSQL_VAR_5H8G79 * MYSQL_VAR_Y1EG4G;

    IF MYSQL_VAR_81LXGJ >= 3 THEN
        SET MYSQL_VAR_LYTA8Z = MYSQL_VAR_LYTA8Z + (MYSQL_VAR_LYTA8Z * 10 / 100);
    END IF;

    RETURN MYSQL_FUNC_XU3QPQ(30, 31);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7YMH98----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7YMH98(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XZ550I DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_Q0SE34 INT DEFAULT 0;

    SELECT MYSQL_FUNC_IDH4E2(30)
    INTO MYSQL_VAR_XZ550I
    FROM CONVERSIONS C
    JOIN CAMPAIGNS CAMP ON C.CAMPAIGN_ID = CAMP.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SET MYSQL_VAR_Q0SE34 = MYSQL_FUNC_NWST3M(10);

    RETURN MYSQL_FUNC_RGNYV8(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TVKE4A----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TVKE4A(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HZZVWT INT DEFAULT 0;
    DECLARE MYSQL_VAR_RFWOR9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_U1PGX0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_KJ6XFF INT DEFAULT FALSE;
    DECLARE MYSQL_VAR_VK17XZ INT;

    DECLARE MYSQL_VAR_FQ22JH CURSOR FOR
        SELECT DISTINCT O.ORDER_ID FROM ORDERS O
        JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
        JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
        WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM AND O.STATUS = 'COMPLETED';

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MYSQL_VAR_KJ6XFF = TRUE;

    OPEN MYSQL_VAR_FQ22JH;

    ORDER_LOOP: LOOP
        FETCH MYSQL_VAR_FQ22JH INTO MYSQL_VAR_VK17XZ;
        IF MYSQL_VAR_KJ6XFF THEN
            LEAVE ORDER_LOOP;
        END IF;

        SELECT SUM(OI.QUANTITY * OI.UNIT_PRICE) INTO MYSQL_VAR_HZZVWT
        FROM ORDER_ITEMS OI
        WHERE OI.ORDER_ID = MYSQL_VAR_VK17XZ;

        SET MYSQL_VAR_U1PGX0 = MYSQL_VAR_U1PGX0 + 1;
    END LOOP ORDER_LOOP;

    CLOSE MYSQL_VAR_FQ22JH;

    RETURN COALESCE(MYSQL_VAR_HZZVWT, 0) + (MYSQL_VAR_U1PGX0 * 100);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WAWX6T() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D9LLWW INT DEFAULT 0;
    SELECT MYSQL_FUNC_TVKE4A(10) INTO MYSQL_VAR_D9LLWW FROM TABLE_F5DBG8.`TABLE3`;
    RETURN MYSQL_FUNC_7YMH98(10);
END//

DELIMITER ;