/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_3y0d8a (
    produto_id INT,
    Quantidade_produto INT
);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (1, 10);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (2, 5);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (3, 0);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_XDH86B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XDH86B(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_196Y6N DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4TFLJ6 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_32T8MD INT DEFAULT 0;

    SELECT COALESCE(SUM(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_196Y6N
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_4TFLJ6
    FROM ORDERS;

    IF MYSQL_VAR_4TFLJ6 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_32T8MD = (MYSQL_VAR_196Y6N * 100) / MYSQL_VAR_4TFLJ6;

    RETURN MYSQL_VAR_32T8MD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6GFJPT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6GFJPT(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RCKQFC INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y3FSR0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_TBCIYZ INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_RCKQFC
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SHIPPING_COST, 0)
    INTO MYSQL_VAR_Y3FSR0
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_RCKQFC = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_TBCIYZ = (MYSQL_VAR_Y3FSR0 * 100) / MYSQL_VAR_RCKQFC;

    RETURN MYSQL_VAR_TBCIYZ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_H1LK9S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H1LK9S(ORDER_ID_PARAM INT, TAX_RATE_PERCENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TZ80F2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_160G6V INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_TZ80F2
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_160G6V = (MYSQL_VAR_TZ80F2 * TAX_RATE_PERCENT) / 100;

    RETURN MYSQL_VAR_160G6V;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MH0A4X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MH0A4X(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WP4S4Q DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_H1LK9S(30, 31) - (0) + COALESCE(COALESCE(SALARY, 0), 0))
    INTO MYSQL_VAR_WP4S4Q
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_WP4S4Q / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RI8G77----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RI8G77(DEPT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NDVD1Q INT DEFAULT 0;
    DECLARE MYSQL_VAR_5QLGY1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_F4TUZ0 INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_NDVD1Q
    FROM DEPARTMENTS
    WHERE DEPT_ID = DEPT_ID_PARAM;

    SELECT (MYSQL_FUNC_6GFJPT(20) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_5QLGY1
    FROM EMPLOYEES
    WHERE DEPT_ID = DEPT_ID_PARAM;

    IF MYSQL_VAR_5QLGY1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_F4TUZ0 = MYSQL_FUNC_XDH86B('test_2_0');

    RETURN (MYSQL_FUNC_MH0A4X(20) - (0) + COALESCE(MYSQL_VAR_F4TUZ0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NMV4W2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NMV4W2(APPT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OGXLEB INT DEFAULT 0;
    DECLARE MYSQL_VAR_O7I7IW INT DEFAULT 0;
    DECLARE MYSQL_VAR_YE93EU INT DEFAULT 0;

    SELECT COALESCE(SCHEDULED_TIME, 0), COALESCE(DURATION_MINUTES, 30)
    INTO MYSQL_VAR_OGXLEB, MYSQL_VAR_O7I7IW
    FROM APPOINTMENTS
    WHERE APPT_ID = APPT_ID_PARAM;

    IF MYSQL_VAR_OGXLEB = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_YE93EU = MYSQL_VAR_OGXLEB + MYSQL_VAR_O7I7IW;

    RETURN MYSQL_VAR_YE93EU;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_38YI9N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_38YI9N(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_L3JZEV INT DEFAULT 0;
    DECLARE MYSQL_VAR_WIMMH2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_KB5TD8 DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(*)
    INTO MYSQL_VAR_L3JZEV
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT DATEDIFF(CURDATE(), REGISTRATION_DATE)
    INTO MYSQL_VAR_WIMMH2
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_WIMMH2 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KB5TD8 = (MYSQL_VAR_L3JZEV * 365.0) / MYSQL_VAR_WIMMH2;

    RETURN FLOOR(MYSQL_VAR_KB5TD8);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4G9A5W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4G9A5W(PROD_ID INT, QTDE_COMPRADA INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4MCEPB INT;
    DECLARE MYSQL_VAR_ZAJVJ3 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_38YI9N(20) - (0) + COALESCE(COUNT(*), 0)) INTO MYSQL_VAR_4MCEPB FROM TABLE_3Y0D8A WHERE PRODUTO_ID = PROD_ID;

    IF MYSQL_VAR_4MCEPB > 0 THEN
        UPDATE TABLE_3Y0D8A SET QUANTIDADE_PRODUTO = QUANTIDADE_PRODUTO + QTDE_COMPRADA
        WHERE PRODUTO_ID = PROD_ID;
        SET MYSQL_VAR_ZAJVJ3 = ROW_COUNT();
    ELSE
        INSERT INTO TABLE_3Y0D8A (PRODUTO_ID, QUANTIDADE_PRODUTO) VALUES (1, NULL);
        SET MYSQL_VAR_ZAJVJ3 = 1;
    END IF;

    RETURN (MYSQL_FUNC_NMV4W2(10) - (0) + COALESCE(MYSQL_VAR_ZAJVJ3, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_59NFQ5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_59NFQ5(INVESTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_F08WT3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_UA2Y7Z DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_9550QI INT DEFAULT 0;
    DECLARE MYSQL_VAR_22PQ2Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_XK7HVO INT DEFAULT 0;

    SELECT COALESCE(PRINCIPAL, 0), COALESCE(INTEREST_RATE, 0.00), COALESCE(TERM_MONTHS, 12)
    INTO MYSQL_VAR_F08WT3, MYSQL_VAR_UA2Y7Z, MYSQL_VAR_9550QI
    FROM INVESTMENTS
    WHERE INVESTMENT_ID = INVESTMENT_ID_PARAM;

    SET MYSQL_VAR_XK7HVO = (MYSQL_VAR_F08WT3 * MYSQL_VAR_UA2Y7Z * MYSQL_VAR_9550QI) / 1200;
    SET MYSQL_VAR_22PQ2Z = MYSQL_VAR_F08WT3 + MYSQL_VAR_XK7HVO;

    RETURN FLOOR(MYSQL_VAR_22PQ2Z);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0R457V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0R457V(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_P6NFSO INT DEFAULT 0;

    SELECT QUARTER(REGISTRATION_DATE)
    INTO MYSQL_VAR_P6NFSO
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_P6NFSO;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4205EF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4205EF(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UFMR82 INT DEFAULT 0;
    DECLARE MYSQL_VAR_1HY73Q INT DEFAULT 0;
    DECLARE MYSQL_VAR_BFOH2I INT DEFAULT 0;
    DECLARE MYSQL_VAR_X0ATDV INT DEFAULT 0;

    SELECT COALESCE(PRICE, 0), COALESCE(STOCK_QUANTITY, 0), COALESCE(REORDER_LEVEL, 0)
    INTO MYSQL_VAR_UFMR82, MYSQL_VAR_1HY73Q, MYSQL_VAR_BFOH2I
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_X0ATDV = MYSQL_VAR_UFMR82 * MYSQL_VAR_1HY73Q;

    IF MYSQL_VAR_1HY73Q < MYSQL_VAR_BFOH2I THEN
        SET MYSQL_VAR_X0ATDV = MYSQL_VAR_X0ATDV + 1000;
    END IF;

    RETURN MYSQL_VAR_X0ATDV;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_01PZD0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_01PZD0() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IUY7VZ INT DEFAULT 0;
    
    SELECT (MYSQL_FUNC_0R457V(10) - (0) + COALESCE(COUNT(*), 0)) INTO MYSQL_VAR_IUY7VZ FROM TABLE_TL7J49.`TABLE3`;
    
    RETURN (MYSQL_FUNC_4205EF(30) - (0) + COALESCE(MYSQL_VAR_IUY7VZ, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1XM6OW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1XM6OW(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FI3ATH VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_8PFH1K INT DEFAULT 0;
    DECLARE MYSQL_VAR_A908W4 INT DEFAULT 0;

    SELECT STATUS, COALESCE(BUDGET, 0), DATEDIFF(CURDATE(), START_DATE)
    INTO MYSQL_VAR_FI3ATH, MYSQL_VAR_8PFH1K, MYSQL_VAR_A908W4
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_FI3ATH != 'ACTIVE' OR MYSQL_VAR_A908W4 = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_8PFH1K / MYSQL_VAR_A908W4;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QF75ZL(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IIZ3PU INT DEFAULT 0;
    DECLARE MYSQL_VAR_5M479K INT DEFAULT 0;
    DECLARE MYSQL_VAR_16INTN INT DEFAULT 0;
    DECLARE MYSQL_VAR_877EWB INT DEFAULT 0;
    DECLARE MYSQL_VAR_LW4AXJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_HZ13VI INT DEFAULT 0;

    SELECT (MYSQL_FUNC_1XM6OW(20) - (0) + COALESCE(COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COALESCE(DISCOUNT_PERCENT, 0), COALESCE(SHIPPING_COST, 0), 0))
    INTO MYSQL_VAR_IIZ3PU, MYSQL_VAR_5M479K, MYSQL_VAR_16INTN
    FROM ORDER_ITEMS OI
    JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_5M479K = COALESCE(
        (SELECT DISCOUNT_PERCENT FROM ORDERS WHERE ORDER_ID = ORDER_ID_PARAM), 0
    );

    SET MYSQL_VAR_877EWB = MYSQL_FUNC_01PZD0();

    SELECT (MYSQL_FUNC_4G9A5W(10, 11) - (0) + COALESCE(COALESCE(TOTAL_AMOUNT, 0) - MYSQL_VAR_877EWB, 0))
    INTO MYSQL_VAR_LW4AXJ
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_877EWB = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_HZ13VI = MYSQL_FUNC_RI8G77(30);

    RETURN (MYSQL_FUNC_59NFQ5(10) - (0) + COALESCE(MYSQL_VAR_HZ13VI, 0));
END//

DELIMITER ;