/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Seed Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_REBZ31(REPAIR_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H9AIMP INT DEFAULT 0;
    DECLARE MYSQL_VAR_5KYPRJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_76A8VI INT DEFAULT 75;
    DECLARE MYSQL_VAR_RRF7MC INT DEFAULT 50;
    DECLARE MYSQL_VAR_ZSW9FF INT DEFAULT 0;

    SELECT COALESCE(PARTS_COST, 0), COALESCE(LABOR_HOURS, 0), COALESCE(LABOR_RATE, 75)
    INTO MYSQL_VAR_H9AIMP, MYSQL_VAR_5KYPRJ, MYSQL_VAR_76A8VI
    FROM APPLIANCE_REPAIRS
    WHERE REPAIR_ID = REPAIR_ID_PARAM;

    SET MYSQL_VAR_ZSW9FF = MYSQL_VAR_H9AIMP + (MYSQL_VAR_5KYPRJ * MYSQL_VAR_76A8VI) + MYSQL_VAR_RRF7MC;

    RETURN CAST(MYSQL_VAR_ZSW9FF AS SIGNED);
END//

DELIMITER ;