/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_gbxzq5 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    make VARCHAR(20),
    milage INT
);
INSERT INTO table_gbxzq5 (make, milage) VALUES 
('Toyota', 50000),
('Honda', 75000),
('Toyota', 30000),
('Ford', 100000),
('Toyota', 90000);

CREATE TABLE IF NOT EXISTS table_3y0d8a (
    produto_id INT,
    Quantidade_produto INT
);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (1, 10);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (2, 5);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (3, 0);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_S0IXK6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S0IXK6(A INT, B INT) RETURNS INT
BEGIN
RETURN A * B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1PRWD4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1PRWD4(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_89SLRQ INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_89SLRQ
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'ACTIVE';

    RETURN MYSQL_VAR_89SLRQ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_55YXPD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_55YXPD(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AQ7TMG VARCHAR(50) DEFAULT '';
    DECLARE MYSQL_VAR_T7I488 INT DEFAULT 0;
    DECLARE MYSQL_VAR_478WRH INT DEFAULT 0;

    SELECT COUNTRY
    INTO MYSQL_VAR_AQ7TMG
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COALESCE(AVG(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_T7I488
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT COALESCE(AVG(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_478WRH
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = MYSQL_VAR_AQ7TMG AND O.STATUS = 'COMPLETED';

    IF MYSQL_VAR_478WRH = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_T7I488 * 100) / MYSQL_VAR_478WRH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JDCNYQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JDCNYQ(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IOD8GB INT DEFAULT 0;
    DECLARE MYSQL_VAR_CH1CXN INT;
    DECLARE MYSQL_VAR_9Q0AM7 INT;
    DECLARE MYSQL_VAR_AGBUBI INT DEFAULT 100;
    DECLARE MYSQL_VAR_7Z54LF INT DEFAULT 0;

    SET MYSQL_VAR_9Q0AM7 = EMP_ID_PARAM;

    LEVEL_LOOP: WHILE MYSQL_VAR_9Q0AM7 IS NOT NULL AND MYSQL_VAR_7Z54LF < MYSQL_VAR_AGBUBI DO
        SELECT MANAGER_ID INTO MYSQL_VAR_CH1CXN
        FROM EMPLOYEES
        WHERE EMP_ID = MYSQL_VAR_9Q0AM7;

        IF MYSQL_VAR_CH1CXN IS NULL THEN
            LEAVE LEVEL_LOOP;
        END IF;

        SET MYSQL_VAR_IOD8GB = MYSQL_VAR_IOD8GB + 1;
        SET MYSQL_VAR_9Q0AM7 = MYSQL_VAR_CH1CXN;
        SET MYSQL_VAR_7Z54LF = MYSQL_VAR_7Z54LF + 1;
    END WHILE LEVEL_LOOP;

    RETURN MYSQL_VAR_IOD8GB;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4CZBJU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4CZBJU(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KG9NFH INT DEFAULT 0;

    SELECT MYSQL_FUNC_JDCNYQ(10)
    INTO MYSQL_VAR_KG9NFH
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_FUNC_55YXPD(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1ENVDN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1ENVDN(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GUQNF5 INT DEFAULT 0;

    SELECT MONTH(START_DATE)
    INTO MYSQL_VAR_GUQNF5
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN MYSQL_VAR_GUQNF5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IK4G9R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IK4G9R(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OE9SLC DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_OE9SLC
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_OE9SLC * 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4G9A5W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4G9A5W(PROD_ID INT, QTDE_COMPRADA INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4MCEPB INT;
    DECLARE MYSQL_VAR_ZAJVJ3 INT DEFAULT 0;

    SELECT COUNT(*) INTO MYSQL_VAR_4MCEPB FROM TABLE_3Y0D8A WHERE PRODUTO_ID = PROD_ID;

    IF MYSQL_VAR_4MCEPB > 0 THEN
        UPDATE TABLE_3Y0D8A SET QUANTIDADE_PRODUTO = QUANTIDADE_PRODUTO + QTDE_COMPRADA
        WHERE PRODUTO_ID = PROD_ID;
        SET MYSQL_VAR_ZAJVJ3 = ROW_COUNT();
    ELSE
        INSERT INTO TABLE_3Y0D8A (PRODUTO_ID, QUANTIDADE_PRODUTO) VALUES (1, NULL);
        SET MYSQL_VAR_ZAJVJ3 = 1;
    END IF;

    RETURN MYSQL_FUNC_IK4G9R(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MLMFPI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MLMFPI(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RWN45V DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_C8KZ3I DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4VO05E DECIMAL(5,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(SALARY), 0)
    INTO MYSQL_VAR_RWN45V
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_C8KZ3I
    FROM DEPARTMENTS
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    IF MYSQL_VAR_C8KZ3I = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_4VO05E = (MYSQL_VAR_RWN45V / MYSQL_VAR_C8KZ3I) * 100;

    RETURN FLOOR(MYSQL_VAR_4VO05E);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YUZCDH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YUZCDH(MK_INT INT, ML INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_60GECU VARCHAR(20);
    DECLARE MYSQL_VAR_YAY922 INT DEFAULT 0;
    
    SET MYSQL_VAR_60GECU = CAST(MK_INT AS CHAR);
    
    SELECT COUNT(*) INTO MYSQL_VAR_YAY922 
    FROM TABLE_GBXZQ5 
    WHERE MAKE LIKE MYSQL_VAR_60GECU AND MILAGE < ML 
    ORDER BY MILAGE;
    
    RETURN MYSQL_VAR_YAY922;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IIEQQZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IIEQQZ(AD_GROUP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XRRVR7 INT DEFAULT 5;
    DECLARE MYSQL_VAR_3OK6BW DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_HSTRCP DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_I5WTUT INT DEFAULT 0;
    DECLARE MYSQL_VAR_XJVDDX INT DEFAULT 0;
    DECLARE MYSQL_VAR_W2JCRK INT DEFAULT 0;
    DECLARE MYSQL_VAR_YNLDWY INT DEFAULT 0;

    SELECT MYSQL_FUNC_4G9A5W(20, 21)
    INTO MYSQL_VAR_I5WTUT, MYSQL_VAR_XJVDDX, MYSQL_VAR_W2JCRK
    FROM AD_GROUPS AG
    JOIN CAMPAIGNS C ON AG.CAMPAIGN_ID = C.CAMPAIGN_ID
    WHERE AG.AD_GROUP_ID = AD_GROUP_ID_PARAM;

    SELECT MYSQL_FUNC_MLMFPI(30)
    INTO MYSQL_VAR_XRRVR7
    FROM AD_GROUPS
    WHERE AD_GROUP_ID = AD_GROUP_ID_PARAM;

    IF MYSQL_VAR_I5WTUT > 0 THEN
        SET MYSQL_VAR_3OK6BW = (MYSQL_VAR_XJVDDX * 100.0) / MYSQL_VAR_I5WTUT;
    END IF;

    IF MYSQL_VAR_XJVDDX > 0 THEN
        SET MYSQL_VAR_HSTRCP = (MYSQL_VAR_W2JCRK * 100.0) / MYSQL_VAR_XJVDDX;
    END IF;

    SET MYSQL_VAR_YNLDWY = MYSQL_FUNC_1ENVDN(20);

    RETURN MYSQL_FUNC_YUZCDH(30, 31);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TRMH9I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TRMH9I(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8KOQGQ INT DEFAULT 2;
    DECLARE MYSQL_VAR_LA6QNT INT DEFAULT 0;

    IF N <= 1 THEN RETURN 0; END IF;
    IF N <= 3 THEN RETURN 1; END IF;
    IF N % 2 = 0 OR N % 3 = 0 THEN RETURN 0; END IF;

    SET MYSQL_VAR_LA6QNT = FLOOR(SQRT(N));
    SET MYSQL_VAR_8KOQGQ = 5;

    PRIME_LOOP: WHILE MYSQL_VAR_8KOQGQ <= MYSQL_VAR_LA6QNT DO
        IF N % MYSQL_VAR_8KOQGQ = 0 OR N % (MYSQL_VAR_8KOQGQ + 2) = 0 THEN
            RETURN 0;
        END IF;
        SET MYSQL_VAR_8KOQGQ = MYSQL_VAR_8KOQGQ + 6;
    END WHILE PRIME_LOOP;

    RETURN 1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_O7MD2W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_O7MD2W(ARR_SIZE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RZD847 INT DEFAULT 0;
    DECLARE MYSQL_VAR_OJUMN1 INT DEFAULT 1;
    DECLARE MYSQL_VAR_JFINNM INT DEFAULT 0;

    IF ARR_SIZE <= 0 OR ARR_SIZE > 10000 THEN
        RETURN 0;
    END IF;

    CALC_LOOP: WHILE MYSQL_VAR_OJUMN1 <= ARR_SIZE DO
        SET MYSQL_VAR_JFINNM = MYSQL_VAR_OJUMN1 * 2;
        SET MYSQL_VAR_RZD847 = MYSQL_VAR_RZD847 + MYSQL_VAR_JFINNM;
        SET MYSQL_VAR_OJUMN1 = MYSQL_VAR_OJUMN1 + 1;
    END WHILE CALC_LOOP;

    RETURN MYSQL_VAR_RZD847;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MOF0FP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MOF0FP(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_801N2H VARCHAR(20) DEFAULT 'BRONZE';
    DECLARE MYSQL_VAR_5FGSYX INT DEFAULT 0;
    DECLARE MYSQL_VAR_Q12YNR INT DEFAULT 0;
    DECLARE MYSQL_VAR_G08AZ2 INT DEFAULT 0;

    SELECT MYSQL_FUNC_TRMH9I(10)
    INTO MYSQL_VAR_801N2H
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MYSQL_FUNC_O7MD2W(30)
    INTO MYSQL_VAR_5FGSYX, MYSQL_VAR_Q12YNR
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SET MYSQL_VAR_G08AZ2 = MYSQL_FUNC_IIEQQZ(20);

    CASE MYSQL_VAR_801N2H
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_G08AZ2 = MYSQL_VAR_G08AZ2 + 50;
        WHEN 'GOLD' THEN SET MYSQL_VAR_G08AZ2 = MYSQL_FUNC_1PRWD4(10);
        WHEN 'SILVER' THEN SET MYSQL_VAR_G08AZ2 = MYSQL_FUNC_S0IXK6(10, 11);
        ELSE SET MYSQL_VAR_G08AZ2 = MYSQL_VAR_G08AZ2 + 5;
    END CASE;

    RETURN MYSQL_FUNC_4CZBJU(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TXZCKT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TXZCKT(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H6L1SR DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_FQYUQD INT DEFAULT 0;
    DECLARE MYSQL_VAR_WXTAFM INT DEFAULT 0;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_H6L1SR
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_FQYUQD
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()) >= 5;

    SET MYSQL_VAR_WXTAFM = (MYSQL_VAR_H6L1SR * 10) + (MYSQL_VAR_FQYUQD * 15);

    RETURN MYSQL_VAR_WXTAFM;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GB04P9(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8GOMLS DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_A6OV55 INT DEFAULT 0;
    DECLARE MYSQL_VAR_PZRX2M INT DEFAULT 0;
    DECLARE MYSQL_VAR_YF4EWQ INT DEFAULT 0;

    SELECT COALESCE(PERFORMANCE_RATING, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), COALESCE(SALARY, 0)
    INTO MYSQL_VAR_8GOMLS, MYSQL_VAR_A6OV55, MYSQL_VAR_PZRX2M
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_YF4EWQ = MYSQL_FUNC_MOF0FP(20);

    RETURN MYSQL_FUNC_TXZCKT(30);
END//

DELIMITER ;