/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_5WJCBM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5WJCBM() RETURNS INT
BEGIN
RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NFTN3V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NFTN3V() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AE4GM8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_1YVDYD BIGINT;
    DECLARE MYSQL_VAR_HR1WIY INT DEFAULT FALSE;
    DECLARE MYSQL_VAR_AL1AHG CURSOR FOR SELECT CBIGINT FROM TABLE_Z9PRQP.`TABLE3`;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MYSQL_VAR_HR1WIY = TRUE;
    
    OPEN MYSQL_VAR_AL1AHG;
    READ_LOOP: LOOP
        FETCH MYSQL_VAR_AL1AHG INTO MYSQL_VAR_1YVDYD;
        IF MYSQL_VAR_HR1WIY THEN
            LEAVE READ_LOOP;
        END IF;
        SET MYSQL_VAR_AE4GM8 = MYSQL_VAR_AE4GM8 + 1;
    END LOOP;
    CLOSE MYSQL_VAR_AL1AHG;
    
    RETURN MYSQL_VAR_AE4GM8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AYUY1Q----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AYUY1Q(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4PPG7W DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_4PPG7W
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_4PPG7W);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1764G2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1764G2() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NRUIOE INT DEFAULT 0;
    
    SELECT COUNT(*) INTO MYSQL_VAR_NRUIOE FROM TABLE_MC5B8G.`TABLE3`;
    
    RETURN MYSQL_VAR_NRUIOE;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_O6PGE6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_O6PGE6(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_81OIGW INT DEFAULT 0;
    DECLARE MYSQL_VAR_YM6GEV DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_GVUCLN DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_2YQA91 INT DEFAULT 50000;
    DECLARE MYSQL_VAR_YJ6AQX INT DEFAULT 0;

    SELECT MYSQL_FUNC_AYUY1Q(20)
    INTO MYSQL_VAR_81OIGW
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COALESCE(AVG_SALARY, 50000)
    INTO MYSQL_VAR_YM6GEV
    FROM DEPARTMENTS D
    JOIN EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
    WHERE E.EMP_ID = EMP_ID_PARAM;

    SELECT COALESCE(PERFORMANCE_RATING, 3.0)
    INTO MYSQL_VAR_GVUCLN
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_YJ6AQX = MYSQL_FUNC_1764G2();

    IF MYSQL_VAR_81OIGW < MYSQL_VAR_YM6GEV THEN
        SET MYSQL_VAR_YJ6AQX = MYSQL_VAR_YJ6AQX - 10;
    END IF;

    IF MYSQL_VAR_GVUCLN >= 4.5 THEN
        SET MYSQL_VAR_YJ6AQX = MYSQL_VAR_YJ6AQX + 15;
    END IF;

    RETURN MYSQL_VAR_YJ6AQX;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_36NBNB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_36NBNB(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YH3HUA INT DEFAULT 0;
    DECLARE MYSQL_VAR_VUWJL1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_KYFQC9 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_YH3HUA
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE());

    SELECT COUNT(*)
    INTO MYSQL_VAR_VUWJL1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE()) - 1;

    IF MYSQL_VAR_VUWJL1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KYFQC9 = MYSQL_FUNC_NFTN3V();

    RETURN MYSQL_FUNC_O6PGE6(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WF953G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WF953G(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GBLMVM INT DEFAULT 0;

    SELECT MYSQL_FUNC_5WJCBM()
    INTO MYSQL_VAR_GBLMVM
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_FUNC_36NBNB(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S0IXK6(A INT, B INT) RETURNS INT
BEGIN
RETURN MYSQL_FUNC_WF953G(20);
END//

DELIMITER ;