/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_svj7l3 (
    emp_no INT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS table_takpkm (
    emp_no INT,
    salary INT,
    FOREIGN KEY (emp_no) REFERENCES table_svj7l3(emp_no)
);
INSERT INTO table_svj7l3 (emp_no) VALUES (10001);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 60117);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 62102);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 66074);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_KO10I2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KO10I2(BASE INT, EXPONENT INT) RETURNS INT
BEGIN
IF EXPONENT < 0 THEN
        RETURN 0;
    END IF;

    IF EXPONENT = 0 THEN
        RETURN 1;
    END IF;

    IF EXPONENT = 1 THEN
        RETURN BASE;
    END IF;

    RETURN BASE * MYSQL_FUNC_KO10I2(BASE, EXPONENT - 1);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5JPH02----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5JPH02(P_EMP_NO INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_U5X0D5 INT;
    
    SELECT AVG(S.SALARY) INTO MYSQL_VAR_U5X0D5
    FROM TABLE_SVJ7L3 E
    JOIN TABLE_TAKPKM S ON E.EMP_NO = S.EMP_NO
    WHERE E.EMP_NO = P_EMP_NO;
    
    RETURN MYSQL_VAR_U5X0D5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ARETGO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ARETGO(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6SG0YZ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_Z5XWLF INT DEFAULT 0;
    DECLARE MYSQL_VAR_1HLST2 DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_5JPH02(20)
    INTO MYSQL_VAR_6SG0YZ, MYSQL_VAR_Z5XWLF
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_1HLST2 = MYSQL_FUNC_KO10I2(10, 11);

    RETURN FLOOR(MYSQL_VAR_1HLST2 / 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JBDOK5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JBDOK5(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Y4AQUI INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_Y4AQUI
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM
      AND REGISTRATION_DATE >= DATE_SUB(CURDATE(), INTERVAL 90 DAY);

    RETURN MYSQL_VAR_Y4AQUI;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FY5T57----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FY5T57(ORIGINAL_PRICE INT, DISCOUNT_PERCENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1X9WK5 INT DEFAULT 0;
    SET MYSQL_VAR_1X9WK5 = MYSQL_FUNC_JBDOK5('test_0_0');
    RETURN MYSQL_VAR_1X9WK5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FKEAXL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FKEAXL(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BOPUCI DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_BOPUCI
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_BOPUCI);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OJSZWT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OJSZWT(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_S30NFY DATE;

    SELECT REGISTRATION_DATE
    INTO MYSQL_VAR_S30NFY
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_S30NFY IS NULL THEN
        RETURN 0;
    END IF;

    RETURN QUARTER(MYSQL_VAR_S30NFY);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PDXDWU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PDXDWU(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7CSS0D VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_7QDMVX INT DEFAULT 0;
    DECLARE MYSQL_VAR_LVV1V3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_H5ZJHP INT DEFAULT 0;

    SELECT TIER_LEVEL
    INTO MYSQL_VAR_7CSS0D
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_7QDMVX
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT DATEDIFF(CURDATE(), REGISTRATION_DATE)
    INTO MYSQL_VAR_LVV1V3
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_7CSS0D = 'BRONZE' AND MYSQL_VAR_7QDMVX >= 1000 AND MYSQL_VAR_LVV1V3 >= 90 THEN
        SET MYSQL_VAR_H5ZJHP = 1;
    ELSEIF MYSQL_VAR_7CSS0D = 'SILVER' AND MYSQL_VAR_7QDMVX >= 5000 AND MYSQL_VAR_LVV1V3 >= 180 THEN
        SET MYSQL_VAR_H5ZJHP = 1;
    ELSEIF MYSQL_VAR_7CSS0D = 'GOLD' AND MYSQL_VAR_7QDMVX >= 10000 AND MYSQL_VAR_LVV1V3 >= 365 THEN
        SET MYSQL_VAR_H5ZJHP = 1;
    END IF;

    RETURN MYSQL_VAR_H5ZJHP;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_R16TA3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_R16TA3(CONTRACT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PK6XV2 INT DEFAULT 5000;
    DECLARE MYSQL_VAR_F8ODPQ INT DEFAULT 2;
    DECLARE MYSQL_VAR_KHEQ9K INT DEFAULT 10000;
    DECLARE MYSQL_VAR_QIAG0Q INT DEFAULT 0;
    DECLARE MYSQL_VAR_M8IJ41 INT DEFAULT 0;

    SELECT MYSQL_FUNC_OJSZWT(10)
    INTO MYSQL_VAR_PK6XV2, MYSQL_VAR_F8ODPQ, MYSQL_VAR_KHEQ9K
    FROM SECURITY_CONTRACTS
    WHERE CONTRACT_ID = CONTRACT_ID_PARAM;

    SET MYSQL_VAR_M8IJ41 = MYSQL_FUNC_FKEAXL(10);

    IF MYSQL_VAR_KHEQ9K > 50000 THEN
        SET MYSQL_VAR_QIAG0Q = MYSQL_VAR_M8IJ41 * 20 / 100;
        SET MYSQL_VAR_M8IJ41 = MYSQL_VAR_M8IJ41 + MYSQL_VAR_QIAG0Q;
    END IF;

    RETURN MYSQL_FUNC_PDXDWU(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QZHT7T(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JFJ76R INT DEFAULT 0;
    DECLARE MYSQL_VAR_C2PTJR INT DEFAULT 0;
    DECLARE MYSQL_VAR_XMH5TL DECIMAL(5,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_R16TA3(10)
    INTO MYSQL_VAR_JFJ76R
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_C2PTJR
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_JFJ76R = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_XMH5TL = MYSQL_FUNC_FY5T57(20, 21);

    RETURN MYSQL_FUNC_ARETGO(30);
END//

DELIMITER ;