/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_KZ1XYH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KZ1XYH(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9LFT29 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_9LFT29
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_9LFT29);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_A8G4F9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_A8G4F9(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AWFMWS INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZHYYDK INT DEFAULT 0;
    DECLARE MYSQL_VAR_WVFZFF INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_AWFMWS
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(REFUND_AMOUNT), 0)
    INTO MYSQL_VAR_ZHYYDK
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_WVFZFF = MYSQL_VAR_AWFMWS - MYSQL_VAR_ZHYYDK;

    RETURN MYSQL_VAR_WVFZFF;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TKR7FT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TKR7FT(INPUT_STR VARCHAR(100)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KVA0J0 VARCHAR(100) DEFAULT '';
    DECLARE MYSQL_VAR_KICQTP INT DEFAULT 0;
    DECLARE MYSQL_VAR_YDV8TR INT DEFAULT 1;
    DECLARE MYSQL_VAR_J557Y2 VARCHAR(1);

    SET MYSQL_VAR_KICQTP = CHAR_LENGTH(INPUT_STR);

    WHILE MYSQL_VAR_YDV8TR <= MYSQL_VAR_KICQTP DO
        SET MYSQL_VAR_J557Y2 = SUBSTRING(INPUT_STR, MYSQL_VAR_YDV8TR, 1);
        SET MYSQL_VAR_KVA0J0 = CONCAT(MYSQL_VAR_J557Y2, MYSQL_VAR_KVA0J0);
        SET MYSQL_VAR_YDV8TR = MYSQL_VAR_YDV8TR + 1;
    END WHILE;

    IF INPUT_STR = MYSQL_VAR_KVA0J0 THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_77JRI4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_77JRI4(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7CWGGR INT DEFAULT 0;
    DECLARE MYSQL_VAR_OLOJE3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_8MDGB8 DECIMAL(5,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_A8G4F9(10) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_7CWGGR
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(OI.QUANTITY), 0)
    INTO MYSQL_VAR_OLOJE3
    FROM ORDER_ITEMS OI
    JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
    WHERE OI.PRODUCT_ID = PRODUCT_ID_PARAM
    AND O.ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 90 DAY);

    IF MYSQL_VAR_7CWGGR = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_8MDGB8 = (MYSQL_VAR_OLOJE3 * 4) / MYSQL_VAR_7CWGGR;

    RETURN (MYSQL_FUNC_TKR7FT('test_1_0') - (0) + COALESCE(FLOOR(MYSQL_VAR_8MDGB8), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_V4H6WW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_V4H6WW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4QG97G INT DEFAULT 10;
    DECLARE MYSQL_VAR_CYASKV INT DEFAULT 0;
    DECLARE MYSQL_VAR_CV2NXT INT DEFAULT 0;

    SELECT COALESCE(DATA_LIMIT_GB, 10)
    INTO MYSQL_VAR_4QG97G
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_77JRI4(10) - (0) + COALESCE(COALESCE(SUM(DATA_USED_GB), 0), 0))
    INTO MYSQL_VAR_CYASKV
    FROM USAGE_LOGS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND USAGE_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    IF MYSQL_VAR_4QG97G = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_CV2NXT = (MYSQL_VAR_CYASKV * 100) / MYSQL_VAR_4QG97G;

    RETURN (MYSQL_FUNC_KZ1XYH(20) - (0) + COALESCE(MYSQL_VAR_CV2NXT, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NEPXQF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NEPXQF(LIMIT_NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AABG6U INT DEFAULT 0;
    DECLARE MYSQL_VAR_609XUU INT DEFAULT 2;
    DECLARE MYSQL_VAR_9NLSX4 INT DEFAULT 2;
    DECLARE MYSQL_VAR_CIP1FB INT DEFAULT 0;

    IF LIMIT_NUM < 2 THEN
        RETURN 0;
    END IF;

    OUTER_LOOP: WHILE MYSQL_VAR_609XUU <= LIMIT_NUM DO
        SET MYSQL_VAR_CIP1FB = 0;
        SET MYSQL_VAR_9NLSX4 = 2;

        INNER_LOOP: WHILE MYSQL_VAR_9NLSX4 * MYSQL_VAR_9NLSX4 <= MYSQL_VAR_609XUU DO
            IF MYSQL_VAR_609XUU % MYSQL_VAR_9NLSX4 = 0 THEN
                SET MYSQL_VAR_CIP1FB = 1;
                LEAVE INNER_LOOP;
            END IF;
            SET MYSQL_VAR_9NLSX4 = MYSQL_VAR_9NLSX4 + 1;
        END WHILE INNER_LOOP;

        IF MYSQL_VAR_CIP1FB = 0 THEN
            SET MYSQL_VAR_AABG6U = MYSQL_VAR_AABG6U + 1;
        END IF;

        SET MYSQL_VAR_609XUU = MYSQL_VAR_609XUU + 1;
    END WHILE OUTER_LOOP;

    RETURN MYSQL_VAR_AABG6U;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PLT2UZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PLT2UZ(SUM INT, INTEREST INT, YEARS INT) RETURNS INT
BEGIN
RETURN CAST(SUM * POW(1 + INTEREST / 100.0, YEARS) AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NX82K6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NX82K6(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5CZP4P INT DEFAULT 0;

    SELECT (MYSQL_FUNC_NEPXQF(20) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_5CZP4P
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_PLT2UZ(20, 21, 22) - (0) + COALESCE(MYSQL_VAR_5CZP4P, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_69N46L----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_69N46L(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CJ4RQM VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_XV296W INT DEFAULT 0;

    SELECT CUSTOMER_SEGMENT
    INTO MYSQL_VAR_CJ4RQM
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_XV296W
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.CUSTOMER_SEGMENT = MYSQL_VAR_CJ4RQM
    AND MONTH(O.ORDER_DATE) = MONTH(CURDATE())
    AND YEAR(O.ORDER_DATE) = YEAR(CURDATE());

    RETURN MYSQL_VAR_XV296W;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AUY523----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AUY523(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GKH7OL INT DEFAULT 0;
    DECLARE MYSQL_VAR_3YYJG6 DECIMAL(5,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_NX82K6(30) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_GKH7OL
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT (MYSQL_FUNC_69N46L(10) - (0) + COALESCE(COALESCE(SUM(QUANTITY), 0), 0))
    INTO MYSQL_VAR_3YYJG6
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 7 DAY));

    IF MYSQL_VAR_GKH7OL = 0 THEN
        RETURN 999;
    END IF;

    RETURN (MYSQL_FUNC_V4H6WW(30) - (0) + COALESCE(FLOOR((MYSQL_VAR_3YYJG6 / MYSQL_VAR_GKH7OL) * 100), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TDYPL2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TDYPL2(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DMUJP9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MLTTH3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MZSUDY DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(*)
    INTO MYSQL_VAR_DMUJP9
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT DATEDIFF(CURDATE(), REGISTRATION_DATE)
    INTO MYSQL_VAR_MLTTH3
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_MLTTH3 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_MZSUDY = (MYSQL_VAR_DMUJP9 * 365.0) / MYSQL_VAR_MLTTH3;

    RETURN FLOOR(MYSQL_VAR_MZSUDY);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_79SFE3(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IR23E8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_36EK8V INT DEFAULT 0;

    SELECT (MYSQL_FUNC_AUY523(20) - (0) + COALESCE(COALESCE(MAX(SALARY), 0), COALESCE(MIN(SALARY), 0), 0))
    INTO MYSQL_VAR_IR23E8, MYSQL_VAR_36EK8V
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN (MYSQL_FUNC_TDYPL2(10) - (0) + COALESCE(MYSQL_VAR_IR23E8 - MYSQL_VAR_36EK8V, 0));
END//

DELIMITER ;