/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_FDUF1N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FDUF1N(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8K1NPL INT DEFAULT 1;
    DECLARE MYSQL_VAR_7GDJXC INT DEFAULT 2;
    DECLARE MYSQL_VAR_QKISZP INT DEFAULT 0;

    IF N <= 1 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_QKISZP = FLOOR(SQRT(N));

    DIVISOR_LOOP: WHILE MYSQL_VAR_7GDJXC <= MYSQL_VAR_QKISZP DO
        IF N % MYSQL_VAR_7GDJXC = 0 THEN
            SET MYSQL_VAR_8K1NPL = MYSQL_VAR_8K1NPL + MYSQL_VAR_7GDJXC;
            IF MYSQL_VAR_7GDJXC != N / MYSQL_VAR_7GDJXC THEN
                SET MYSQL_VAR_8K1NPL = MYSQL_VAR_8K1NPL + (N / MYSQL_VAR_7GDJXC);
            END IF;
        END IF;
        SET MYSQL_VAR_7GDJXC = MYSQL_VAR_7GDJXC + 1;
    END WHILE DIVISOR_LOOP;

    IF MYSQL_VAR_8K1NPL = N THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_L6HGQ1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L6HGQ1(RESTAURANT_ID_PARAM INT, ORDER_DISTANCE_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1LHMOP INT DEFAULT 0;
    DECLARE MYSQL_VAR_VP7WMX DECIMAL(2,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_6Q31WB INT DEFAULT 0;
    DECLARE MYSQL_VAR_C2MDKJ INT DEFAULT 0;

    SELECT COALESCE(DELIVERY_RADIUS_MILES, 5), COALESCE(RATING, 3.0), COALESCE(AVERAGE_PRICE, 20)
    INTO MYSQL_VAR_1LHMOP, MYSQL_VAR_VP7WMX, MYSQL_VAR_6Q31WB
    FROM RESTAURANTS
    WHERE RESTAURANT_ID = RESTAURANT_ID_PARAM;

    IF ORDER_DISTANCE_PARAM > MYSQL_VAR_1LHMOP THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_C2MDKJ = (MYSQL_VAR_VP7WMX * 20) - (MYSQL_VAR_6Q31WB / 5) + ((MYSQL_VAR_1LHMOP - ORDER_DISTANCE_PARAM) * 5);

    RETURN GREATEST(MYSQL_VAR_C2MDKJ, 0);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_D6GAUI(SHIPMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6Q0E6B DATE;
    DECLARE MYSQL_VAR_FPPC55 DATE;
    DECLARE MYSQL_VAR_XVH695 DATE;
    DECLARE MYSQL_VAR_KM0BZE INT DEFAULT 0;

    SELECT MYSQL_FUNC_FDUF1N(20)
    INTO MYSQL_VAR_6Q0E6B, MYSQL_VAR_XVH695
    FROM SHIPPING_SHIPMENTS
    WHERE SHIPMENT_ID = SHIPMENT_ID_PARAM;

    IF MYSQL_VAR_6Q0E6B IS NULL THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_FPPC55 = DATE_ADD(MYSQL_VAR_6Q0E6B, INTERVAL 7 DAY);

    IF MYSQL_VAR_XVH695 IS NULL THEN
        SET MYSQL_VAR_KM0BZE = DATEDIFF(CURDATE(), MYSQL_VAR_FPPC55);
    ELSE
        SET MYSQL_VAR_KM0BZE = DATEDIFF(MYSQL_VAR_XVH695, MYSQL_VAR_FPPC55);
    END IF;

    IF MYSQL_VAR_KM0BZE < 0 THEN
        SET MYSQL_VAR_KM0BZE = 0;
    END IF;

    RETURN MYSQL_FUNC_L6HGQ1(10, 11);
END//

DELIMITER ;