/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_FYUX5X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FYUX5X(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EWIMFV INT DEFAULT 0;
    DECLARE MYSQL_VAR_RJ2V8N DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_0QKDME INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_EWIMFV, MYSQL_VAR_RJ2V8N
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    IF MYSQL_VAR_EWIMFV >= 10 AND MYSQL_VAR_RJ2V8N >= 5000 THEN
        SET MYSQL_VAR_0QKDME = 3;
    ELSEIF MYSQL_VAR_EWIMFV >= 5 AND MYSQL_VAR_RJ2V8N >= 1000 THEN
        SET MYSQL_VAR_0QKDME = 2;
    ELSE
        SET MYSQL_VAR_0QKDME = 1;
    END IF;

    RETURN MYSQL_VAR_0QKDME;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I4J4SU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I4J4SU(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_29FYU6 VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_377OE9 INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_29FYU6, MYSQL_VAR_377OE9
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_29FYU6 != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_FYUX5X(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MH0A4X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MH0A4X(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WP4S4Q DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_WP4S4Q
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_WP4S4Q / 1000);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_US2KIP(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZPKJWL DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_84N1P9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_J7IHJP DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_MH0A4X(20)
    INTO MYSQL_VAR_ZPKJWL
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT TIMESTAMPDIFF(MONTH, REGISTRATION_DATE, CURDATE())
    INTO MYSQL_VAR_84N1P9
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_84N1P9 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_J7IHJP = MYSQL_FUNC_I4J4SU(30);

    RETURN FLOOR(MYSQL_VAR_J7IHJP);
END//

DELIMITER ;