/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_7SWC2B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7SWC2B(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UAF4YK INT DEFAULT 0;
    DECLARE MYSQL_VAR_7QNKXG INT DEFAULT 1;
    DECLARE MYSQL_VAR_BIUS89 INT DEFAULT 1;
    DECLARE MYSQL_VAR_NYBK00 INT DEFAULT 0;

    IF N <= 0 OR N > 100 THEN
        RETURN 0;
    END IF;

    OUTER_LOOP: WHILE MYSQL_VAR_7QNKXG <= N DO
        INNER_LOOP: WHILE MYSQL_VAR_BIUS89 <= N DO
            IF MYSQL_VAR_7QNKXG = MYSQL_VAR_BIUS89 THEN
                SET MYSQL_VAR_NYBK00 = MYSQL_VAR_NYBK00 + (MYSQL_VAR_7QNKXG * MYSQL_VAR_BIUS89);
            END IF;
            SET MYSQL_VAR_BIUS89 = MYSQL_VAR_BIUS89 + 1;
        END WHILE INNER_LOOP;
        SET MYSQL_VAR_BIUS89 = 1;
        SET MYSQL_VAR_7QNKXG = MYSQL_VAR_7QNKXG + 1;
    END WHILE OUTER_LOOP;

    RETURN MYSQL_VAR_NYBK00;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3WBU08----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3WBU08(P_VALUE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_APY8HL INT DEFAULT 2;
    DECLARE MYSQL_VAR_1P3I56 INT;
    DECLARE MYSQL_VAR_YIY6AB INT DEFAULT 1;
    IF P_VALUE <= 1 THEN
        RETURN 0;
    END IF;
    IF P_VALUE = 2 THEN
        RETURN 1;
    END IF;
    IF P_VALUE % 2 = 0 THEN
        RETURN 0;
    END IF;
    SET MYSQL_VAR_1P3I56 = CAST(SQRT(P_VALUE) AS UNSIGNED);
    SET MYSQL_VAR_APY8HL = 3;
    WHILE MYSQL_VAR_APY8HL <= MYSQL_VAR_1P3I56 DO
        IF P_VALUE % MYSQL_VAR_APY8HL = 0 THEN
            SET MYSQL_VAR_YIY6AB = 0;
        END IF;
        SET MYSQL_VAR_APY8HL = MYSQL_VAR_APY8HL + 2;
    END WHILE;
    RETURN MYSQL_VAR_YIY6AB;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FY5T57----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FY5T57(ORIGINAL_PRICE INT, DISCOUNT_PERCENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1X9WK5 INT DEFAULT 0;
    SET MYSQL_VAR_1X9WK5 = MYSQL_FUNC_3WBU08(10);
    RETURN MYSQL_VAR_1X9WK5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6HYJG5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6HYJG5(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FX0IE6 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_FX0IE6
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_VAR_FX0IE6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z1IBA4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z1IBA4(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3Z6QKM INT DEFAULT 0;
    DECLARE MYSQL_VAR_68U8XF INT DEFAULT 0;
    DECLARE MYSQL_VAR_D3F97E INT DEFAULT 0;
    DECLARE MYSQL_VAR_H41G35 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MOA6U1 VARCHAR(50) DEFAULT '';

    SELECT REFERRAL_CODE
    INTO MYSQL_VAR_MOA6U1
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_FY5T57(20, 21) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_3Z6QKM
    FROM CUSTOMERS
    WHERE REFERRED_BY = MYSQL_VAR_MOA6U1;

    SELECT COALESCE(SUM(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_68U8XF
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.REFERRED_BY = MYSQL_VAR_MOA6U1;

    SELECT (MYSQL_FUNC_6HYJG5(10) - (0) + COALESCE(COALESCE(SUM(TOTAL_AMOUNT), 0), 0))
    INTO MYSQL_VAR_D3F97E
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_D3F97E = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_H41G35 = ((MYSQL_VAR_68U8XF - MYSQL_VAR_D3F97E) * 100) / MYSQL_VAR_D3F97E;

    RETURN (MYSQL_FUNC_7SWC2B(30) - (0) + COALESCE(MYSQL_VAR_H41G35, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UC92KM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UC92KM(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XHA7OL INT DEFAULT 0;
    DECLARE MYSQL_VAR_ESX9EN INT DEFAULT 0;
    DECLARE MYSQL_VAR_XEGAFX INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_XHA7OL
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_ESX9EN
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_XHA7OL = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_XEGAFX = ((MYSQL_VAR_ESX9EN - MYSQL_VAR_XHA7OL) * 100) / MYSQL_VAR_XHA7OL;

    RETURN MYSQL_VAR_XEGAFX;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TM7YX0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TM7YX0(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H98W5B INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_H98W5B
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_H98W5B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KSZFWV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KSZFWV(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_96U0ZF INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_96U0ZF
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_VAR_96U0ZF * 3;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XS82MK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XS82MK(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4DHPT0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_TRA3SS INT DEFAULT 1;
    DECLARE MYSQL_VAR_MHR2TL INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y5BOTZ INT DEFAULT 2;

    IF N = 0 THEN
        RETURN 0;
    END IF;
    IF N = 1 THEN
        RETURN 1;
    END IF;

    WHILE MYSQL_VAR_Y5BOTZ <= N DO
        SET MYSQL_VAR_MHR2TL = MYSQL_VAR_4DHPT0 + MYSQL_VAR_TRA3SS;
        SET MYSQL_VAR_4DHPT0 = MYSQL_VAR_TRA3SS;
        SET MYSQL_VAR_TRA3SS = MYSQL_VAR_MHR2TL;
        SET MYSQL_VAR_Y5BOTZ = MYSQL_VAR_Y5BOTZ + 1;
    END WHILE;

    RETURN MYSQL_VAR_TRA3SS;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2D730N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2D730N(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4MZJW5 DECIMAL(3,1) DEFAULT 0.0;

    SELECT (MYSQL_FUNC_XS82MK(30) - (0) + COALESCE(COALESCE(SUPPLIER_RATING, 3.0), 0))
    INTO MYSQL_VAR_4MZJW5
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_KSZFWV(10) - (0) + COALESCE(FLOOR(MYSQL_VAR_4MZJW5 * 20), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EIGM1N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EIGM1N(METER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5LSO30 INT DEFAULT 0;
    DECLARE MYSQL_VAR_E6JZOL INT DEFAULT 0;
    DECLARE MYSQL_VAR_BKX330 INT DEFAULT 15;
    DECLARE MYSQL_VAR_E77C4C INT DEFAULT 8;
    DECLARE MYSQL_VAR_QB7CGA INT DEFAULT 0;

    SELECT (MYSQL_FUNC_2D730N(20) - (0) + COALESCE((MYSQL_FUNC_UC92KM(10) - (0) + COALESCE(COALESCE(SUM(KWH_USED), 0), 0)), 0)) INTO MYSQL_VAR_5LSO30
    FROM ELECTRICITY_READINGS
    WHERE METER_ID = METER_ID_PARAM AND READING_TYPE = 'PEAK';

    SELECT COALESCE(SUM(KWH_USED), 0) INTO MYSQL_VAR_E6JZOL
    FROM ELECTRICITY_READINGS
    WHERE METER_ID = METER_ID_PARAM AND READING_TYPE = 'OFFPEAK';

    SET MYSQL_VAR_QB7CGA = MYSQL_FUNC_Z1IBA4(20);

    RETURN (MYSQL_FUNC_TM7YX0(30) - (0) + COALESCE(CAST(MYSQL_VAR_QB7CGA AS SIGNED), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4A4GWR(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_K7973A VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_EDO8VB DATE;
    DECLARE MYSQL_VAR_823VEW DATE;
    DECLARE MYSQL_VAR_XLW4VV INT DEFAULT 0;

    SELECT STATUS, START_DATE, END_DATE
    INTO MYSQL_VAR_K7973A, MYSQL_VAR_EDO8VB, MYSQL_VAR_823VEW
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_EIGM1N(20) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_XLW4VV
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_K7973A != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_XLW4VV * 100) / GREATEST(DATEDIFF(CURDATE(), MYSQL_VAR_EDO8VB), 1));
END//

DELIMITER ;