/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_R9IRRR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_R9IRRR(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2QGQ5O DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_MAJSOW DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_QCBVZ5 INT DEFAULT 0;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_2QGQ5O
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    IF MYSQL_VAR_MAJSOW = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_QCBVZ5 = ((MYSQL_VAR_2QGQ5O - MYSQL_VAR_MAJSOW) * 100) / MYSQL_VAR_MAJSOW;

    RETURN MYSQL_VAR_QCBVZ5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7LBCM1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7LBCM1(EMPLOYEE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BQOTMX INT DEFAULT 0;
    DECLARE MYSQL_VAR_GWOAFS INT DEFAULT 0;
    DECLARE MYSQL_VAR_6UQ887 INT DEFAULT 0;
    DECLARE MYSQL_VAR_T5PFUF INT DEFAULT 0;
    DECLARE MYSQL_VAR_B446RF INT DEFAULT 0;

    SELECT COALESCE(IS_REMOTE, 0), COALESCE(SALARY, 50000)
    INTO MYSQL_VAR_BQOTMX, MYSQL_VAR_GWOAFS
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = EMPLOYEE_ID_PARAM;

    SELECT COUNT(*), COUNT(CASE WHEN STATUS = 'COMPLETED' THEN 1 END)
    INTO MYSQL_VAR_6UQ887, MYSQL_VAR_T5PFUF
    FROM PROJECTS
    WHERE TEAM_LEAD_ID = EMPLOYEE_ID_PARAM;

    IF MYSQL_VAR_BQOTMX = 1 THEN
        SET MYSQL_VAR_B446RF = 80 + (MYSQL_VAR_T5PFUF * 5) - (MYSQL_VAR_GWOAFS / 10000);
    ELSE
        SET MYSQL_VAR_B446RF = 70 + (MYSQL_VAR_T5PFUF * 3);
    END IF;

    RETURN (MYSQL_FUNC_R9IRRR(30) - (0) + COALESCE(MYSQL_VAR_B446RF, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XDN16B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XDN16B(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YBMGCL INT DEFAULT 3;
    DECLARE MYSQL_VAR_1GF1MQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_647XK3 INT DEFAULT 0;

    SELECT DATEDIFF(COALESCE(DELIVERY_DATE, CURDATE()), ORDER_DATE)
    INTO MYSQL_VAR_1GF1MQ
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_647XK3 = 100 - ABS(MYSQL_VAR_1GF1MQ - MYSQL_VAR_YBMGCL) * 10;

    RETURN (MYSQL_FUNC_7LBCM1(20) - (0) + COALESCE(GREATEST(MYSQL_VAR_647XK3, 0), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CX86MG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CX86MG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SYZGFE DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_SYZGFE
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_SYZGFE);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9Q34KK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9Q34KK(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Y907XU INT DEFAULT 0;
    DECLARE MYSQL_VAR_QEDQM3 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_1RQPSX DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_SQ59ZU INT DEFAULT 0;

    SELECT (MYSQL_FUNC_CX86MG(20) - (0) + COALESCE(COUNT(*), COALESCE(AVG(SALARY), 0), COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0), 0))
    INTO MYSQL_VAR_Y907XU, MYSQL_VAR_QEDQM3, MYSQL_VAR_1RQPSX
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_SQ59ZU = (MYSQL_VAR_Y907XU * 5) + (MYSQL_VAR_QEDQM3 / 1000 * 10) + (MYSQL_VAR_1RQPSX * 8);

    RETURN (MYSQL_FUNC_XDN16B(20) - (0) + COALESCE(MYSQL_VAR_SQ59ZU, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FCGW2L(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ONFGF5 INT DEFAULT 0;
    WHILE B != 0 DO
        SET MYSQL_VAR_ONFGF5 = B;
        SET B = A % B;
        SET A = MYSQL_VAR_ONFGF5;
    END WHILE;
    RETURN (MYSQL_FUNC_9Q34KK(30) - (0) + COALESCE(A, 0));
END//

DELIMITER ;