/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_FX2YRB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FX2YRB(NUM INT, BIT_POSITIONS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_I4RATZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_MQSN04 INT DEFAULT 0;
    DECLARE MYSQL_VAR_STJA9S INT;

    TOGGLE_LOOP: WHILE BIT_POSITIONS > 0 DO
        SET MYSQL_VAR_MQSN04 = BIT_POSITIONS MOD 10;
        SET MYSQL_VAR_STJA9S = (NUM >> MYSQL_VAR_MQSN04) & 1;

        IF MYSQL_VAR_STJA9S = 0 THEN
            SET MYSQL_VAR_I4RATZ = MYSQL_VAR_I4RATZ | (1 << MYSQL_VAR_MQSN04);
        END IF;

        SET BIT_POSITIONS = BIT_POSITIONS DIV 10;
    END WHILE TOGGLE_LOOP;

    RETURN MYSQL_VAR_I4RATZ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1PVB2M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1PVB2M(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_B8NFQT INT DEFAULT 0;
    DECLARE MYSQL_VAR_W4LXBD INT DEFAULT 1;

    IF N <= 0 THEN
        RETURN 0;
    END IF;

    MY_LOOP: WHILE MYSQL_VAR_W4LXBD <= N DO
        SET MYSQL_VAR_B8NFQT = MYSQL_VAR_B8NFQT * 2;
        SET MYSQL_VAR_B8NFQT = MYSQL_VAR_B8NFQT + 1;
        SET MYSQL_VAR_W4LXBD = MYSQL_VAR_W4LXBD + 1;
    END WHILE MY_LOOP;

    RETURN MYSQL_VAR_B8NFQT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4TOOXN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4TOOXN(PROPERTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XPKFHS INT DEFAULT 0;
    DECLARE MYSQL_VAR_XOYC9B INT DEFAULT 0;
    DECLARE MYSQL_VAR_UTJHWH INT DEFAULT 0;
    DECLARE MYSQL_VAR_4W3RR6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_8S3J4L INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_RENT, 0), COALESCE(NUM_UNITS, 1)
    INTO MYSQL_VAR_XPKFHS, MYSQL_VAR_XOYC9B
    FROM RENTAL_PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_UTJHWH
    FROM LEASE_AGREEMENTS
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM
      AND END_DATE > CURDATE();

    IF MYSQL_VAR_XOYC9B = 0 THEN
        RETURN 100;
    END IF;

    SET MYSQL_VAR_4W3RR6 = ((MYSQL_VAR_XOYC9B - MYSQL_VAR_UTJHWH) * 100) / MYSQL_VAR_XOYC9B;
    SET MYSQL_VAR_8S3J4L = MYSQL_FUNC_FX2YRB(20, 21);

    IF MYSQL_VAR_XPKFHS > 5000 THEN
        SET MYSQL_VAR_8S3J4L = MYSQL_VAR_8S3J4L + 10;
    END IF;

    RETURN MYSQL_FUNC_1PVB2M(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_STNAGE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_STNAGE(X INT) RETURNS INT
BEGIN
RETURN X;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AJH8QL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AJH8QL(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XUBHNK INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_XUBHNK
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN LEAST(MYSQL_VAR_XUBHNK, 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BLMXQK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BLMXQK(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GDKRKJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_M0TS6O DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_UMYSOS INT DEFAULT 0;

    SELECT COALESCE(SUM(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_GDKRKJ
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_M0TS6O
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SET MYSQL_VAR_UMYSOS = FLOOR(MYSQL_VAR_M0TS6O * 0.2);

    IF MYSQL_VAR_GDKRKJ > 1000 THEN
        SET MYSQL_VAR_UMYSOS = MYSQL_VAR_UMYSOS + 10;
    END IF;

    RETURN MYSQL_VAR_UMYSOS;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S110UQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S110UQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SEVR7B INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_SEVR7B
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'ACTIVE';

    RETURN MYSQL_VAR_SEVR7B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P0O4FP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P0O4FP(PORTFOLIO_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FBBYWA INT DEFAULT 0;
    DECLARE MYSQL_VAR_VKNBOE INT DEFAULT 0;
    DECLARE MYSQL_VAR_XF96Q3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_DW8WCT DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_LUOXUN INT DEFAULT 0;

    SELECT MYSQL_FUNC_S110UQ(20)
    INTO MYSQL_VAR_FBBYWA, MYSQL_VAR_VKNBOE
    FROM INVESTMENTS
    WHERE PORTFOLIO_ID = PORTFOLIO_ID_PARAM;

    SELECT COALESCE(AVG(RISK_RATING), 3.0)
    INTO MYSQL_VAR_DW8WCT
    FROM INVESTMENTS
    WHERE PORTFOLIO_ID = PORTFOLIO_ID_PARAM;

    IF MYSQL_VAR_FBBYWA = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_XF96Q3 = MYSQL_FUNC_BLMXQK(30);

    SET MYSQL_VAR_LUOXUN = MYSQL_FUNC_AJH8QL(10);

    RETURN MYSQL_VAR_LUOXUN;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BBBXW3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BBBXW3(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YHXEQR DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_YHXEQR
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_YHXEQR / 500);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z6BMFT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z6BMFT(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9J54E7 DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_BBBXW3(10)
    INTO MYSQL_VAR_9J54E7
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
    AND ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    RETURN FLOOR(MYSQL_VAR_9J54E7);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I9TT68----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I9TT68(TARGET_DATE DATE) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_W3PK39 DATE DEFAULT CURDATE();
    DECLARE MYSQL_VAR_397IS1 INT DEFAULT 0;

    SET MYSQL_VAR_397IS1 = MYSQL_FUNC_P0O4FP(30);

    RETURN MYSQL_FUNC_Z6BMFT(30);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GY2NI0(EVENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z04RYO INT DEFAULT 0;
    DECLARE MYSQL_VAR_3WXAGL INT DEFAULT 0;
    DECLARE MYSQL_VAR_VGPIM4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_EV7OP1 INT DEFAULT 0;

    SELECT MYSQL_FUNC_I9TT68('2024-01-11')
    INTO MYSQL_VAR_Z04RYO, MYSQL_VAR_3WXAGL, MYSQL_VAR_VGPIM4
    FROM EVENT_TICKETS T
    JOIN EVENTS E ON T.EVENT_ID = E.EVENT_ID
    WHERE T.EVENT_ID = EVENT_ID_PARAM
    GROUP BY T.EVENT_ID;

    IF MYSQL_VAR_3WXAGL = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_EV7OP1 = MYSQL_FUNC_STNAGE(30);

    RETURN MYSQL_FUNC_4TOOXN(30);
END//

DELIMITER ;