/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_3GZX3U----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3GZX3U(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_L49U2B INT DEFAULT 0;
    DECLARE MYSQL_VAR_DX6UFW INT DEFAULT 0;
    DECLARE MYSQL_VAR_6JC9NE INT DEFAULT 0;

    SELECT COALESCE(SUM(C.CREDITS), 0)
    INTO MYSQL_VAR_L49U2B
    FROM ENROLLMENTS E
    JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID
    WHERE E.STUDENT_ID = STUDENT_ID_PARAM AND E.GRADE IN ('A', 'B', 'C', 'D', 'P');

    SELECT COALESCE(SUM(C.CREDITS), 0)
    INTO MYSQL_VAR_DX6UFW
    FROM ENROLLMENTS E
    JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID
    WHERE E.STUDENT_ID = STUDENT_ID_PARAM;

    IF MYSQL_VAR_DX6UFW = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_6JC9NE = (MYSQL_VAR_L49U2B * 100) / MYSQL_VAR_DX6UFW;

    RETURN MYSQL_VAR_6JC9NE;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9KIPOH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9KIPOH(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KSJR2W INT DEFAULT 0;
    DECLARE MYSQL_VAR_6Q37BG DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_95FAJA INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_KSJR2W
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(AVG(QUANTITY), 0) / 30
    INTO MYSQL_VAR_6Q37BG
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY));

    IF MYSQL_VAR_6Q37BG = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_95FAJA = MYSQL_VAR_KSJR2W / MYSQL_VAR_6Q37BG;

    RETURN MYSQL_VAR_95FAJA;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_27O7KS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_27O7KS(DEPT_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_R5ZHUK INT DEFAULT 0;
    DECLARE MYSQL_VAR_COJBYF INT DEFAULT 0;
    DECLARE MYSQL_VAR_WJANZW INT DEFAULT 0;
    DECLARE MYSQL_VAR_1W0K38 INT DEFAULT 0;
    DECLARE MYSQL_VAR_22C0T1 INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(AVG(SALARY), 0), COALESCE(MAX(SALARY), 0), COALESCE(MIN(SALARY), 0)
    INTO MYSQL_VAR_1W0K38, MYSQL_VAR_R5ZHUK, MYSQL_VAR_COJBYF, MYSQL_VAR_WJANZW
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPT_ID;

    SET MYSQL_VAR_22C0T1 = MYSQL_VAR_COJBYF - MYSQL_VAR_WJANZW;

    CASE
        WHEN MYSQL_VAR_1W0K38 = 0 THEN RETURN 0;
        WHEN MYSQL_VAR_R5ZHUK < 3000 THEN SET MYSQL_VAR_22C0T1 = MYSQL_VAR_22C0T1 * 8 / 10;
        WHEN MYSQL_VAR_R5ZHUK > 10000 THEN SET MYSQL_VAR_22C0T1 = MYSQL_VAR_22C0T1 * 12 / 10;
        ELSE SET MYSQL_VAR_22C0T1 = MYSQL_VAR_22C0T1 * 10 / 10;
    END CASE;

    RETURN MYSQL_VAR_22C0T1;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z3TZAI(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SNTETE INT DEFAULT 0;
    DECLARE MYSQL_VAR_HSJA1P DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4RLE0K INT DEFAULT 7;
    DECLARE MYSQL_VAR_GYO6O8 INT DEFAULT 0;

    SELECT MYSQL_FUNC_27O7KS(20)
    INTO MYSQL_VAR_SNTETE
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT MYSQL_FUNC_9KIPOH(10)
    INTO MYSQL_VAR_HSJA1P
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY));

    SET MYSQL_VAR_GYO6O8 = (MYSQL_VAR_SNTETE / GREATEST(MYSQL_VAR_HSJA1P, 0.1)) - MYSQL_VAR_4RLE0K;

    RETURN MYSQL_FUNC_3GZX3U(30);
END//

DELIMITER ;