/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_EE5BIO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EE5BIO(CLASS_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EQVE08 INT DEFAULT 0;
    DECLARE MYSQL_VAR_EY4ALY INT DEFAULT 0;
    DECLARE MYSQL_VAR_CTU2TS INT DEFAULT 0;
    DECLARE MYSQL_VAR_LMLHBM INT DEFAULT 0;
    DECLARE MYSQL_VAR_1Z41ZW INT DEFAULT 0;
    DECLARE MYSQL_VAR_L2GEUN INT DEFAULT 0;

    SELECT COALESCE(CAPACITY, 20), COALESCE(CURRENT_ENROLLMENT, 0), COALESCE(DURATION_MINUTES, 60)
    INTO MYSQL_VAR_EQVE08, MYSQL_VAR_EY4ALY, MYSQL_VAR_CTU2TS
    FROM FITNESS_CLASSES
    WHERE CLASS_ID = CLASS_ID_PARAM;

    SELECT COUNT(*), COALESCE(AVG(CASE ATTENDANCE_STATUS WHEN 'ATTENDED' THEN 1 ELSE 0 END) * 100, 0)
    INTO MYSQL_VAR_LMLHBM, MYSQL_VAR_1Z41ZW
    FROM BOOKINGS
    WHERE CLASS_ID = CLASS_ID_PARAM;

    SET MYSQL_VAR_L2GEUN = ((MYSQL_VAR_EY4ALY * 100) / MYSQL_VAR_EQVE08) + (MYSQL_VAR_LMLHBM * 2) + (MYSQL_VAR_1Z41ZW / 2);

    RETURN MYSQL_VAR_L2GEUN;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1XM6OW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1XM6OW(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FI3ATH VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_8PFH1K INT DEFAULT 0;
    DECLARE MYSQL_VAR_A908W4 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_EE5BIO(10) - (0) + COALESCE(STATUS, COALESCE(BUDGET, 0), DATEDIFF(CURDATE(), START_DATE), 0))
    INTO MYSQL_VAR_FI3ATH, MYSQL_VAR_8PFH1K, MYSQL_VAR_A908W4
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_FI3ATH != 'ACTIVE' OR MYSQL_VAR_A908W4 = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_8PFH1K / MYSQL_VAR_A908W4;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2F23RH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2F23RH(DEPT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_35OYO7 DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_9QHH5T INT DEFAULT 0;
    DECLARE MYSQL_VAR_0H8FEK INT DEFAULT 0;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_35OYO7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPT_ID_PARAM;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_9QHH5T
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPT_ID_PARAM;

    SET MYSQL_VAR_0H8FEK = 100 - (MYSQL_VAR_35OYO7 * 10) - (MYSQL_VAR_9QHH5T / 1000);

    RETURN GREATEST(MYSQL_VAR_0H8FEK, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YCWHRI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YCWHRI(LENGTH_PARAM INT) RETURNS VARCHAR(100)
BEGIN
DECLARE MYSQL_VAR_JCY3EH VARCHAR(100) DEFAULT '';
    DECLARE MYSQL_VAR_B7IGOV INT DEFAULT 1;
    DECLARE MYSQL_VAR_40E9TK INT DEFAULT 0;
    DECLARE MYSQL_VAR_CVYS70 INT DEFAULT 0;

    IF LENGTH_PARAM <= 0 THEN
        RETURN '';
    END IF;

    SET MYSQL_VAR_B7IGOV = MYSQL_FUNC_1XM6OW(30);

    PASSWORD_LOOP: WHILE MYSQL_VAR_B7IGOV <= LENGTH_PARAM DO
        SET MYSQL_VAR_CVYS70 = RAND() * 10;

        IF MYSQL_VAR_CVYS70 < 3 AND MYSQL_VAR_B7IGOV < LENGTH_PARAM THEN
            SET MYSQL_VAR_40E9TK = RAND() * 10 + 33;
        ELSEIF MYSQL_VAR_CVYS70 < 6 THEN
            SET MYSQL_VAR_40E9TK = RAND() * 26 + 65;
        ELSE
            SET MYSQL_VAR_40E9TK = RAND() * 26 + 97;
        END IF;

        SET MYSQL_VAR_JCY3EH = CONCAT(MYSQL_VAR_JCY3EH, CHAR(MYSQL_VAR_40E9TK));
        SET MYSQL_VAR_B7IGOV = MYSQL_VAR_B7IGOV + 1;
    END WHILE PASSWORD_LOOP;

    RETURN MYSQL_FUNC_2F23RH(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7G349Y----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7G349Y(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_E7MCOH DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_SRER41 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_E7MCOH
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_SRER41
    FROM EMPLOYEES;

    RETURN FLOOR((MYSQL_VAR_E7MCOH * 100) / MYSQL_VAR_SRER41);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_US2KIP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_US2KIP(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZPKJWL DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_84N1P9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_J7IHJP DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_ZPKJWL
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT TIMESTAMPDIFF(MONTH, REGISTRATION_DATE, CURDATE())
    INTO MYSQL_VAR_84N1P9
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_84N1P9 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_J7IHJP = MYSQL_VAR_ZPKJWL / MYSQL_VAR_84N1P9;

    RETURN FLOOR(MYSQL_VAR_J7IHJP);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GA85T5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GA85T5(ARR_SIZE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HKREKI INT DEFAULT -2147483648;
    DECLARE MYSQL_VAR_FGZ7MG INT DEFAULT 1;
    DECLARE MYSQL_VAR_LNYNI3 INT;

    IF ARR_SIZE <= 0 THEN
        RETURN 0;
    END IF;

    SAMPLE_LOOP: WHILE MYSQL_VAR_FGZ7MG <= ARR_SIZE DO
        SET MYSQL_VAR_LNYNI3 = FLOOR(1 + RAND() * 1000);
        IF MYSQL_VAR_LNYNI3 > MYSQL_VAR_HKREKI THEN
            SET MYSQL_VAR_HKREKI = MYSQL_VAR_LNYNI3;
        END IF;
        SET MYSQL_VAR_FGZ7MG = MYSQL_VAR_FGZ7MG + 1;
    END WHILE SAMPLE_LOOP;

    RETURN MYSQL_VAR_HKREKI;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RI8G77----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RI8G77(DEPT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NDVD1Q INT DEFAULT 0;
    DECLARE MYSQL_VAR_5QLGY1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_F4TUZ0 INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_NDVD1Q
    FROM DEPARTMENTS
    WHERE DEPT_ID = DEPT_ID_PARAM;

    SELECT (MYSQL_FUNC_US2KIP(10) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_5QLGY1
    FROM EMPLOYEES
    WHERE DEPT_ID = DEPT_ID_PARAM;

    IF MYSQL_VAR_5QLGY1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_F4TUZ0 = MYSQL_FUNC_7G349Y(30);

    RETURN (MYSQL_FUNC_GA85T5(30) - (0) + COALESCE(MYSQL_VAR_F4TUZ0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BSMSFO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BSMSFO(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TNKHLH INT DEFAULT 0;

    SELECT DATEDIFF(END_DATE, START_DATE)
    INTO MYSQL_VAR_TNKHLH
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN MYSQL_VAR_TNKHLH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZKHUUB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZKHUUB(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GANC0G DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_PFKUC2 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_VIISE9 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_RI8G77(30) - (0) + COALESCE(COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_GANC0G
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_PFKUC2
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_VIISE9 = MYSQL_VAR_GANC0G - MYSQL_VAR_PFKUC2;

    RETURN (MYSQL_FUNC_BSMSFO(10) - (0) + COALESCE(FLOOR(MYSQL_VAR_VIISE9), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9JMF6W(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2EAH10 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_ZKHUUB(30) - (0) + COALESCE(COALESCE(SALARY, 0), 0))
    INTO MYSQL_VAR_2EAH10
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN (MYSQL_FUNC_YCWHRI(30) - (0) + COALESCE(FLOOR(MYSQL_VAR_2EAH10 / 1000), 0));
END//

DELIMITER ;