/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_YBC99J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YBC99J(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZYH2SV INT DEFAULT 0;
    DECLARE MYSQL_VAR_D5LKLV DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_I0R0Q0 DECIMAL(10,2) DEFAULT 0.00;

    SELECT DEPARTMENT_ID, COALESCE(SALARY, 0)
    INTO MYSQL_VAR_ZYH2SV, MYSQL_VAR_D5LKLV
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_I0R0Q0
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = MYSQL_VAR_ZYH2SV;

    RETURN FLOOR((MYSQL_VAR_D5LKLV * 100) / MYSQL_VAR_I0R0Q0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XY1NEG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XY1NEG(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UZ44GM DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_UZ44GM
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_UZ44GM);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_D56L6L----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_D56L6L(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4PX3B7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_P3N4N9 DATE;
    DECLARE MYSQL_VAR_69WVNB DATE;

    SELECT MYSQL_FUNC_XY1NEG(10)
    INTO MYSQL_VAR_4PX3B7, MYSQL_VAR_P3N4N9, MYSQL_VAR_69WVNB
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_4PX3B7 < 2 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_YBC99J(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UKF8QD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UKF8QD(BOOKING_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M9QDIK INT DEFAULT 0;
    DECLARE MYSQL_VAR_EAAQF4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_3YE16H INT DEFAULT 75;
    DECLARE MYSQL_VAR_4GSQHR VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_S68ZJY INT DEFAULT 0;

    SELECT COALESCE(GUEST_COUNT, 0), COALESCE(CART_RENTAL, 0)
    INTO MYSQL_VAR_M9QDIK, MYSQL_VAR_EAAQF4
    FROM GOLF_COURSE_BOOKINGS
    WHERE BOOKING_ID = BOOKING_ID_PARAM;

    SELECT COALESCE(MEMBERSHIP_TYPE, 'REGULAR')
    INTO MYSQL_VAR_4GSQHR
    FROM GOLF_COURSE_BOOKINGS GCB
    JOIN MEMBERS M ON GCB.MEMBER_ID = M.MEMBER_ID
    WHERE GCB.BOOKING_ID = BOOKING_ID_PARAM;

    IF MYSQL_VAR_4GSQHR = 'PREMIUM' THEN
        SET MYSQL_VAR_3YE16H = MYSQL_VAR_3YE16H - 25;
    END IF;

    SET MYSQL_VAR_S68ZJY = (MYSQL_VAR_3YE16H * (1 + MYSQL_VAR_M9QDIK)) + MYSQL_VAR_EAAQF4;

    RETURN CAST(MYSQL_VAR_S68ZJY AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KHTKEG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KHTKEG(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VKZ3I7 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_VKZ3I7
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_UKF8QD(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_H1LK9S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H1LK9S(ORDER_ID_PARAM INT, TAX_RATE_PERCENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TZ80F2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_160G6V INT DEFAULT 0;

    SELECT MYSQL_FUNC_D56L6L(10)
    INTO MYSQL_VAR_TZ80F2
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_160G6V = (MYSQL_VAR_TZ80F2 * TAX_RATE_PERCENT) / 100;

    RETURN MYSQL_FUNC_KHTKEG(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_44NGN1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_44NGN1(ROW_NUM INT, COL_NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CH1VN3 INT DEFAULT 1;
    DECLARE MYSQL_VAR_FOU1E3 INT DEFAULT 0;

    IF COL_NUM = 0 OR COL_NUM = ROW_NUM THEN
        RETURN 1;
    END IF;

    IF COL_NUM > ROW_NUM OR COL_NUM < 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_FOU1E3 = 0;
    WHILE MYSQL_VAR_FOU1E3 < COL_NUM DO
        SET MYSQL_VAR_CH1VN3 = MYSQL_VAR_CH1VN3 * (ROW_NUM - MYSQL_VAR_FOU1E3);
        SET MYSQL_VAR_CH1VN3 = MYSQL_VAR_CH1VN3 / (MYSQL_VAR_FOU1E3 + 1);
        SET MYSQL_VAR_FOU1E3 = MYSQL_VAR_FOU1E3 + 1;
    END WHILE;

    RETURN MYSQL_FUNC_H1LK9S(10, 11);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7YB6FA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7YB6FA(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z1AJ6I INT DEFAULT 0;
    DECLARE MYSQL_VAR_B3LAGS INT DEFAULT 0;
    DECLARE MYSQL_VAR_GUFF0V INT DEFAULT 0;
    DECLARE MYSQL_VAR_2PZQTP INT DEFAULT 0;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_Z1AJ6I
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COALESCE(NEW_SALARY, MYSQL_VAR_Z1AJ6I)
    INTO MYSQL_VAR_B3LAGS
    FROM SALARIES
    WHERE EMP_ID = EMP_ID_PARAM
    ORDER BY EFFECTIVE_DATE DESC
    LIMIT 1;

    SELECT TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_GUFF0V
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    IF MYSQL_VAR_Z1AJ6I = 0 OR MYSQL_VAR_GUFF0V = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_2PZQTP = (((MYSQL_VAR_B3LAGS - MYSQL_VAR_Z1AJ6I) * 100) / MYSQL_VAR_Z1AJ6I) / MYSQL_VAR_GUFF0V;

    RETURN MYSQL_VAR_2PZQTP;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WDETTX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FO67SF DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_44NGN1(30, 31)
    INTO MYSQL_VAR_FO67SF
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN MYSQL_FUNC_7YB6FA(30);
END//

DELIMITER ;