/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_SZ3NF4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SZ3NF4(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_I87F94 INT DEFAULT 0;
    DECLARE MYSQL_VAR_X1D6QN INT DEFAULT 0;
    DECLARE MYSQL_VAR_KCARUS INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_I87F94
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_X1D6QN
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = (SELECT COUNTRY FROM CUSTOMERS WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM);

    IF MYSQL_VAR_X1D6QN = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KCARUS = (MYSQL_VAR_I87F94 * 100) / MYSQL_VAR_X1D6QN;

    RETURN MYSQL_VAR_KCARUS;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9L484X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9L484X(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1NJDTL INT DEFAULT 0;

    SELECT MONTH(ORDER_DATE)
    INTO MYSQL_VAR_1NJDTL
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_1NJDTL;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DA0GFD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DA0GFD(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EH5OT1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_F1P3R8 INT DEFAULT 0;

    SELECT COUNT(DISTINCT CATEGORY_ID), COUNT(*)
    INTO MYSQL_VAR_EH5OT1, MYSQL_VAR_F1P3R8
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    IF MYSQL_VAR_F1P3R8 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_EH5OT1 * 100) / MYSQL_VAR_F1P3R8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CQ08ZQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CQ08ZQ(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D2CCLH DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_D2CCLH
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM AND O.STATUS = 'COMPLETED';

    RETURN (MYSQL_FUNC_DA0GFD(30) - (0) + COALESCE(FLOOR(MYSQL_VAR_D2CCLH), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3EWCOM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3EWCOM(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LM8TRL INT DEFAULT 0;
    DECLARE MYSQL_VAR_WXKV68 INT DEFAULT 1;

    SELECT (MYSQL_FUNC_CQ08ZQ('test_1_0') - (0) + COALESCE(COUNT(*), TIMESTAMPDIFF(MONTH, MIN(O.ORDER_DATE), CURDATE()), 0))
    INTO MYSQL_VAR_LM8TRL, MYSQL_VAR_WXKV68
    FROM ORDERS O
    WHERE O.CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_WXKV68 <= 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_9L484X(30) - (0) + COALESCE((MYSQL_VAR_LM8TRL * 100) / MYSQL_VAR_WXKV68, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZYRUGJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZYRUGJ(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YBQUY5 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(PRICE, 0)
    INTO MYSQL_VAR_YBQUY5
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_YBQUY5);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4F968M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4F968M(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_B323NY INT DEFAULT 0;
    DECLARE MYSQL_VAR_J60J9Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_0T50BV INT DEFAULT 0;
    DECLARE MYSQL_VAR_J8893R INT DEFAULT 0;
    DECLARE MYSQL_VAR_S984YO INT DEFAULT 0;
    DECLARE MYSQL_VAR_IN937Z INT DEFAULT 1;
    DECLARE MYSQL_VAR_I7Y12A VARCHAR(20) DEFAULT 'REGULAR';

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0), COUNT(*)
    INTO MYSQL_VAR_B323NY, MYSQL_VAR_J60J9Z
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT (MYSQL_FUNC_ZYRUGJ(10) - (0) + COALESCE(CUSTOMER_SEGMENT, 0))
    INTO MYSQL_VAR_I7Y12A
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT DATEDIFF(CURDATE(), MIN(ORDER_DATE))
    INTO MYSQL_VAR_J8893R
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_J60J9Z > 0 THEN
        SET MYSQL_VAR_0T50BV = MYSQL_VAR_B323NY / MYSQL_VAR_J60J9Z;
    END IF;

    SET MYSQL_VAR_IN937Z = CASE MYSQL_VAR_I7Y12A
        WHEN 'PREMIUM' THEN 4
        WHEN 'VIP' THEN 5
        WHEN 'REGULAR' THEN 2
        ELSE 1
    END;

    IF MYSQL_VAR_J8893R > 0 THEN
        SET MYSQL_VAR_S984YO = (MYSQL_VAR_B323NY * MYSQL_VAR_IN937Z * 365) / MYSQL_VAR_J8893R;
    ELSE
        SET MYSQL_VAR_S984YO = MYSQL_VAR_0T50BV * 12 * MYSQL_VAR_IN937Z;
    END IF;

    RETURN MYSQL_VAR_S984YO;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AC2OEJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AC2OEJ(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5CUX9L DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_5CUX9L
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_5CUX9L);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8FYA73----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8FYA73(PARK_ID_PARAM INT, TARGET_DATE_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KD32DL INT DEFAULT 0;
    DECLARE MYSQL_VAR_4UT7AB INT DEFAULT 0;
    DECLARE MYSQL_VAR_R2UQG9 INT DEFAULT 0;

    SELECT COUNT(DISTINCT VISITOR_ID) INTO MYSQL_VAR_KD32DL
    FROM AMUSEMENT_PARKS
    WHERE PARK_ID = PARK_ID_PARAM
      AND YEAR(VISIT_DATE) = TARGET_DATE_PARAM;

    SELECT COALESCE(CAPACITY, 1000) INTO MYSQL_VAR_4UT7AB
    FROM PARKS
    WHERE PARK_ID = PARK_ID_PARAM;

    IF MYSQL_VAR_4UT7AB = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_R2UQG9 = (MYSQL_VAR_KD32DL * 100) / MYSQL_VAR_4UT7AB;

    RETURN CAST(MYSQL_VAR_R2UQG9 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_W4WLM4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_W4WLM4(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_I6F262 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Z8HJ9U INT DEFAULT 0;
    DECLARE MYSQL_VAR_UU983J INT DEFAULT 0;

    SELECT (MYSQL_FUNC_AC2OEJ(30) - (0) + COALESCE(DATEDIFF(END_DATE, START_DATE), 0))
    INTO MYSQL_VAR_I6F262
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_8FYA73(20, 21) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_Z8HJ9U
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_I6F262 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_UU983J = MYSQL_VAR_Z8HJ9U / MYSQL_VAR_I6F262;

    RETURN MYSQL_VAR_UU983J;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5HE6A9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5HE6A9(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_II00AF INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_II00AF
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_W4WLM4(20) - (0) + COALESCE(MYSQL_VAR_II00AF * 12, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DFJCNW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DFJCNW(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WO83XZ VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_1P17H2 INT DEFAULT 0;

    SELECT C.TIER_LEVEL
    INTO MYSQL_VAR_WO83XZ
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    CASE MYSQL_VAR_WO83XZ
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_1P17H2 = 20;
        WHEN 'GOLD' THEN SET MYSQL_VAR_1P17H2 = 15;
        WHEN 'SILVER' THEN SET MYSQL_VAR_1P17H2 = 10;
        ELSE SET MYSQL_VAR_1P17H2 = 0;
    END CASE;

    RETURN MYSQL_VAR_1P17H2;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1DT1O5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1DT1O5(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3D6A5F INT DEFAULT 0;
    DECLARE MYSQL_VAR_BYAQNP INT DEFAULT 0;
    DECLARE MYSQL_VAR_2IA9YW INT DEFAULT 0;
    DECLARE MYSQL_VAR_YY0A8U INT DEFAULT 0;

    SET MYSQL_VAR_BYAQNP = MYSQL_FUNC_DFJCNW(20);
    SET MYSQL_VAR_2IA9YW = MYSQL_FUNC_5HE6A9(30);

    WHILE MYSQL_VAR_BYAQNP > 0 DO
        SET MYSQL_VAR_YY0A8U = MYSQL_VAR_BYAQNP % 10;
        SET MYSQL_VAR_3D6A5F = MYSQL_VAR_3D6A5F + POW(MYSQL_VAR_YY0A8U, MYSQL_VAR_2IA9YW);
        SET MYSQL_VAR_BYAQNP = MYSQL_VAR_BYAQNP / 10;
    END WHILE;

    IF MYSQL_VAR_3D6A5F = N THEN
        RETURN 1;
    END IF;

    RETURN (MYSQL_FUNC_4F968M(30) - (0) + COALESCE(0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FMPN6C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FMPN6C(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ST28RX INT DEFAULT 0;

    SELECT MAX(ORDER_ID)
    INTO MYSQL_VAR_ST28RX
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_ST28RX % 1000;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6MABR9(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RHBYEA INT DEFAULT 0;
    DECLARE MYSQL_VAR_US4NWA INT DEFAULT 0;
    DECLARE MYSQL_VAR_0Z9JPH DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_ETXJ66 DECIMAL(10,6) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_FMPN6C(30) - (0) + COALESCE(COALESCE(SUM(CONVERSION_VALUE), 0), 0))
    INTO MYSQL_VAR_RHBYEA
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_3EWCOM(20) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_US4NWA
    FROM CAMPAIGN_IMPRESSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_US4NWA = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_ETXJ66 = MYSQL_FUNC_SZ3NF4(30);

    RETURN (MYSQL_FUNC_1DT1O5(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_ETXJ66 * 10000), 0));
END//

DELIMITER ;