/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_ZXZAL3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZXZAL3(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OQOAIJ DATE;
    DECLARE MYSQL_VAR_AGD2WH INT DEFAULT 0;

    SELECT HIRE_DATE
    INTO MYSQL_VAR_OQOAIJ
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_AGD2WH = TIMESTAMPDIFF(YEAR, MYSQL_VAR_OQOAIJ, CURDATE());

    RETURN MYSQL_VAR_AGD2WH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_C6QBVQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_C6QBVQ(POLICY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V3DGQ7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_XCBGRR INT DEFAULT 0;
    DECLARE MYSQL_VAR_GIUCOA INT DEFAULT 0;

    SELECT COALESCE(PREMIUM_ANNUAL, 0)
    INTO MYSQL_VAR_V3DGQ7
    FROM INSURANCE_POLICIES
    WHERE POLICY_ID = POLICY_ID_PARAM;

    SELECT COALESCE(SUM(CLAIM_AMOUNT), 0)
    INTO MYSQL_VAR_XCBGRR
    FROM CLAIMS
    WHERE POLICY_ID = POLICY_ID_PARAM AND STATUS = 'APPROVED';

    IF MYSQL_VAR_V3DGQ7 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_GIUCOA = (MYSQL_VAR_XCBGRR * 100) / MYSQL_VAR_V3DGQ7;

    RETURN MYSQL_VAR_GIUCOA;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TVKE4A----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TVKE4A(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HZZVWT INT DEFAULT 0;
    DECLARE MYSQL_VAR_RFWOR9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_U1PGX0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_KJ6XFF INT DEFAULT FALSE;
    DECLARE MYSQL_VAR_VK17XZ INT;

    DECLARE MYSQL_VAR_FQ22JH CURSOR FOR
        SELECT DISTINCT O.ORDER_ID FROM ORDERS O
        JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
        JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
        WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM AND O.STATUS = 'COMPLETED';

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MYSQL_VAR_KJ6XFF = TRUE;

    OPEN MYSQL_VAR_FQ22JH;

    ORDER_LOOP: LOOP
        FETCH MYSQL_VAR_FQ22JH INTO MYSQL_VAR_VK17XZ;
        IF MYSQL_VAR_KJ6XFF THEN
            LEAVE ORDER_LOOP;
        END IF;

        SELECT MYSQL_FUNC_ZXZAL3(20) INTO MYSQL_VAR_HZZVWT
        FROM ORDER_ITEMS OI
        WHERE OI.ORDER_ID = MYSQL_VAR_VK17XZ;

        SET MYSQL_VAR_U1PGX0 = MYSQL_VAR_U1PGX0 + 1;
    END LOOP ORDER_LOOP;

    CLOSE MYSQL_VAR_FQ22JH;

    RETURN MYSQL_FUNC_C6QBVQ(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9HHANA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9HHANA(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4GIDU6 VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_AUB3W4 INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_4GIDU6, MYSQL_VAR_AUB3W4
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_4GIDU6 != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_AUB3W4 * 5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XN9NC8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XN9NC8(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2MU5F0 INT DEFAULT 0;

    SELECT MYSQL_FUNC_TVKE4A(10)
    INTO MYSQL_VAR_2MU5F0
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_FUNC_9HHANA(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5H5DM7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5H5DM7(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5RJ61V INT DEFAULT 0;

    SELECT MYSQL_FUNC_XN9NC8(30)
    INTO MYSQL_VAR_5RJ61V
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_VAR_5RJ61V;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AE2EPO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AE2EPO(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BFBWSI INT DEFAULT 0;
    DECLARE MYSQL_VAR_OMC7UB INT DEFAULT 0;

    SELECT COUNT(*), COUNT(O.ORDER_ID)
    INTO MYSQL_VAR_BFBWSI, MYSQL_VAR_OMC7UB
    FROM CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    IF MYSQL_VAR_BFBWSI = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_OMC7UB * 100) / MYSQL_VAR_BFBWSI;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VZVROU(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_O84KAZ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_5KZFIF INT DEFAULT 0;

    SELECT MYSQL_FUNC_AE2EPO('test_2_0')
    INTO MYSQL_VAR_O84KAZ, MYSQL_VAR_5KZFIF
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_5KZFIF = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_5H5DM7(10);
END//

DELIMITER ;