/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_w67prt (
    emp_no INT,
    salary INT
);
INSERT INTO table_w67prt (emp_no, salary) VALUES
(10001, 60117),
(10001, 62102),
(10001, 66074),
(10002, 65828),
(10002, 65909),
(10002, 67534);

CREATE TABLE IF NOT EXISTS table_hbda4d (
    `id` INT PRIMARY KEY,
    `age` INT
);
CREATE TABLE IF NOT EXISTS table_jgsjl0 (
    `user_id` INT,
    `address` VARCHAR(30),
    `town` VARCHAR(30)
);
INSERT INTO table_hbda4d (`id`, `age`) VALUES (1, 25), (2, 30), (3, 40);
INSERT INTO table_jgsjl0 (`user_id`, `address`, `town`) VALUES (1, '123 Main St', 'Springfield'), (2, '456 Oak Ave', 'Shelbyville'), (3, '789 Pine Rd', 'Springfield');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_S0IXK6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S0IXK6(A INT, B INT) RETURNS INT
BEGIN
RETURN A * B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CHAZ9V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CHAZ9V() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YMI56F INT DEFAULT 0;
    
    SELECT COUNT(*) INTO MYSQL_VAR_YMI56F 
    FROM MYSQL.PROCS_PRIV 
    WHERE USER LIKE 'U2%';
    
    RETURN MYSQL_VAR_YMI56F;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Y60I2T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Y60I2T(P_ADDRESS INT, V_TOWN INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UA5ZC8 INT DEFAULT 0;
    
    UPDATE TABLE_HBDA4D AS U
    JOIN TABLE_JGSJL0 AS A
    ON U.`ID` = A.`USER_ID`
    SET `AGE` = `AGE` + 10
    WHERE A.`ADDRESS` = CAST(P_ADDRESS AS CHAR) AND A.`TOWN` = CAST(V_TOWN AS CHAR);
    
    SET MYSQL_VAR_UA5ZC8 = MYSQL_FUNC_S0IXK6(30, 31);
    
    RETURN (MYSQL_FUNC_CHAZ9V() - (0) + COALESCE(MYSQL_VAR_UA5ZC8, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PT7PK9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PT7PK9(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8U8QPW DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(SALARY), 0)
    INTO MYSQL_VAR_8U8QPW
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_8U8QPW / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2PG2LZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2PG2LZ() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XV592I INT DEFAULT 0;
    
    SELECT (MYSQL_FUNC_PT7PK9(10) - (0) + COALESCE(COUNT(*), 0)) INTO MYSQL_VAR_XV592I FROM TABLE_UPBWNL.`TABLE3`;
    
    RETURN (MYSQL_FUNC_Y60I2T(20, 21) - (0) + COALESCE(MYSQL_VAR_XV592I, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YCWHRI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YCWHRI(LENGTH_PARAM INT) RETURNS VARCHAR(100)
BEGIN
DECLARE MYSQL_VAR_JCY3EH VARCHAR(100) DEFAULT '';
    DECLARE MYSQL_VAR_B7IGOV INT DEFAULT 1;
    DECLARE MYSQL_VAR_40E9TK INT DEFAULT 0;
    DECLARE MYSQL_VAR_CVYS70 INT DEFAULT 0;

    IF LENGTH_PARAM <= 0 THEN
        RETURN '';
    END IF;

    SET MYSQL_VAR_B7IGOV = 1;

    PASSWORD_LOOP: WHILE MYSQL_VAR_B7IGOV <= LENGTH_PARAM DO
        SET MYSQL_VAR_CVYS70 = RAND() * 10;

        IF MYSQL_VAR_CVYS70 < 3 AND MYSQL_VAR_B7IGOV < LENGTH_PARAM THEN
            SET MYSQL_VAR_40E9TK = RAND() * 10 + 33;
        ELSEIF MYSQL_VAR_CVYS70 < 6 THEN
            SET MYSQL_VAR_40E9TK = RAND() * 26 + 65;
        ELSE
            SET MYSQL_VAR_40E9TK = RAND() * 26 + 97;
        END IF;

        SET MYSQL_VAR_JCY3EH = CONCAT(MYSQL_VAR_JCY3EH, CHAR(MYSQL_VAR_40E9TK));
        SET MYSQL_VAR_B7IGOV = MYSQL_VAR_B7IGOV + 1;
    END WHILE PASSWORD_LOOP;

    RETURN MYSQL_VAR_JCY3EH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HHMQJV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HHMQJV() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_THXPVL INT DEFAULT 0;
    SELECT CSET INTO MYSQL_VAR_THXPVL FROM TABLE_7UF0YV.`TABLE3` LIMIT 1;
    RETURN MYSQL_VAR_THXPVL;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IP2KIK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IP2KIK() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_90X96D INT DEFAULT 0;
    SELECT COUNT(*) INTO MYSQL_VAR_90X96D FROM TABLE_VB60CU.`TABLE3`;
    RETURN MYSQL_VAR_90X96D;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XGQ0PJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XGQ0PJ(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1MJJJU INT DEFAULT 2;
    DECLARE MYSQL_VAR_F6ISFQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_L6RSCK INT DEFAULT 0;
    DECLARE MYSQL_VAR_O4L81Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_V88748 INT DEFAULT 0;

    SELECT COALESCE(WARRANTY_YEARS, 2), COALESCE(COVERAGE_AMOUNT, 1000), COALESCE(DEDUCTIBLE, 100)
    INTO MYSQL_VAR_1MJJJU, MYSQL_VAR_F6ISFQ, MYSQL_VAR_L6RSCK
    FROM INSURANCE_WARRANTY
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(REPAIR_COST), 0) INTO MYSQL_VAR_O4L81Z
    FROM WARRANTY_CLAIMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM AND STATUS = 'APPROVED';

    SET MYSQL_VAR_V88748 = (MYSQL_VAR_1MJJJU * 20) + (MYSQL_VAR_F6ISFQ / 100) - (MYSQL_VAR_L6RSCK / 10);

    IF MYSQL_VAR_O4L81Z > 500 THEN
        SET MYSQL_VAR_V88748 = MYSQL_VAR_V88748 - 30;
    END IF;

    RETURN CAST(MYSQL_VAR_V88748 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P603YI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P603YI(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DSL3PI DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_DSL3PI
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_XGQ0PJ(10) - (0) + COALESCE(FLOOR(MYSQL_VAR_DSL3PI * 20), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AJH8QL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AJH8QL(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XUBHNK INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_XUBHNK
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN LEAST(MYSQL_VAR_XUBHNK, 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BUFBMO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BUFBMO(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PI7MU8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_354KGX INT DEFAULT 0;
    DECLARE MYSQL_VAR_7IIPC4 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_HHMQJV() - (0) + COALESCE(COALESCE(TOTAL_AMOUNT, 0), 0))
    INTO MYSQL_VAR_PI7MU8
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT (MYSQL_FUNC_IP2KIK() - (0) + COALESCE(COALESCE(SUM(REFUND_AMOUNT), 0), 0))
    INTO MYSQL_VAR_354KGX
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_7IIPC4 = MYSQL_FUNC_P603YI(10);

    RETURN (MYSQL_FUNC_AJH8QL(10) - (0) + COALESCE(MYSQL_VAR_7IIPC4, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_O5NBRR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_O5NBRR(P_EMP_NO INT, CHAR_SEQ INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QYIACO INT;
    
    IF CHAR_SEQ = 0 THEN
        SELECT MIN(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    ELSEIF CHAR_SEQ = 1 THEN
        SELECT MAX(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    ELSE
        SELECT MAX(SALARY) - MIN(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    END IF;
    
    RETURN IFNULL(MYSQL_VAR_QYIACO, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LBIJLR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LBIJLR(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SEKNO0 DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_YWF5IC DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_QQQYU1 INT DEFAULT 0;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_SEKNO0
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(STDDEV(SALARY), 0) / 1000
    INTO MYSQL_VAR_YWF5IC
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_QQQYU1 = (MYSQL_VAR_SEKNO0 * 15) - (MYSQL_VAR_YWF5IC * 5);

    RETURN GREATEST(MYSQL_VAR_QQQYU1, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LBL99S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LBL99S(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LQXFN5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7GKSFV DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4IWMC7 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_YCWHRI(30) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_LQXFN5
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT (MYSQL_FUNC_O5NBRR(20, 21) - (0) + COALESCE(COALESCE(AVG(QUANTITY), 0) / 30, 0))
    INTO MYSQL_VAR_7GKSFV
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 90 DAY));

    IF MYSQL_VAR_7GKSFV = 0 THEN
        RETURN 999;
    END IF;

    SET MYSQL_VAR_4IWMC7 = MYSQL_FUNC_LBIJLR(30);

    RETURN (MYSQL_FUNC_BUFBMO(20) - (0) + COALESCE(MYSQL_VAR_4IWMC7, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JWFJEB(DATA_FIRST INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_K9YWLH INT;
    SET MYSQL_VAR_K9YWLH = MYSQL_FUNC_LBL99S(10);
    RETURN (MYSQL_FUNC_2PG2LZ() - (0) + COALESCE(MYSQL_VAR_K9YWLH - DATA_FIRST, 0));
END//

DELIMITER ;