/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_w67prt (
    emp_no INT,
    salary INT
);
INSERT INTO table_w67prt (emp_no, salary) VALUES
(10001, 60117),
(10001, 62102),
(10001, 66074),
(10002, 65828),
(10002, 65909),
(10002, 67534);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_7SWC2B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7SWC2B(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UAF4YK INT DEFAULT 0;
    DECLARE MYSQL_VAR_7QNKXG INT DEFAULT 1;
    DECLARE MYSQL_VAR_BIUS89 INT DEFAULT 1;
    DECLARE MYSQL_VAR_NYBK00 INT DEFAULT 0;

    IF N <= 0 OR N > 100 THEN
        RETURN 0;
    END IF;

    OUTER_LOOP: WHILE MYSQL_VAR_7QNKXG <= N DO
        INNER_LOOP: WHILE MYSQL_VAR_BIUS89 <= N DO
            IF MYSQL_VAR_7QNKXG = MYSQL_VAR_BIUS89 THEN
                SET MYSQL_VAR_NYBK00 = MYSQL_VAR_NYBK00 + (MYSQL_VAR_7QNKXG * MYSQL_VAR_BIUS89);
            END IF;
            SET MYSQL_VAR_BIUS89 = MYSQL_VAR_BIUS89 + 1;
        END WHILE INNER_LOOP;
        SET MYSQL_VAR_BIUS89 = 1;
        SET MYSQL_VAR_7QNKXG = MYSQL_VAR_7QNKXG + 1;
    END WHILE OUTER_LOOP;

    RETURN MYSQL_VAR_NYBK00;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_M1YTTC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M1YTTC(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H1XNEE INT DEFAULT 0;
    DECLARE MYSQL_VAR_LRBQPT INT DEFAULT 7;
    DECLARE MYSQL_VAR_FDHQY4 INT DEFAULT 90;
    DECLARE MYSQL_VAR_JJK50U INT DEFAULT 10;
    DECLARE MYSQL_VAR_PO87ZF INT DEFAULT 0;
    DECLARE MYSQL_VAR_UP62SP INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 100)
    INTO MYSQL_VAR_H1XNEE
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(LEAD_TIME_DAYS, 7), COALESCE(RELIABILITY_SCORE, 90)
    INTO MYSQL_VAR_LRBQPT, MYSQL_VAR_FDHQY4
    FROM SUPPLIERS S
    JOIN PRODUCTS P ON S.BRAND_ID = P.BRAND_ID
    WHERE P.PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_JJK50U = 10;
    SET MYSQL_VAR_PO87ZF = MYSQL_VAR_H1XNEE / MYSQL_VAR_JJK50U;

    IF MYSQL_VAR_PO87ZF < MYSQL_VAR_LRBQPT THEN
        SET MYSQL_VAR_UP62SP = 50 + ((MYSQL_VAR_LRBQPT - MYSQL_VAR_PO87ZF) * 5);
    ELSE
        SET MYSQL_VAR_UP62SP = 100 - MYSQL_VAR_FDHQY4;
    END IF;

    RETURN MYSQL_VAR_UP62SP;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_X01DP4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_X01DP4(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UFJ2AG VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_21DFTP INT DEFAULT 0;
    DECLARE MYSQL_VAR_HORBDQ DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_M1YTTC(30)
    INTO MYSQL_VAR_UFJ2AG, MYSQL_VAR_21DFTP
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_HORBDQ
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_UFJ2AG != 'ACTIVE' OR MYSQL_VAR_21DFTP = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_HORBDQ * 100) / MYSQL_VAR_21DFTP);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UD3RZO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UD3RZO(GYM_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EJNEFN INT DEFAULT 0;
    DECLARE MYSQL_VAR_NBHLS4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_QCADXN INT DEFAULT 0;
    DECLARE MYSQL_VAR_1ILNFP INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_FEE, 50), COALESCE(EQUIPMENT_COUNT, 50)
    INTO MYSQL_VAR_EJNEFN, MYSQL_VAR_NBHLS4
    FROM GYMS
    WHERE GYM_ID = GYM_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_QCADXN
    FROM MEMBERSHIPS
    WHERE GYM_ID = GYM_ID_PARAM AND STATUS = 'ACTIVE';

    SET MYSQL_VAR_1ILNFP = (MYSQL_VAR_NBHLS4 / 5) + (MYSQL_VAR_QCADXN / 10) - (MYSQL_VAR_EJNEFN / 10);

    RETURN MYSQL_VAR_1ILNFP;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_O5NBRR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_O5NBRR(P_EMP_NO INT, CHAR_SEQ INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QYIACO INT;
    
    IF CHAR_SEQ = 0 THEN
        SELECT MIN(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    ELSEIF CHAR_SEQ = 1 THEN
        SELECT MAX(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    ELSE
        SELECT MAX(SALARY) - MIN(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    END IF;
    
    RETURN IFNULL(MYSQL_VAR_QYIACO, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_T3STUR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_T3STUR(INPUT_VAL VARCHAR(50), MULTIPLIER INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AU4NLW INT DEFAULT 0;
    DECLARE MYSQL_VAR_MTME44 INT DEFAULT 0;

    SET MYSQL_VAR_AU4NLW = CAST(INPUT_VAL AS SIGNED);

    IF MYSQL_VAR_AU4NLW < 0 THEN
        SET MYSQL_VAR_AU4NLW = 0 - MYSQL_VAR_AU4NLW;
    END IF;

    SET MYSQL_VAR_MTME44 = MYSQL_VAR_AU4NLW * MULTIPLIER;

    RETURN MYSQL_VAR_MTME44;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BLX130----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BLX130(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GMUGGZ INT DEFAULT 0;

    SELECT MYSQL_FUNC_O5NBRR(30, 31)
    INTO MYSQL_VAR_GMUGGZ
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_T3STUR('test_1_0', 21);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JRP5H5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JRP5H5(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MQ93S6 INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_MQ93S6
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN 30 - MYSQL_VAR_MQ93S6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OB1WFE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OB1WFE(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EYBWR2 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_OZJVNY DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_JRP5H5(10)
    INTO MYSQL_VAR_EYBWR2
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT MYSQL_FUNC_UD3RZO(30)
    INTO MYSQL_VAR_OZJVNY
    FROM ORDERS
    WHERE STATUS = 'COMPLETED';

    IF MYSQL_VAR_OZJVNY = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_BLX130(10);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5TNCFY(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MUOQWZ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_IKP0TF INT DEFAULT 0;
    DECLARE MYSQL_VAR_1H9MLF DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_OB1WFE(30)
    INTO MYSQL_VAR_MUOQWZ
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT MYSQL_FUNC_X01DP4(10)
    INTO MYSQL_VAR_IKP0TF
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_IKP0TF = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_1H9MLF = MYSQL_FUNC_7SWC2B(20);

    RETURN FLOOR(MYSQL_VAR_1H9MLF);
END//

DELIMITER ;