/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_J1RJ2X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J1RJ2X(INVOICE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NXUDJL DATE;
    DECLARE MYSQL_VAR_7KUGZW INT DEFAULT 0;
    DECLARE MYSQL_VAR_GR7U6F INT DEFAULT 0;
    DECLARE MYSQL_VAR_6GZA4F INT DEFAULT 0;
    DECLARE MYSQL_VAR_7VQ3MM INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0), DUE_DATE
    INTO MYSQL_VAR_7KUGZW, MYSQL_VAR_NXUDJL
    FROM INVOICES
    WHERE INVOICE_ID = INVOICE_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT_PAID), 0)
    INTO MYSQL_VAR_GR7U6F
    FROM PAYMENTS
    WHERE INVOICE_ID = INVOICE_ID_PARAM;

    SET MYSQL_VAR_6GZA4F = MYSQL_VAR_7KUGZW - MYSQL_VAR_GR7U6F;

    IF MYSQL_VAR_6GZA4F <= 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_7VQ3MM = DATEDIFF(CURDATE(), MYSQL_VAR_NXUDJL);

    IF MYSQL_VAR_7VQ3MM < 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_7VQ3MM;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3CDZ3E----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3CDZ3E(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_B416CC INT DEFAULT 1;
    DECLARE MYSQL_VAR_3JKPDW INT DEFAULT 1;

    IF N < 0 THEN
        RETURN 0;
    END IF;

    SIMPLE_LOOP: WHILE MYSQL_VAR_3JKPDW <= N DO
        SET MYSQL_VAR_B416CC = MYSQL_VAR_B416CC * MYSQL_VAR_3JKPDW;
        SET MYSQL_VAR_3JKPDW = MYSQL_VAR_3JKPDW + 1;
    END WHILE SIMPLE_LOOP;

    RETURN MYSQL_FUNC_J1RJ2X(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VDMAOH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VDMAOH(PRODUCT_ID_PARAM INT, WAREHOUSE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RF2PUF INT DEFAULT 0;
    DECLARE MYSQL_VAR_BZW1YU INT DEFAULT 0;
    DECLARE MYSQL_VAR_2KLDCH INT DEFAULT 0;
    DECLARE MYSQL_VAR_BZ59PK INT DEFAULT 0;
    DECLARE MYSQL_VAR_DVYREV INT DEFAULT 0;

    SELECT MYSQL_FUNC_3CDZ3E(30)
    INTO MYSQL_VAR_RF2PUF, MYSQL_VAR_BZW1YU, MYSQL_VAR_2KLDCH
    FROM INVENTORY I
    JOIN PRODUCTS P ON I.PRODUCT_ID = P.PRODUCT_ID
    WHERE I.PRODUCT_ID = PRODUCT_ID_PARAM AND I.WAREHOUSE_ID = WAREHOUSE_ID_PARAM;

    IF MYSQL_VAR_RF2PUF < MYSQL_VAR_BZW1YU THEN
        SET MYSQL_VAR_BZ59PK = MYSQL_VAR_BZW1YU * 2 - MYSQL_VAR_RF2PUF;
        SET MYSQL_VAR_DVYREV = MYSQL_VAR_BZ59PK * MYSQL_VAR_2KLDCH;
        RETURN MYSQL_VAR_DVYREV;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AFZQCH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AFZQCH(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_C50CYE INT DEFAULT 0;
    DECLARE MYSQL_VAR_I39HA1 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_JMWDSD DECIMAL(10,2) DEFAULT 0.00;

    SELECT COUNT(*), COALESCE(AVG(SALARY), 0),
           COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_C50CYE, MYSQL_VAR_I39HA1, MYSQL_VAR_JMWDSD
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_I39HA1 * MYSQL_VAR_JMWDSD) / GREATEST(MYSQL_VAR_C50CYE, 1));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZOU44V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZOU44V(WARRANTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HAKN9G DATE;
    DECLARE MYSQL_VAR_ZNCB2Y INT DEFAULT 0;
    DECLARE MYSQL_VAR_NPC6HS DATE;
    DECLARE MYSQL_VAR_WCBOZX INT DEFAULT 0;
    DECLARE MYSQL_VAR_04PS9D INT DEFAULT 0;

    SELECT PURCHASE_DATE, WARRANTY_MONTHS
    INTO MYSQL_VAR_HAKN9G, MYSQL_VAR_ZNCB2Y
    FROM WARRANTIES
    WHERE WARRANTY_ID = WARRANTY_ID_PARAM;

    IF MYSQL_VAR_HAKN9G IS NULL THEN
        RETURN -1;
    END IF;

    SET MYSQL_VAR_NPC6HS = DATE_ADD(MYSQL_VAR_HAKN9G, INTERVAL MYSQL_VAR_ZNCB2Y MONTH);
    SET MYSQL_VAR_WCBOZX = DATEDIFF(MYSQL_VAR_NPC6HS, CURDATE());

    IF MYSQL_VAR_WCBOZX < 0 THEN
        SET MYSQL_VAR_04PS9D = 0;
    ELSEIF MYSQL_VAR_WCBOZX <= 30 THEN
        SET MYSQL_VAR_04PS9D = 1;
    ELSE
        SET MYSQL_VAR_04PS9D = 2;
    END IF;

    RETURN MYSQL_VAR_04PS9D;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WDETTX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WDETTX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FO67SF DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_FO67SF
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_FO67SF);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UGOF8I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UGOF8I(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V64TQO INT DEFAULT 0;
    DECLARE MYSQL_VAR_8D324A VARCHAR(20) DEFAULT 'INACTIVE';

    SELECT MYSQL_FUNC_WDETTX(20)
    INTO MYSQL_VAR_V64TQO, MYSQL_VAR_8D324A
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_8D324A != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_V64TQO * 12;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4BD807----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4BD807(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IGXKPM INT DEFAULT 0;
    DECLARE MYSQL_VAR_1VR3EW INT DEFAULT 0;
    DECLARE MYSQL_VAR_VOCOD6 INT DEFAULT 0;

    SELECT MYSQL_FUNC_ZOU44V(10)
    INTO MYSQL_VAR_IGXKPM
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT MYSQL_FUNC_UGOF8I(10)
    INTO MYSQL_VAR_1VR3EW
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_IGXKPM = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_VOCOD6 = (MYSQL_VAR_1VR3EW * 100) / MYSQL_VAR_IGXKPM;

    RETURN MYSQL_FUNC_AFZQCH(10);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RB6TTU(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7KD3VJ INT DEFAULT 0;

    SELECT MYSQL_FUNC_4BD807(10)
    INTO MYSQL_VAR_7KD3VJ
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_FUNC_VDMAOH(30, 31);
END//

DELIMITER ;