/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_TRMH9I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TRMH9I(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8KOQGQ INT DEFAULT 2;
    DECLARE MYSQL_VAR_LA6QNT INT DEFAULT 0;

    IF N <= 1 THEN RETURN 0; END IF;
    IF N <= 3 THEN RETURN 1; END IF;
    IF N % 2 = 0 OR N % 3 = 0 THEN RETURN 0; END IF;

    SET MYSQL_VAR_LA6QNT = FLOOR(SQRT(N));
    SET MYSQL_VAR_8KOQGQ = 5;

    PRIME_LOOP: WHILE MYSQL_VAR_8KOQGQ <= MYSQL_VAR_LA6QNT DO
        IF N % MYSQL_VAR_8KOQGQ = 0 OR N % (MYSQL_VAR_8KOQGQ + 2) = 0 THEN
            RETURN 0;
        END IF;
        SET MYSQL_VAR_8KOQGQ = MYSQL_VAR_8KOQGQ + 6;
    END WHILE PRIME_LOOP;

    RETURN 1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OJSZWT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OJSZWT(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_S30NFY DATE;

    SELECT MYSQL_FUNC_TRMH9I(30)
    INTO MYSQL_VAR_S30NFY
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_S30NFY IS NULL THEN
        RETURN 0;
    END IF;

    RETURN QUARTER(MYSQL_VAR_S30NFY);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7YMH98----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7YMH98(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XZ550I DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_Q0SE34 INT DEFAULT 0;

    SELECT MYSQL_FUNC_OJSZWT(30)
    INTO MYSQL_VAR_XZ550I
    FROM CONVERSIONS C
    JOIN CAMPAIGNS CAMP ON C.CAMPAIGN_ID = CAMP.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SET MYSQL_VAR_Q0SE34 = GREATEST(100 - (MYSQL_VAR_XZ550I * 5), 0);

    RETURN MYSQL_VAR_Q0SE34;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8LUT9O----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8LUT9O(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_62WUSE INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y5ZIL9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_PQKBUU INT DEFAULT 0;

    SELECT COALESCE(TUITION_BALANCE, 0)
    INTO MYSQL_VAR_62WUSE
    FROM SCHOOL_STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT), 0) INTO MYSQL_VAR_Y5ZIL9
    FROM PAYMENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_PQKBUU = MYSQL_VAR_62WUSE - MYSQL_VAR_Y5ZIL9;

    IF MYSQL_VAR_PQKBUU < 0 THEN
        SET MYSQL_VAR_PQKBUU = 0;
    END IF;

    RETURN CAST(MYSQL_VAR_PQKBUU AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1K7PC8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1K7PC8(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LEBMVS INT DEFAULT 0;
    DECLARE MYSQL_VAR_AQXI8Y INT DEFAULT 0;
    DECLARE MYSQL_VAR_TKVGWP INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_LEBMVS
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_AQXI8Y
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_TKVGWP = MYSQL_VAR_LEBMVS - MYSQL_VAR_AQXI8Y;

    RETURN MYSQL_VAR_TKVGWP;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7TP2YD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7TP2YD(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_J0CVVQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_ITRPJM DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_J0CVVQ
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_ITRPJM
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_J0CVVQ = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_ITRPJM * 100) / MYSQL_VAR_J0CVVQ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2NGTSO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2NGTSO(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1I12DV DATE;
    DECLARE MYSQL_VAR_GJ8E0P DATE;

    SELECT START_DATE, END_DATE
    INTO MYSQL_VAR_1I12DV, MYSQL_VAR_GJ8E0P
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_1I12DV IS NULL OR MYSQL_VAR_GJ8E0P IS NULL THEN
        RETURN 0;
    END IF;

    RETURN DATEDIFF(MYSQL_VAR_GJ8E0P, MYSQL_VAR_1I12DV);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I4PM6N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I4PM6N(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZHIKJD INT DEFAULT 0;
    DECLARE MYSQL_VAR_E2XD1T INT DEFAULT 0;
    DECLARE MYSQL_VAR_1W4V61 DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_ND7LR5 INT DEFAULT 0;

    SELECT MYSQL_FUNC_2NGTSO(30)
    INTO MYSQL_VAR_ZHIKJD
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MYSQL_FUNC_1K7PC8(30)
    INTO MYSQL_VAR_E2XD1T
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_E2XD1T = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_1W4V61 = MYSQL_FUNC_7TP2YD(10);
    SET MYSQL_VAR_ND7LR5 = FLOOR((MYSQL_VAR_ZHIKJD / MYSQL_VAR_1W4V61) * 100);

    RETURN MYSQL_FUNC_8LUT9O(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CHAZ9V() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YMI56F INT DEFAULT 0;
    
    SELECT MYSQL_FUNC_I4PM6N(30) INTO MYSQL_VAR_YMI56F 
    FROM MYSQL.PROCS_PRIV 
    WHERE USER LIKE 'U2%';
    
    RETURN MYSQL_FUNC_7YMH98(20);
END//

DELIMITER ;