/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_H1LK9S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H1LK9S(ORDER_ID_PARAM INT, TAX_RATE_PERCENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TZ80F2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_160G6V INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_TZ80F2
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_160G6V = (MYSQL_VAR_TZ80F2 * TAX_RATE_PERCENT) / 100;

    RETURN MYSQL_VAR_160G6V;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9U0FND----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9U0FND(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M2XF2N INT DEFAULT 0;
    DECLARE MYSQL_VAR_KKNMEK INT DEFAULT 0;
    DECLARE MYSQL_VAR_60C56P DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(DISTINCT PRODUCT_ID), COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_M2XF2N, MYSQL_VAR_KKNMEK
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_KKNMEK = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_60C56P = (MYSQL_VAR_M2XF2N * 100.0) / MYSQL_VAR_KKNMEK;

    RETURN FLOOR(MYSQL_VAR_60C56P);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QHVSQ0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QHVSQ0(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6A7LNI INT DEFAULT 0;
    DECLARE MYSQL_VAR_8ICA4Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_EVLX3A INT DEFAULT 0;
    DECLARE MYSQL_VAR_LO274O INT DEFAULT 0;

    SELECT COALESCE(AVG(RATING), 0), COALESCE(SUM(HELPFUL_COUNT), 0), COUNT(*)
    INTO MYSQL_VAR_6A7LNI, MYSQL_VAR_8ICA4Z, MYSQL_VAR_EVLX3A
    FROM REVIEWS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_EVLX3A = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_LO274O = (MYSQL_VAR_6A7LNI * 20) + (MYSQL_VAR_8ICA4Z / 10) + (MYSQL_VAR_EVLX3A * 2);

    RETURN CAST(MYSQL_VAR_LO274O AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4BD807----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4BD807(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IGXKPM INT DEFAULT 0;
    DECLARE MYSQL_VAR_1VR3EW INT DEFAULT 0;
    DECLARE MYSQL_VAR_VOCOD6 INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_IGXKPM
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(REFUND_AMOUNT), 0)
    INTO MYSQL_VAR_1VR3EW
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_IGXKPM = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_VOCOD6 = (MYSQL_VAR_1VR3EW * 100) / MYSQL_VAR_IGXKPM;

    RETURN MYSQL_VAR_VOCOD6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1G0O5N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1G0O5N(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1OPC88 VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_ZH9NC2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_AQRYBC VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_LKBH8D DECIMAL(10,2) DEFAULT 0.00;

    SELECT C.STATUS, COALESCE(C.BUDGET, 0), C.CHANNEL,
           COALESCE(SUM(CV.CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_1OPC88, MYSQL_VAR_ZH9NC2, MYSQL_VAR_AQRYBC, MYSQL_VAR_LKBH8D
    FROM CAMPAIGNS C
    LEFT JOIN CONVERSIONS CV ON C.CAMPAIGN_ID = CV.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM
    GROUP BY C.CAMPAIGN_ID;

    IF MYSQL_VAR_1OPC88 != 'ACTIVE' OR MYSQL_VAR_ZH9NC2 = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_LKBH8D * 100) / MYSQL_VAR_ZH9NC2);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6MABR9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6MABR9(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RHBYEA INT DEFAULT 0;
    DECLARE MYSQL_VAR_US4NWA INT DEFAULT 0;
    DECLARE MYSQL_VAR_0Z9JPH DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_ETXJ66 DECIMAL(10,6) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_9U0FND(20) - (0) + COALESCE(COALESCE(SUM(CONVERSION_VALUE), 0), 0))
    INTO MYSQL_VAR_RHBYEA
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_4BD807(30) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_US4NWA
    FROM CAMPAIGN_IMPRESSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_US4NWA = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_ETXJ66 = MYSQL_FUNC_QHVSQ0(30);

    RETURN (MYSQL_FUNC_1G0O5N(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_ETXJ66 * 10000), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DK7NTV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DK7NTV(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GFK58C INT DEFAULT 0;

    SELECT (MYSQL_FUNC_6MABR9(30) - (0) + COALESCE(COALESCE(BUDGET, 0), 0))
    INTO MYSQL_VAR_GFK58C
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN (MYSQL_FUNC_H1LK9S(20, 21) - (0) + COALESCE(MYSQL_VAR_GFK58C / 100, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1J189G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1J189G(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5DZKQX INT DEFAULT 0;

    SELECT CUSTOMER_ID
    INTO MYSQL_VAR_5DZKQX
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_5DZKQX % 100;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7JHA7A(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AF0VT8 DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_WOF5NT INT DEFAULT 0;

    SELECT (MYSQL_FUNC_DK7NTV(20) - (0) + COALESCE(COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7), 0))
    INTO MYSQL_VAR_AF0VT8, MYSQL_VAR_WOF5NT
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_1J189G(30) - (0) + COALESCE((MYSQL_VAR_AF0VT8 * 15) - (MYSQL_VAR_WOF5NT * 2), 0));
END//

DELIMITER ;