/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_H4COTX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H4COTX(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_A0OWJF INT DEFAULT 0;
    DECLARE MYSQL_VAR_YD4H91 INT DEFAULT 0;

    SELECT COUNT(DISTINCT SUPPLIER_ID), COUNT(*)
    INTO MYSQL_VAR_A0OWJF, MYSQL_VAR_YD4H91
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_YD4H91 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_A0OWJF * 100) / MYSQL_VAR_YD4H91;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CA0TUQ(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6XE1B8 INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_6XE1B8
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN MYSQL_FUNC_H4COTX(30);
END//

DELIMITER ;