/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Seed Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4NMTOM(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_167ZVJ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_HYUXHE INT DEFAULT 0;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0), COUNT(*)
    INTO MYSQL_VAR_167ZVJ, MYSQL_VAR_HYUXHE
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    IF MYSQL_VAR_HYUXHE = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR(MYSQL_VAR_167ZVJ / MYSQL_VAR_HYUXHE);
END//

DELIMITER ;