/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_8M56HY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8M56HY(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AJYF9O INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_AJYF9O
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN LEAST(MYSQL_VAR_AJYF9O, 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YVJHK4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YVJHK4(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N2N7UM INT DEFAULT 0;

    SELECT COUNT(DISTINCT CATEGORY_ID)
    INTO MYSQL_VAR_N2N7UM
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_VAR_N2N7UM * 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OQO8UB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OQO8UB(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_64F5FK INT DEFAULT 0;

    SELECT DATEDIFF(CURDATE(), REGISTRATION_DATE)
    INTO MYSQL_VAR_64F5FK
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_64F5FK;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_79SFE3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_79SFE3(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IR23E8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_36EK8V INT DEFAULT 0;

    SELECT COALESCE(MAX(SALARY), 0), COALESCE(MIN(SALARY), 0)
    INTO MYSQL_VAR_IR23E8, MYSQL_VAR_36EK8V
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_VAR_IR23E8 - MYSQL_VAR_36EK8V;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JEJG4Z----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JEJG4Z(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RQ0E5J INT DEFAULT 0;

    IF N <= 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_RQ0E5J = N;

    UGLY_LOOP: WHILE MYSQL_VAR_RQ0E5J % 2 = 0 DO
        SET MYSQL_VAR_RQ0E5J = MYSQL_VAR_RQ0E5J / 2;
    END WHILE;

    UGLY_LOOP2: WHILE MYSQL_VAR_RQ0E5J % 3 = 0 DO
        SET MYSQL_VAR_RQ0E5J = MYSQL_VAR_RQ0E5J / 3;
    END WHILE;

    UGLY_LOOP3: WHILE MYSQL_VAR_RQ0E5J % 5 = 0 DO
        SET MYSQL_VAR_RQ0E5J = MYSQL_VAR_RQ0E5J / 5;
    END WHILE;

    IF MYSQL_VAR_RQ0E5J = 1 THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8NVH8S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8NVH8S(PROPERTY_SIZE_PARAM INT, JOB_TYPE_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_0X5K50 INT DEFAULT 2;
    DECLARE MYSQL_VAR_MID337 INT DEFAULT 50;
    DECLARE MYSQL_VAR_XXSSDK INT DEFAULT 1;
    DECLARE MYSQL_VAR_ZPM70Z INT DEFAULT 0;

    CASE JOB_TYPE_PARAM
        WHEN 'LAWN_MAINTENANCE' THEN SET MYSQL_VAR_XXSSDK = 1;
        WHEN 'TREE_TRIMMING' THEN SET MYSQL_VAR_XXSSDK = MYSQL_FUNC_YVJHK4(10);
        WHEN 'LANDSCAPE_DESIGN' THEN SET MYSQL_VAR_XXSSDK = MYSQL_FUNC_8M56HY(30);
        WHEN 'IRRIGATION' THEN SET MYSQL_VAR_XXSSDK = MYSQL_FUNC_79SFE3(20);
        ELSE SET MYSQL_VAR_XXSSDK = 1;
    END CASE;

    SET MYSQL_VAR_ZPM70Z = MYSQL_FUNC_OQO8UB(10);

    RETURN MYSQL_FUNC_JEJG4Z(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8L3VST() RETURNS INT
BEGIN
RETURN MYSQL_FUNC_8NVH8S(20, 'test_1_1');
END//

DELIMITER ;