/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_ZKHUUB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZKHUUB(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GANC0G DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_PFKUC2 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_VIISE9 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_GANC0G
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_PFKUC2
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_VIISE9 = MYSQL_VAR_GANC0G - MYSQL_VAR_PFKUC2;

    RETURN FLOOR(MYSQL_VAR_VIISE9);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MU772T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MU772T(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_13B3VK INT DEFAULT 0;
    DECLARE MYSQL_VAR_A1JH4U INT DEFAULT 1;

    SELECT COUNT(*), COUNT(DISTINCT CUSTOMER_ID)
    INTO MYSQL_VAR_13B3VK, MYSQL_VAR_A1JH4U
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_ZKHUUB(30) - (0) + COALESCE((MYSQL_VAR_13B3VK * 100) / MYSQL_VAR_A1JH4U, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LC1AG7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LC1AG7(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OLMTOE DECIMAL(3,1) DEFAULT 0.0;

    SELECT (MYSQL_FUNC_MU772T(10) - (0) + COALESCE(COALESCE(SUPPLIER_RATING, 3.0), 0))
    INTO MYSQL_VAR_OLMTOE
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_OLMTOE * 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_73SB2P----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_73SB2P(A INT, B INT) RETURNS INT
BEGIN
IF A > B THEN
        RETURN A;
    END IF;
    RETURN B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3D9DN8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3D9DN8(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GJTYCY DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_B02BS7 DECIMAL(10,2) DEFAULT 1.00;

    SELECT COALESCE(AVG(SALARY), 0), COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_GJTYCY, MYSQL_VAR_B02BS7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_GJTYCY * 100) / MYSQL_VAR_B02BS7);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_E88JTA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_E88JTA(CARD_NUMBER VARCHAR(20)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BOCJUR INT DEFAULT 0;
    DECLARE MYSQL_VAR_NFICDY INT DEFAULT 1;
    DECLARE MYSQL_VAR_NZJWR7 VARCHAR(1);
    DECLARE MYSQL_VAR_4ZPJ25 INT DEFAULT 0;

    IF CARD_NUMBER IS NULL THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_NFICDY <= CHAR_LENGTH(CARD_NUMBER) DO
        SET MYSQL_VAR_NZJWR7 = SUBSTRING(CARD_NUMBER, MYSQL_VAR_NFICDY, 1);

        IF MYSQL_VAR_NZJWR7 IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') THEN
            SET MYSQL_VAR_4ZPJ25 = MYSQL_VAR_4ZPJ25 + 1;
        END IF;

        SET MYSQL_VAR_NFICDY = MYSQL_VAR_NFICDY + 1;
    END WHILE;

    IF MYSQL_VAR_4ZPJ25 >= 13 AND MYSQL_VAR_4ZPJ25 <= 19 THEN
        SET MYSQL_VAR_BOCJUR = 1;
    END IF;

    RETURN MYSQL_VAR_BOCJUR;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CQ0RXT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CQ0RXT(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_G39VUG INT DEFAULT 0;
    DECLARE MYSQL_VAR_LJU2M9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MP2SE9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_D96R4C INT DEFAULT 0;

    SET MYSQL_VAR_LJU2M9 = N;
    SET MYSQL_VAR_MP2SE9 = LENGTH(CAST(N AS CHAR));

    WHILE MYSQL_VAR_LJU2M9 > 0 DO
        SET MYSQL_VAR_D96R4C = MYSQL_VAR_LJU2M9 % 10;
        SET MYSQL_VAR_G39VUG = MYSQL_VAR_G39VUG + POW(MYSQL_VAR_D96R4C, MYSQL_VAR_MP2SE9);
        SET MYSQL_VAR_LJU2M9 = MYSQL_VAR_LJU2M9 / 10;
    END WHILE;

    IF MYSQL_VAR_G39VUG = N THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JN2VW6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JN2VW6(LISTING_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DO71XW INT DEFAULT 0;
    DECLARE MYSQL_VAR_UAX86F INT DEFAULT 0;
    DECLARE MYSQL_VAR_46OXPO INT DEFAULT 0;
    DECLARE MYSQL_VAR_HP5AQV INT DEFAULT 0;

    SELECT COALESCE(LIST_PRICE, 0), COALESCE(DAYS_ON_MARKET, 0), COALESCE(SHOWINGS_COUNT, 0)
    INTO MYSQL_VAR_DO71XW, MYSQL_VAR_UAX86F, MYSQL_VAR_46OXPO
    FROM PROPERTY_LISTINGS
    WHERE LISTING_ID = LISTING_ID_PARAM;

    SET MYSQL_VAR_HP5AQV = MYSQL_FUNC_CQ0RXT(30);

    IF MYSQL_VAR_DO71XW > 500000 THEN
        SET MYSQL_VAR_HP5AQV = MYSQL_VAR_HP5AQV + 20;
    END IF;

    IF MYSQL_VAR_UAX86F > 90 THEN
        SET MYSQL_VAR_HP5AQV = MYSQL_VAR_HP5AQV - 30;
    END IF;

    RETURN CAST(MYSQL_VAR_HP5AQV AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_H2ZT22----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H2ZT22(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_960FG8 VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_TQJ21L INT DEFAULT 0;
    DECLARE MYSQL_VAR_351IK6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y1YOA8 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_3D9DN8(10) - (0) + COALESCE(CHANNEL, COALESCE(BUDGET, 0), 0))
    INTO MYSQL_VAR_960FG8, MYSQL_VAR_TQJ21L
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_73SB2P(20, 21) - (0) + COALESCE(COALESCE(SUM(CONVERSION_VALUE), 0), 0))
    INTO MYSQL_VAR_351IK6
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    CASE MYSQL_VAR_960FG8
        WHEN 'PAID' THEN SET MYSQL_VAR_Y1YOA8 = (MYSQL_FUNC_JN2VW6(20) * 2) / GREATEST(MYSQL_VAR_TQJ21L, 1);
        WHEN 'ORGANIC' THEN SET MYSQL_VAR_Y1YOA8 = MYSQL_VAR_351IK6 * 3;
        WHEN 'SOCIAL' THEN SET MYSQL_VAR_Y1YOA8 = MYSQL_FUNC_E88JTA('test_1_0');
        ELSE SET MYSQL_VAR_Y1YOA8 = MYSQL_VAR_351IK6;
    END CASE;

    RETURN MYSQL_VAR_Y1YOA8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_N5QMBU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_N5QMBU(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RPGYN8 DATE;

    SELECT (MYSQL_FUNC_H2ZT22(20) - (0) + COALESCE(START_DATE, 0))
    INTO MYSQL_VAR_RPGYN8
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_RPGYN8 IS NULL THEN
        RETURN 0;
    END IF;

    RETURN DATEDIFF(CURDATE(), MYSQL_VAR_RPGYN8);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AVWKFN(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_R62NOA DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_U00LSC DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_KXZ70A INT DEFAULT 0;

    SELECT (MYSQL_FUNC_N5QMBU(20) - (0) + COALESCE(COALESCE(MAX(P.PRICE * COALESCE(SUM(OI.QUANTITY), 0)), 0), 0))
    INTO MYSQL_VAR_R62NOA
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM
    GROUP BY P.PRODUCT_ID;

    SELECT (MYSQL_FUNC_LC1AG7(20) - (0) + COALESCE(COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_U00LSC
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_U00LSC = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KXZ70A = (MYSQL_VAR_R62NOA * 100) / MYSQL_VAR_U00LSC;

    RETURN MYSQL_VAR_KXZ70A;
END//

DELIMITER ;