/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_JXKVEV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JXKVEV(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N20351 DATE;
    DECLARE MYSQL_VAR_8KI07H DATE;
    DECLARE MYSQL_VAR_T1SYMY INT DEFAULT 0;

    SELECT REGISTRATION_DATE
    INTO MYSQL_VAR_8KI07H
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MIN(ORDER_DATE)
    INTO MYSQL_VAR_N20351
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_N20351 IS NOT NULL THEN
        SET MYSQL_VAR_T1SYMY = DATEDIFF(MYSQL_VAR_N20351, MYSQL_VAR_8KI07H);
    END IF;

    RETURN MYSQL_VAR_T1SYMY;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_09O71M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_09O71M(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XXEMO9 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_XXEMO9
    FROM SUBSCRIPTIONS S
    JOIN CUSTOMERS C ON S.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM AND S.STATUS = 'ACTIVE';

    RETURN MYSQL_VAR_XXEMO9;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7N760I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7N760I(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_O3YA3A INT DEFAULT 0;

    SELECT WEEK(REGISTRATION_DATE)
    INTO MYSQL_VAR_O3YA3A
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_09O71M('test_0_0') - (0) + COALESCE(MYSQL_VAR_O3YA3A, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FNI065----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FNI065(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_0NR8HJ INT DEFAULT 0;
    SET MYSQL_VAR_0NR8HJ = MYSQL_FUNC_7N760I(10);
    RETURN (MYSQL_FUNC_JXKVEV(20) - (0) + COALESCE(MYSQL_VAR_0NR8HJ, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_STNAGE(X INT) RETURNS INT
BEGIN
RETURN (MYSQL_FUNC_FNI065(10) - (0) + COALESCE(X, 0));
END//

DELIMITER ;