/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_IO0UZG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IO0UZG(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PQ6HVP INT DEFAULT 0;
    DECLARE MYSQL_VAR_UVAFBV DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_AD85FF INT DEFAULT 0;
    DECLARE MYSQL_VAR_8EQPX6 INT DEFAULT 0;

    SELECT SALARY, COALESCE(PERFORMANCE_RATING, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_PQ6HVP, MYSQL_VAR_UVAFBV, MYSQL_VAR_AD85FF
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    IF MYSQL_VAR_UVAFBV >= 4.5 THEN
        SET MYSQL_VAR_8EQPX6 = MYSQL_VAR_PQ6HVP * 1.15;
    ELSEIF MYSQL_VAR_UVAFBV >= 4.0 THEN
        SET MYSQL_VAR_8EQPX6 = MYSQL_VAR_PQ6HVP * 1.10;
    ELSEIF MYSQL_VAR_UVAFBV >= 3.5 THEN
        SET MYSQL_VAR_8EQPX6 = MYSQL_VAR_PQ6HVP * 1.05;
    ELSE
        SET MYSQL_VAR_8EQPX6 = MYSQL_VAR_PQ6HVP;
    END IF;

    RETURN MYSQL_VAR_8EQPX6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XUM2XW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XUM2XW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_02DXBE DATE;
    DECLARE MYSQL_VAR_E4ZHQP DATE;

    SELECT MIN(ORDER_DATE), MAX(ORDER_DATE)
    INTO MYSQL_VAR_02DXBE, MYSQL_VAR_E4ZHQP
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_02DXBE IS NULL THEN
        RETURN 0;
    END IF;

    RETURN DATEDIFF(MYSQL_VAR_E4ZHQP, MYSQL_VAR_02DXBE);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_L57884----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L57884(CAR_ID_PARAM INT, WASH_TYPE_PARAM VARCHAR(20)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9K68DQ INT DEFAULT 1;
    DECLARE MYSQL_VAR_2ZGPYN INT DEFAULT 20;
    DECLARE MYSQL_VAR_2Z8H48 INT DEFAULT 1;
    DECLARE MYSQL_VAR_FJEDPT INT DEFAULT 0;

    SELECT COALESCE(SIZE_CATEGORY, 1) INTO MYSQL_VAR_9K68DQ
    FROM CARS
    WHERE CAR_ID = CAR_ID_PARAM;

    CASE WASH_TYPE_PARAM
        WHEN 'BASIC' THEN SET MYSQL_VAR_2Z8H48 = 1;
        WHEN 'STANDARD' THEN SET MYSQL_VAR_2Z8H48 = 2;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_2Z8H48 = 3;
        WHEN 'FULL_DETAIL' THEN SET MYSQL_VAR_2Z8H48 = 5;
        ELSE SET MYSQL_VAR_2Z8H48 = 1;
    END CASE;

    SET MYSQL_VAR_FJEDPT = MYSQL_VAR_2ZGPYN * MYSQL_VAR_9K68DQ * MYSQL_VAR_2Z8H48;

    RETURN CAST(MYSQL_VAR_FJEDPT AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TVKE4A----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TVKE4A(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HZZVWT INT DEFAULT 0;
    DECLARE MYSQL_VAR_RFWOR9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_U1PGX0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_KJ6XFF INT DEFAULT FALSE;
    DECLARE MYSQL_VAR_VK17XZ INT;

    DECLARE MYSQL_VAR_FQ22JH CURSOR FOR
        SELECT DISTINCT O.ORDER_ID FROM ORDERS O
        JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
        JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
        WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM AND O.STATUS = 'COMPLETED';

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET MYSQL_VAR_KJ6XFF = TRUE;

    OPEN MYSQL_VAR_FQ22JH;

    ORDER_LOOP: LOOP
        FETCH MYSQL_VAR_FQ22JH INTO MYSQL_VAR_VK17XZ;
        IF MYSQL_VAR_KJ6XFF THEN
            LEAVE ORDER_LOOP;
        END IF;

        SELECT (MYSQL_FUNC_XUM2XW(30) - (0) + COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0)) INTO MYSQL_VAR_HZZVWT
        FROM ORDER_ITEMS OI
        WHERE OI.ORDER_ID = MYSQL_VAR_VK17XZ;

        SET MYSQL_VAR_U1PGX0 = MYSQL_FUNC_IO0UZG(30);
    END LOOP ORDER_LOOP;

    CLOSE MYSQL_VAR_FQ22JH;

    RETURN (MYSQL_FUNC_L57884(10, 'test_0_1') - (0) + COALESCE(COALESCE(MYSQL_VAR_HZZVWT, 0) + (MYSQL_VAR_U1PGX0 * 100), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9QDU9N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9QDU9N(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EJ68VW INT DEFAULT 0;
    DECLARE MYSQL_VAR_4GH5W0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_HADER0 DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(*), DATEDIFF(END_DATE, START_DATE)
    INTO MYSQL_VAR_EJ68VW, MYSQL_VAR_4GH5W0
    FROM CAMPAIGNS C
    LEFT JOIN CONVERSIONS CV ON C.CAMPAIGN_ID = CV.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM
    GROUP BY C.CAMPAIGN_ID;

    IF MYSQL_VAR_4GH5W0 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_HADER0 = MYSQL_VAR_EJ68VW / MYSQL_VAR_4GH5W0;

    RETURN FLOOR(MYSQL_VAR_HADER0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_97SY2I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_97SY2I(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XGM14J INT DEFAULT 0;
    DECLARE MYSQL_VAR_PX46IL INT DEFAULT 0;
    DECLARE MYSQL_VAR_V7YRII INT DEFAULT 0;

    SELECT COUNT(DISTINCT P.CATEGORY_ID), COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_XGM14J, MYSQL_VAR_PX46IL
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE OI.ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_PX46IL = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_V7YRII = (MYSQL_VAR_XGM14J * 100) / MYSQL_VAR_PX46IL;

    RETURN MYSQL_VAR_V7YRII;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5B0S8P----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5B0S8P(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XAH940 VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_1P49K7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_RNEHFQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_MSV7NY INT DEFAULT 0;

    SELECT CHANNEL, DATEDIFF(END_DATE, START_DATE)
    INTO MYSQL_VAR_XAH940, MYSQL_VAR_1P49K7
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_RNEHFQ
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    CASE MYSQL_VAR_XAH940
        WHEN 'PAID' THEN SET MYSQL_VAR_MSV7NY = MYSQL_VAR_RNEHFQ * 5;
        WHEN 'ORGANIC' THEN SET MYSQL_VAR_MSV7NY = MYSQL_VAR_RNEHFQ * 8;
        WHEN 'SOCIAL' THEN SET MYSQL_VAR_MSV7NY = MYSQL_VAR_RNEHFQ * 6;
        WHEN 'EMAIL' THEN SET MYSQL_VAR_MSV7NY = MYSQL_VAR_RNEHFQ * 7;
        ELSE SET MYSQL_VAR_MSV7NY = MYSQL_VAR_RNEHFQ * 4;
    END CASE;

    RETURN MYSQL_VAR_MSV7NY;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MKYQKX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MKYQKX(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PH5ASA INT DEFAULT 0;
    DECLARE MYSQL_VAR_TCOUDJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_CFYOXC DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(STOCK_QUANTITY, 0), PRICE
    INTO MYSQL_VAR_PH5ASA, MYSQL_VAR_CFYOXC
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_TCOUDJ
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_PH5ASA = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_TCOUDJ * 100) / MYSQL_VAR_PH5ASA;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2ZT2PS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2ZT2PS(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9T3285 INT DEFAULT 0;
    DECLARE MYSQL_VAR_37N668 INT;
    DECLARE MYSQL_VAR_8PSCZL INT;

    SET MYSQL_VAR_37N668 = MYSQL_FUNC_MKYQKX(10);
    SET MYSQL_VAR_8PSCZL = ABS(B);

    IF MYSQL_VAR_37N668 = 0 OR MYSQL_VAR_8PSCZL = 0 THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_8PSCZL != 0 DO
        SET MYSQL_VAR_9T3285 = MYSQL_VAR_8PSCZL;
        SET MYSQL_VAR_8PSCZL = MYSQL_VAR_37N668 MOD MYSQL_VAR_8PSCZL;
        SET MYSQL_VAR_37N668 = MYSQL_VAR_9T3285;
    END WHILE;

    RETURN (MYSQL_FUNC_5B0S8P(30) - (0) + COALESCE((ABS(A) / MYSQL_VAR_9T3285) * ABS(B), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z3TZAI(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SNTETE INT DEFAULT 0;
    DECLARE MYSQL_VAR_HSJA1P DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4RLE0K INT DEFAULT 7;
    DECLARE MYSQL_VAR_GYO6O8 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_2ZT2PS(10, 11) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_SNTETE
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT (MYSQL_FUNC_97SY2I(20) - (0) + COALESCE(COALESCE(AVG(QUANTITY), 0) / 30, 0))
    INTO MYSQL_VAR_HSJA1P
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY));

    SET MYSQL_VAR_GYO6O8 = MYSQL_FUNC_9QDU9N(10);

    RETURN (MYSQL_FUNC_TVKE4A(30) - (0) + COALESCE(MYSQL_VAR_GYO6O8, 0));
END//

DELIMITER ;