/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_EPCCKP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EPCCKP(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5XW42R INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_5XW42R
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_5XW42R;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FNI065----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FNI065(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_0NR8HJ INT DEFAULT 0;
    SET MYSQL_VAR_0NR8HJ = N * (N + 1) / 2;
    RETURN MYSQL_VAR_0NR8HJ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QB5C3I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QB5C3I(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6UJVZK DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_SW9T6H INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_6UJVZK
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT (MYSQL_FUNC_FNI065(30) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_SW9T6H
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_VAR_6UJVZK * 10) + (MYSQL_VAR_SW9T6H * 2);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S464W9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S464W9(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_APOBPO INT DEFAULT 0;

    SELECT COALESCE(SUM(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_APOBPO
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_QB5C3I(20) - (0) + COALESCE(LEAST(MYSQL_VAR_APOBPO, 1000), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PL0847(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LLLEM9 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_S464W9(30) - (0) + COALESCE(COALESCE(MONTHLY_COST, 0), 0))
    INTO MYSQL_VAR_LLLEM9
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_EPCCKP('test_2_0') - (0) + COALESCE(MYSQL_VAR_LLLEM9, 0));
END//

DELIMITER ;