/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_XDH86B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XDH86B(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_196Y6N DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4TFLJ6 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_32T8MD INT DEFAULT 0;

    SELECT COALESCE(SUM(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_196Y6N
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_4TFLJ6
    FROM ORDERS;

    IF MYSQL_VAR_4TFLJ6 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_32T8MD = (MYSQL_VAR_196Y6N * 100) / MYSQL_VAR_4TFLJ6;

    RETURN MYSQL_VAR_32T8MD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CVBGPG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CVBGPG(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_X4KSBV INT DEFAULT 0;

    SELECT COALESCE(PRICE, 0) * COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_X4KSBV
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN MYSQL_VAR_X4KSBV;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CMGDTN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CMGDTN(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KH3D42 DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_NEU4O9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_IVXCIX INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZLOGVQ INT DEFAULT 0;

    SELECT (MYSQL_FUNC_CVBGPG(30) - (0) + COALESCE(COALESCE(SUPPLIER_RATING, 3.0), 0))
    INTO MYSQL_VAR_KH3D42
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*), COALESCE(AVG(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_NEU4O9, MYSQL_VAR_IVXCIX
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_ZLOGVQ = (MYSQL_VAR_KH3D42 * 20) + (MYSQL_VAR_NEU4O9 * 3) + (MYSQL_VAR_IVXCIX / 100);

    RETURN MYSQL_VAR_ZLOGVQ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5R9UPI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5R9UPI(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JLMB6O INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZQPOL1 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_JLMB6O
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_ZQPOL1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMP_ID = EMP_ID_PARAM);

    IF MYSQL_VAR_ZQPOL1 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_JLMB6O * 100) / MYSQL_VAR_ZQPOL1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6FFIYL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6FFIYL() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KJU462 INT DEFAULT 0;
    SELECT COUNT(*) INTO MYSQL_VAR_KJU462 FROM TABLE_9AEQOO.`TABLE3`;
    RETURN MYSQL_VAR_KJU462;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UORL6J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UORL6J(CHILD_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PZUBEO INT DEFAULT 0;
    DECLARE MYSQL_VAR_AV96WC INT DEFAULT 0;
    DECLARE MYSQL_VAR_2IN23X INT DEFAULT 0;
    DECLARE MYSQL_VAR_8EVX73 INT DEFAULT 0;
    DECLARE MYSQL_VAR_YL1LUQ INT DEFAULT 0;

    SELECT TIMESTAMPDIFF(YEAR, DATE_OF_BIRTH, CURDATE())
    INTO MYSQL_VAR_PZUBEO
    FROM CHILDREN
    WHERE CHILD_ID = CHILD_ID_PARAM;

    SELECT WEEKLY_RATE
    INTO MYSQL_VAR_AV96WC
    FROM CHILDCARE_ENROLLMENTS
    WHERE CHILD_ID = CHILD_ID_PARAM
    ORDER BY START_DATE DESC LIMIT 1;

    IF MYSQL_VAR_AV96WC IS NULL THEN
        SET MYSQL_VAR_AV96WC = 200;
    END IF;

    SET MYSQL_VAR_YL1LUQ = MYSQL_FUNC_6FFIYL();

    IF MYSQL_VAR_PZUBEO < 2 THEN
        SET MYSQL_VAR_8EVX73 = MYSQL_VAR_AV96WC * 25 / 100;
        SET MYSQL_VAR_YL1LUQ = MYSQL_VAR_YL1LUQ + MYSQL_VAR_8EVX73;
    END IF;

    RETURN CAST(MYSQL_VAR_YL1LUQ AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZNQHPG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZNQHPG(A INT, B INT, C INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JKTAJ0 INT DEFAULT 0;
    SET MYSQL_VAR_JKTAJ0 = MYSQL_FUNC_5R9UPI(20);
    IF B > MYSQL_VAR_JKTAJ0 THEN SET MYSQL_VAR_JKTAJ0 = B; END IF;
    IF C > MYSQL_VAR_JKTAJ0 THEN SET MYSQL_VAR_JKTAJ0 = C; END IF;
    RETURN (MYSQL_FUNC_UORL6J(30) - (0) + COALESCE(MYSQL_VAR_JKTAJ0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_C8XQV4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_C8XQV4(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
RETURN CUSTOMER_ID_PARAM % 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DXVG73----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DXVG73(SALE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DT1HRA INT DEFAULT 0;
    DECLARE MYSQL_VAR_IV0RYW INT DEFAULT 3;
    DECLARE MYSQL_VAR_BRWSXZ INT DEFAULT 60;
    DECLARE MYSQL_VAR_4YMBCK INT DEFAULT 0;
    DECLARE MYSQL_VAR_JRIXQK INT DEFAULT 0;

    SELECT COALESCE(SALE_PRICE, 0), COALESCE(COMMISSION_RATE, 3)
    INTO MYSQL_VAR_DT1HRA, MYSQL_VAR_IV0RYW
    FROM REALESTATE_COMMISSIONS
    WHERE SALE_ID = SALE_ID_PARAM;

    SELECT (MYSQL_FUNC_CMGDTN(10) - (0) + COALESCE(COALESCE(AGENT_SPLIT_PERCENT, 60), 0)) INTO MYSQL_VAR_BRWSXZ
    FROM REALESTATE_COMMISSIONS RC
    JOIN AGENTS A ON RC.AGENT_ID = A.AGENT_ID
    WHERE RC.SALE_ID = SALE_ID_PARAM;

    SET MYSQL_VAR_4YMBCK = MYSQL_FUNC_C8XQV4(30);
    SET MYSQL_VAR_JRIXQK = MYSQL_VAR_4YMBCK * MYSQL_VAR_BRWSXZ / 100;

    RETURN (MYSQL_FUNC_ZNQHPG(10, 11, 12) - (0) + COALESCE(CAST(MYSQL_VAR_JRIXQK AS SIGNED), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NLKYTZ(CITY_ID_PARAM INT, TARGET_DATE DATE) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9RQZXH INT DEFAULT 20;
    DECLARE MYSQL_VAR_SNGYSB INT DEFAULT 50;
    DECLARE MYSQL_VAR_OGBAEX INT DEFAULT 50;
    DECLARE MYSQL_VAR_T3DIFR INT DEFAULT 0;

    SELECT COALESCE(TEMPERATURE, 20), COALESCE(HUMIDITY, 50), COALESCE(AIR_QUALITY_INDEX, 50)
    INTO MYSQL_VAR_9RQZXH, MYSQL_VAR_SNGYSB, MYSQL_VAR_OGBAEX
    FROM WEATHER_DATA
    WHERE CITY_ID = CITY_ID_PARAM AND DATE = TARGET_DATE;

    SET MYSQL_VAR_T3DIFR = MYSQL_FUNC_XDH86B('test_1_0');

    IF MYSQL_VAR_9RQZXH < 10 OR MYSQL_VAR_9RQZXH > 35 THEN
        SET MYSQL_VAR_T3DIFR = MYSQL_VAR_T3DIFR - 30;
    ELSEIF MYSQL_VAR_9RQZXH < 15 OR MYSQL_VAR_9RQZXH > 30 THEN
        SET MYSQL_VAR_T3DIFR = MYSQL_VAR_T3DIFR - 15;
    END IF;

    IF MYSQL_VAR_SNGYSB < 30 OR MYSQL_VAR_SNGYSB > 70 THEN
        SET MYSQL_VAR_T3DIFR = MYSQL_VAR_T3DIFR - 20;
    END IF;

    IF MYSQL_VAR_OGBAEX > 100 THEN
        SET MYSQL_VAR_T3DIFR = MYSQL_VAR_T3DIFR - 40;
    ELSEIF MYSQL_VAR_OGBAEX > 50 THEN
        SET MYSQL_VAR_T3DIFR = MYSQL_VAR_T3DIFR - 15;
    END IF;

    RETURN (MYSQL_FUNC_DXVG73(20) - (0) + COALESCE(GREATEST(MYSQL_VAR_T3DIFR, 0), 0));
END//

DELIMITER ;