/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_t7j0h0 (
    table_t7j0h0_id INT PRIMARY KEY,
    film_id INT,
    store_id INT
);
INSERT INTO table_t7j0h0 (table_t7j0h0_id, film_id, store_id) VALUES
(1, 1, 1),
(2, 1, 1),
(3, 1, 2),
(4, 2, 1),
(5, 2, 2);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_OCXOJB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OCXOJB(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H7UFEX DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_BR9Z49 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0)
    INTO MYSQL_VAR_H7UFEX
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_BR9Z49
    FROM ORDER_ITEMS;

    IF MYSQL_VAR_BR9Z49 = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_H7UFEX * 100) / MYSQL_VAR_BR9Z49);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YAI80U----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YAI80U(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4EUG1Q DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_UXP3AF INT DEFAULT 0;
    DECLARE MYSQL_VAR_AFJ44J DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_EOEVOM INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_4EUG1Q
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*), COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_UXP3AF, MYSQL_VAR_AFJ44J
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_EOEVOM = (MYSQL_VAR_4EUG1Q * 10) + (MYSQL_VAR_UXP3AF * 3) + (MYSQL_VAR_AFJ44J / 50);

    RETURN MYSQL_VAR_EOEVOM;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PK1G4W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PK1G4W(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PSJMKN INT DEFAULT 0;
    DECLARE MYSQL_VAR_4CSAH5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZZPCG2 INT DEFAULT 0;

    SET MYSQL_VAR_4CSAH5 = POW(A, 3) + POW(B, 3);

    IF MYSQL_VAR_4CSAH5 > 0 THEN
        SET MYSQL_VAR_ZZPCG2 = FLOOR(SQRT(MYSQL_VAR_4CSAH5));
    END IF;

    SET MYSQL_VAR_PSJMKN = (A * B) + MYSQL_VAR_ZZPCG2 + (A % B);

    RETURN MYSQL_VAR_PSJMKN;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZPP0AS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZPP0AS(BASE INT, EXPONENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2SBK2B INT DEFAULT 1;
    DECLARE MYSQL_VAR_D9PS26 INT DEFAULT 0;

    IF EXPONENT < 0 THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_D9PS26 < EXPONENT DO
        SET MYSQL_VAR_2SBK2B = MYSQL_VAR_2SBK2B * BASE;
        SET MYSQL_VAR_D9PS26 = MYSQL_VAR_D9PS26 + 1;
    END WHILE;

    RETURN MYSQL_VAR_2SBK2B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XTHE6M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XTHE6M(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PGFPKJ DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_ZPP0AS(20, 21)
    INTO MYSQL_VAR_PGFPKJ
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_FUNC_PK1G4W(10, 11);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9BMDSN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9BMDSN(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ML379P INT DEFAULT 0;
    DECLARE MYSQL_VAR_0QP5KS INT DEFAULT 0;
    DECLARE MYSQL_VAR_J55K1E INT DEFAULT 0;

    SET MYSQL_VAR_J55K1E = DEPARTMENT_ID_PARAM;

    DEPTH_LOOP: WHILE MYSQL_VAR_J55K1E IS NOT NULL AND MYSQL_VAR_J55K1E != 0 DO
        SELECT COALESCE(PARENT_DEPARTMENT_ID, 0)
        INTO MYSQL_VAR_0QP5KS
        FROM DEPARTMENTS
        WHERE DEPARTMENT_ID = MYSQL_VAR_J55K1E;

        IF MYSQL_VAR_0QP5KS = 0 OR MYSQL_VAR_0QP5KS = MYSQL_VAR_J55K1E THEN
            LEAVE DEPTH_LOOP;
        END IF;

        SET MYSQL_VAR_ML379P = MYSQL_VAR_ML379P + 1;
        SET MYSQL_VAR_J55K1E = MYSQL_VAR_0QP5KS;
    END WHILE DEPTH_LOOP;

    RETURN MYSQL_VAR_ML379P;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DVE6U6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DVE6U6(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
RETURN SUPPLIER_ID_PARAM % 100;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0R457V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0R457V(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_P6NFSO INT DEFAULT 0;

    SELECT QUARTER(REGISTRATION_DATE)
    INTO MYSQL_VAR_P6NFSO
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_P6NFSO;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VMMPQU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VMMPQU(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LE6FS5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_APT8IK INT DEFAULT 0;
    DECLARE MYSQL_VAR_UALRNO INT DEFAULT 0;

    SELECT MYSQL_FUNC_0R457V(20)
    INTO MYSQL_VAR_LE6FS5, MYSQL_VAR_APT8IK
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_UALRNO = MYSQL_FUNC_DVE6U6(10);

    RETURN MYSQL_FUNC_9BMDSN(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z3TZAI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z3TZAI(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SNTETE INT DEFAULT 0;
    DECLARE MYSQL_VAR_HSJA1P DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4RLE0K INT DEFAULT 7;
    DECLARE MYSQL_VAR_GYO6O8 INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_SNTETE
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(AVG(QUANTITY), 0) / 30
    INTO MYSQL_VAR_HSJA1P
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY));

    SET MYSQL_VAR_GYO6O8 = (MYSQL_VAR_SNTETE / GREATEST(MYSQL_VAR_HSJA1P, 0.1)) - MYSQL_VAR_4RLE0K;

    RETURN MYSQL_VAR_GYO6O8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KSZFWV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KSZFWV(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_96U0ZF INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_96U0ZF
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_VAR_96U0ZF * 3;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_H87GHX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H87GHX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N0LU55 DATE;

    SELECT MYSQL_FUNC_Z3TZAI(10)
    INTO MYSQL_VAR_N0LU55
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_KSZFWV(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Y8JI4F----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Y8JI4F(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6ZAJ1G DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_CWS8K5 DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_H3669M INT DEFAULT 0;
    DECLARE MYSQL_VAR_AB38DM INT DEFAULT 0;

    SELECT COALESCE(SALARY, 0), COALESCE(PERFORMANCE_RATING, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_6ZAJ1G, MYSQL_VAR_CWS8K5, MYSQL_VAR_H3669M
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_AB38DM = (MYSQL_VAR_6ZAJ1G / 1000) + (MYSQL_VAR_CWS8K5 * 10) + (MYSQL_VAR_H3669M * 3);

    RETURN MYSQL_VAR_AB38DM;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_K698WX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_K698WX(DISTANCE_MILES_PARAM INT, TRUCK_SIZE_PARAM VARCHAR(20)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BRY2U2 INT DEFAULT 2;
    DECLARE MYSQL_VAR_F0BBJ4 INT DEFAULT 1;
    DECLARE MYSQL_VAR_FY4FTY INT DEFAULT 50;
    DECLARE MYSQL_VAR_W3E78Z INT DEFAULT 0;

    CASE TRUCK_SIZE_PARAM
        WHEN 'SMALL' THEN SET MYSQL_VAR_F0BBJ4 = MYSQL_FUNC_YAI80U(20);
        WHEN 'MEDIUM' THEN SET MYSQL_VAR_F0BBJ4 = MYSQL_FUNC_H87GHX(30);
        WHEN 'LARGE' THEN SET MYSQL_VAR_F0BBJ4 = MYSQL_FUNC_Y8JI4F(20);
        WHEN 'EXTRA_LARGE' THEN SET MYSQL_VAR_F0BBJ4 = MYSQL_FUNC_XTHE6M(10);
        ELSE SET MYSQL_VAR_F0BBJ4 = 1;
    END CASE;

    SET MYSQL_VAR_W3E78Z = (DISTANCE_MILES_PARAM * MYSQL_VAR_BRY2U2 * MYSQL_VAR_F0BBJ4) + MYSQL_VAR_FY4FTY;

    IF DISTANCE_MILES_PARAM > 500 THEN
        SET MYSQL_VAR_W3E78Z = MYSQL_VAR_W3E78Z - (MYSQL_VAR_W3E78Z * 10 / 100);
    END IF;

    RETURN MYSQL_FUNC_VMMPQU(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LGBTYU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LGBTYU(P_FILM_ID INT, P_STORE_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QPKTNT INT DEFAULT 0;
    
    SELECT COUNT(*)
    FROM TABLE_T7J0H0
    WHERE FILM_ID = P_FILM_ID
    AND STORE_ID = P_STORE_ID
    AND TABLE_T7J0H0_IN_STOCK(TABLE_T7J0H0_ID)
    INTO MYSQL_VAR_QPKTNT;
    
    RETURN MYSQL_VAR_QPKTNT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RS0AD1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RS0AD1(START_NUM INT, END_NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_0BIU33 INT DEFAULT 0;
    DECLARE MYSQL_VAR_4C3IZT INT DEFAULT 0;
    DECLARE MYSQL_VAR_522YRB INT;

    IF START_NUM > END_NUM THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_522YRB = START_NUM;

    CALC_LOOP: WHILE MYSQL_VAR_522YRB <= END_NUM DO
        IF MYSQL_VAR_522YRB MOD 2 = 0 THEN
            SET MYSQL_VAR_0BIU33 = MYSQL_VAR_0BIU33 + MYSQL_VAR_522YRB;
            SET MYSQL_VAR_4C3IZT = MYSQL_VAR_4C3IZT + 1;
        END IF;
        SET MYSQL_VAR_522YRB = MYSQL_VAR_522YRB + 1;
    END WHILE CALC_LOOP;

    IF MYSQL_VAR_4C3IZT = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_0BIU33 / MYSQL_VAR_4C3IZT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_67KJWU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_67KJWU(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VOB8TC INT DEFAULT 0;
    DECLARE MYSQL_VAR_W4GEYW INT DEFAULT 0;
    DECLARE MYSQL_VAR_5U7JDL INT DEFAULT 0;
    DECLARE MYSQL_VAR_YFPJLF INT DEFAULT 0;

    SELECT MYSQL_FUNC_RS0AD1(10, 11)
    INTO MYSQL_VAR_VOB8TC, MYSQL_VAR_W4GEYW, MYSQL_VAR_5U7JDL
    FROM INVENTORY_PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_YFPJLF = MYSQL_VAR_W4GEYW - MYSQL_VAR_VOB8TC;

    IF MYSQL_VAR_5U7JDL > 100 THEN
        SET MYSQL_VAR_YFPJLF = MYSQL_VAR_YFPJLF + 5;
    END IF;

    RETURN MYSQL_FUNC_LGBTYU(30, 31);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HU4JM8(DOCTOR_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1EBFWA INT DEFAULT 0;
    DECLARE MYSQL_VAR_0JKVF2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_C4GDDD INT DEFAULT 0;
    DECLARE MYSQL_VAR_R2SHL6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_RFNFZW INT DEFAULT 0;

    SELECT COALESCE(YEARS_EXPERIENCE, 0), COALESCE(CONSULTATION_FEE, 100)
    INTO MYSQL_VAR_1EBFWA, MYSQL_VAR_0JKVF2
    FROM DOCTORS
    WHERE DOCTOR_ID = DOCTOR_ID_PARAM;

    SELECT MYSQL_FUNC_67KJWU(30)
    INTO MYSQL_VAR_C4GDDD
    FROM APPOINTMENTS
    WHERE DOCTOR_ID = DOCTOR_ID_PARAM
      AND MONTH(APPOINTMENT_DATE) = MONTH(CURDATE())
      AND STATUS = 'COMPLETED';

    SET MYSQL_VAR_R2SHL6 = MYSQL_FUNC_K698WX(20, 'test_1_1');
    SET MYSQL_VAR_RFNFZW = (MYSQL_VAR_C4GDDD * 100) / MYSQL_VAR_R2SHL6;

    IF MYSQL_VAR_1EBFWA > 10 THEN
        SET MYSQL_VAR_RFNFZW = MYSQL_VAR_RFNFZW + 10;
    END IF;

    RETURN MYSQL_FUNC_OCXOJB(10);
END//

DELIMITER ;