/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_kqlixh (
    employee_id INT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    salary INT
);
INSERT INTO table_kqlixh (employee_id, first_name, last_name, salary) VALUES
(1, 'John', 'Doe', 40000),
(2, 'Jane', 'Smith', 30000),
(3, 'Bob', 'Johnson', 50000),
(4, 'Alice', 'Williams', 25000);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_6TBYKX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6TBYKX(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BGMQ12 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_KFV2DT INT DEFAULT 0;

    SELECT COALESCE(PRICE, 0), COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_BGMQ12, MYSQL_VAR_KFV2DT
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_BGMQ12 * MYSQL_VAR_KFV2DT) / 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UQJS1G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UQJS1G() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6DKJ4A INT DEFAULT 0;
    
    SELECT COUNT(*) INTO MYSQL_VAR_6DKJ4A
    FROM TABLE_KQLIXH
    WHERE SALARY > 35000
    ORDER BY FIRST_NAME, LAST_NAME, EMPLOYEE_ID;
    
    RETURN MYSQL_VAR_6DKJ4A;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JRP5H5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JRP5H5(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MQ93S6 INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_MQ93S6
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN 30 - MYSQL_VAR_MQ93S6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QWVHXD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QWVHXD(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H29XNA INT DEFAULT 0;
    DECLARE MYSQL_VAR_3EF3B8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_RDCPIN INT DEFAULT 0;

    SELECT COALESCE(COST_USD, 0), COALESCE(REVENUE_USD, 0)
    INTO MYSQL_VAR_H29XNA, MYSQL_VAR_3EF3B8
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_H29XNA = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_RDCPIN = MYSQL_FUNC_UQJS1G();

    RETURN MYSQL_FUNC_JRP5H5(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EM0BQD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EM0BQD(CASE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GRRPEA INT DEFAULT 0;
    DECLARE MYSQL_VAR_FK8309 INT DEFAULT 0;
    DECLARE MYSQL_VAR_EBKNY7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7UKWS5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZMLIX0 INT DEFAULT 0;

    SELECT MYSQL_FUNC_6TBYKX(20)
    INTO MYSQL_VAR_GRRPEA
    FROM LEGAL_CASES
    WHERE CASE_ID = CASE_ID_PARAM;

    SELECT COALESCE(SUM(HOURS_BILLED * HOURLY_RATE), 0), COALESCE(SUM(HOURS_BILLED), 0)
    INTO MYSQL_VAR_7UKWS5, MYSQL_VAR_FK8309
    FROM LEGAL_TASKS
    WHERE CASE_ID = CASE_ID_PARAM;

    IF MYSQL_VAR_GRRPEA = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_ZMLIX0 = MYSQL_VAR_GRRPEA - MYSQL_VAR_7UKWS5;

    IF MYSQL_VAR_FK8309 > 100 THEN
        SET MYSQL_VAR_ZMLIX0 = MYSQL_VAR_ZMLIX0 - (MYSQL_VAR_FK8309 - 100) * 10;
    END IF;

    RETURN MYSQL_FUNC_QWVHXD(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_N5QMBU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_N5QMBU(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RPGYN8 DATE;

    SELECT START_DATE
    INTO MYSQL_VAR_RPGYN8
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_RPGYN8 IS NULL THEN
        RETURN 0;
    END IF;

    RETURN DATEDIFF(CURDATE(), MYSQL_VAR_RPGYN8);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_F57EOQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_F57EOQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZHEXU4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_L5FDYV DATE;
    DECLARE MYSQL_VAR_WP56IY DATE;
    DECLARE MYSQL_VAR_FKMNVI INT DEFAULT 0;
    DECLARE MYSQL_VAR_3KZY6P INT DEFAULT 0;

    SELECT COUNT(*), MIN(ORDER_DATE), MAX(ORDER_DATE)
    INTO MYSQL_VAR_ZHEXU4, MYSQL_VAR_L5FDYV, MYSQL_VAR_WP56IY
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_ZHEXU4 < 2 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_FKMNVI = DATEDIFF(MYSQL_VAR_WP56IY, MYSQL_VAR_L5FDYV);

    IF MYSQL_VAR_FKMNVI = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_3KZY6P = MYSQL_VAR_FKMNVI / (MYSQL_VAR_ZHEXU4 - 1);

    RETURN MYSQL_VAR_3KZY6P;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_W3AKIT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_W3AKIT(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RMTWAU INT DEFAULT 0;

    SELECT MYSQL_FUNC_F57EOQ(20)
    INTO MYSQL_VAR_RMTWAU
    FROM SUBSCRIPTIONS S
    JOIN CUSTOMERS C ON S.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM AND S.STATUS = 'ACTIVE';

    RETURN MYSQL_FUNC_N5QMBU(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OCXOJB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OCXOJB(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H7UFEX DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_BR9Z49 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0)
    INTO MYSQL_VAR_H7UFEX
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_BR9Z49
    FROM ORDER_ITEMS;

    IF MYSQL_VAR_BR9Z49 = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_W3AKIT('test_2_0');
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XPWVU1(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7TNE5M DATE;

    SELECT MYSQL_FUNC_OCXOJB(10)
    INTO MYSQL_VAR_7TNE5M
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    IF MYSQL_VAR_7TNE5M IS NULL THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_EM0BQD(30);
END//

DELIMITER ;