/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_BXSSS3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BXSSS3(DEPT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VLT6TE INT DEFAULT 0;
    DECLARE MYSQL_VAR_YYCD4A INT DEFAULT 0;
    DECLARE MYSQL_VAR_C806W3 INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_VLT6TE
    FROM DEPARTMENTS
    WHERE DEPT_ID = DEPT_ID_PARAM;

    SELECT COALESCE(SUM(SALARY), 0)
    INTO MYSQL_VAR_YYCD4A
    FROM EMPLOYEES
    WHERE DEPT_ID = DEPT_ID_PARAM;

    SET MYSQL_VAR_C806W3 = MYSQL_VAR_VLT6TE - MYSQL_VAR_YYCD4A;

    RETURN MYSQL_VAR_C806W3;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CHGYIE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CHGYIE(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_30NKC5 DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_XU90BK INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_30NKC5, MYSQL_VAR_XU90BK
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_VAR_30NKC5 * 10) - (MYSQL_VAR_XU90BK * 2);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4MLORP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4MLORP(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QQX0ZX INT DEFAULT 0;

    SELECT (MYSQL_FUNC_CHGYIE(20) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_QQX0ZX
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_VAR_QQX0ZX;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7JAD8J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7JAD8J(DEPT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M6JB8L INT DEFAULT 0;
    DECLARE MYSQL_VAR_WTOMHW INT DEFAULT 0;
    DECLARE MYSQL_VAR_LED7EI INT DEFAULT 0;

    SELECT COALESCE(SUM(SALARY), 0) INTO MYSQL_VAR_M6JB8L
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPT_ID_PARAM;

    SELECT (MYSQL_FUNC_BXSSS3(30) - (0) + COALESCE(COALESCE(BUDGET, 0), 0)) INTO MYSQL_VAR_WTOMHW
    FROM DEPARTMENTS
    WHERE DEPT_ID = DEPT_ID_PARAM;

    IF MYSQL_VAR_WTOMHW = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_LED7EI = (MYSQL_VAR_M6JB8L * 100) / MYSQL_VAR_WTOMHW;

    RETURN (MYSQL_FUNC_4MLORP(20) - (0) + COALESCE(CAST(MYSQL_VAR_LED7EI AS SIGNED), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BHAJTX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OII7AG INT DEFAULT 0;
    DECLARE MYSQL_VAR_5YQLY0 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_O7XAIV DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_T7DZN6 INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_OII7AG, MYSQL_VAR_5YQLY0
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    IF MYSQL_VAR_OII7AG = 0 THEN
        RETURN 1;
    END IF;

    SET MYSQL_VAR_O7XAIV = MYSQL_VAR_5YQLY0 / MYSQL_VAR_OII7AG;

    IF MYSQL_VAR_O7XAIV > 500 THEN
        SET MYSQL_VAR_T7DZN6 = 5;
    ELSEIF MYSQL_VAR_O7XAIV > 200 THEN
        SET MYSQL_VAR_T7DZN6 = 4;
    ELSEIF MYSQL_VAR_O7XAIV > 100 THEN
        SET MYSQL_VAR_T7DZN6 = 3;
    ELSEIF MYSQL_VAR_O7XAIV > 50 THEN
        SET MYSQL_VAR_T7DZN6 = 2;
    ELSE
        SET MYSQL_VAR_T7DZN6 = 1;
    END IF;

    RETURN (MYSQL_FUNC_7JAD8J(20) - (0) + COALESCE(MYSQL_VAR_T7DZN6, 0));
END//

DELIMITER ;