/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_5DSCH2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5DSCH2(VEHICLE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SGXOAF INT DEFAULT 0;
    DECLARE MYSQL_VAR_CHIL5Y INT DEFAULT 2020;
    DECLARE MYSQL_VAR_GAXMTW INT DEFAULT 0;
    DECLARE MYSQL_VAR_0PN2SO INT DEFAULT 500;
    DECLARE MYSQL_VAR_GYK100 INT DEFAULT 0;

    SELECT COALESCE(INSURED_VALUE, 50000), COALESCE(YEAR(CURDATE()) - YEAR, 0)
    INTO MYSQL_VAR_SGXOAF, MYSQL_VAR_CHIL5Y
    FROM INSURANCE_VEHICLES
    WHERE VEHICLE_ID = VEHICLE_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_GAXMTW
    FROM AUTO_INSURANCE_CLAIMS
    WHERE VEHICLE_ID = VEHICLE_ID_PARAM AND STATUS = 'APPROVED';

    SET MYSQL_VAR_GYK100 = (MYSQL_VAR_SGXOAF / 1000) + MYSQL_VAR_0PN2SO;

    IF MYSQL_VAR_CHIL5Y < 2015 THEN
        SET MYSQL_VAR_GYK100 = MYSQL_VAR_GYK100 + 100;
    END IF;

    IF MYSQL_VAR_GAXMTW > 0 THEN
        SET MYSQL_VAR_GYK100 = MYSQL_VAR_GYK100 + (MYSQL_VAR_GAXMTW * 200);
    END IF;

    RETURN CAST(MYSQL_VAR_GYK100 AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UY9PPR(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NUYZS7 INT DEFAULT 0;

    SELECT MYSQL_FUNC_5DSCH2(10)
    INTO MYSQL_VAR_NUYZS7
    FROM SUBSCRIPTIONS S
    JOIN CUSTOMERS C ON S.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_NUYZS7;
END//

DELIMITER ;