/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_3D9DN8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3D9DN8(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GJTYCY DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_B02BS7 DECIMAL(10,2) DEFAULT 1.00;

    SELECT COALESCE(AVG(SALARY), 0), COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_GJTYCY, MYSQL_VAR_B02BS7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_GJTYCY * 100) / MYSQL_VAR_B02BS7);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0CCG20----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0CCG20(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z9XZRV INT DEFAULT 0;
    DECLARE MYSQL_VAR_NL27VB INT DEFAULT EMP_ID_PARAM;

    WHILE MYSQL_VAR_NL27VB IS NOT NULL DO
        SET MYSQL_VAR_Z9XZRV = MYSQL_VAR_Z9XZRV + 1;
        SELECT MANAGER_ID INTO MYSQL_VAR_NL27VB FROM EMPLOYEES WHERE EMP_ID = MYSQL_VAR_NL27VB;
    END WHILE;

    RETURN MYSQL_FUNC_3D9DN8(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KKOU8N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KKOU8N(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AQMN6O INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_AQMN6O
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_AQMN6O / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VAQVBW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VAQVBW(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6KCSHI INT DEFAULT 0;
    DECLARE MYSQL_VAR_HMVLIR INT DEFAULT 0;
    DECLARE MYSQL_VAR_FQ6JP7 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_6KCSHI
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT DATEDIFF(END_DATE, START_DATE)
    INTO MYSQL_VAR_HMVLIR
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_HMVLIR = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_FQ6JP7 = MYSQL_VAR_6KCSHI / MYSQL_VAR_HMVLIR;

    RETURN MYSQL_VAR_FQ6JP7;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_826WIA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_826WIA(EMPLOYEE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PYHM8D INT DEFAULT 0;
    DECLARE MYSQL_VAR_PBCASI DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_MY5U3W INT DEFAULT 0;
    DECLARE MYSQL_VAR_YA38AK INT DEFAULT 0;
    DECLARE MYSQL_VAR_1X8RMZ DECIMAL(3,2) DEFAULT 1.00;

    SELECT MYSQL_FUNC_KKOU8N(30)
    INTO MYSQL_VAR_PYHM8D, MYSQL_VAR_PBCASI
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = EMPLOYEE_ID_PARAM;

    SELECT MYSQL_FUNC_VAQVBW(20)
    INTO MYSQL_VAR_MY5U3W
    FROM BONUSES
    WHERE EMPLOYEE_ID = EMPLOYEE_ID_PARAM;

    SET MYSQL_VAR_1X8RMZ = MYSQL_FUNC_0CCG20(10);

    SET MYSQL_VAR_YA38AK = (MYSQL_VAR_PYHM8D * MYSQL_VAR_1X8RMZ) / 10;

    IF MYSQL_VAR_PBCASI >= 4.5 THEN
        SET MYSQL_VAR_YA38AK = MYSQL_VAR_YA38AK + (MYSQL_VAR_YA38AK * 50 / 100);
    END IF;

    RETURN MYSQL_VAR_YA38AK;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6BPUPK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6BPUPK(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_17SOO7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7YXJ9D INT DEFAULT 0;
    DECLARE MYSQL_VAR_MDGEOI INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_17SOO7
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SHIPPING_COST, 0)
    INTO MYSQL_VAR_7YXJ9D
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_17SOO7 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_MDGEOI = ((MYSQL_VAR_17SOO7 - MYSQL_VAR_7YXJ9D) * 100) / MYSQL_VAR_17SOO7;

    RETURN MYSQL_VAR_MDGEOI;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z0PJ4I(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QVCHHI INT DEFAULT 0;

    SELECT MYSQL_FUNC_826WIA(30)
    INTO MYSQL_VAR_QVCHHI
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_FUNC_6BPUPK(20);
END//

DELIMITER ;