/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_svj7l3 (
    emp_no INT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS table_takpkm (
    emp_no INT,
    salary INT,
    FOREIGN KEY (emp_no) REFERENCES table_svj7l3(emp_no)
);
INSERT INTO table_svj7l3 (emp_no) VALUES (10001);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 60117);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 62102);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 66074);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_H87GHX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H87GHX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N0LU55 DATE;

    SELECT REGISTRATION_DATE
    INTO MYSQL_VAR_N0LU55
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN QUARTER(MYSQL_VAR_N0LU55);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QMV709----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QMV709(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CDK7YJ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_9YM8HK DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_UBNOIX DECIMAL(5,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_CDK7YJ
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_9YM8HK
    FROM PRODUCTS;

    IF MYSQL_VAR_9YM8HK = 0 THEN
        RETURN 100;
    END IF;

    SET MYSQL_VAR_UBNOIX = (MYSQL_VAR_CDK7YJ / MYSQL_VAR_9YM8HK) * 100;

    RETURN FLOOR(MYSQL_VAR_UBNOIX);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5JPH02----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5JPH02(P_EMP_NO INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_U5X0D5 INT;
    
    SELECT (MYSQL_FUNC_QMV709(20) - (0) + COALESCE(AVG(S.SALARY), 0)) INTO MYSQL_VAR_U5X0D5
    FROM TABLE_SVJ7L3 E
    JOIN TABLE_TAKPKM S ON E.EMP_NO = S.EMP_NO
    WHERE E.EMP_NO = P_EMP_NO;
    
    RETURN MYSQL_VAR_U5X0D5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GJQFPZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GJQFPZ(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OX7OHA DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_6JYFPG INT DEFAULT 0;
    DECLARE MYSQL_VAR_5LQYKD INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_OX7OHA, MYSQL_VAR_6JYFPG
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_5LQYKD = (MYSQL_VAR_OX7OHA * 10) + (30 - MYSQL_VAR_6JYFPG);

    RETURN MYSQL_VAR_5LQYKD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4QGORF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4QGORF(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZBGL9O DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_H17HUH INT DEFAULT 0;
    DECLARE MYSQL_VAR_XTXRQD INT DEFAULT 0;

    SELECT COALESCE(AVG(PRICE), 0), COALESCE(MAX(PRICE), 0)
    INTO MYSQL_VAR_ZBGL9O, MYSQL_VAR_H17HUH
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_H17HUH = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_XTXRQD = (MYSQL_VAR_ZBGL9O * 100) / MYSQL_VAR_H17HUH;

    RETURN MYSQL_VAR_XTXRQD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AE2EPO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AE2EPO(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BFBWSI INT DEFAULT 0;
    DECLARE MYSQL_VAR_OMC7UB INT DEFAULT 0;

    SELECT (MYSQL_FUNC_4QGORF(20) - (0) + COALESCE(COUNT(*), COUNT(O.ORDER_ID), 0))
    INTO MYSQL_VAR_BFBWSI, MYSQL_VAR_OMC7UB
    FROM CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    IF MYSQL_VAR_BFBWSI = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_GJQFPZ(10) - (0) + COALESCE((MYSQL_VAR_OMC7UB * 100) / MYSQL_VAR_BFBWSI, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1X2F2W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1X2F2W(START_DATE_PARAM DATE, END_DATE_PARAM DATE) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_19CMYR INT DEFAULT 0;
    DECLARE MYSQL_VAR_P2PZJT DATE DEFAULT NULL;
    DECLARE MYSQL_VAR_07862Q INT DEFAULT 0;

    IF START_DATE_PARAM IS NULL OR END_DATE_PARAM IS NULL THEN
        RETURN 0;
    END IF;

    IF START_DATE_PARAM > END_DATE_PARAM THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_P2PZJT = START_DATE_PARAM;

    BUSINESS_DAYS_LOOP: WHILE MYSQL_VAR_P2PZJT <= END_DATE_PARAM DO
        SET MYSQL_VAR_07862Q = DAYOFWEEK(MYSQL_VAR_P2PZJT);

        IF MYSQL_VAR_07862Q NOT IN (1, 7) THEN
            SET MYSQL_VAR_19CMYR = MYSQL_VAR_19CMYR + 1;
        END IF;

        SET MYSQL_VAR_P2PZJT = DATE_ADD(MYSQL_VAR_P2PZJT, INTERVAL 1 DAY);
    END WHILE BUSINESS_DAYS_LOOP;

    RETURN MYSQL_VAR_19CMYR;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9EU4R5(PROPERTY_ID_PARAM INT, SERVICE_TYPE VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LL4UJ1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7X5P2P INT DEFAULT 0;
    DECLARE MYSQL_VAR_OEKMSK INT DEFAULT 50;
    DECLARE MYSQL_VAR_ZUNLDC INT DEFAULT 0;

    SELECT (MYSQL_FUNC_1X2F2W('2024-01-12', '2024-01-12') - (0) + COALESCE(COALESCE(AREA_SQFT, 500), COALESCE(NUM_ROOMS, 2), 0))
    INTO MYSQL_VAR_LL4UJ1, MYSQL_VAR_7X5P2P
    FROM PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_OEKMSK;

    SET MYSQL_VAR_ZUNLDC = MYSQL_FUNC_AE2EPO('test_1_0');

    SET MYSQL_VAR_ZUNLDC = MYSQL_FUNC_5JPH02(10);

    IF SERVICE_TYPE = 'DEEP' THEN
        SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC * 150 / 100;
    ELSEIF SERVICE_TYPE = 'MOVE_OUT' THEN
        SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC * 175 / 100;
    END IF;

    RETURN (MYSQL_FUNC_H87GHX(30) - (0) + COALESCE(CAST(MYSQL_VAR_ZUNLDC AS SIGNED), 0));
END//

DELIMITER ;