/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_GJQFPZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GJQFPZ(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OX7OHA DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_6JYFPG INT DEFAULT 0;
    DECLARE MYSQL_VAR_5LQYKD INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_OX7OHA, MYSQL_VAR_6JYFPG
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_5LQYKD = (MYSQL_VAR_OX7OHA * 10) + (30 - MYSQL_VAR_6JYFPG);

    RETURN MYSQL_VAR_5LQYKD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1J189G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1J189G(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5DZKQX INT DEFAULT 0;

    SELECT CUSTOMER_ID
    INTO MYSQL_VAR_5DZKQX
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_5DZKQX % 100;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HVABBX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HVABBX(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N7JFGF INT DEFAULT 0;
    DECLARE MYSQL_VAR_DLFY8S DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_GJQFPZ(20)
    INTO MYSQL_VAR_N7JFGF
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT MYSQL_FUNC_1J189G(10)
    INTO MYSQL_VAR_DLFY8S
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_N7JFGF = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_DLFY8S * 100) / MYSQL_VAR_N7JFGF);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OQ1NDN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OQ1NDN(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LTID0P INT DEFAULT 0;
    DECLARE MYSQL_VAR_VJ8PFO INT DEFAULT 0;
    DECLARE MYSQL_VAR_8RORBC INT DEFAULT 100;
    DECLARE MYSQL_VAR_BK94UN INT DEFAULT 0;

    SELECT COALESCE(QUANTITY_ORDERED, 0), COALESCE(DEFECT_COUNT, 0)
    INTO MYSQL_VAR_LTID0P, MYSQL_VAR_VJ8PFO
    FROM MANUFACTURING_ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_LTID0P = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_8RORBC = ((MYSQL_VAR_LTID0P - MYSQL_VAR_VJ8PFO) * 100) / MYSQL_VAR_LTID0P;

    IF MYSQL_VAR_VJ8PFO > 10 THEN
        SET MYSQL_VAR_BK94UN = MYSQL_VAR_VJ8PFO * 50;
        SET MYSQL_VAR_8RORBC = MYSQL_VAR_8RORBC - 10;
    END IF;

    RETURN CAST(MYSQL_VAR_8RORBC AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S110UQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S110UQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SEVR7B INT DEFAULT 0;

    SELECT MYSQL_FUNC_OQ1NDN(20)
    INTO MYSQL_VAR_SEVR7B
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'ACTIVE';

    RETURN MYSQL_VAR_SEVR7B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VDTWGK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VDTWGK(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8N96DV INT DEFAULT 0;

    SELECT MYSQL_FUNC_S110UQ(30)
    INTO MYSQL_VAR_8N96DV
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_HVABBX(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RGNYV8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RGNYV8(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SSYYRT INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_SSYYRT
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_SSYYRT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VIOBK8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VIOBK8(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3SIJ67 INT DEFAULT 0;
    DECLARE MYSQL_VAR_TZUDY5 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COUNT(*), COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_3SIJ67, MYSQL_VAR_TZUDY5
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_3SIJ67 * MYSQL_VAR_TZUDY5) / 10);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XKZXKA(PRINCIPAL INT, RATE_PERCENT DECIMAL(5,2), YEARS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZSVHTM INT DEFAULT 0;
    DECLARE MYSQL_VAR_KOWUTF INT DEFAULT 1;
    DECLARE MYSQL_VAR_CQJS4Z INT DEFAULT 0;

    IF PRINCIPAL <= 0 OR YEARS <= 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_CQJS4Z = MYSQL_FUNC_VIOBK8(10);

    INTEREST_LOOP: WHILE MYSQL_VAR_KOWUTF <= YEARS DO
        SET MYSQL_VAR_CQJS4Z = MYSQL_VAR_CQJS4Z + (MYSQL_VAR_CQJS4Z * RATE_PERCENT / 100);
        SET MYSQL_VAR_KOWUTF = MYSQL_VAR_KOWUTF + 1;
    END WHILE INTEREST_LOOP;

    SET MYSQL_VAR_ZSVHTM = MYSQL_FUNC_RGNYV8(10);

    RETURN MYSQL_FUNC_VDTWGK(10);
END//

DELIMITER ;