/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_E88JTA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_E88JTA(CARD_NUMBER VARCHAR(20)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BOCJUR INT DEFAULT 0;
    DECLARE MYSQL_VAR_NFICDY INT DEFAULT 1;
    DECLARE MYSQL_VAR_NZJWR7 VARCHAR(1);
    DECLARE MYSQL_VAR_4ZPJ25 INT DEFAULT 0;

    IF CARD_NUMBER IS NULL THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_NFICDY <= CHAR_LENGTH(CARD_NUMBER) DO
        SET MYSQL_VAR_NZJWR7 = SUBSTRING(CARD_NUMBER, MYSQL_VAR_NFICDY, 1);

        IF MYSQL_VAR_NZJWR7 IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') THEN
            SET MYSQL_VAR_4ZPJ25 = MYSQL_VAR_4ZPJ25 + 1;
        END IF;

        SET MYSQL_VAR_NFICDY = MYSQL_VAR_NFICDY + 1;
    END WHILE;

    IF MYSQL_VAR_4ZPJ25 >= 13 AND MYSQL_VAR_4ZPJ25 <= 19 THEN
        SET MYSQL_VAR_BOCJUR = 1;
    END IF;

    RETURN MYSQL_VAR_BOCJUR;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2ZRPF2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2ZRPF2(NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WCC8CZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_WAGK8M INT;

    SET MYSQL_VAR_WAGK8M = ABS(NUM);

    IF MYSQL_VAR_WAGK8M = 0 THEN
        RETURN 1;
    END IF;

    COUNT_LOOP: WHILE MYSQL_VAR_WAGK8M > 0 DO
        SET MYSQL_VAR_WCC8CZ = MYSQL_VAR_WCC8CZ + 1;
        SET MYSQL_VAR_WAGK8M = MYSQL_VAR_WAGK8M DIV 10;
    END WHILE COUNT_LOOP;

    RETURN MYSQL_VAR_WCC8CZ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_38YI9N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_38YI9N(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_L3JZEV INT DEFAULT 0;
    DECLARE MYSQL_VAR_WIMMH2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_KB5TD8 DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(*)
    INTO MYSQL_VAR_L3JZEV
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MYSQL_FUNC_E88JTA('test_1_0')
    INTO MYSQL_VAR_WIMMH2
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_WIMMH2 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KB5TD8 = MYSQL_FUNC_2ZRPF2(10);

    RETURN FLOOR(MYSQL_VAR_KB5TD8);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BMOZ1K(N INT, R INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9K825M INT DEFAULT 1;
    DECLARE MYSQL_VAR_WXUZ8T INT DEFAULT 1;
    DECLARE MYSQL_VAR_PFR40Q INT DEFAULT 1;
    DECLARE MYSQL_VAR_XX9RKO INT DEFAULT 1;

    IF R < 0 OR R > N OR N < 0 THEN
        RETURN 0;
    END IF;

    IF R = 0 OR R = N THEN
        RETURN 1;
    END IF;

    IF R > N - R THEN
        SET R = N - R;
    END IF;

    CALC_LOOP: WHILE MYSQL_VAR_PFR40Q <= R DO
        SET MYSQL_VAR_9K825M = MYSQL_VAR_9K825M * (N - MYSQL_VAR_PFR40Q + 1);
        SET MYSQL_VAR_WXUZ8T = MYSQL_VAR_WXUZ8T * MYSQL_VAR_PFR40Q;
        SET MYSQL_VAR_PFR40Q = MYSQL_VAR_PFR40Q + 1;
    END WHILE CALC_LOOP;

    SET MYSQL_VAR_XX9RKO = MYSQL_VAR_9K825M / MYSQL_VAR_WXUZ8T;

    RETURN MYSQL_FUNC_38YI9N(10);
END//

DELIMITER ;