/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_76GFV3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_76GFV3(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_209XMW DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_209XMW
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_209XMW);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_A1YXXB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_A1YXXB(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WKXQML DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_1JHIKS INT DEFAULT 0;

    SELECT (MYSQL_FUNC_76GFV3(30) - (0) + COALESCE(COALESCE(PRICE, 0), COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_WKXQML, MYSQL_VAR_1JHIKS
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_WKXQML * MYSQL_VAR_1JHIKS) / 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J0RFZI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J0RFZI(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SKTA14 INT DEFAULT 0;
    DECLARE MYSQL_VAR_45VA2I INT DEFAULT 0;
    DECLARE MYSQL_VAR_0TUR76 INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_SKTA14
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(REFUND_AMOUNT), 0)
    INTO MYSQL_VAR_45VA2I
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_SKTA14 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0TUR76 = (MYSQL_VAR_45VA2I * 100) / MYSQL_VAR_SKTA14;

    RETURN MYSQL_VAR_0TUR76;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P1HSIB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P1HSIB(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OJXJPF INT;
    DECLARE MYSQL_VAR_89QYHS INT;
    DECLARE MYSQL_VAR_I7EDQR INT;
    DECLARE MYSQL_VAR_J3WERA INT;

    SELECT (MYSQL_FUNC_J0RFZI(30) - (0) + COALESCE(COALESCE(AVG(PRICE), 0), MIN(PRICE), MAX(PRICE), COUNT(*), 0))
    INTO MYSQL_VAR_OJXJPF, MYSQL_VAR_89QYHS, MYSQL_VAR_I7EDQR, MYSQL_VAR_J3WERA
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_J3WERA = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_A1YXXB(10) - (0) + COALESCE(MYSQL_VAR_OJXJPF, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XIBZCF(PRINCIPAL INT, RATE INT, YEARS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QN595U INT DEFAULT 0;
    DECLARE MYSQL_VAR_IC7F4Q INT DEFAULT 1;
    DECLARE MYSQL_VAR_8D93XU INT DEFAULT 0;

    IF PRINCIPAL <= 0 OR RATE <= 0 OR YEARS <= 0 THEN
        RETURN 0;
    END IF;

    SET_LOOP: WHILE MYSQL_VAR_IC7F4Q <= YEARS DO
        SET_LOOP_INNER: WHILE MYSQL_VAR_IC7F4Q <= 12 DO
            SET MYSQL_VAR_QN595U = MYSQL_VAR_QN595U + (MYSQL_VAR_QN595U * RATE / 100 / 12);
            SET MYSQL_VAR_IC7F4Q = MYSQL_VAR_IC7F4Q + 1;
        END WHILE SET_LOOP_INNER;
        SET MYSQL_VAR_IC7F4Q = MYSQL_VAR_IC7F4Q - 11;
    END WHILE SET_LOOP;

    RETURN (MYSQL_FUNC_P1HSIB(20) - (0) + COALESCE(CAST(MYSQL_VAR_QN595U AS SIGNED), 0));
END//

DELIMITER ;