/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_IK4G9R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IK4G9R(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OE9SLC DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_OE9SLC
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_OE9SLC * 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EBADOC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EBADOC(MEMBER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZNSUD8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZSUKQX INT DEFAULT 0;
    DECLARE MYSQL_VAR_1SCJD3 INT DEFAULT 50;
    DECLARE MYSQL_VAR_BOIDEZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_8BS9B2 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_FEE, 0) INTO MYSQL_VAR_ZNSUD8
    FROM GYM_MEMBERS
    WHERE MEMBER_ID = MEMBER_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_8BS9B2
    FROM TRAINER_SESSIONS
    WHERE MEMBER_ID = MEMBER_ID_PARAM
      AND SESSION_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SET MYSQL_VAR_1SCJD3 = MYSQL_VAR_1SCJD3 * MYSQL_VAR_8BS9B2;
    SET MYSQL_VAR_BOIDEZ = MYSQL_VAR_ZNSUD8 + MYSQL_VAR_1SCJD3;

    RETURN MYSQL_VAR_BOIDEZ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PMKVDZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PMKVDZ(INNER_RADIUS INT, OUTER_RADIUS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z78C5L DECIMAL(10,2) DEFAULT 0.00;

    IF INNER_RADIUS >= OUTER_RADIUS THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_Z78C5L = MYSQL_FUNC_EBADOC(10);
    RETURN MYSQL_FUNC_IK4G9R(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AZY9GD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AZY9GD(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GGZIPF INT DEFAULT 0;
    DECLARE MYSQL_VAR_9JMK91 INT DEFAULT 1;

    SELECT COALESCE(BUDGET, 0), DATEDIFF(END_DATE, START_DATE) + 1
    INTO MYSQL_VAR_GGZIPF, MYSQL_VAR_9JMK91
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_9JMK91 <= 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_PMKVDZ(20, 21);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CHAZ9V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CHAZ9V() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YMI56F INT DEFAULT 0;
    
    SELECT MYSQL_FUNC_AZY9GD(30) INTO MYSQL_VAR_YMI56F 
    FROM MYSQL.PROCS_PRIV 
    WHERE USER LIKE 'U2%';
    
    RETURN MYSQL_VAR_YMI56F;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P1HSIB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P1HSIB(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OJXJPF INT;
    DECLARE MYSQL_VAR_89QYHS INT;
    DECLARE MYSQL_VAR_I7EDQR INT;
    DECLARE MYSQL_VAR_J3WERA INT;

    SELECT COALESCE(AVG(PRICE), 0), MIN(PRICE), MAX(PRICE), COUNT(*)
    INTO MYSQL_VAR_OJXJPF, MYSQL_VAR_89QYHS, MYSQL_VAR_I7EDQR, MYSQL_VAR_J3WERA
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_J3WERA = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_CHAZ9V();
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JHEMUH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JHEMUH(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LXZABP INT DEFAULT 0;
    DECLARE MYSQL_VAR_RDUYUI INT DEFAULT 0;
    DECLARE MYSQL_VAR_S1ALO7 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_LXZABP
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE());

    SET MYSQL_VAR_RDUYUI = 5000 + (MYSQL_VAR_LXZABP * 1000);

    IF MYSQL_VAR_LXZABP = 0 THEN
        RETURN MYSQL_VAR_RDUYUI;
    END IF;

    SET MYSQL_VAR_S1ALO7 = MYSQL_VAR_RDUYUI / MYSQL_VAR_LXZABP;

    RETURN MYSQL_VAR_S1ALO7;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XKOLZJ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8HODW9 INT DEFAULT 0;

    SELECT MYSQL_FUNC_P1HSIB(10)
    INTO MYSQL_VAR_8HODW9
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_JHEMUH(20);
END//

DELIMITER ;