/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_DZGHLQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DZGHLQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4U68NA VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_FFP061 INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_4U68NA, MYSQL_VAR_FFP061
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_4U68NA != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_FFP061 * 5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LKBXU5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LKBXU5(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2K1413 INT DEFAULT 0;

    SELECT TIMESTAMPDIFF(MONTH, REGISTRATION_DATE, CURDATE())
    INTO MYSQL_VAR_2K1413
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_2K1413;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I0MWJF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I0MWJF(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1SBHSI VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_A9AEI9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0R0IRL INT DEFAULT 0;

    SELECT MYSQL_FUNC_DZGHLQ(10)
    INTO MYSQL_VAR_1SBHSI, MYSQL_VAR_A9AEI9, MYSQL_VAR_0R0IRL
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_1SBHSI != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_LKBXU5(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4KDMSH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4KDMSH(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2JDOQA DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_I0MWJF(20)
    INTO MYSQL_VAR_2JDOQA
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_2JDOQA);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XDN16B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XDN16B(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YBMGCL INT DEFAULT 3;
    DECLARE MYSQL_VAR_1GF1MQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_647XK3 INT DEFAULT 0;

    SELECT DATEDIFF(COALESCE(DELIVERY_DATE, CURDATE()), ORDER_DATE)
    INTO MYSQL_VAR_1GF1MQ
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_647XK3 = MYSQL_FUNC_4KDMSH(20);

    RETURN GREATEST(MYSQL_VAR_647XK3, 0);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZPP0AS(BASE INT, EXPONENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2SBK2B INT DEFAULT 1;
    DECLARE MYSQL_VAR_D9PS26 INT DEFAULT 0;

    IF EXPONENT < 0 THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_D9PS26 < EXPONENT DO
        SET MYSQL_VAR_2SBK2B = MYSQL_VAR_2SBK2B * BASE;
        SET MYSQL_VAR_D9PS26 = MYSQL_VAR_D9PS26 + 1;
    END WHILE;

    RETURN MYSQL_FUNC_XDN16B(30);
END//

DELIMITER ;