/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_7RW84V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7RW84V(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DPXTF4 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_DPXTF4
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_DPXTF4 / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ESYX5C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ESYX5C(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4XHYP1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_WW0X11 INT DEFAULT 0;
    DECLARE MYSQL_VAR_VJGWEU INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_4XHYP1, MYSQL_VAR_WW0X11
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_WW0X11 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_VJGWEU = MYSQL_VAR_4XHYP1 / MYSQL_VAR_WW0X11;

    RETURN MYSQL_VAR_VJGWEU;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AFZQCH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AFZQCH(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_C50CYE INT DEFAULT 0;
    DECLARE MYSQL_VAR_I39HA1 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_JMWDSD DECIMAL(10,2) DEFAULT 0.00;

    SELECT COUNT(*), COALESCE(AVG(SALARY), 0),
           COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_C50CYE, MYSQL_VAR_I39HA1, MYSQL_VAR_JMWDSD
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN (MYSQL_FUNC_ESYX5C(20) - (0) + COALESCE(FLOOR((MYSQL_VAR_I39HA1 * MYSQL_VAR_JMWDSD) / GREATEST(MYSQL_VAR_C50CYE, 1)), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_67KJWU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_67KJWU(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VOB8TC INT DEFAULT 0;
    DECLARE MYSQL_VAR_W4GEYW INT DEFAULT 0;
    DECLARE MYSQL_VAR_5U7JDL INT DEFAULT 0;
    DECLARE MYSQL_VAR_YFPJLF INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0), COALESCE(REORDER_POINT, 10), COALESCE(UNIT_COST, 0)
    INTO MYSQL_VAR_VOB8TC, MYSQL_VAR_W4GEYW, MYSQL_VAR_5U7JDL
    FROM INVENTORY_PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_YFPJLF = MYSQL_VAR_W4GEYW - MYSQL_VAR_VOB8TC;

    IF MYSQL_VAR_5U7JDL > 100 THEN
        SET MYSQL_VAR_YFPJLF = MYSQL_VAR_YFPJLF + 5;
    END IF;

    RETURN CAST(MYSQL_VAR_YFPJLF AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9EU4R5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9EU4R5(PROPERTY_ID_PARAM INT, SERVICE_TYPE VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LL4UJ1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7X5P2P INT DEFAULT 0;
    DECLARE MYSQL_VAR_OEKMSK INT DEFAULT 50;
    DECLARE MYSQL_VAR_ZUNLDC INT DEFAULT 0;

    SELECT COALESCE(AREA_SQFT, 500), COALESCE(NUM_ROOMS, 2)
    INTO MYSQL_VAR_LL4UJ1, MYSQL_VAR_7X5P2P
    FROM PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_OEKMSK;

    SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC + (MYSQL_VAR_LL4UJ1 / 100) * 10;

    SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC + (MYSQL_VAR_7X5P2P * 15);

    IF SERVICE_TYPE = 'DEEP' THEN
        SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC * 150 / 100;
    ELSEIF SERVICE_TYPE = 'MOVE_OUT' THEN
        SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC * 175 / 100;
    END IF;

    RETURN CAST(MYSQL_VAR_ZUNLDC AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7D6D9S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7D6D9S(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4F4JIA DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_PCGI3K INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_4F4JIA, MYSQL_VAR_PCGI3K
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_VAR_4F4JIA * 10) + (30 - MYSQL_VAR_PCGI3K);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XBX1FE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XBX1FE(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_R1UWS0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_EETT5S INT DEFAULT 0;

    SELECT (MYSQL_FUNC_9EU4R5(10, 'test_0_1') - (0) + COALESCE(COALESCE(DATEDIFF(CURDATE(), MAX(ORDER_DATE)), 999), 0))
    INTO MYSQL_VAR_R1UWS0
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_EETT5S = MYSQL_FUNC_7D6D9S(20);

    RETURN MYSQL_VAR_EETT5S;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GVU2OC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GVU2OC(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CUJ73B INT DEFAULT 0;
    DECLARE MYSQL_VAR_CAMSCT INT DEFAULT 0;
    DECLARE MYSQL_VAR_290XDR INT DEFAULT 0;

    SELECT (MYSQL_FUNC_XBX1FE(20) - (0) + COALESCE(COUNT(DISTINCT PRODUCT_ID), COALESCE(SUM(QUANTITY), 0), 0))
    INTO MYSQL_VAR_CUJ73B, MYSQL_VAR_CAMSCT
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_CAMSCT = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_290XDR = MYSQL_FUNC_AFZQCH(30);

    RETURN (MYSQL_FUNC_67KJWU(30) - (0) + COALESCE(MYSQL_VAR_290XDR, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OQH1OB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OQH1OB(A INT, B INT) RETURNS INT
BEGIN
IF A < B THEN
        RETURN A;
    END IF;
    RETURN B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_K698WX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_K698WX(DISTANCE_MILES_PARAM INT, TRUCK_SIZE_PARAM VARCHAR(20)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BRY2U2 INT DEFAULT 2;
    DECLARE MYSQL_VAR_F0BBJ4 INT DEFAULT 1;
    DECLARE MYSQL_VAR_FY4FTY INT DEFAULT 50;
    DECLARE MYSQL_VAR_W3E78Z INT DEFAULT 0;

    CASE TRUCK_SIZE_PARAM
        WHEN 'SMALL' THEN SET MYSQL_VAR_F0BBJ4 = 1;
        WHEN 'MEDIUM' THEN SET MYSQL_VAR_F0BBJ4 = 2;
        WHEN 'LARGE' THEN SET MYSQL_VAR_F0BBJ4 = 3;
        WHEN 'EXTRA_LARGE' THEN SET MYSQL_VAR_F0BBJ4 = 4;
        ELSE SET MYSQL_VAR_F0BBJ4 = 1;
    END CASE;

    SET MYSQL_VAR_W3E78Z = (DISTANCE_MILES_PARAM * MYSQL_VAR_BRY2U2 * MYSQL_VAR_F0BBJ4) + MYSQL_VAR_FY4FTY;

    IF DISTANCE_MILES_PARAM > 500 THEN
        SET MYSQL_VAR_W3E78Z = MYSQL_VAR_W3E78Z - (MYSQL_VAR_W3E78Z * 10 / 100);
    END IF;

    RETURN CAST(MYSQL_VAR_W3E78Z AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L25TPN(POLICY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M0JADL INT DEFAULT 0;
    DECLARE MYSQL_VAR_7CAEDP INT DEFAULT 0;
    DECLARE MYSQL_VAR_S6KB7B INT DEFAULT 0;
    DECLARE MYSQL_VAR_112OSF INT DEFAULT 0;

    SELECT (MYSQL_FUNC_GVU2OC(20) - (0) + COALESCE(COALESCE(BENEFIT_DURATION_MONTHS, 12), COALESCE(MONTHLY_BENEFIT, 2000), 0))
    INTO MYSQL_VAR_M0JADL, MYSQL_VAR_S6KB7B
    FROM INSURANCE_DISABILITY
    WHERE POLICY_ID = POLICY_ID_PARAM;

    SELECT (MYSQL_FUNC_K698WX(30, 'test_2_1') - (0) + COALESCE(COALESCE(SUM(TOTAL_BENEFITS_PAID), 0), 0)) INTO MYSQL_VAR_7CAEDP
    FROM DISABILITY_CLAIMS
    WHERE POLICY_ID = POLICY_ID_PARAM;

    SET MYSQL_VAR_112OSF = MYSQL_FUNC_OQH1OB(30, 31);

    RETURN (MYSQL_FUNC_7RW84V(20) - (0) + COALESCE(CAST(MYSQL_VAR_112OSF AS SIGNED), 0));
END//

DELIMITER ;