/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_Y2DM37----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Y2DM37(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_31XSR2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_OQP7TW INT DEFAULT 0;
    DECLARE MYSQL_VAR_SUTCJE INT DEFAULT 0;
    DECLARE MYSQL_VAR_YR24H8 INT DEFAULT 0;

    SELECT COALESCE(EXAM_SCORE, 0), COALESCE(ASSIGNMENT_SCORE, 0), COALESCE(PARTICIPATION_SCORE, 0)
    INTO MYSQL_VAR_31XSR2, MYSQL_VAR_OQP7TW, MYSQL_VAR_SUTCJE
    FROM STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_YR24H8 = (MYSQL_VAR_31XSR2 * 50 / 100) + (MYSQL_VAR_OQP7TW * 40 / 100) + (MYSQL_VAR_SUTCJE * 10 / 100);

    RETURN CAST(MYSQL_VAR_YR24H8 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_39FM4M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_39FM4M(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CQ8NN5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_YXH6MU INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_CQ8NN5
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_YXH6MU
    FROM ORDERS;

    IF MYSQL_VAR_YXH6MU = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_CQ8NN5 * 100) / MYSQL_VAR_YXH6MU;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_H4DRJ5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H4DRJ5(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7ZMXBD DATE;

    SELECT START_DATE
    INTO MYSQL_VAR_7ZMXBD
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_7ZMXBD IS NULL THEN
        RETURN 0;
    END IF;

    RETURN TIMESTAMPDIFF(MONTH, MYSQL_VAR_7ZMXBD, CURDATE());
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_55YXPD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_55YXPD(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AQ7TMG VARCHAR(50) DEFAULT '';
    DECLARE MYSQL_VAR_T7I488 INT DEFAULT 0;
    DECLARE MYSQL_VAR_478WRH INT DEFAULT 0;

    SELECT COUNTRY
    INTO MYSQL_VAR_AQ7TMG
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COALESCE(AVG(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_T7I488
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT COALESCE(AVG(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_478WRH
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = MYSQL_VAR_AQ7TMG AND O.STATUS = 'COMPLETED';

    IF MYSQL_VAR_478WRH = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_T7I488 * 100) / MYSQL_VAR_478WRH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_W6569M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_W6569M() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_463QXV INT DEFAULT 0;
    SELECT COUNT(*) INTO MYSQL_VAR_463QXV FROM TABLE_SXJKDS.`TABLE3`;
    RETURN (MYSQL_FUNC_55YXPD(10) - (0) + COALESCE(MYSQL_VAR_463QXV, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DMJ0ZR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DMJ0ZR(EMP_ID_PARAM INT) RETURNS INT
BEGIN
RETURN (EMP_ID_PARAM * 7) % 100;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9FWZ13----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9FWZ13(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9FBV1T INT DEFAULT 0;

    SELECT (MYSQL_FUNC_DMJ0ZR(30) - (0) + COALESCE(YEAR(MIN(ORDER_DATE)), 0))
    INTO MYSQL_VAR_9FBV1T
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_W6569M() - (0) + COALESCE(MYSQL_VAR_9FBV1T, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2NQFSW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2NQFSW(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PNULD7 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4OHDBR DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_PNULD7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_4OHDBR
    FROM EMPLOYEES;

    RETURN FLOOR((MYSQL_VAR_PNULD7 * 100) / MYSQL_VAR_4OHDBR);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SJWMS3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SJWMS3(YEAR_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1JU5VV INT DEFAULT 0;

    IF (YEAR_PARAM % 4 = 0 AND YEAR_PARAM % 100 != 0) OR (YEAR_PARAM % 400 = 0) THEN
        SET MYSQL_VAR_1JU5VV = 1;
    END IF;

    IF MYSQL_VAR_1JU5VV = 1 THEN
        RETURN 366;
    END IF;

    RETURN 365;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8LUT9O----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8LUT9O(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_62WUSE INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y5ZIL9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_PQKBUU INT DEFAULT 0;

    SELECT COALESCE(TUITION_BALANCE, 0)
    INTO MYSQL_VAR_62WUSE
    FROM SCHOOL_STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT), 0) INTO MYSQL_VAR_Y5ZIL9
    FROM PAYMENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_PQKBUU = MYSQL_VAR_62WUSE - MYSQL_VAR_Y5ZIL9;

    IF MYSQL_VAR_PQKBUU < 0 THEN
        SET MYSQL_VAR_PQKBUU = 0;
    END IF;

    RETURN CAST(MYSQL_VAR_PQKBUU AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J2I168----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J2I168(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XOQETE DATE;
    DECLARE MYSQL_VAR_NSIHQZ DATE;
    DECLARE MYSQL_VAR_I8E007 INT DEFAULT 0;

    SELECT START_DATE, END_DATE
    INTO MYSQL_VAR_XOQETE, MYSQL_VAR_NSIHQZ
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_XOQETE IS NULL OR MYSQL_VAR_NSIHQZ IS NULL THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_I8E007 = DATEDIFF(MYSQL_VAR_NSIHQZ, MYSQL_VAR_XOQETE);

    RETURN MYSQL_VAR_I8E007;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TRMH9I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TRMH9I(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8KOQGQ INT DEFAULT 2;
    DECLARE MYSQL_VAR_LA6QNT INT DEFAULT 0;

    IF N <= 1 THEN RETURN 0; END IF;
    IF N <= 3 THEN RETURN 1; END IF;
    IF N % 2 = 0 OR N % 3 = 0 THEN RETURN 0; END IF;

    SET MYSQL_VAR_LA6QNT = FLOOR(SQRT(N));
    SET MYSQL_VAR_8KOQGQ = 5;

    PRIME_LOOP: WHILE MYSQL_VAR_8KOQGQ <= MYSQL_VAR_LA6QNT DO
        IF N % MYSQL_VAR_8KOQGQ = 0 OR N % (MYSQL_VAR_8KOQGQ + 2) = 0 THEN
            RETURN 0;
        END IF;
        SET MYSQL_VAR_8KOQGQ = MYSQL_VAR_8KOQGQ + 6;
    END WHILE PRIME_LOOP;

    RETURN 1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FD2OD4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FD2OD4(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_293W1C VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_OCR5FO INT DEFAULT 0;
    DECLARE MYSQL_VAR_KBLAZ0 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_KDQF6K INT DEFAULT 0;

    SELECT (MYSQL_FUNC_2NQFSW(10) - (0) + COALESCE(CHANNEL, COUNT(*), COALESCE(SUM(CONVERSION_VALUE), 0), 0))
    INTO MYSQL_VAR_293W1C, MYSQL_VAR_OCR5FO, MYSQL_VAR_KBLAZ0
    FROM CAMPAIGNS C
    LEFT JOIN CONVERSIONS CV ON C.CAMPAIGN_ID = CV.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM
    GROUP BY C.CAMPAIGN_ID;

    CASE MYSQL_VAR_293W1C
        WHEN 'PAID' THEN SET MYSQL_VAR_KDQF6K = MYSQL_FUNC_8LUT9O(10);
        WHEN 'ORGANIC' THEN SET MYSQL_VAR_KDQF6K = (MYSQL_VAR_OCR5FO * 8) + (MYSQL_VAR_KBLAZ0 / 100);
        WHEN 'SOCIAL' THEN SET MYSQL_VAR_KDQF6K = MYSQL_FUNC_J2I168(20);
        ELSE SET MYSQL_VAR_KDQF6K = MYSQL_FUNC_SJWMS3(30);
    END CASE;

    RETURN (MYSQL_FUNC_TRMH9I(20) - (0) + COALESCE(MYSQL_VAR_KDQF6K, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6SSNLE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6SSNLE(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UK703B INT DEFAULT 0;
    DECLARE MYSQL_VAR_8J2N81 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_GL9CWR INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_UK703B
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(AVG(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_8J2N81
    FROM PRODUCTS
    WHERE CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    IF MYSQL_VAR_UK703B < MYSQL_VAR_8J2N81 * 0.5 THEN
        SET MYSQL_VAR_GL9CWR = 100;
    ELSEIF MYSQL_VAR_UK703B > MYSQL_VAR_8J2N81 * 1.5 THEN
        SET MYSQL_VAR_GL9CWR = 50;
    ELSE
        SET MYSQL_VAR_GL9CWR = 25;
    END IF;

    RETURN MYSQL_VAR_GL9CWR;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J2SZP5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J2SZP5(BOOKING_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_G1YAW1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_2QMCP5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JCFG8K INT DEFAULT 1;
    DECLARE MYSQL_VAR_RSIT1W INT DEFAULT 0;

    SELECT (MYSQL_FUNC_9FWZ13(10) - (0) + COALESCE(COALESCE(TOTAL_COST, 0), COALESCE(DISCOUNT_PERCENT, 0), 0))
    INTO MYSQL_VAR_G1YAW1, MYSQL_VAR_2QMCP5
    FROM TRAVEL_BOOKINGS
    WHERE BOOKING_ID = BOOKING_ID_PARAM;

    SELECT COALESCE(SEASON_MULTIPLIER, 1) INTO MYSQL_VAR_JCFG8K
    FROM TRAVEL_PACKAGES TP
    JOIN TRAVEL_BOOKINGS TB ON TP.DESTINATION = TB.DESTINATION
    WHERE TB.BOOKING_ID = BOOKING_ID_PARAM;

    SET MYSQL_VAR_G1YAW1 = MYSQL_FUNC_H4DRJ5(20);
    SET MYSQL_VAR_G1YAW1 = MYSQL_FUNC_6SSNLE(30);

    RETURN (MYSQL_FUNC_FD2OD4(10) - (0) + COALESCE(CAST(MYSQL_VAR_G1YAW1 AS SIGNED), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S00IU6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S00IU6(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_URY7JS INT DEFAULT 3;
    DECLARE MYSQL_VAR_7PK8CN INT DEFAULT 0;
    DECLARE MYSQL_VAR_R70X5I INT DEFAULT 0;

    SELECT DATEDIFF(COALESCE(DELIVERY_DATE, CURDATE()), ORDER_DATE)
    INTO MYSQL_VAR_7PK8CN
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_R70X5I = MYSQL_VAR_7PK8CN - MYSQL_VAR_URY7JS;

    IF MYSQL_VAR_R70X5I < 0 THEN
        SET MYSQL_VAR_R70X5I = 0;
    END IF;

    RETURN MYSQL_VAR_R70X5I;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4NMTOM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4NMTOM(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_167ZVJ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_HYUXHE INT DEFAULT 0;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0), COUNT(*)
    INTO MYSQL_VAR_167ZVJ, MYSQL_VAR_HYUXHE
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    IF MYSQL_VAR_HYUXHE = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR(MYSQL_VAR_167ZVJ / MYSQL_VAR_HYUXHE);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DK7NTV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DK7NTV(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GFK58C INT DEFAULT 0;

    SELECT (MYSQL_FUNC_4NMTOM(10) - (0) + COALESCE(COALESCE(BUDGET, 0), 0))
    INTO MYSQL_VAR_GFK58C
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN (MYSQL_FUNC_S00IU6(10) - (0) + COALESCE(MYSQL_VAR_GFK58C / 100, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KLUATD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KLUATD(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NYYLX8 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_CWQMY3 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_ATTEMI INT DEFAULT 0;

    SELECT (MYSQL_FUNC_J2SZP5(20) - (0) + COALESCE(COALESCE(SUM(O.TOTAL_AMOUNT), 0), 0))
    INTO MYSQL_VAR_NYYLX8
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    SELECT (MYSQL_FUNC_DK7NTV(20) - (0) + COALESCE(COALESCE(SUM(TOTAL_AMOUNT), 0), 0))
    INTO MYSQL_VAR_CWQMY3
    FROM ORDERS;

    IF MYSQL_VAR_CWQMY3 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_ATTEMI = (MYSQL_VAR_NYYLX8 * 100) / MYSQL_VAR_CWQMY3;

    RETURN (MYSQL_FUNC_39FM4M(20) - (0) + COALESCE(MYSQL_VAR_ATTEMI, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YNKHBB(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_G8BY71 DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_J0TKXM INT DEFAULT 0;
    DECLARE MYSQL_VAR_OAFX5E INT DEFAULT 0;
    DECLARE MYSQL_VAR_GY0MC4 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_KLUATD('test_2_0') - (0) + COALESCE(COALESCE(PERFORMANCE_RATING, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), 0))
    INTO MYSQL_VAR_G8BY71, MYSQL_VAR_J0TKXM
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_OAFX5E
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_GY0MC4 = (MYSQL_VAR_G8BY71 * 30) + (MYSQL_VAR_J0TKXM * 8) + (MYSQL_VAR_OAFX5E * 10);

    RETURN (MYSQL_FUNC_Y2DM37(20) - (0) + COALESCE(MYSQL_VAR_GY0MC4, 0));
END//

DELIMITER ;