/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_03sl93 (
    id INT,
    name VARCHAR(100)
);
INSERT INTO table_03sl93 (id, name) VALUES (1, 'Client A');
INSERT INTO table_03sl93 (id, name) VALUES (2, 'Client B');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_UVYF34----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UVYF34(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2ZFF9O DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_2ZFF9O
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_2ZFF9O);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_81ZC7B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_81ZC7B(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BZRXMT INT DEFAULT 0;
    DECLARE MYSQL_VAR_C39JAC INT DEFAULT 1;

    IF N <= 0 THEN
        RETURN 0;
    END IF;

    DIVISOR_LOOP: WHILE MYSQL_VAR_C39JAC <= N / 2 DO
        IF N % MYSQL_VAR_C39JAC = 0 THEN
            SET MYSQL_VAR_BZRXMT = MYSQL_VAR_BZRXMT + MYSQL_VAR_C39JAC;
        END IF;
        SET MYSQL_VAR_C39JAC = MYSQL_VAR_C39JAC + 1;
    END WHILE DIVISOR_LOOP;

    SET MYSQL_VAR_BZRXMT = MYSQL_VAR_BZRXMT + N;

    RETURN MYSQL_VAR_BZRXMT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VDPXVG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VDPXVG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2IK9NW INT DEFAULT 0;
    DECLARE MYSQL_VAR_G8DX0C INT DEFAULT 0;
    DECLARE MYSQL_VAR_2LOJWT INT;
    DECLARE MYSQL_VAR_0H0X9Z INT;
    DECLARE MYSQL_VAR_SZ8MBH INT DEFAULT YEAR(CURDATE());
    DECLARE MYSQL_VAR_34X3T6 INT DEFAULT 0;

    SELECT COALESCE(TOTAL_ORDERS, 0), COALESCE(TOTAL_SPENT, 0), YEAR(REGISTRATION_DATE)
    INTO MYSQL_VAR_2IK9NW, MYSQL_VAR_G8DX0C, MYSQL_VAR_2LOJWT
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_0H0X9Z = MYSQL_VAR_SZ8MBH - MYSQL_VAR_2LOJWT;

    IF MYSQL_VAR_0H0X9Z < 0 THEN
        SET MYSQL_VAR_0H0X9Z = 0;
    END IF;

    SET MYSQL_VAR_34X3T6 = (MYSQL_VAR_G8DX0C / 100) + (MYSQL_VAR_2IK9NW * 10) + (MYSQL_VAR_0H0X9Z * 50);

    RETURN MYSQL_VAR_34X3T6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VDTWGK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VDTWGK(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8N96DV INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_8N96DV
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID_PARAM;

    RETURN MYSQL_VAR_8N96DV;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NLCPO9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NLCPO9(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YKYIPS DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_YKYIPS
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN FLOOR(MYSQL_VAR_YKYIPS);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XN9NC8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XN9NC8(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2MU5F0 INT DEFAULT 0;

    SELECT MYSQL_FUNC_NLCPO9('test_1_0')
    INTO MYSQL_VAR_2MU5F0
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN GREATEST(100 - (MYSQL_VAR_2MU5F0 * 5), 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SZ3NF4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SZ3NF4(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_I87F94 INT DEFAULT 0;
    DECLARE MYSQL_VAR_X1D6QN INT DEFAULT 0;
    DECLARE MYSQL_VAR_KCARUS INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_I87F94
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_X1D6QN
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = (SELECT COUNTRY FROM CUSTOMERS WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM);

    IF MYSQL_VAR_X1D6QN = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KCARUS = (MYSQL_VAR_I87F94 * 100) / MYSQL_VAR_X1D6QN;

    RETURN MYSQL_VAR_KCARUS;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FEDMQN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FEDMQN() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8L0FBD INT;
    
    SELECT COUNT(*) INTO MYSQL_VAR_8L0FBD FROM TABLE_03SL93;
    
    RETURN MYSQL_VAR_8L0FBD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WMESRL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WMESRL(RADIUS INT, HEIGHT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JU66CS DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_KVPXZB DECIMAL(10,2) DEFAULT 0.00;

    SET MYSQL_VAR_JU66CS = MYSQL_FUNC_FEDMQN();
    SET MYSQL_VAR_KVPXZB = 3.14159 * RADIUS * (RADIUS + MYSQL_VAR_JU66CS);

    RETURN MYSQL_FUNC_SZ3NF4(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NP24O8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NP24O8(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OUHJFS DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_WMESRL(10, 11)
    INTO MYSQL_VAR_OUHJFS
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
      AND ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)
      AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_OUHJFS);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_M85E1G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M85E1G(SERVICE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PQ3Z5J INT DEFAULT 15000;
    DECLARE MYSQL_VAR_H67J0V INT DEFAULT 0;
    DECLARE MYSQL_VAR_ODFHIF INT DEFAULT 0;
    DECLARE MYSQL_VAR_T91L29 INT DEFAULT 0;
    DECLARE MYSQL_VAR_27B6S8 INT DEFAULT 0;

    SELECT MYSQL_FUNC_VDTWGK(30)
    INTO MYSQL_VAR_PQ3Z5J, MYSQL_VAR_H67J0V, MYSQL_VAR_ODFHIF
    FROM SWIMMING_POOL_SERVICE
    WHERE SERVICE_ID = SERVICE_ID_PARAM;

    SELECT MYSQL_FUNC_XN9NC8(30) INTO MYSQL_VAR_T91L29
    FROM SWIMMING_POOL_SERVICE SS
    JOIN POOL_EQUIPMENT PE ON SS.SERVICE_ID = PE.SERVICE_ID
    WHERE SS.SERVICE_ID = SERVICE_ID_PARAM;

    SET MYSQL_VAR_27B6S8 = (MYSQL_VAR_H67J0V * 65) + MYSQL_VAR_ODFHIF + (MYSQL_VAR_T91L29 / 12);

    IF MYSQL_VAR_PQ3Z5J > 30000 THEN
        SET MYSQL_VAR_27B6S8 = MYSQL_VAR_27B6S8 + 50;
    END IF;

    RETURN MYSQL_FUNC_NP24O8(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_20BRDV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_20BRDV(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M5OFYZ INT DEFAULT 0;

    SELECT MYSQL_FUNC_VDPXVG(20)
    INTO MYSQL_VAR_M5OFYZ
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_M85E1G(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YKYV36(COURSE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GI1OHH INT DEFAULT 0;
    DECLARE MYSQL_VAR_LLAG8E INT DEFAULT 0;
    DECLARE MYSQL_VAR_LHDI1E INT DEFAULT 0;
    DECLARE MYSQL_VAR_CD74JB INT DEFAULT 0;

    SELECT MYSQL_FUNC_20BRDV(20)
    INTO MYSQL_VAR_GI1OHH, MYSQL_VAR_LLAG8E, MYSQL_VAR_LHDI1E
    FROM ENROLLMENTS
    WHERE COURSE_ID = COURSE_ID_PARAM;

    IF MYSQL_VAR_GI1OHH = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_CD74JB = MYSQL_FUNC_81ZC7B(20);

    IF MYSQL_VAR_LHDI1E >= 90 THEN
        SET MYSQL_VAR_CD74JB = MYSQL_VAR_CD74JB + 5;
    END IF;

    RETURN MYSQL_FUNC_UVYF34(20);
END//

DELIMITER ;