/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_hbda4d (
    `id` INT PRIMARY KEY,
    `age` INT
);
CREATE TABLE IF NOT EXISTS table_jgsjl0 (
    `user_id` INT,
    `address` VARCHAR(30),
    `town` VARCHAR(30)
);
INSERT INTO table_hbda4d (`id`, `age`) VALUES (1, 25), (2, 30), (3, 40);
INSERT INTO table_jgsjl0 (`user_id`, `address`, `town`) VALUES (1, '123 Main St', 'Springfield'), (2, '456 Oak Ave', 'Shelbyville'), (3, '789 Pine Rd', 'Springfield');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_Y60I2T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Y60I2T(P_ADDRESS INT, V_TOWN INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UA5ZC8 INT DEFAULT 0;
    
    UPDATE TABLE_HBDA4D AS U
    JOIN TABLE_JGSJL0 AS A
    ON U.`ID` = A.`USER_ID`
    SET `AGE` = `AGE` + 10
    WHERE A.`ADDRESS` = CAST(P_ADDRESS AS CHAR) AND A.`TOWN` = CAST(V_TOWN AS CHAR);
    
    SET MYSQL_VAR_UA5ZC8 = ROW_COUNT();
    
    RETURN MYSQL_VAR_UA5ZC8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TCKHKL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TCKHKL(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RA0GTS INT DEFAULT 5;
    DECLARE MYSQL_VAR_6Q4F21 INT DEFAULT 0;
    DECLARE MYSQL_VAR_GJPD8H INT DEFAULT 0;
    DECLARE MYSQL_VAR_AGP14R INT DEFAULT 0;

    SELECT S.DELIVERY_RADIUS_MILES INTO MYSQL_VAR_6Q4F21
    FROM GROCERY_ORDERS O
    JOIN STORES S ON O.STORE_ID = S.STORE_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_6Q4F21 > 10 THEN
        SET MYSQL_VAR_GJPD8H = (MYSQL_VAR_6Q4F21 - 10) * 2;
    END IF;

    SET MYSQL_VAR_AGP14R = MYSQL_VAR_RA0GTS + MYSQL_VAR_GJPD8H;

    RETURN CAST(MYSQL_VAR_AGP14R AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_W6569M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_W6569M() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_463QXV INT DEFAULT 0;
    SELECT COUNT(*) INTO MYSQL_VAR_463QXV FROM TABLE_SXJKDS.`TABLE3`;
    RETURN MYSQL_VAR_463QXV;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AYXZGF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AYXZGF(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6QWKE1 DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_J66GHF INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_6QWKE1, MYSQL_VAR_J66GHF
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_VAR_6QWKE1 * 10) - (MYSQL_VAR_J66GHF * 3);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CMGDTN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CMGDTN(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KH3D42 DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_NEU4O9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_IVXCIX INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZLOGVQ INT DEFAULT 0;

    SELECT MYSQL_FUNC_Y60I2T(10, 11)
    INTO MYSQL_VAR_KH3D42
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT MYSQL_FUNC_TCKHKL(10)
    INTO MYSQL_VAR_NEU4O9, MYSQL_VAR_IVXCIX
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_ZLOGVQ = MYSQL_FUNC_W6569M();

    RETURN MYSQL_FUNC_AYXZGF(10);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YJYWPM(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5OSVCW INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_5OSVCW
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_FUNC_CMGDTN(10);
END//

DELIMITER ;