/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_YH4JKO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YH4JKO(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TJX3MG INT DEFAULT 0;
    DECLARE MYSQL_VAR_C86EGS INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_TJX3MG
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_C86EGS
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_TJX3MG = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_C86EGS / MYSQL_VAR_TJX3MG;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AENQQW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AENQQW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H3AXN9 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_H3AXN9
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN (MYSQL_FUNC_YH4JKO(10) - (0) + COALESCE(FLOOR(MYSQL_VAR_H3AXN9), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HBXEHS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HBXEHS(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QJBMFR DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_QJBMFR
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_QJBMFR);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FPRO7X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FPRO7X(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MHH7YR INT DEFAULT 0;

    SELECT (MYSQL_FUNC_HBXEHS(30) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_MHH7YR
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_MHH7YR;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1ENVDN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1ENVDN(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GUQNF5 INT DEFAULT 0;

    SELECT MONTH(START_DATE)
    INTO MYSQL_VAR_GUQNF5
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN MYSQL_VAR_GUQNF5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FD2OD4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FD2OD4(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_293W1C VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_OCR5FO INT DEFAULT 0;
    DECLARE MYSQL_VAR_KBLAZ0 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_KDQF6K INT DEFAULT 0;

    SELECT CHANNEL, COUNT(*), COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_293W1C, MYSQL_VAR_OCR5FO, MYSQL_VAR_KBLAZ0
    FROM CAMPAIGNS C
    LEFT JOIN CONVERSIONS CV ON C.CAMPAIGN_ID = CV.CAMPAIGN_ID
    WHERE C.CAMPAIGN_ID = CAMPAIGN_ID_PARAM
    GROUP BY C.CAMPAIGN_ID;

    CASE MYSQL_VAR_293W1C
        WHEN 'PAID' THEN SET MYSQL_VAR_KDQF6K = (MYSQL_VAR_OCR5FO * 5) + (MYSQL_VAR_KBLAZ0 / 100);
        WHEN 'ORGANIC' THEN SET MYSQL_VAR_KDQF6K = (MYSQL_VAR_OCR5FO * 8) + (MYSQL_VAR_KBLAZ0 / 100);
        WHEN 'SOCIAL' THEN SET MYSQL_VAR_KDQF6K = (MYSQL_VAR_OCR5FO * 6) + (MYSQL_VAR_KBLAZ0 / 100);
        ELSE SET MYSQL_VAR_KDQF6K = (MYSQL_VAR_OCR5FO * 3) + (MYSQL_VAR_KBLAZ0 / 100);
    END CASE;

    RETURN MYSQL_VAR_KDQF6K;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4232M4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4232M4(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QAP6R6 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(MAX(PRICE), 0)
    INTO MYSQL_VAR_QAP6R6
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_FD2OD4(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_QAP6R6), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_42MJ5R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_42MJ5R(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EF5R5F INT DEFAULT 0;
    DECLARE MYSQL_VAR_0M9MR1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0QOMES INT DEFAULT 0;

    SELECT (MYSQL_FUNC_AENQQW(10) - (0) + COALESCE((MYSQL_FUNC_FPRO7X('test_2_0') - (0) + COALESCE(COUNT(*), 0)), 0))
    INTO MYSQL_VAR_EF5R5F
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE());

    SELECT COUNT(*)
    INTO MYSQL_VAR_0M9MR1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    IF MYSQL_VAR_0M9MR1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0QOMES = MYSQL_FUNC_4232M4(30);

    RETURN (MYSQL_FUNC_1ENVDN(20) - (0) + COALESCE(MYSQL_VAR_0QOMES, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1QDZNH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1QDZNH(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5A13VY DECIMAL(5,1) DEFAULT 0.0;

    SELECT COALESCE(TIMESTAMPDIFF(YEAR, START_DATE, CURDATE()), 0)
    INTO MYSQL_VAR_5A13VY
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_5A13VY);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XKZXKA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XKZXKA(PRINCIPAL INT, RATE_PERCENT DECIMAL(5,2), YEARS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZSVHTM INT DEFAULT 0;
    DECLARE MYSQL_VAR_KOWUTF INT DEFAULT 1;
    DECLARE MYSQL_VAR_CQJS4Z INT DEFAULT 0;

    IF PRINCIPAL <= 0 OR YEARS <= 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_CQJS4Z = MYSQL_FUNC_1QDZNH(30);

    INTEREST_LOOP: WHILE MYSQL_VAR_KOWUTF <= YEARS DO
        SET MYSQL_VAR_CQJS4Z = MYSQL_VAR_CQJS4Z + (MYSQL_VAR_CQJS4Z * RATE_PERCENT / 100);
        SET MYSQL_VAR_KOWUTF = MYSQL_VAR_KOWUTF + 1;
    END WHILE INTEREST_LOOP;

    SET MYSQL_VAR_ZSVHTM = MYSQL_FUNC_42MJ5R(30);

    RETURN FLOOR(MYSQL_VAR_ZSVHTM);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QF75ZL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QF75ZL(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IIZ3PU INT DEFAULT 0;
    DECLARE MYSQL_VAR_5M479K INT DEFAULT 0;
    DECLARE MYSQL_VAR_16INTN INT DEFAULT 0;
    DECLARE MYSQL_VAR_877EWB INT DEFAULT 0;
    DECLARE MYSQL_VAR_LW4AXJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_HZ13VI INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COALESCE(DISCOUNT_PERCENT, 0), COALESCE(SHIPPING_COST, 0)
    INTO MYSQL_VAR_IIZ3PU, MYSQL_VAR_5M479K, MYSQL_VAR_16INTN
    FROM ORDER_ITEMS OI
    JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_5M479K = COALESCE(
        (SELECT DISCOUNT_PERCENT FROM ORDERS WHERE ORDER_ID = ORDER_ID_PARAM), 0
    );

    SET MYSQL_VAR_877EWB = MYSQL_VAR_IIZ3PU - (MYSQL_VAR_IIZ3PU * MYSQL_VAR_5M479K / 100) + MYSQL_VAR_16INTN;

    SELECT COALESCE(TOTAL_AMOUNT, 0) - MYSQL_VAR_877EWB
    INTO MYSQL_VAR_LW4AXJ
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_877EWB = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_HZ13VI = (MYSQL_VAR_LW4AXJ * 100) / MYSQL_VAR_877EWB;

    RETURN MYSQL_VAR_HZ13VI;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DAHM1Z(N INT, K INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2RFIRC INT DEFAULT 1;
    DECLARE MYSQL_VAR_CFYYWX INT DEFAULT 0;

    IF K < 0 OR K > N THEN
        RETURN 0;
    END IF;

    IF K > N - K THEN
        SET K = N - K;
    END IF;

    SET MYSQL_VAR_CFYYWX = MYSQL_FUNC_XKZXKA(30, 31.5, 32);

    WHILE MYSQL_VAR_CFYYWX < K DO
        SET MYSQL_VAR_2RFIRC = MYSQL_VAR_2RFIRC * (N - MYSQL_VAR_CFYYWX);
        SET MYSQL_VAR_2RFIRC = MYSQL_VAR_2RFIRC / (MYSQL_VAR_CFYYWX + 1);
        SET MYSQL_VAR_CFYYWX = MYSQL_VAR_CFYYWX + 1;
    END WHILE;

    RETURN (MYSQL_FUNC_QF75ZL(30) - (0) + COALESCE(FLOOR(MYSQL_VAR_2RFIRC), 0));
END//

DELIMITER ;