/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_svj7l3 (
    emp_no INT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS table_takpkm (
    emp_no INT,
    salary INT,
    FOREIGN KEY (emp_no) REFERENCES table_svj7l3(emp_no)
);
INSERT INTO table_svj7l3 (emp_no) VALUES (10001);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 60117);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 62102);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 66074);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_QB5C3I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QB5C3I(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6UJVZK DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_SW9T6H INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_6UJVZK
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_SW9T6H
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_VAR_6UJVZK * 10) + (MYSQL_VAR_SW9T6H * 2);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VIXANQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VIXANQ(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_P4O5SJ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_N5JU8M INT DEFAULT 0;
    DECLARE MYSQL_VAR_MLOS0D DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_P4O5SJ
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COUNT(DISTINCT PRODUCT_ID)
    INTO MYSQL_VAR_N5JU8M
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_N5JU8M = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_MLOS0D = MYSQL_VAR_P4O5SJ / MYSQL_VAR_N5JU8M;

    RETURN FLOOR(MYSQL_VAR_MLOS0D);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6MABR9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6MABR9(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RHBYEA INT DEFAULT 0;
    DECLARE MYSQL_VAR_US4NWA INT DEFAULT 0;
    DECLARE MYSQL_VAR_0Z9JPH DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_ETXJ66 DECIMAL(10,6) DEFAULT 0.00;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_RHBYEA
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_US4NWA
    FROM CAMPAIGN_IMPRESSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_US4NWA = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_ETXJ66 = (MYSQL_VAR_RHBYEA * 1.0) / MYSQL_VAR_US4NWA;

    RETURN FLOOR(MYSQL_VAR_ETXJ66 * 10000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_C48Y62----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_C48Y62(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QAE33B DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_XVX09J DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_6MABR9(10) - (0) + COALESCE(COALESCE(SUM(PRICE * STOCK_QUANTITY), 0), 0))
    INTO MYSQL_VAR_QAE33B
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT (MYSQL_FUNC_VIXANQ(20) - (0) + COALESCE(COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_XVX09J
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_QAE33B = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_XVX09J * 12) / MYSQL_VAR_QAE33B);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1LQ4NF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1LQ4NF(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H8E7I8 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_8AC32T INT DEFAULT 0;
    DECLARE MYSQL_VAR_HP8AJW INT DEFAULT 0;

    SELECT COALESCE(PRICE, 0), COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_H8E7I8, MYSQL_VAR_8AC32T
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_HP8AJW = (MYSQL_VAR_H8E7I8 * MYSQL_VAR_8AC32T) / 100;

    RETURN MYSQL_VAR_HP8AJW;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8C545F----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8C545F(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4Q1PMF VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_344KRW INT DEFAULT 0;
    DECLARE MYSQL_VAR_EJQLTY INT DEFAULT 0;
    DECLARE MYSQL_VAR_JFF47P INT DEFAULT 0;

    SELECT PLAN_TYPE, COALESCE(MONTHLY_COST, 0), TIMESTAMPDIFF(MONTH, START_DATE, CURDATE())
    INTO MYSQL_VAR_4Q1PMF, MYSQL_VAR_344KRW, MYSQL_VAR_EJQLTY
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_JFF47P = (MYSQL_VAR_EJQLTY * 5) + (MYSQL_VAR_344KRW / 5);

    CASE MYSQL_VAR_4Q1PMF
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_JFF47P = MYSQL_VAR_JFF47P + 50;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_JFF47P = MYSQL_VAR_JFF47P + 30;
        WHEN 'BASIC' THEN SET MYSQL_VAR_JFF47P = MYSQL_VAR_JFF47P + 10;
    END CASE;

    RETURN MYSQL_VAR_JFF47P;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_R9H81C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_R9H81C(N INT, LEVELS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RYRLA0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7EUULB INT DEFAULT 1;

    IF LEVELS <= 0 OR N <= 0 THEN
        RETURN 0;
    END IF;

    OUTER_LOOP: WHILE MYSQL_VAR_7EUULB <= N DO
        SET MYSQL_VAR_RYRLA0 = MYSQL_VAR_RYRLA0 + MYSQL_VAR_7EUULB;

        IF LEVELS > 1 AND MYSQL_VAR_7EUULB > 1 THEN
            SET MYSQL_VAR_RYRLA0 = MYSQL_VAR_RYRLA0 + MYSQL_FUNC_R9H81C(MYSQL_VAR_7EUULB - 1, LEVELS - 1);
        END IF;

        SET MYSQL_VAR_7EUULB = MYSQL_VAR_7EUULB + 1;
    END WHILE OUTER_LOOP;

    RETURN MYSQL_VAR_RYRLA0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5JPH02----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5JPH02(P_EMP_NO INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_U5X0D5 INT;
    
    SELECT AVG(S.SALARY) INTO MYSQL_VAR_U5X0D5
    FROM TABLE_SVJ7L3 E
    JOIN TABLE_TAKPKM S ON E.EMP_NO = S.EMP_NO
    WHERE E.EMP_NO = P_EMP_NO;
    
    RETURN MYSQL_VAR_U5X0D5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GV0PLT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GV0PLT(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VRHE5N INT DEFAULT 0;
    DECLARE MYSQL_VAR_HKA87N INT DEFAULT 0;
    DECLARE MYSQL_VAR_Q254KE INT DEFAULT 1;
    DECLARE MYSQL_VAR_F9WP41 INT DEFAULT 0;
    DECLARE MYSQL_VAR_K5ADJ2 VARCHAR(20) DEFAULT 'BASIC';

    SELECT (MYSQL_FUNC_8C545F(10) - (0) + COALESCE(COALESCE(REFERRAL_COUNT, 0), MONTHLY_FEE, 0))
    INTO MYSQL_VAR_VRHE5N, MYSQL_VAR_HKA87N
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_R9H81C(30, 31) - (0) + COALESCE(PLAN_TYPE, 0))
    INTO MYSQL_VAR_K5ADJ2
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_Q254KE = CASE MYSQL_VAR_K5ADJ2
        WHEN 'ENTERPRISE' THEN 4
        WHEN 'PREMIUM' THEN 3
        WHEN 'STANDARD' THEN 2
        ELSE 1
    END;

    SET MYSQL_VAR_F9WP41 = MYSQL_FUNC_1LQ4NF(20);

    RETURN (MYSQL_FUNC_5JPH02(30) - (0) + COALESCE(MYSQL_VAR_F9WP41, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XTHE6M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XTHE6M(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PGFPKJ DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_C48Y62(30) - (0) + COALESCE(COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_PGFPKJ
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_GV0PLT(10) - (0) + COALESCE(FLOOR(MYSQL_VAR_PGFPKJ), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BBIAM1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BBIAM1(PROPERTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZTVMF5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_FI3ITY DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_QHJPSF INT DEFAULT 0;
    DECLARE MYSQL_VAR_JC5FU6 INT DEFAULT 2000;
    DECLARE MYSQL_VAR_2ND2IK INT DEFAULT 0;
    DECLARE MYSQL_VAR_I5ZLB5 INT DEFAULT 0;

    SELECT COALESCE(BEDROOMS, 0), COALESCE(BATHROOMS, 1.0), COALESCE(SQUARE_FEET, 1000), COALESCE(YEAR_BUILT, 2000)
    INTO MYSQL_VAR_ZTVMF5, MYSQL_VAR_FI3ITY, MYSQL_VAR_QHJPSF, MYSQL_VAR_JC5FU6
    FROM PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_2ND2IK
    FROM PROPERTY_FEATURES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SET MYSQL_VAR_I5ZLB5 = (MYSQL_VAR_ZTVMF5 * 20) + (MYSQL_VAR_FI3ITY * 15) + (MYSQL_VAR_QHJPSF / 100) + ((2024 - MYSQL_VAR_JC5FU6) * 2) + (MYSQL_VAR_2ND2IK * 10);

    RETURN MYSQL_VAR_I5ZLB5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FG6CYO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FG6CYO(CS_ID INT, CLUSTER_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3QAN2L BIGINT UNSIGNED DEFAULT 1;
    DECLARE MYSQL_VAR_3O4UJH VARCHAR(36);
    DECLARE MYSQL_VAR_YIVDB9 VARCHAR(36);
    
    SET MYSQL_VAR_3O4UJH = MYSQL_FUNC_BBIAM1(10);
    SET MYSQL_VAR_YIVDB9 = CONCAT('CLUSTER', CLUSTER_ID);
    
    DELETE FROM MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS
    WHERE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTERSET_ID = MYSQL_VAR_3O4UJH
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTER_ID = MYSQL_VAR_YIVDB9
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.VIEW_ID = MYSQL_VAR_3QAN2L;

    UPDATE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERS C
    SET C.CLUSTERSET_ID = NULL
    WHERE C.CLUSTER_ID = MYSQL_VAR_YIVDB9;

    RETURN 1;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1SRFO8(CONFERENCE_ID_PARAM INT, DAYS_BEFORE_EVENT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LOFFH4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JOD45N INT DEFAULT 0;
    DECLARE MYSQL_VAR_9XMRHN INT DEFAULT 0;

    SELECT (MYSQL_FUNC_XTHE6M(20) - (0) + COALESCE(COALESCE(BASE_PRICE, 100), 0)) INTO MYSQL_VAR_LOFFH4
    FROM CONFERENCES
    WHERE CONFERENCE_ID = CONFERENCE_ID_PARAM;

    IF DAYS_BEFORE_EVENT >= 30 THEN
        SET MYSQL_VAR_JOD45N = 25;
    ELSEIF DAYS_BEFORE_EVENT >= 14 THEN
        SET MYSQL_VAR_JOD45N = 15;
    ELSEIF DAYS_BEFORE_EVENT >= 7 THEN
        SET MYSQL_VAR_JOD45N = 10;
    ELSE
        SET MYSQL_VAR_JOD45N = 0;
    END IF;

    SET MYSQL_VAR_9XMRHN = MYSQL_FUNC_FG6CYO(30, 31);

    RETURN (MYSQL_FUNC_QB5C3I(30) - (0) + COALESCE(CAST(MYSQL_VAR_9XMRHN AS SIGNED), 0));
END//

DELIMITER ;