/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_AIYQQL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AIYQQL(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EZRSXH INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_EZRSXH
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_VAR_EZRSXH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6IT93A----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6IT93A(INCOME INT, TAX_YEAR INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QIHP22 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZV8037 INT DEFAULT 0;

    SET MYSQL_VAR_ZV8037 = INCOME;

    IF INCOME <= 0 THEN
        RETURN 0;
    END IF;

    IF INCOME <= 10000 THEN
        SET MYSQL_VAR_QIHP22 = INCOME * 10 / 100;
    ELSEIF INCOME <= 40000 THEN
        SET MYSQL_VAR_QIHP22 = 1000 + ((INCOME - 10000) * 20 / 100);
    ELSEIF INCOME <= 85000 THEN
        SET MYSQL_VAR_QIHP22 = 1000 + 6000 + ((INCOME - 40000) * 30 / 100);
    ELSE
        SET MYSQL_VAR_QIHP22 = 1000 + 6000 + 13500 + ((INCOME - 85000) * 35 / 100);
    END IF;

    RETURN CAST(MYSQL_VAR_QIHP22 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5H5DM7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5H5DM7(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5RJ61V INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_5RJ61V
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_6IT93A(10, 11) - (0) + COALESCE(MYSQL_VAR_5RJ61V, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FK7XJJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FK7XJJ(PROJECT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9EUGCJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_P7QGRM INT DEFAULT 0;
    DECLARE MYSQL_VAR_E4L9OP INT DEFAULT 0;
    DECLARE MYSQL_VAR_OR7EKE INT DEFAULT 0;
    DECLARE MYSQL_VAR_8YDZGL INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_9EUGCJ
    FROM TASKS
    WHERE PROJECT_ID = PROJECT_ID_PARAM;

    SELECT COUNT(CASE WHEN STATUS = 'COMPLETED' THEN 1 END),
           COUNT(CASE WHEN STATUS != 'COMPLETED' AND DUE_DATE < CURDATE() THEN 1 END)
    INTO MYSQL_VAR_P7QGRM, MYSQL_VAR_E4L9OP
    FROM TASKS
    WHERE PROJECT_ID = PROJECT_ID_PARAM;

    SELECT DATEDIFF(DEADLINE, CURDATE())
    INTO MYSQL_VAR_OR7EKE
    FROM PROJECTS
    WHERE PROJECT_ID = PROJECT_ID_PARAM;

    IF MYSQL_VAR_9EUGCJ > 0 THEN
        SET MYSQL_VAR_8YDZGL = (MYSQL_VAR_P7QGRM * 100) / MYSQL_VAR_9EUGCJ;
    END IF;

    IF MYSQL_VAR_OR7EKE < 7 AND MYSQL_VAR_E4L9OP > 0 THEN
        SET MYSQL_VAR_8YDZGL = MYSQL_VAR_8YDZGL - 30;
    END IF;

    RETURN GREATEST(MYSQL_VAR_8YDZGL, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Q7UN8B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Q7UN8B(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PF7YYW DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_61WQCG INT DEFAULT 0;
    DECLARE MYSQL_VAR_LGU1NH INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0), COUNT(*)
    INTO MYSQL_VAR_PF7YYW, MYSQL_VAR_61WQCG
    FROM ORDERS O
    LEFT JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM
    GROUP BY O.ORDER_ID;

    SET MYSQL_VAR_LGU1NH = MYSQL_FUNC_FK7XJJ(30);

    RETURN MYSQL_VAR_LGU1NH;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6SSNLE(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UK703B INT DEFAULT 0;
    DECLARE MYSQL_VAR_8J2N81 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_GL9CWR INT DEFAULT 0;

    SELECT (MYSQL_FUNC_AIYQQL(20) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_UK703B
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT (MYSQL_FUNC_Q7UN8B(30) - (0) + COALESCE(COALESCE(AVG(STOCK_QUANTITY), 0), 0))
    INTO MYSQL_VAR_8J2N81
    FROM PRODUCTS
    WHERE CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    IF MYSQL_VAR_UK703B < MYSQL_VAR_8J2N81 * 0.5 THEN
        SET MYSQL_VAR_GL9CWR = 100;
    ELSEIF MYSQL_VAR_UK703B > MYSQL_VAR_8J2N81 * 1.5 THEN
        SET MYSQL_VAR_GL9CWR = 50;
    ELSE
        SET MYSQL_VAR_GL9CWR = 25;
    END IF;

    RETURN (MYSQL_FUNC_5H5DM7(30) - (0) + COALESCE(MYSQL_VAR_GL9CWR, 0));
END//

DELIMITER ;