/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_36NBNB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_36NBNB(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YH3HUA INT DEFAULT 0;
    DECLARE MYSQL_VAR_VUWJL1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_KYFQC9 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_YH3HUA
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE());

    SELECT COUNT(*)
    INTO MYSQL_VAR_VUWJL1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE()) - 1;

    IF MYSQL_VAR_VUWJL1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KYFQC9 = ((MYSQL_VAR_YH3HUA - MYSQL_VAR_VUWJL1) * 100) / MYSQL_VAR_VUWJL1;

    RETURN MYSQL_VAR_KYFQC9;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DFID95----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DFID95(A INT, B INT) RETURNS INT
BEGIN
RETURN A + B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LY8IXF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LY8IXF(A INT, B INT, C INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_88CD4J DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_YA61UO DECIMAL(10,2) DEFAULT 0.00;

    IF A + B <= C OR B + C <= A OR A + C <= B THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_88CD4J = MYSQL_FUNC_DFID95(30, 31);
    SET MYSQL_VAR_YA61UO = MYSQL_FUNC_36NBNB(10);

    RETURN FLOOR(MYSQL_VAR_YA61UO);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ENB4I7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ENB4I7(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3RHDU4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZBDLVQ INT DEFAULT N;
    DECLARE MYSQL_VAR_MAPY5G INT DEFAULT 0;

    WHILE N > 0 DO
        SET MYSQL_VAR_MAPY5G = N % 10;
        SET MYSQL_VAR_3RHDU4 = MYSQL_VAR_3RHDU4 * 10 + MYSQL_VAR_MAPY5G;
        SET N = N / 10;
    END WHILE;

    IF MYSQL_VAR_3RHDU4 = MYSQL_VAR_ZBDLVQ THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1QDZNH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1QDZNH(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5A13VY DECIMAL(5,1) DEFAULT 0.0;

    SELECT COALESCE(TIMESTAMPDIFF(YEAR, START_DATE, CURDATE()), 0)
    INTO MYSQL_VAR_5A13VY
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_ENB4I7(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_43JHI4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_43JHI4(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KZ6CIC DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_KZ6CIC
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_KZ6CIC / 5.0) * 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2D730N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2D730N(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4MZJW5 DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_4MZJW5
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_4MZJW5 * 20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BHAJTX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BHAJTX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OII7AG INT DEFAULT 0;
    DECLARE MYSQL_VAR_5YQLY0 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_O7XAIV DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_T7DZN6 INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_OII7AG, MYSQL_VAR_5YQLY0
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    IF MYSQL_VAR_OII7AG = 0 THEN
        RETURN 1;
    END IF;

    SET MYSQL_VAR_O7XAIV = MYSQL_VAR_5YQLY0 / MYSQL_VAR_OII7AG;

    IF MYSQL_VAR_O7XAIV > 500 THEN
        SET MYSQL_VAR_T7DZN6 = 5;
    ELSEIF MYSQL_VAR_O7XAIV > 200 THEN
        SET MYSQL_VAR_T7DZN6 = 4;
    ELSEIF MYSQL_VAR_O7XAIV > 100 THEN
        SET MYSQL_VAR_T7DZN6 = 3;
    ELSEIF MYSQL_VAR_O7XAIV > 50 THEN
        SET MYSQL_VAR_T7DZN6 = 2;
    ELSE
        SET MYSQL_VAR_T7DZN6 = 1;
    END IF;

    RETURN MYSQL_VAR_T7DZN6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MEXPPR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MEXPPR(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HJ4E1W DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_HJ4E1W
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_HJ4E1W / 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3BU19K----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3BU19K(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OOQG3X DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_ERBH84 INT DEFAULT 0;
    DECLARE MYSQL_VAR_RVZSPA INT DEFAULT 0;
    DECLARE MYSQL_VAR_4ZXFEB INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_OOQG3X, MYSQL_VAR_ERBH84
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT MYSQL_FUNC_2D730N(10)
    INTO MYSQL_VAR_RVZSPA
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_4ZXFEB = MYSQL_FUNC_BHAJTX(20);

    RETURN MYSQL_FUNC_MEXPPR(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UKF8QD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UKF8QD(BOOKING_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M9QDIK INT DEFAULT 0;
    DECLARE MYSQL_VAR_EAAQF4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_3YE16H INT DEFAULT 75;
    DECLARE MYSQL_VAR_4GSQHR VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_S68ZJY INT DEFAULT 0;

    SELECT MYSQL_FUNC_LY8IXF(10, 11, 12)
    INTO MYSQL_VAR_M9QDIK, MYSQL_VAR_EAAQF4
    FROM GOLF_COURSE_BOOKINGS
    WHERE BOOKING_ID = BOOKING_ID_PARAM;

    SELECT MYSQL_FUNC_3BU19K(30)
    INTO MYSQL_VAR_4GSQHR
    FROM GOLF_COURSE_BOOKINGS GCB
    JOIN MEMBERS M ON GCB.MEMBER_ID = M.MEMBER_ID
    WHERE GCB.BOOKING_ID = BOOKING_ID_PARAM;

    IF MYSQL_VAR_4GSQHR = 'PREMIUM' THEN
        SET MYSQL_VAR_3YE16H = MYSQL_VAR_3YE16H - 25;
    END IF;

    SET MYSQL_VAR_S68ZJY = MYSQL_FUNC_43JHI4(30);

    RETURN MYSQL_FUNC_1QDZNH(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LBIJLR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LBIJLR(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SEKNO0 DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_YWF5IC DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_QQQYU1 INT DEFAULT 0;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_SEKNO0
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(STDDEV(SALARY), 0) / 1000
    INTO MYSQL_VAR_YWF5IC
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_QQQYU1 = (MYSQL_VAR_SEKNO0 * 15) - (MYSQL_VAR_YWF5IC * 5);

    RETURN GREATEST(MYSQL_VAR_QQQYU1, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LTQ4E4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LTQ4E4(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JMMGWD INT DEFAULT 0;

    SELECT CUSTOMER_ID
    INTO MYSQL_VAR_JMMGWD
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_JMMGWD % 50;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MM0IKF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MM0IKF(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6DGIJT INT DEFAULT 0;
    DECLARE MYSQL_VAR_DIKRBY INT DEFAULT 1;

    SELECT MYSQL_FUNC_LTQ4E4(10)
    INTO MYSQL_VAR_6DGIJT, MYSQL_VAR_DIKRBY
    FROM CUSTOMERS C
    LEFT JOIN SUBSCRIPTIONS S ON C.CUSTOMER_ID = S.CUSTOMER_ID AND S.STATUS = 'ACTIVE'
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN (MYSQL_VAR_6DGIJT * 100) / MYSQL_VAR_DIKRBY;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XLN2XT(ACCOUNT_ID_PARAM INT, AMOUNT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DQQ6FI INT DEFAULT 0;
    DECLARE MYSQL_VAR_QPUM5C INT DEFAULT 0;
    DECLARE MYSQL_VAR_5SW4IU INT DEFAULT 0;
    DECLARE MYSQL_VAR_1IL3FF INT DEFAULT 0;

    

    SELECT MYSQL_FUNC_LBIJLR(30)
    INTO MYSQL_VAR_DQQ6FI, MYSQL_VAR_QPUM5C
    FROM ACCOUNTS
    WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM;

    SET MYSQL_VAR_5SW4IU = MYSQL_FUNC_MM0IKF('test_1_0');

    IF MYSQL_VAR_5SW4IU >= AMOUNT THEN
        SET MYSQL_VAR_1IL3FF = 1;
    ELSE
        SET MYSQL_VAR_1IL3FF = 0;
    END IF;

    RETURN MYSQL_FUNC_UKF8QD(30);
END//

DELIMITER ;