/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_BRJX12----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BRJX12(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_28JNKU INT DEFAULT 0;

    DECLARE CONTINUE HANDLER FOR SQLSTATE '22012' BEGIN SET MYSQL_VAR_28JNKU = 0; END;
    DECLARE CONTINUE HANDLER FOR SQLSTATE '2201I' BEGIN SET MYSQL_VAR_28JNKU = 0; END;

    IF B = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_28JNKU = A / B;

    RETURN MYSQL_VAR_28JNKU;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XTHE6M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XTHE6M(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PGFPKJ DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0)
    INTO MYSQL_VAR_PGFPKJ
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_PGFPKJ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ILACKF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ILACKF(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_22RI5E DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_XTHE6M(30) - (0) + COALESCE(COALESCE(AVG(SALARY), 0), 0))
    INTO MYSQL_VAR_22RI5E
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_22RI5E / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P7D01M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P7D01M(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N8574Y INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_N8574Y
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN (MYSQL_FUNC_ILACKF(30) - (0) + COALESCE(MYSQL_VAR_N8574Y, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YUB8VG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YUB8VG(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UB1EEM INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_UB1EEM
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_UB1EEM;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8VIS2N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8VIS2N(STORE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XG8FLF INT DEFAULT 0;
    DECLARE MYSQL_VAR_PIFH7D INT DEFAULT 0;
    DECLARE MYSQL_VAR_LXSCL8 INT DEFAULT 0;

    SELECT COUNT(*) INTO MYSQL_VAR_XG8FLF
    FROM TRANSACTIONS
    WHERE STORE_ID = STORE_ID_PARAM
      AND TRANSACTION_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SELECT COUNT(*) INTO MYSQL_VAR_PIFH7D
    FROM RETAIL_RETURNS R
    JOIN TRANSACTIONS T ON R.TRANSACTION_ID = T.TRANSACTION_ID
    WHERE T.STORE_ID = STORE_ID_PARAM
      AND R.RETURN_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    IF MYSQL_VAR_XG8FLF = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_LXSCL8 = (MYSQL_VAR_PIFH7D * 100) / MYSQL_VAR_XG8FLF;

    RETURN CAST(MYSQL_VAR_LXSCL8 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_W6569M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_W6569M() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_463QXV INT DEFAULT 0;
    SELECT COUNT(*) INTO MYSQL_VAR_463QXV FROM TABLE_SXJKDS.`TABLE3`;
    RETURN MYSQL_VAR_463QXV;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_E3X50X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_E3X50X(N INT) RETURNS INT
BEGIN
IF N > 0 THEN
        RETURN 1;
    END IF;
    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GVU2OC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GVU2OC(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CUJ73B INT DEFAULT 0;
    DECLARE MYSQL_VAR_CAMSCT INT DEFAULT 0;
    DECLARE MYSQL_VAR_290XDR INT DEFAULT 0;

    SELECT (MYSQL_FUNC_E3X50X(20) - (0) + COALESCE(COUNT(DISTINCT PRODUCT_ID), COALESCE(SUM(QUANTITY), 0), 0))
    INTO MYSQL_VAR_CUJ73B, MYSQL_VAR_CAMSCT
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_CAMSCT = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_290XDR = MYSQL_FUNC_8VIS2N(10);

    RETURN (MYSQL_FUNC_W6569M() - (0) + COALESCE(MYSQL_VAR_290XDR, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AUY523----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AUY523(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GKH7OL INT DEFAULT 0;
    DECLARE MYSQL_VAR_3YYJG6 DECIMAL(5,2) DEFAULT 0.00;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_GKH7OL
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_3YYJG6
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 7 DAY));

    IF MYSQL_VAR_GKH7OL = 0 THEN
        RETURN 999;
    END IF;

    RETURN (MYSQL_FUNC_GVU2OC(30) - (0) + COALESCE(FLOOR((MYSQL_VAR_3YYJG6 / MYSQL_VAR_GKH7OL) * 100), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XWX4IS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XWX4IS(ORDER_ID_PARAM INT, ZONE_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_L2LI85 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JCV9ZF INT DEFAULT 500;
    DECLARE MYSQL_VAR_9MBLZA INT DEFAULT 0;
    DECLARE MYSQL_VAR_5VIC9O INT DEFAULT 0;

    SELECT COALESCE(WEIGHT, 0) INTO MYSQL_VAR_L2LI85
    FROM SHIPPING
    WHERE ORDER_ID = ORDER_ID_PARAM;

    CASE ZONE_PARAM
        WHEN 1 THEN SET MYSQL_VAR_9MBLZA = 0;
        WHEN 2 THEN SET MYSQL_VAR_9MBLZA = 100;
        WHEN 3 THEN SET MYSQL_VAR_9MBLZA = 200;
        WHEN 4 THEN SET MYSQL_VAR_9MBLZA = 300;
        ELSE SET MYSQL_VAR_9MBLZA = 500;
    END CASE;

    SET MYSQL_VAR_5VIC9O = MYSQL_VAR_JCV9ZF + (MYSQL_VAR_L2LI85 * 10) + MYSQL_VAR_9MBLZA;

    RETURN MYSQL_VAR_5VIC9O;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IAX85K----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IAX85K(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VYRDM9 INT DEFAULT 0;

    SELECT MONTH(HIRE_DATE)
    INTO MYSQL_VAR_VYRDM9
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_VAR_VYRDM9;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EVKI4E----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EVKI4E(SET_OF_LETTERS INT, WTABLE_YG6POCD INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RCHZDH VARCHAR(50);
    DECLARE MYSQL_VAR_09T4VD VARCHAR(50);
    
    SET MYSQL_VAR_RCHZDH = CAST(SET_OF_LETTERS AS CHAR);
    SET MYSQL_VAR_09T4VD = CAST(WTABLE_YG6POCD AS CHAR);
    
    RETURN (SELECT MYSQL_VAR_09T4VD REGEXP MYSQL_VAR_RCHZDH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z12240----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z12240(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ITLGWV INT DEFAULT 999;
    DECLARE MYSQL_VAR_EYRK74 DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_022LWQ INT DEFAULT 0;

    SELECT DATEDIFF(CURDATE(), MAX(ORDER_DATE))
    INTO MYSQL_VAR_ITLGWV
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_EVKI4E(30, 31) - (0) + COALESCE(COUNT(*) / GREATEST(DATEDIFF(CURDATE(), MIN(ORDER_DATE)) / 30, 1), 0))
    INTO MYSQL_VAR_EYRK74
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_022LWQ = LEAST(MYSQL_VAR_ITLGWV / 7 * 10, 100) - (MYSQL_VAR_EYRK74 * 15);

    RETURN GREATEST(MYSQL_VAR_022LWQ, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NSW71L----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NSW71L(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RFEBS3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_UW04BA INT DEFAULT 1;
    DECLARE MYSQL_VAR_SJ2S8A INT DEFAULT 0;
    DECLARE MYSQL_VAR_0XPY2O INT DEFAULT 2;
    DECLARE MYSQL_VAR_28CILA INT DEFAULT 0;

    IF N = 0 THEN RETURN 0; END IF;
    IF N = 1 THEN RETURN 1; END IF;

    SET MYSQL_VAR_0XPY2O = 2;

    FIB_LOOP: WHILE MYSQL_VAR_0XPY2O <= N DO
        SET MYSQL_VAR_28CILA = MYSQL_VAR_UW04BA;
        SET MYSQL_VAR_UW04BA = MYSQL_VAR_RFEBS3 + MYSQL_VAR_UW04BA;
        SET MYSQL_VAR_RFEBS3 = MYSQL_VAR_28CILA;
        SET MYSQL_VAR_0XPY2O = MYSQL_VAR_0XPY2O + 1;
    END WHILE FIB_LOOP;

    RETURN MYSQL_VAR_UW04BA;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5EI3CR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5EI3CR(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HAC7E6 VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_BH5F35 VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_AL21M5 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_IAX85K(10) - (0) + COALESCE(PLAN_TYPE, 0))
    INTO MYSQL_VAR_HAC7E6
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_XWX4IS(10, 11) - (0) + COALESCE(TIER_LEVEL, 0))
    INTO MYSQL_VAR_BH5F35
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    CASE MYSQL_VAR_HAC7E6
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_AL21M5 = 100;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_Z12240(30);
        WHEN 'BASIC' THEN SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_NSW71L(30);
        ELSE SET MYSQL_VAR_AL21M5 = 10;
    END CASE;

    CASE MYSQL_VAR_BH5F35
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_AUY523(20);
        WHEN 'GOLD' THEN SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_YUB8VG('test_0_0');
        WHEN 'SILVER' THEN SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_P7D01M(30);
    END CASE;

    RETURN MYSQL_VAR_AL21M5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_X5NGOX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_X5NGOX(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LTXORX DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_53SF0K INT DEFAULT 0;
    DECLARE MYSQL_VAR_K3USEH INT DEFAULT 0;
    DECLARE MYSQL_VAR_VQSLQ1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZAW8V6 DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_XT3Q12 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_5EI3CR(10) - (0) + COALESCE(COALESCE(GPA, 0.00), MAJOR_ID, 0))
    INTO MYSQL_VAR_LTXORX, MYSQL_VAR_53SF0K
    FROM STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SELECT DEPARTMENT_ID
    INTO MYSQL_VAR_K3USEH
    FROM MAJORS
    WHERE MAJOR_ID = MYSQL_VAR_53SF0K;

    SELECT COUNT(*), COALESCE(AVG(S.GPA), 0.00)
    INTO MYSQL_VAR_VQSLQ1, MYSQL_VAR_ZAW8V6
    FROM STUDENTS S
    JOIN MAJORS M ON S.MAJOR_ID = M.MAJOR_ID
    WHERE M.DEPARTMENT_ID = MYSQL_VAR_K3USEH;

    IF MYSQL_VAR_LTXORX > MYSQL_VAR_ZAW8V6 THEN
        SET MYSQL_VAR_XT3Q12 = ((MYSQL_VAR_LTXORX - MYSQL_VAR_ZAW8V6) * 100) + (MYSQL_VAR_VQSLQ1 * 2);
    ELSE
        SET MYSQL_VAR_XT3Q12 = (MYSQL_VAR_LTXORX * 100) / GREATEST(MYSQL_VAR_ZAW8V6, 1);
    END IF;

    RETURN FLOOR(MYSQL_VAR_XT3Q12);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_X9GNT9(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LLO5CS INT DEFAULT 0;

    SELECT (MYSQL_FUNC_X5NGOX(20) - (0) + COALESCE(TIMESTAMPDIFF(DAY, REGISTRATION_DATE, CURDATE()), 0))
    INTO MYSQL_VAR_LLO5CS
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_BRJX12(30, 31) - (0) + COALESCE(MYSQL_VAR_LLO5CS, 0));
END//

DELIMITER ;