/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_r2pva5 (
    name VARCHAR(50)
);
INSERT INTO table_r2pva5 (name) VALUES 
('Sofia'),
('Plovdiv'),
('Varna'),
('Burgas'),
('Stara Zagora'),
('Pleven'),
('Ruse'),
('Shumen'),
('Sliven'),
('Smolyan');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_YBC99J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YBC99J(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZYH2SV INT DEFAULT 0;
    DECLARE MYSQL_VAR_D5LKLV DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_I0R0Q0 DECIMAL(10,2) DEFAULT 0.00;

    SELECT DEPARTMENT_ID, COALESCE(SALARY, 0)
    INTO MYSQL_VAR_ZYH2SV, MYSQL_VAR_D5LKLV
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_I0R0Q0
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = MYSQL_VAR_ZYH2SV;

    RETURN FLOOR((MYSQL_VAR_D5LKLV * 100) / MYSQL_VAR_I0R0Q0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WRS0ES----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WRS0ES(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_P4GHXD VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_FFTBLF INT DEFAULT 0;
    DECLARE MYSQL_VAR_KFI3WP INT DEFAULT 0;
    DECLARE MYSQL_VAR_6VC1R6 INT DEFAULT 0;

    SELECT STATUS, COALESCE(BUDGET, 0), DATEDIFF(CURDATE(), START_DATE)
    INTO MYSQL_VAR_P4GHXD, MYSQL_VAR_FFTBLF, MYSQL_VAR_KFI3WP
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_6VC1R6
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_P4GHXD != 'ACTIVE' OR MYSQL_VAR_KFI3WP = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_6VC1R6 * 100) / (MYSQL_VAR_FFTBLF * MYSQL_VAR_KFI3WP);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XPYY7D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XPYY7D(START_STR INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FM8ECE INT DEFAULT 0;
    
    SELECT MYSQL_FUNC_YBC99J(10) INTO MYSQL_VAR_FM8ECE 
    FROM TABLE_R2PVA5 
    WHERE NAME LIKE CONCAT(CAST(START_STR AS CHAR), '%');
    
    RETURN MYSQL_FUNC_WRS0ES(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_255SSF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_255SSF(RES_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8VX5E4 DATE;
    DECLARE MYSQL_VAR_QUP87M DATE;
    DECLARE MYSQL_VAR_IZE4ZC INT DEFAULT 0;

    SELECT CHECK_IN_DATE, CHECK_OUT_DATE
    INTO MYSQL_VAR_8VX5E4, MYSQL_VAR_QUP87M
    FROM RESERVATIONS
    WHERE RES_ID = RES_ID_PARAM;

    IF MYSQL_VAR_8VX5E4 IS NULL OR MYSQL_VAR_QUP87M IS NULL THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_IZE4ZC = DATEDIFF(MYSQL_VAR_QUP87M, MYSQL_VAR_8VX5E4);

    IF MYSQL_VAR_IZE4ZC < 0 THEN
        SET MYSQL_VAR_IZE4ZC = 0;
    END IF;

    RETURN MYSQL_VAR_IZE4ZC;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SKTOIG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SKTOIG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_W0JQFI INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_W0JQFI
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_W0JQFI * 12;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_F0U97D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_F0U97D(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DMJC8C DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_DMJC8C
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_DMJC8C);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KZ1XYH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KZ1XYH(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9LFT29 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_9LFT29
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_9LFT29);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PBRR5J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PBRR5J(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7D0D06 DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_F0U97D(20)
    INTO MYSQL_VAR_7D0D06
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_FUNC_KZ1XYH(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VDPXVG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VDPXVG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2IK9NW INT DEFAULT 0;
    DECLARE MYSQL_VAR_G8DX0C INT DEFAULT 0;
    DECLARE MYSQL_VAR_2LOJWT INT;
    DECLARE MYSQL_VAR_0H0X9Z INT;
    DECLARE MYSQL_VAR_SZ8MBH INT DEFAULT YEAR(CURDATE());
    DECLARE MYSQL_VAR_34X3T6 INT DEFAULT 0;

    SELECT MYSQL_FUNC_PBRR5J(10)
    INTO MYSQL_VAR_2IK9NW, MYSQL_VAR_G8DX0C, MYSQL_VAR_2LOJWT
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_0H0X9Z = MYSQL_VAR_SZ8MBH - MYSQL_VAR_2LOJWT;

    IF MYSQL_VAR_0H0X9Z < 0 THEN
        SET MYSQL_VAR_0H0X9Z = 0;
    END IF;

    SET MYSQL_VAR_34X3T6 = MYSQL_FUNC_255SSF(10);

    RETURN MYSQL_FUNC_SKTOIG(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VSIF2U----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VSIF2U(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BEXW7V INT DEFAULT 0;

    SELECT YEAR(ORDER_DATE)
    INTO MYSQL_VAR_BEXW7V
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_BEXW7V;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_41B7HC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_41B7HC(ACCOUNT_ID_PARAM INT, MIN_AMOUNT INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EOV6ZK INT DEFAULT 0;
    DECLARE MYSQL_VAR_46RDFZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_UGV6FH INT DEFAULT 0;
    DECLARE MYSQL_VAR_U1LNJX INT DEFAULT 0;
    DECLARE MYSQL_VAR_NQ4YDM INT DEFAULT 0;

    SELECT COALESCE(SUM(AMOUNT), 0), COUNT(*)
    INTO MYSQL_VAR_46RDFZ, MYSQL_VAR_U1LNJX
    FROM TRANSACTIONS
    WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM
      AND TRANSACTION_TYPE = 'CREDIT'
      AND AMOUNT >= MIN_AMOUNT;

    SELECT COALESCE(SUM(AMOUNT), 0)
    INTO MYSQL_VAR_EOV6ZK
    FROM TRANSACTIONS
    WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM
      AND TRANSACTION_TYPE = 'DEBIT';

    SELECT BALANCE INTO MYSQL_VAR_NQ4YDM FROM ACCOUNTS WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM;

    SET MYSQL_VAR_UGV6FH = MYSQL_VAR_46RDFZ - MYSQL_VAR_EOV6ZK;

    RETURN COALESCE(MYSQL_VAR_NQ4YDM, 0) + MYSQL_VAR_UGV6FH;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UVRUZM(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RWE2ZG INT DEFAULT 0;
    DECLARE MYSQL_VAR_N6PPCT INT DEFAULT 0;
    DECLARE MYSQL_VAR_CIH2P8 INT DEFAULT 0;

    SELECT MYSQL_FUNC_XPYY7D(20)
    INTO MYSQL_VAR_RWE2ZG
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT MYSQL_FUNC_41B7HC(10, 11)
    INTO MYSQL_VAR_N6PPCT
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_RWE2ZG = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_CIH2P8 = MYSQL_FUNC_VSIF2U(20);

    RETURN MYSQL_FUNC_VDPXVG(20);
END//

DELIMITER ;