/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_4EEBVL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4EEBVL(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D5CYB4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_A08NE3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_K1M7V7 INT DEFAULT 0;

    SELECT SALARY, DEPARTMENT_ID
    INTO MYSQL_VAR_D5CYB4, MYSQL_VAR_K1M7V7
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COUNT(*) + 1
    INTO MYSQL_VAR_A08NE3
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = MYSQL_VAR_K1M7V7 AND SALARY > MYSQL_VAR_D5CYB4;

    RETURN MYSQL_VAR_A08NE3;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_978Q2P----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_978Q2P(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_12O101 INT DEFAULT 0;
    DECLARE MYSQL_VAR_6XJDDK INT DEFAULT 0;
    DECLARE MYSQL_VAR_QWO69T INT DEFAULT 5;
    DECLARE MYSQL_VAR_5M7JNX INT DEFAULT 0;
    DECLARE MYSQL_VAR_X9H0EG INT DEFAULT 0;

    SELECT COALESCE(S.TOTAL_AMOUNT, 0), COALESCE(S.SHIPPING_COST, 0)
    INTO MYSQL_VAR_6XJDDK, MYSQL_VAR_12O101
    FROM ORDERS O
    JOIN SHIPMENTS S ON O.ORDER_ID = S.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SELECT DATEDIFF(COALESCE(S.ACTUAL_DELIVERY, CURDATE()), S.ESTIMATED_DELIVERY)
    INTO MYSQL_VAR_5M7JNX
    FROM SHIPMENTS S
    WHERE S.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_X9H0EG = 100 - ((MYSQL_VAR_12O101 * 100) / GREATEST(MYSQL_VAR_6XJDDK, 1)) - (MYSQL_VAR_5M7JNX * 10);

    RETURN GREATEST(MYSQL_VAR_X9H0EG, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KXTD7Q----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KXTD7Q(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_0QNBWQ DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_YQIJ2Q INT DEFAULT 0;

    SELECT (MYSQL_FUNC_978Q2P(20) - (0) + COALESCE(COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7), 0))
    INTO MYSQL_VAR_0QNBWQ, MYSQL_VAR_YQIJ2Q
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_4EEBVL(20) - (0) + COALESCE((MYSQL_VAR_YQIJ2Q * 10) - (MYSQL_VAR_0QNBWQ * 15), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2NQFSW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2NQFSW(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PNULD7 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4OHDBR DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_PNULD7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_4OHDBR
    FROM EMPLOYEES;

    RETURN FLOOR((MYSQL_VAR_PNULD7 * 100) / MYSQL_VAR_4OHDBR);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_R8K8RL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_R8K8RL(INPUT_STRING VARCHAR(255)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Q5M2YQ INT DEFAULT 0;
    SET MYSQL_VAR_Q5M2YQ = MYSQL_FUNC_2NQFSW(30);
    RETURN MYSQL_VAR_Q5M2YQ;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DFTGHY(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_S5ZO04 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_R8K8RL('test_2_0') - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_S5ZO04
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID_PARAM;

    RETURN (MYSQL_FUNC_KXTD7Q(10) - (0) + COALESCE(MYSQL_VAR_S5ZO04, 0));
END//

DELIMITER ;