/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_72QXGW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_72QXGW(A INT, B INT) RETURNS INT
BEGIN
IF B = 0 THEN
        RETURN 0;
    END IF;
    RETURN A / B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1QDZNH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1QDZNH(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5A13VY DECIMAL(5,1) DEFAULT 0.0;

    SELECT COALESCE(TIMESTAMPDIFF(YEAR, START_DATE, CURDATE()), 0)
    INTO MYSQL_VAR_5A13VY
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_5A13VY);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GA85T5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GA85T5(ARR_SIZE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HKREKI INT DEFAULT -2147483648;
    DECLARE MYSQL_VAR_FGZ7MG INT DEFAULT 1;
    DECLARE MYSQL_VAR_LNYNI3 INT;

    IF ARR_SIZE <= 0 THEN
        RETURN 0;
    END IF;

    SAMPLE_LOOP: WHILE MYSQL_VAR_FGZ7MG <= ARR_SIZE DO
        SET MYSQL_VAR_LNYNI3 = FLOOR(1 + RAND() * 1000);
        IF MYSQL_VAR_LNYNI3 > MYSQL_VAR_HKREKI THEN
            SET MYSQL_VAR_HKREKI = MYSQL_VAR_LNYNI3;
        END IF;
        SET MYSQL_VAR_FGZ7MG = MYSQL_VAR_FGZ7MG + 1;
    END WHILE SAMPLE_LOOP;

    RETURN MYSQL_FUNC_1QDZNH(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3VB4SS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3VB4SS(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N6I45M DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_N6I45M
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_N6I45M / 5.0) * 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KSMH8W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KSMH8W(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5QNS4E DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_3VB4SS(20)
    INTO MYSQL_VAR_5QNS4E
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_FUNC_GA85T5(10);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FFGECQ(PAGE_COUNT_PARAM INT, QUANTITY_PARAM INT, COLOR_MODE_PARAM VARCHAR(10)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QS8COS INT DEFAULT 1;
    DECLARE MYSQL_VAR_YRFL8R INT DEFAULT 3;
    DECLARE MYSQL_VAR_MQ8Q8Q INT DEFAULT 0;
    DECLARE MYSQL_VAR_8XUV7U INT DEFAULT 0;

    IF COLOR_MODE_PARAM = 'COLOR' THEN
        SET MYSQL_VAR_QS8COS = MYSQL_VAR_QS8COS * MYSQL_VAR_YRFL8R;
    END IF;

    SET MYSQL_VAR_8XUV7U = PAGE_COUNT_PARAM * QUANTITY_PARAM * MYSQL_VAR_QS8COS;

    IF QUANTITY_PARAM >= 100 THEN
        SET MYSQL_VAR_MQ8Q8Q = MYSQL_VAR_8XUV7U * 20 / 100;
    ELSEIF QUANTITY_PARAM >= 50 THEN
        SET MYSQL_VAR_MQ8Q8Q = MYSQL_VAR_8XUV7U * 10 / 100;
    END IF;

    SET MYSQL_VAR_8XUV7U = MYSQL_FUNC_KSMH8W(30);

    RETURN MYSQL_FUNC_72QXGW(30, 31);
END//

DELIMITER ;