/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_H5BE6P----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H5BE6P(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PDK9M0 DATE;

    SELECT START_DATE
    INTO MYSQL_VAR_PDK9M0
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_PDK9M0 IS NULL THEN
        RETURN 0;
    END IF;

    RETURN TIMESTAMPDIFF(MONTH, MYSQL_VAR_PDK9M0, CURDATE());
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Y2DM37----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Y2DM37(STUDENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_31XSR2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_OQP7TW INT DEFAULT 0;
    DECLARE MYSQL_VAR_SUTCJE INT DEFAULT 0;
    DECLARE MYSQL_VAR_YR24H8 INT DEFAULT 0;

    SELECT COALESCE(EXAM_SCORE, 0), COALESCE(ASSIGNMENT_SCORE, 0), COALESCE(PARTICIPATION_SCORE, 0)
    INTO MYSQL_VAR_31XSR2, MYSQL_VAR_OQP7TW, MYSQL_VAR_SUTCJE
    FROM STUDENTS
    WHERE STUDENT_ID = STUDENT_ID_PARAM;

    SET MYSQL_VAR_YR24H8 = (MYSQL_VAR_31XSR2 * 50 / 100) + (MYSQL_VAR_OQP7TW * 40 / 100) + (MYSQL_VAR_SUTCJE * 10 / 100);

    RETURN CAST(MYSQL_VAR_YR24H8 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P6XMEJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P6XMEJ(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_600HP9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_K8EX72 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_0QKRVH DECIMAL(5,2) DEFAULT 0.00;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_600HP9
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_H5BE6P(30) - (0) + COALESCE(COALESCE(SUM(CONVERSION_VALUE), 0), 0))
    INTO MYSQL_VAR_K8EX72
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_600HP9 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0QKRVH = MYSQL_FUNC_Y2DM37(20);

    RETURN FLOOR(MYSQL_VAR_0QKRVH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_T7ESRQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_T7ESRQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9P5BW5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_VZ8EOU INT DEFAULT 0;
    DECLARE MYSQL_VAR_4PZL1U INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_9P5BW5
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COALESCE(DATEDIFF(CURDATE(), MAX(ORDER_DATE)), 0)
    INTO MYSQL_VAR_VZ8EOU
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_9P5BW5 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_4PZL1U = 100 - LEAST((MYSQL_VAR_VZ8EOU * 5) + (100 / MYSQL_VAR_9P5BW5), 100);

    RETURN GREATEST(MYSQL_VAR_4PZL1U, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J0RFZI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J0RFZI(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SKTA14 INT DEFAULT 0;
    DECLARE MYSQL_VAR_45VA2I INT DEFAULT 0;
    DECLARE MYSQL_VAR_0TUR76 INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_SKTA14
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(REFUND_AMOUNT), 0)
    INTO MYSQL_VAR_45VA2I
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_SKTA14 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0TUR76 = (MYSQL_VAR_45VA2I * 100) / MYSQL_VAR_SKTA14;

    RETURN MYSQL_VAR_0TUR76;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HCKJN3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HCKJN3() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VWQ4NB INT;
    SELECT (MYSQL_FUNC_J0RFZI(30) - (0) + COALESCE(`CTIME`, 0)) INTO MYSQL_VAR_VWQ4NB FROM TABLE_VCQVOQ.`TABLE3`;
    RETURN (MYSQL_FUNC_T7ESRQ(30) - (0) + COALESCE(MYSQL_VAR_VWQ4NB, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1H5P1O(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FBBT6K DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_THBSH3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_8W2J3E DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_HCKJN3() - (0) + COALESCE(COALESCE(PRICE, 0), COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_FBBT6K, MYSQL_VAR_THBSH3
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(AVG(P.STOCK_QUANTITY * P.PRICE), 0)
    INTO MYSQL_VAR_8W2J3E
    FROM PRODUCTS P
    WHERE P.CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    IF MYSQL_VAR_8W2J3E = 0 THEN
        RETURN 100;
    END IF;

    RETURN (MYSQL_FUNC_P6XMEJ(20) - (0) + COALESCE(FLOOR((MYSQL_VAR_FBBT6K * MYSQL_VAR_THBSH3 * 100) / MYSQL_VAR_8W2J3E), 0));
END//

DELIMITER ;