/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_MU772T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MU772T(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_13B3VK INT DEFAULT 0;
    DECLARE MYSQL_VAR_A1JH4U INT DEFAULT 1;

    SELECT COUNT(*), COUNT(DISTINCT CUSTOMER_ID)
    INTO MYSQL_VAR_13B3VK, MYSQL_VAR_A1JH4U
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_VAR_13B3VK * 100) / MYSQL_VAR_A1JH4U;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_T51PQP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_T51PQP(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EL0R2P DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_YGBDXU INT DEFAULT 0;

    SELECT COALESCE(SALARY, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_EL0R2P, MYSQL_VAR_YGBDXU
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_EL0R2P * MYSQL_VAR_YGBDXU) / 10000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CC5T7F----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CC5T7F(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GIJYV1 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_VV1ERB INT DEFAULT 0;

    SELECT MYSQL_FUNC_MU772T(20)
    INTO MYSQL_VAR_GIJYV1, MYSQL_VAR_VV1ERB
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_FUNC_T51PQP(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RKDNDI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RKDNDI(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NAGXOD INT DEFAULT 0;

    SELECT TIMESTAMPDIFF(YEAR, REGISTRATION_DATE, CURDATE())
    INTO MYSQL_VAR_NAGXOD
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_NAGXOD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_18IJYS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_18IJYS(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MC3L1T INT DEFAULT 0;
    DECLARE MYSQL_VAR_64V8TK INT DEFAULT 0;
    DECLARE MYSQL_VAR_EKRCI0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_1LA9BV INT DEFAULT 0;
    DECLARE MYSQL_VAR_LCZ1G8 INT DEFAULT 0;

    SELECT MYSQL_FUNC_RKDNDI(20)
    INTO MYSQL_VAR_MC3L1T, MYSQL_VAR_64V8TK
    FROM ORDERS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_64V8TK = 0 THEN
        RETURN 0;
    END IF;

    SELECT DATEDIFF(CURDATE(), MAX(ORDER_DATE))
    INTO MYSQL_VAR_1LA9BV
    FROM ORDERS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_EKRCI0 = MYSQL_VAR_MC3L1T / MYSQL_VAR_64V8TK;

    SET MYSQL_VAR_LCZ1G8 = (MYSQL_VAR_64V8TK * 10) + (MYSQL_VAR_EKRCI0 * 5);

    IF MYSQL_VAR_1LA9BV <= 7 THEN
        SET MYSQL_VAR_LCZ1G8 = MYSQL_VAR_LCZ1G8 + 20;
    ELSEIF MYSQL_VAR_1LA9BV <= 30 THEN
        SET MYSQL_VAR_LCZ1G8 = MYSQL_VAR_LCZ1G8 + 10;
    ELSEIF MYSQL_VAR_1LA9BV > 90 THEN
        SET MYSQL_VAR_LCZ1G8 = MYSQL_VAR_LCZ1G8 - 30;
    END IF;

    RETURN MYSQL_VAR_LCZ1G8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_X3T384----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_X3T384(LISTING_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_B9HDKS INT DEFAULT 0;
    DECLARE MYSQL_VAR_QVMP1S INT DEFAULT 0;
    DECLARE MYSQL_VAR_MD9LWV INT DEFAULT 0;
    DECLARE MYSQL_VAR_E9UMGF INT DEFAULT 0;
    DECLARE MYSQL_VAR_56BM8I INT DEFAULT 0;

    SELECT COALESCE(SALARY_MIN, 0), COALESCE(SALARY_MAX, 0), COUNT(*)
    INTO MYSQL_VAR_B9HDKS, MYSQL_VAR_QVMP1S, MYSQL_VAR_MD9LWV
    FROM JOB_LISTINGS L
    LEFT JOIN JOB_APPLICATIONS A ON L.LISTING_ID = A.LISTING_ID
    WHERE L.LISTING_ID = LISTING_ID_PARAM
    GROUP BY L.LISTING_ID;

    SELECT DATEDIFF(CURDATE(), POSTED_DATE) INTO MYSQL_VAR_E9UMGF
    FROM JOB_LISTINGS
    WHERE LISTING_ID = LISTING_ID_PARAM;

    IF MYSQL_VAR_E9UMGF = 0 THEN
        SET MYSQL_VAR_E9UMGF = 1;
    END IF;

    SET MYSQL_VAR_56BM8I = (MYSQL_VAR_MD9LWV * 100) / MYSQL_VAR_E9UMGF;

    IF MYSQL_VAR_QVMP1S > 100000 THEN
        SET MYSQL_VAR_56BM8I = MYSQL_VAR_56BM8I + 20;
    END IF;

    RETURN MYSQL_FUNC_18IJYS(30);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FDUF1N(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8K1NPL INT DEFAULT 1;
    DECLARE MYSQL_VAR_7GDJXC INT DEFAULT 2;
    DECLARE MYSQL_VAR_QKISZP INT DEFAULT 0;

    IF N <= 1 THEN
        RETURN MYSQL_FUNC_X3T384(30);
    END IF;

    SET MYSQL_VAR_QKISZP = MYSQL_FUNC_CC5T7F(30);

    DIVISOR_LOOP: WHILE MYSQL_VAR_7GDJXC <= MYSQL_VAR_QKISZP DO
        IF N % MYSQL_VAR_7GDJXC = 0 THEN
            SET MYSQL_VAR_8K1NPL = MYSQL_VAR_8K1NPL + MYSQL_VAR_7GDJXC;
            IF MYSQL_VAR_7GDJXC != N / MYSQL_VAR_7GDJXC THEN
                SET MYSQL_VAR_8K1NPL = MYSQL_VAR_8K1NPL + (N / MYSQL_VAR_7GDJXC);
            END IF;
        END IF;
        SET MYSQL_VAR_7GDJXC = MYSQL_VAR_7GDJXC + 1;
    END WHILE DIVISOR_LOOP;

    IF MYSQL_VAR_8K1NPL = N THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;