/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_0GV05Z----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0GV05Z(METER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5WBLZD INT DEFAULT 0;
    DECLARE MYSQL_VAR_2R29OX INT DEFAULT 0;
    DECLARE MYSQL_VAR_N50OFW INT DEFAULT 0;
    DECLARE MYSQL_VAR_SA8JZX INT DEFAULT 25;
    DECLARE MYSQL_VAR_AA3USZ INT DEFAULT 0;

    SELECT COALESCE(CURRENT_READING, 0), COALESCE(PREVIOUS_READING, 0)
    INTO MYSQL_VAR_5WBLZD, MYSQL_VAR_2R29OX
    FROM UTILITY_METERS
    WHERE METER_ID = METER_ID_PARAM;

    SET MYSQL_VAR_N50OFW = MYSQL_VAR_5WBLZD - MYSQL_VAR_2R29OX;

    IF MYSQL_VAR_N50OFW < 0 THEN
        SET MYSQL_VAR_N50OFW = 0;
    END IF;

    SET MYSQL_VAR_AA3USZ = MYSQL_VAR_SA8JZX + (MYSQL_VAR_N50OFW * 3);

    IF MYSQL_VAR_N50OFW > 100 THEN
        SET MYSQL_VAR_AA3USZ = MYSQL_VAR_AA3USZ + ((MYSQL_VAR_N50OFW - 100) * 5);
    END IF;

    RETURN CAST(MYSQL_VAR_AA3USZ AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GWCN0K----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GWCN0K(INVOICE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JZPCII INT DEFAULT 0;
    DECLARE MYSQL_VAR_VPL4BP INT DEFAULT 0;
    DECLARE MYSQL_VAR_IUNGID INT DEFAULT 5;
    DECLARE MYSQL_VAR_B0CNPU INT DEFAULT 0;
    DECLARE MYSQL_VAR_DWSRYR DATE;
    DECLARE MYSQL_VAR_334YEU INT DEFAULT 0;
    DECLARE MYSQL_VAR_KPTG1N INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0), COALESCE(PAID_AMOUNT, 0), DUE_DATE
    INTO MYSQL_VAR_334YEU, MYSQL_VAR_KPTG1N, MYSQL_VAR_DWSRYR
    FROM INVOICES
    WHERE INVOICE_ID = INVOICE_ID_PARAM;

    SET MYSQL_VAR_VPL4BP = MYSQL_VAR_334YEU - MYSQL_VAR_KPTG1N;

    IF MYSQL_VAR_VPL4BP <= 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_JZPCII = DATEDIFF(CURDATE(), MYSQL_VAR_DWSRYR);

    IF MYSQL_VAR_JZPCII <= 0 THEN
        RETURN 0;
    END IF;

    IF MYSQL_VAR_JZPCII > 90 THEN
        SET MYSQL_VAR_IUNGID = 15;
    ELSEIF MYSQL_VAR_JZPCII > 30 THEN
        SET MYSQL_VAR_IUNGID = 10;
    END IF;

    SET MYSQL_VAR_B0CNPU = (MYSQL_VAR_VPL4BP * MYSQL_VAR_IUNGID) / 100;

    RETURN MYSQL_VAR_B0CNPU;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3HNV04(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZUSRCA DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_GWCN0K(20)
    INTO MYSQL_VAR_ZUSRCA
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_FUNC_0GV05Z(10);
END//

DELIMITER ;