/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_SJWMS3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SJWMS3(YEAR_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1JU5VV INT DEFAULT 0;

    IF (YEAR_PARAM % 4 = 0 AND YEAR_PARAM % 100 != 0) OR (YEAR_PARAM % 400 = 0) THEN
        SET MYSQL_VAR_1JU5VV = 1;
    END IF;

    IF MYSQL_VAR_1JU5VV = 1 THEN
        RETURN 366;
    END IF;

    RETURN 365;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BBIAM1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BBIAM1(PROPERTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZTVMF5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_FI3ITY DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_QHJPSF INT DEFAULT 0;
    DECLARE MYSQL_VAR_JC5FU6 INT DEFAULT 2000;
    DECLARE MYSQL_VAR_2ND2IK INT DEFAULT 0;
    DECLARE MYSQL_VAR_I5ZLB5 INT DEFAULT 0;

    SELECT COALESCE(BEDROOMS, 0), COALESCE(BATHROOMS, 1.0), COALESCE(SQUARE_FEET, 1000), COALESCE(YEAR_BUILT, 2000)
    INTO MYSQL_VAR_ZTVMF5, MYSQL_VAR_FI3ITY, MYSQL_VAR_QHJPSF, MYSQL_VAR_JC5FU6
    FROM PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_2ND2IK
    FROM PROPERTY_FEATURES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SET MYSQL_VAR_I5ZLB5 = (MYSQL_VAR_ZTVMF5 * 20) + (MYSQL_VAR_FI3ITY * 15) + (MYSQL_VAR_QHJPSF / 100) + ((2024 - MYSQL_VAR_JC5FU6) * 2) + (MYSQL_VAR_2ND2IK * 10);

    RETURN MYSQL_VAR_I5ZLB5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EPCCKP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EPCCKP(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5XW42R INT DEFAULT 0;

    SELECT (MYSQL_FUNC_BBIAM1(20) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_5XW42R
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN (MYSQL_FUNC_SJWMS3(20) - (0) + COALESCE(MYSQL_VAR_5XW42R, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_A4OHKG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_A4OHKG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AOJO8A INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_AOJO8A
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'ACTIVE';

    RETURN MYSQL_VAR_AOJO8A;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_N0F9GL(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2K3QWZ DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_A4OHKG(30) - (0) + COALESCE(COALESCE(PRICE, 0), 0))
    INTO MYSQL_VAR_2K3QWZ
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN (MYSQL_FUNC_EPCCKP('test_2_0') - (0) + COALESCE(FLOOR(MYSQL_VAR_2K3QWZ), 0));
END//

DELIMITER ;