/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_U4QQDW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_U4QQDW(PART_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZS0PUE INT DEFAULT 0;
    DECLARE MYSQL_VAR_KGKETC INT DEFAULT 0;
    DECLARE MYSQL_VAR_JBXWSR INT DEFAULT 0;
    DECLARE MYSQL_VAR_0MJF62 INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0), COALESCE(REORDER_POINT, 10)
    INTO MYSQL_VAR_ZS0PUE, MYSQL_VAR_KGKETC
    FROM AUTO_PARTS
    WHERE PART_ID = PART_ID_PARAM;

    IF MYSQL_VAR_KGKETC = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0MJF62 = (MYSQL_VAR_ZS0PUE * 100) / MYSQL_VAR_KGKETC;

    CASE
        WHEN MYSQL_VAR_ZS0PUE = 0 THEN SET MYSQL_VAR_JBXWSR = 100;
        WHEN MYSQL_VAR_0MJF62 < 25 THEN SET MYSQL_VAR_JBXWSR = 80;
        WHEN MYSQL_VAR_0MJF62 < 50 THEN SET MYSQL_VAR_JBXWSR = 60;
        WHEN MYSQL_VAR_0MJF62 < 75 THEN SET MYSQL_VAR_JBXWSR = 40;
        WHEN MYSQL_VAR_0MJF62 < 100 THEN SET MYSQL_VAR_JBXWSR = 20;
        ELSE SET MYSQL_VAR_JBXWSR = 0;
    END CASE;

    RETURN MYSQL_VAR_JBXWSR;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GQH2SH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GQH2SH(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QHFK20 INT DEFAULT 0;

    SELECT MYSQL_FUNC_U4QQDW(30)
    INTO MYSQL_VAR_QHFK20
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_VAR_QHFK20;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NAAO5S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NAAO5S(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_96EC7Q VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_9R24K3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_J6ON7W INT DEFAULT 0;

    SELECT PLAN_TYPE, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_96EC7Q, MYSQL_VAR_9R24K3
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    CASE MYSQL_VAR_96EC7Q
        WHEN 'BASIC' THEN SET MYSQL_VAR_J6ON7W = 70;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_J6ON7W = 40;
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_J6ON7W = 10;
        ELSE SET MYSQL_VAR_J6ON7W = 50;
    END CASE;

    SET MYSQL_VAR_J6ON7W = MYSQL_VAR_J6ON7W - (MYSQL_VAR_9R24K3 / 20);

    RETURN GREATEST(MYSQL_VAR_J6ON7W, 5);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7YB6FA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7YB6FA(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z1AJ6I INT DEFAULT 0;
    DECLARE MYSQL_VAR_B3LAGS INT DEFAULT 0;
    DECLARE MYSQL_VAR_GUFF0V INT DEFAULT 0;
    DECLARE MYSQL_VAR_2PZQTP INT DEFAULT 0;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_Z1AJ6I
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COALESCE(NEW_SALARY, MYSQL_VAR_Z1AJ6I)
    INTO MYSQL_VAR_B3LAGS
    FROM SALARIES
    WHERE EMP_ID = EMP_ID_PARAM
    ORDER BY EFFECTIVE_DATE DESC
    LIMIT 1;

    SELECT TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_GUFF0V
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    IF MYSQL_VAR_Z1AJ6I = 0 OR MYSQL_VAR_GUFF0V = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_2PZQTP = (((MYSQL_VAR_B3LAGS - MYSQL_VAR_Z1AJ6I) * 100) / MYSQL_VAR_Z1AJ6I) / MYSQL_VAR_GUFF0V;

    RETURN MYSQL_VAR_2PZQTP;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7A7GZ6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7A7GZ6(AUTHOR_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AB5FHA INT DEFAULT 0;
    DECLARE MYSQL_VAR_HJMECL DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_UED2C5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_XXP5ZJ INT DEFAULT 0;

    SELECT COALESCE(TOTAL_BOOKS_SOLD, 0)
    INTO MYSQL_VAR_AB5FHA
    FROM AUTHORS
    WHERE AUTHOR_ID = AUTHOR_ID_PARAM;

    SELECT COUNT(*), COALESCE(AVG(AVERAGE_RATING), 0)
    INTO MYSQL_VAR_UED2C5, MYSQL_VAR_HJMECL
    FROM BOOKS
    WHERE AUTHOR_ID = AUTHOR_ID_PARAM;

    SET MYSQL_VAR_XXP5ZJ = (MYSQL_VAR_AB5FHA / 1000) + (MYSQL_VAR_UED2C5 * 10) + (MYSQL_VAR_HJMECL * 15);

    RETURN MYSQL_VAR_XXP5ZJ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HVABBX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HVABBX(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N7JFGF INT DEFAULT 0;
    DECLARE MYSQL_VAR_DLFY8S DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_7YB6FA(10)
    INTO MYSQL_VAR_N7JFGF
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT MYSQL_FUNC_NAAO5S(10)
    INTO MYSQL_VAR_DLFY8S
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_N7JFGF = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_7A7GZ6(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XIBZCF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XIBZCF(PRINCIPAL INT, RATE INT, YEARS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QN595U INT DEFAULT 0;
    DECLARE MYSQL_VAR_IC7F4Q INT DEFAULT 1;
    DECLARE MYSQL_VAR_8D93XU INT DEFAULT 0;

    IF PRINCIPAL <= 0 OR RATE <= 0 OR YEARS <= 0 THEN
        RETURN 0;
    END IF;

    SET_LOOP: WHILE MYSQL_VAR_IC7F4Q <= YEARS DO
        SET_LOOP_INNER: WHILE MYSQL_VAR_IC7F4Q <= 12 DO
            SET MYSQL_VAR_QN595U = MYSQL_VAR_QN595U + (MYSQL_VAR_QN595U * RATE / 100 / 12);
            SET MYSQL_VAR_IC7F4Q = MYSQL_VAR_IC7F4Q + 1;
        END WHILE SET_LOOP_INNER;
        SET MYSQL_VAR_IC7F4Q = MYSQL_VAR_IC7F4Q - 11;
    END WHILE SET_LOOP;

    RETURN CAST(MYSQL_VAR_QN595U AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7H9996----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7H9996() RETURNS INT
BEGIN
RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VXG1JG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VXG1JG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M09T5H DATE;

    SELECT MYSQL_FUNC_7H9996()
    INTO MYSQL_VAR_M09T5H
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_M09T5H IS NULL THEN
        RETURN -1;
    END IF;

    RETURN MYSQL_FUNC_XIBZCF(10, 11, 12);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RO8V5G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RO8V5G(X INT) RETURNS INT
BEGIN
RETURN MYSQL_FUNC_VXG1JG(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Q7UN8B----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Q7UN8B(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PF7YYW DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_61WQCG INT DEFAULT 0;
    DECLARE MYSQL_VAR_LGU1NH INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0), COUNT(*)
    INTO MYSQL_VAR_PF7YYW, MYSQL_VAR_61WQCG
    FROM ORDERS O
    LEFT JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM
    GROUP BY O.ORDER_ID;

    SET MYSQL_VAR_LGU1NH = (MYSQL_VAR_PF7YYW / 100) + (MYSQL_VAR_61WQCG * 5);

    RETURN MYSQL_VAR_LGU1NH;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BM17AU(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QASHBZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_IOK7T8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_I5QUC3 DECIMAL(5,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_Q7UN8B(10)
    INTO MYSQL_VAR_QASHBZ
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT MYSQL_FUNC_RO8V5G(20)
    INTO MYSQL_VAR_IOK7T8
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY));

    IF MYSQL_VAR_IOK7T8 = 0 THEN
        RETURN MYSQL_VAR_QASHBZ;
    END IF;

    SET MYSQL_VAR_I5QUC3 = MYSQL_FUNC_HVABBX(10);

    RETURN MYSQL_FUNC_GQH2SH(20);
END//

DELIMITER ;