/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_73SB2P----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_73SB2P(A INT, B INT) RETURNS INT
BEGIN
IF A > B THEN
        RETURN A;
    END IF;
    RETURN B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PPMX2H----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PPMX2H(NUMBER_ID_PARAM INT, BILLING_MONTH_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DRN9H0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0L00YB INT DEFAULT 0;
    DECLARE MYSQL_VAR_4C1F0I INT DEFAULT 0;
    DECLARE MYSQL_VAR_DVO8CF INT DEFAULT 0;
    DECLARE MYSQL_VAR_LDTAOY INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZU8G30 INT DEFAULT 0;

    SELECT T.MONTHLY_FEE, COALESCE(U.CALL_MINUTES, 0), COALESCE(U.DATA_MB, 0), COALESCE(U.SMS_COUNT, 0)
    INTO MYSQL_VAR_DRN9H0, MYSQL_VAR_0L00YB, MYSQL_VAR_4C1F0I, MYSQL_VAR_DVO8CF
    FROM TELECOM_NUMBERS T
    LEFT JOIN TELECOM_USAGE U ON T.NUMBER_ID = U.NUMBER_ID AND U.BILLING_MONTH = BILLING_MONTH_PARAM
    WHERE T.NUMBER_ID = NUMBER_ID_PARAM;

    SET MYSQL_VAR_LDTAOY = MYSQL_FUNC_73SB2P(10, 11);

    IF MYSQL_VAR_0L00YB > 500 THEN
        SET MYSQL_VAR_ZU8G30 = MYSQL_VAR_0L00YB - 500;
        SET MYSQL_VAR_LDTAOY = MYSQL_VAR_LDTAOY + (MYSQL_VAR_ZU8G30 * 2);
    END IF;

    IF MYSQL_VAR_4C1F0I > 5000 THEN
        SET MYSQL_VAR_LDTAOY = MYSQL_VAR_LDTAOY + ((MYSQL_VAR_4C1F0I - 5000) / 100) * 5;
    END IF;

    RETURN CAST(MYSQL_VAR_LDTAOY AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9FVA7U----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9FVA7U(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4BTBYL INT DEFAULT 0;
    DECLARE MYSQL_VAR_1PJJQY INT DEFAULT 0;

    SELECT SUPPLIER_ID, CATEGORY_ID
    INTO MYSQL_VAR_4BTBYL, MYSQL_VAR_1PJJQY
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN (MYSQL_VAR_4BTBYL + MYSQL_VAR_1PJJQY) % 100;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XIBZCF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XIBZCF(PRINCIPAL INT, RATE INT, YEARS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QN595U INT DEFAULT 0;
    DECLARE MYSQL_VAR_IC7F4Q INT DEFAULT 1;
    DECLARE MYSQL_VAR_8D93XU INT DEFAULT 0;

    IF PRINCIPAL <= 0 OR RATE <= 0 OR YEARS <= 0 THEN
        RETURN 0;
    END IF;

    SET_LOOP: WHILE MYSQL_VAR_IC7F4Q <= YEARS DO
        SET_LOOP_INNER: WHILE MYSQL_VAR_IC7F4Q <= 12 DO
            SET MYSQL_VAR_QN595U = MYSQL_VAR_QN595U + (MYSQL_VAR_QN595U * RATE / 100 / 12);
            SET MYSQL_VAR_IC7F4Q = MYSQL_VAR_IC7F4Q + 1;
        END WHILE SET_LOOP_INNER;
        SET MYSQL_VAR_IC7F4Q = MYSQL_VAR_IC7F4Q - 11;
    END WHILE SET_LOOP;

    RETURN CAST(MYSQL_VAR_QN595U AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KSCS6C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KSCS6C(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_A0OQSY VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_5EIQ0T INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_A0OQSY, MYSQL_VAR_5EIQ0T
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_A0OQSY != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_5EIQ0T * 12;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AC42IH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AC42IH(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9VD6G2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_9UW973 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_KSCS6C(20) - (0) + COALESCE(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), COALESCE(SALARY, 0), 0))
    INTO MYSQL_VAR_9VD6G2, MYSQL_VAR_9UW973
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN (MYSQL_FUNC_XIBZCF(20, 21, 22) - (0) + COALESCE((MYSQL_VAR_9VD6G2 * 1000) + FLOOR(MYSQL_VAR_9UW973 / 1000), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3BU19K----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3BU19K(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OOQG3X DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_ERBH84 INT DEFAULT 0;
    DECLARE MYSQL_VAR_RVZSPA INT DEFAULT 0;
    DECLARE MYSQL_VAR_4ZXFEB INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_OOQG3X, MYSQL_VAR_ERBH84
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_RVZSPA
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_4ZXFEB = (MYSQL_VAR_OOQG3X * 15) + (50 - MYSQL_VAR_ERBH84 * 3) + (MYSQL_VAR_RVZSPA * 2);

    RETURN MYSQL_VAR_4ZXFEB;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_F57EOQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_F57EOQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZHEXU4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_L5FDYV DATE;
    DECLARE MYSQL_VAR_WP56IY DATE;
    DECLARE MYSQL_VAR_FKMNVI INT DEFAULT 0;
    DECLARE MYSQL_VAR_3KZY6P INT DEFAULT 0;

    SELECT COUNT(*), MIN(ORDER_DATE), MAX(ORDER_DATE)
    INTO MYSQL_VAR_ZHEXU4, MYSQL_VAR_L5FDYV, MYSQL_VAR_WP56IY
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_ZHEXU4 < 2 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_FKMNVI = MYSQL_FUNC_3BU19K(20);

    IF MYSQL_VAR_FKMNVI = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_3KZY6P = MYSQL_VAR_FKMNVI / (MYSQL_VAR_ZHEXU4 - 1);

    RETURN MYSQL_VAR_3KZY6P;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ESYX5C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ESYX5C(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4XHYP1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_WW0X11 INT DEFAULT 0;
    DECLARE MYSQL_VAR_VJGWEU INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_4XHYP1, MYSQL_VAR_WW0X11
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_WW0X11 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_VJGWEU = MYSQL_VAR_4XHYP1 / MYSQL_VAR_WW0X11;

    RETURN MYSQL_VAR_VJGWEU;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AVWKFN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AVWKFN(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_R62NOA DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_U00LSC DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_KXZ70A INT DEFAULT 0;

    SELECT (MYSQL_FUNC_F57EOQ(20) - (0) + COALESCE(COALESCE(MAX(P.PRICE * COALESCE(SUM(OI.QUANTITY), 0)), 0), 0))
    INTO MYSQL_VAR_R62NOA
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM
    GROUP BY P.PRODUCT_ID;

    SELECT (MYSQL_FUNC_ESYX5C(10) - (0) + COALESCE(COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_U00LSC
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_U00LSC = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_KXZ70A = (MYSQL_VAR_R62NOA * 100) / MYSQL_VAR_U00LSC;

    RETURN MYSQL_VAR_KXZ70A;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VIXANQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VIXANQ(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_P4O5SJ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_N5JU8M INT DEFAULT 0;
    DECLARE MYSQL_VAR_MLOS0D DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_P4O5SJ
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COUNT(DISTINCT PRODUCT_ID)
    INTO MYSQL_VAR_N5JU8M
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_N5JU8M = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_MLOS0D = MYSQL_FUNC_AC42IH(30);

    RETURN (MYSQL_FUNC_AVWKFN(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_MLOS0D), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OHRCD0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OHRCD0(PLAYLIST_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_A2G3KK INT DEFAULT 0;
    DECLARE MYSQL_VAR_HZYLS2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_24K52R INT DEFAULT 0;
    DECLARE MYSQL_VAR_QINOT5 INT DEFAULT 0;

    SELECT COALESCE(TRACK_COUNT, 0), COALESCE(TOTAL_DURATION, 0)
    INTO MYSQL_VAR_A2G3KK, MYSQL_VAR_HZYLS2
    FROM MUSIC_STREAMING_PLAYLISTS
    WHERE PLAYLIST_ID = PLAYLIST_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_24K52R
    FROM PLAYLIST_FOLLOWERS
    WHERE PLAYLIST_ID = PLAYLIST_ID_PARAM;

    SET MYSQL_VAR_QINOT5 = (MYSQL_VAR_24K52R * 50) + (MYSQL_VAR_A2G3KK * 2) + (MYSQL_VAR_HZYLS2 / 60);

    RETURN CAST(MYSQL_VAR_QINOT5 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DI51P1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DI51P1(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SGZ2TF INT DEFAULT 0;
    DECLARE MYSQL_VAR_S3TN5T INT DEFAULT 0;
    DECLARE MYSQL_VAR_U68HIV INT DEFAULT 0;
    DECLARE MYSQL_VAR_7RL08W INT DEFAULT 0;

    SELECT COALESCE(GOAL_AMOUNT, 1000), COALESCE(RAISED_AMOUNT, 0)
    INTO MYSQL_VAR_SGZ2TF, MYSQL_VAR_S3TN5T
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*), COALESCE(SUM(AMOUNT), 0)
    INTO MYSQL_VAR_U68HIV, MYSQL_VAR_S3TN5T
    FROM CHARITY_DONATIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_SGZ2TF = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_7RL08W = (MYSQL_VAR_S3TN5T * 100) / MYSQL_VAR_SGZ2TF;

    IF MYSQL_VAR_7RL08W > 100 THEN
        SET MYSQL_VAR_7RL08W = 100;
    END IF;

    RETURN CAST(MYSQL_VAR_7RL08W AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GWG7B7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GWG7B7(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KTVOPR VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_VQ0Q3X INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_KTVOPR, MYSQL_VAR_VQ0Q3X
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_KTVOPR != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_VQ0Q3X * 5;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H2ZT22(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_960FG8 VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_TQJ21L INT DEFAULT 0;
    DECLARE MYSQL_VAR_351IK6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y1YOA8 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_9FVA7U(10) - (0) + COALESCE(CHANNEL, COALESCE(BUDGET, 0), 0))
    INTO MYSQL_VAR_960FG8, MYSQL_VAR_TQJ21L
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_DI51P1(30) - (0) + COALESCE(COALESCE(SUM(CONVERSION_VALUE), 0), 0))
    INTO MYSQL_VAR_351IK6
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    CASE MYSQL_VAR_960FG8
        WHEN 'PAID' THEN SET MYSQL_VAR_Y1YOA8 = (MYSQL_FUNC_VIXANQ(10) * 2) / GREATEST(MYSQL_VAR_TQJ21L, 1);
        WHEN 'ORGANIC' THEN SET MYSQL_VAR_Y1YOA8 = MYSQL_FUNC_GWG7B7(20);
        WHEN 'SOCIAL' THEN SET MYSQL_VAR_Y1YOA8 = MYSQL_FUNC_OHRCD0(20);
        ELSE SET MYSQL_VAR_Y1YOA8 = MYSQL_VAR_351IK6;
    END CASE;

    RETURN (MYSQL_FUNC_PPMX2H(10, 11) - (0) + COALESCE(MYSQL_VAR_Y1YOA8, 0));
END//

DELIMITER ;