/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_CJJN0T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CJJN0T(N INT) RETURNS INT
BEGIN
IF N < 0 THEN
        RETURN -N;
    END IF;
    RETURN N;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2NQFSW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2NQFSW(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PNULD7 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4OHDBR DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_CJJN0T(10)
    INTO MYSQL_VAR_PNULD7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_4OHDBR
    FROM EMPLOYEES;

    RETURN FLOOR((MYSQL_VAR_PNULD7 * 100) / MYSQL_VAR_4OHDBR);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VNO6BO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VNO6BO(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MZR8N8 INT DEFAULT 0;

    SELECT MONTH(MIN(ORDER_DATE))
    INTO MYSQL_VAR_MZR8N8
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_2NQFSW(30);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NSW71L(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RFEBS3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_UW04BA INT DEFAULT 1;
    DECLARE MYSQL_VAR_SJ2S8A INT DEFAULT 0;
    DECLARE MYSQL_VAR_0XPY2O INT DEFAULT 2;
    DECLARE MYSQL_VAR_28CILA INT DEFAULT 0;

    IF N = 0 THEN RETURN 0; END IF;
    IF N = 1 THEN RETURN 1; END IF;

    SET MYSQL_VAR_0XPY2O = MYSQL_FUNC_VNO6BO(20);

    FIB_LOOP: WHILE MYSQL_VAR_0XPY2O <= N DO
        SET MYSQL_VAR_28CILA = MYSQL_VAR_UW04BA;
        SET MYSQL_VAR_UW04BA = MYSQL_VAR_RFEBS3 + MYSQL_VAR_UW04BA;
        SET MYSQL_VAR_RFEBS3 = MYSQL_VAR_28CILA;
        SET MYSQL_VAR_0XPY2O = MYSQL_VAR_0XPY2O + 1;
    END WHILE FIB_LOOP;

    RETURN MYSQL_VAR_UW04BA;
END//

DELIMITER ;