/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_svj7l3 (
    emp_no INT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS table_takpkm (
    emp_no INT,
    salary INT,
    FOREIGN KEY (emp_no) REFERENCES table_svj7l3(emp_no)
);
INSERT INTO table_svj7l3 (emp_no) VALUES (10001);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 60117);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 62102);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 66074);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_VAIE78----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VAIE78(CUSTOMER_ID_PARAM INT, CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2GCHVP INT DEFAULT 0;
    DECLARE MYSQL_VAR_ER8MQH INT DEFAULT 0;
    DECLARE MYSQL_VAR_IG6T1D INT DEFAULT 0;
    DECLARE MYSQL_VAR_1CZI0L INT DEFAULT 0;
    DECLARE MYSQL_VAR_JCF941 DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(*), COALESCE(SUM(OI.QUANTITY * P.PRICE), 0)
    INTO MYSQL_VAR_2GCHVP, MYSQL_VAR_IG6T1D
    FROM ORDERS O
    JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE O.CUSTOMER_ID = CUSTOMER_ID_PARAM AND P.CATEGORY_ID = CATEGORY_ID_PARAM AND O.STATUS = 'COMPLETED';

    SELECT COUNT(*), COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_ER8MQH, MYSQL_VAR_1CZI0L
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    IF MYSQL_VAR_ER8MQH = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_JCF941 = ((MYSQL_VAR_2GCHVP * 1.0) / MYSQL_VAR_ER8MQH * 50) +
                             ((MYSQL_VAR_IG6T1D * 1.0) / MYSQL_VAR_1CZI0L * 50);

    RETURN FLOOR(MYSQL_VAR_JCF941);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AJPTKB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AJPTKB(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QHJRNX DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_QHJRNX
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_QHJRNX * 15);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EERRQA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EERRQA(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V8XNB0 INT DEFAULT 0;

    SELECT MYSQL_FUNC_AJPTKB(20)
    INTO MYSQL_VAR_V8XNB0
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_FUNC_VAIE78(30, 31);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_98WDW1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_98WDW1(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H8Q2WK INT DEFAULT 0;
    DECLARE MYSQL_VAR_EXT8O4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_XGWD19 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_H8Q2WK
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM
    AND YEAR(O.ORDER_DATE) = YEAR(CURDATE());

    SELECT COUNT(*)
    INTO MYSQL_VAR_EXT8O4
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM
    AND YEAR(O.ORDER_DATE) = YEAR(CURDATE()) - 1;

    IF MYSQL_VAR_EXT8O4 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_XGWD19 = ((MYSQL_VAR_H8Q2WK - MYSQL_VAR_EXT8O4) * 100) / MYSQL_VAR_EXT8O4;

    RETURN MYSQL_VAR_XGWD19;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5JPH02----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5JPH02(P_EMP_NO INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_U5X0D5 INT;
    
    SELECT AVG(S.SALARY) INTO MYSQL_VAR_U5X0D5
    FROM TABLE_SVJ7L3 E
    JOIN TABLE_TAKPKM S ON E.EMP_NO = S.EMP_NO
    WHERE E.EMP_NO = P_EMP_NO;
    
    RETURN MYSQL_FUNC_98WDW1('test_2_0');
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NSW71L(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RFEBS3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_UW04BA INT DEFAULT 1;
    DECLARE MYSQL_VAR_SJ2S8A INT DEFAULT 0;
    DECLARE MYSQL_VAR_0XPY2O INT DEFAULT 2;
    DECLARE MYSQL_VAR_28CILA INT DEFAULT 0;

    IF N = 0 THEN RETURN 0; END IF;
    IF N = 1 THEN RETURN 1; END IF;

    SET MYSQL_VAR_0XPY2O = MYSQL_FUNC_5JPH02(10);

    FIB_LOOP: WHILE MYSQL_VAR_0XPY2O <= N DO
        SET MYSQL_VAR_28CILA = MYSQL_VAR_UW04BA;
        SET MYSQL_VAR_UW04BA = MYSQL_VAR_RFEBS3 + MYSQL_VAR_UW04BA;
        SET MYSQL_VAR_RFEBS3 = MYSQL_VAR_28CILA;
        SET MYSQL_VAR_0XPY2O = MYSQL_VAR_0XPY2O + 1;
    END WHILE FIB_LOOP;

    RETURN MYSQL_FUNC_EERRQA(10);
END//

DELIMITER ;