/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_P6XMEJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P6XMEJ(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_600HP9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_K8EX72 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_0QKRVH DECIMAL(5,2) DEFAULT 0.00;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_600HP9
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_K8EX72
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_600HP9 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0QKRVH = (MYSQL_VAR_K8EX72 / MYSQL_VAR_600HP9) * 100;

    RETURN FLOOR(MYSQL_VAR_0QKRVH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KEGLIS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KEGLIS(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_W46109 INT DEFAULT 0;
    DECLARE MYSQL_VAR_V7N3VM INT DEFAULT 500;
    DECLARE MYSQL_VAR_YLIF19 INT DEFAULT 0;
    DECLARE MYSQL_VAR_1QRMGE INT DEFAULT 0;

    SELECT COALESCE(SUM(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_W46109
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(SUM(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_YLIF19
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM AND STOCK_QUANTITY > MYSQL_VAR_V7N3VM;

    IF MYSQL_VAR_W46109 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_1QRMGE = (MYSQL_VAR_YLIF19 * 100) / MYSQL_VAR_W46109;

    RETURN MYSQL_VAR_1QRMGE;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4WNOFN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4WNOFN(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EBU23G DATE;
    DECLARE MYSQL_VAR_4A8U8K DATE;

    SELECT START_DATE, END_DATE
    INTO MYSQL_VAR_EBU23G, MYSQL_VAR_4A8U8K
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_EBU23G IS NULL OR MYSQL_VAR_4A8U8K IS NULL THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_KEGLIS(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VZ0U1M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VZ0U1M(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FBQTPY INT DEFAULT 0;
    DECLARE MYSQL_VAR_4WA972 INT DEFAULT 0;

    SELECT COUNT(DISTINCT C.CUSTOMER_ID), COUNT(O.ORDER_ID)
    INTO MYSQL_VAR_FBQTPY, MYSQL_VAR_4WA972
    FROM CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    IF MYSQL_VAR_FBQTPY = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_4WA972 * 100) / MYSQL_VAR_FBQTPY;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OQ1NDN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OQ1NDN(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LTID0P INT DEFAULT 0;
    DECLARE MYSQL_VAR_VJ8PFO INT DEFAULT 0;
    DECLARE MYSQL_VAR_8RORBC INT DEFAULT 100;
    DECLARE MYSQL_VAR_BK94UN INT DEFAULT 0;

    SELECT COALESCE(QUANTITY_ORDERED, 0), COALESCE(DEFECT_COUNT, 0)
    INTO MYSQL_VAR_LTID0P, MYSQL_VAR_VJ8PFO
    FROM MANUFACTURING_ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_LTID0P = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_8RORBC = ((MYSQL_VAR_LTID0P - MYSQL_VAR_VJ8PFO) * 100) / MYSQL_VAR_LTID0P;

    IF MYSQL_VAR_VJ8PFO > 10 THEN
        SET MYSQL_VAR_BK94UN = MYSQL_VAR_VJ8PFO * 50;
        SET MYSQL_VAR_8RORBC = MYSQL_VAR_8RORBC - 10;
    END IF;

    RETURN CAST(MYSQL_VAR_8RORBC AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ENP0WR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ENP0WR(X1 INT, Y1 INT, X2 INT, Y2 INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZD2JFV INT DEFAULT 0;
    SET MYSQL_VAR_ZD2JFV = ABS(X1 - X2) + ABS(Y1 - Y2);
    RETURN MYSQL_VAR_ZD2JFV;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MWRV3H----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MWRV3H(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GVTPXF VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_D3TY3R INT DEFAULT 0;
    DECLARE MYSQL_VAR_QMW01K VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_49J43V INT DEFAULT 0;

    SELECT PLAN_TYPE, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_GVTPXF, MYSQL_VAR_D3TY3R
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT TIER_LEVEL
    INTO MYSQL_VAR_QMW01K
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_49J43V = MYSQL_VAR_D3TY3R;

    CASE MYSQL_VAR_GVTPXF
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_49J43V = MYSQL_VAR_49J43V + 100;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_49J43V = MYSQL_VAR_49J43V + 50;
        WHEN 'BASIC' THEN SET MYSQL_VAR_49J43V = MYSQL_VAR_49J43V + 10;
    END CASE;

    CASE MYSQL_VAR_QMW01K
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_49J43V = MYSQL_VAR_49J43V + 80;
        WHEN 'GOLD' THEN SET MYSQL_VAR_49J43V = MYSQL_VAR_49J43V + 40;
        WHEN 'SILVER' THEN SET MYSQL_VAR_49J43V = MYSQL_VAR_49J43V + 20;
    END CASE;

    RETURN MYSQL_VAR_49J43V;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8VIS2N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8VIS2N(STORE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XG8FLF INT DEFAULT 0;
    DECLARE MYSQL_VAR_PIFH7D INT DEFAULT 0;
    DECLARE MYSQL_VAR_LXSCL8 INT DEFAULT 0;

    SELECT MYSQL_FUNC_ENP0WR(20, 21, 22, 23) INTO MYSQL_VAR_XG8FLF
    FROM TRANSACTIONS
    WHERE STORE_ID = STORE_ID_PARAM
      AND TRANSACTION_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SELECT COUNT(*) INTO MYSQL_VAR_PIFH7D
    FROM RETAIL_RETURNS R
    JOIN TRANSACTIONS T ON R.TRANSACTION_ID = T.TRANSACTION_ID
    WHERE T.STORE_ID = STORE_ID_PARAM
      AND R.RETURN_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    IF MYSQL_VAR_XG8FLF = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_LXSCL8 = (MYSQL_VAR_PIFH7D * 100) / MYSQL_VAR_XG8FLF;

    RETURN MYSQL_FUNC_MWRV3H(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CSOL7I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CSOL7I(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H19CX1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_L2TSWW INT DEFAULT 0;
    DECLARE MYSQL_VAR_5TMM3O INT DEFAULT 0;

    SELECT MYSQL_FUNC_8VIS2N(10)
    INTO MYSQL_VAR_H19CX1
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MYSQL_FUNC_OQ1NDN(30)
    INTO MYSQL_VAR_L2TSWW
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE O.CUSTOMER_ID = CUSTOMER_ID_PARAM AND O.SHIPPING_COUNTRY != C.COUNTRY;

    IF MYSQL_VAR_H19CX1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_5TMM3O = MYSQL_FUNC_VZ0U1M('test_2_0');

    RETURN MYSQL_VAR_5TMM3O;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_44NGN1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_44NGN1(ROW_NUM INT, COL_NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CH1VN3 INT DEFAULT 1;
    DECLARE MYSQL_VAR_FOU1E3 INT DEFAULT 0;

    IF COL_NUM = 0 OR COL_NUM = ROW_NUM THEN
        RETURN 1;
    END IF;

    IF COL_NUM > ROW_NUM OR COL_NUM < 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_FOU1E3 = 0;
    WHILE MYSQL_VAR_FOU1E3 < COL_NUM DO
        SET MYSQL_VAR_CH1VN3 = MYSQL_VAR_CH1VN3 * (ROW_NUM - MYSQL_VAR_FOU1E3);
        SET MYSQL_VAR_CH1VN3 = MYSQL_VAR_CH1VN3 / (MYSQL_VAR_FOU1E3 + 1);
        SET MYSQL_VAR_FOU1E3 = MYSQL_VAR_FOU1E3 + 1;
    END WHILE;

    RETURN MYSQL_VAR_CH1VN3;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_U47B4D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_U47B4D(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4EU1TL DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_CSOL7I(30)
    INTO MYSQL_VAR_4EU1TL
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN MYSQL_FUNC_44NGN1(10, 11);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8ZSQ64(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IWOH3F INT DEFAULT 5;
    DECLARE MYSQL_VAR_D8RM6Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_C0JAXN INT DEFAULT 0;
    DECLARE MYSQL_VAR_GEZ5KX INT DEFAULT 0;
    DECLARE MYSQL_VAR_IN3ZOH INT DEFAULT 0;
    DECLARE MYSQL_VAR_DVOXV9 INT DEFAULT 0;

    SELECT MYSQL_FUNC_4WNOFN(30)
    INTO MYSQL_VAR_IN3ZOH
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT DATEDIFF(COALESCE(DELIVERY_DATE, CURDATE()), SHIPPING_DATE)
    INTO MYSQL_VAR_D8RM6Z
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_C0JAXN = MYSQL_FUNC_U47B4D(30);

    IF MYSQL_VAR_C0JAXN <= 0 THEN
        SET MYSQL_VAR_DVOXV9 = 100;
    ELSE
        SET MYSQL_VAR_DVOXV9 = 100 - (MYSQL_VAR_C0JAXN * 10);
    END IF;

    RETURN MYSQL_FUNC_P6XMEJ(20);
END//

DELIMITER ;