/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_9EU4R5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9EU4R5(PROPERTY_ID_PARAM INT, SERVICE_TYPE VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LL4UJ1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7X5P2P INT DEFAULT 0;
    DECLARE MYSQL_VAR_OEKMSK INT DEFAULT 50;
    DECLARE MYSQL_VAR_ZUNLDC INT DEFAULT 0;

    SELECT COALESCE(AREA_SQFT, 500), COALESCE(NUM_ROOMS, 2)
    INTO MYSQL_VAR_LL4UJ1, MYSQL_VAR_7X5P2P
    FROM PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_OEKMSK;

    SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC + (MYSQL_VAR_LL4UJ1 / 100) * 10;

    SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC + (MYSQL_VAR_7X5P2P * 15);

    IF SERVICE_TYPE = 'DEEP' THEN
        SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC * 150 / 100;
    ELSEIF SERVICE_TYPE = 'MOVE_OUT' THEN
        SET MYSQL_VAR_ZUNLDC = MYSQL_VAR_ZUNLDC * 175 / 100;
    END IF;

    RETURN CAST(MYSQL_VAR_ZUNLDC AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QTCSUX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QTCSUX(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LLQ69N INT DEFAULT 0;
    DECLARE MYSQL_VAR_K25882 INT DEFAULT 0;

    SET MYSQL_VAR_K25882 = ABS(N);

    IF MYSQL_VAR_K25882 = 0 THEN
        RETURN 1;
    END IF;

    DIGIT_COUNT_LOOP: WHILE MYSQL_VAR_K25882 > 0 DO
        SET MYSQL_VAR_LLQ69N = MYSQL_VAR_LLQ69N + 1;
        SET MYSQL_VAR_K25882 = MYSQL_VAR_K25882 / 10;
    END WHILE DIGIT_COUNT_LOOP;

    RETURN MYSQL_VAR_LLQ69N;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_K81VX0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_K81VX0(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TU2EZ9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_AO1C3C INT DEFAULT 1;

    SELECT MYSQL_FUNC_QTCSUX(30)
    INTO MYSQL_VAR_TU2EZ9, MYSQL_VAR_AO1C3C
    FROM CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID AND O.STATUS = 'COMPLETED'
    WHERE C.COUNTRY = COUNTRY_PARAM;

    IF MYSQL_VAR_AO1C3C = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_9EU4R5(30, 'test_2_1');
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FIZG0X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FIZG0X(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XXPA8S DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_B7ALZK INT DEFAULT 0;
    DECLARE MYSQL_VAR_BNMH6W DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_LZC97F INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_XXPA8S
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*), COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_B7ALZK, MYSQL_VAR_BNMH6W
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_LZC97F = (MYSQL_VAR_XXPA8S * 20) + (MYSQL_VAR_B7ALZK * 5) + (MYSQL_VAR_BNMH6W / 10);

    RETURN MYSQL_VAR_LZC97F;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3D9DN8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3D9DN8(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GJTYCY DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_B02BS7 DECIMAL(10,2) DEFAULT 1.00;

    SELECT COALESCE(AVG(SALARY), 0), COALESCE(AVG(SALARY), 1)
    INTO MYSQL_VAR_GJTYCY, MYSQL_VAR_B02BS7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_GJTYCY * 100) / MYSQL_VAR_B02BS7);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_86P4DA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_86P4DA(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_CV3REF INT DEFAULT 0;

    SELECT DEPARTMENT_ID
    INTO MYSQL_VAR_CV3REF
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_VAR_CV3REF % 100;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XO4DVP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XO4DVP(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PFGPB3 DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_86P4DA(20)
    INTO MYSQL_VAR_PFGPB3
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_PFGPB3);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JHEMUH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JHEMUH(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LXZABP INT DEFAULT 0;
    DECLARE MYSQL_VAR_RDUYUI INT DEFAULT 0;
    DECLARE MYSQL_VAR_S1ALO7 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_LXZABP
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE());

    SET MYSQL_VAR_RDUYUI = 5000 + (MYSQL_VAR_LXZABP * 1000);

    IF MYSQL_VAR_LXZABP = 0 THEN
        RETURN MYSQL_VAR_RDUYUI;
    END IF;

    SET MYSQL_VAR_S1ALO7 = MYSQL_VAR_RDUYUI / MYSQL_VAR_LXZABP;

    RETURN MYSQL_VAR_S1ALO7;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VYFLE8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VYFLE8(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DP20UH DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_QEPSI4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_QX969J INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_DP20UH, MYSQL_VAR_QEPSI4
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_QX969J
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_VAR_DP20UH * 10) + (30 - MYSQL_VAR_QEPSI4) + (MYSQL_VAR_QX969J * 2);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JJQXXF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JJQXXF(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_75YQKC INT DEFAULT 0;
    DECLARE MYSQL_VAR_TC605A INT DEFAULT 0;
    DECLARE MYSQL_VAR_FK35NB INT DEFAULT 0;

    SELECT MYSQL_FUNC_VYFLE8(10)
    INTO MYSQL_VAR_75YQKC, MYSQL_VAR_TC605A
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_FK35NB = MYSQL_VAR_75YQKC * 5 + MYSQL_VAR_TC605A * 2;

    RETURN MYSQL_VAR_FK35NB;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7YB6FA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7YB6FA(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z1AJ6I INT DEFAULT 0;
    DECLARE MYSQL_VAR_B3LAGS INT DEFAULT 0;
    DECLARE MYSQL_VAR_GUFF0V INT DEFAULT 0;
    DECLARE MYSQL_VAR_2PZQTP INT DEFAULT 0;

    SELECT MYSQL_FUNC_JHEMUH(10)
    INTO MYSQL_VAR_Z1AJ6I
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT MYSQL_FUNC_XO4DVP(30)
    INTO MYSQL_VAR_B3LAGS
    FROM SALARIES
    WHERE EMP_ID = EMP_ID_PARAM
    ORDER BY EFFECTIVE_DATE DESC
    LIMIT 1;

    SELECT MYSQL_FUNC_JJQXXF(20)
    INTO MYSQL_VAR_GUFF0V
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    IF MYSQL_VAR_Z1AJ6I = 0 OR MYSQL_VAR_GUFF0V = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_2PZQTP = (((MYSQL_VAR_B3LAGS - MYSQL_VAR_Z1AJ6I) * 100) / MYSQL_VAR_Z1AJ6I) / MYSQL_VAR_GUFF0V;

    RETURN MYSQL_FUNC_3D9DN8(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6HYJG5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6HYJG5(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FX0IE6 INT DEFAULT 0;

    SELECT MYSQL_FUNC_FIZG0X(20)
    INTO MYSQL_VAR_FX0IE6
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_FUNC_7YB6FA(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_T51PQP(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EL0R2P DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_YGBDXU INT DEFAULT 0;

    SELECT MYSQL_FUNC_6HYJG5(30)
    INTO MYSQL_VAR_EL0R2P, MYSQL_VAR_YGBDXU
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_K81VX0('test_0_0');
END//

DELIMITER ;