/* -----Seed Dependency----- */
CREATE TABLE IF NOT EXISTS table_svj7l3 (
    emp_no INT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS table_takpkm (
    emp_no INT,
    salary INT,
    FOREIGN KEY (emp_no) REFERENCES table_svj7l3(emp_no)
);
INSERT INTO table_svj7l3 (emp_no) VALUES (10001);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 60117);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 62102);
INSERT INTO table_takpkm (emp_no, salary) VALUES (10001, 66074);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_5K9RQB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5K9RQB(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DNVFLJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_75O218 INT DEFAULT 0;

    SELECT COUNT(DISTINCT S.CUSTOMER_ID), COUNT(DISTINCT C.CUSTOMER_ID)
    INTO MYSQL_VAR_DNVFLJ, MYSQL_VAR_75O218
    FROM CUSTOMERS C
    LEFT JOIN SUBSCRIPTIONS S ON C.CUSTOMER_ID = S.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    IF MYSQL_VAR_75O218 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_DNVFLJ * 100) / MYSQL_VAR_75O218;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HU4JM8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HU4JM8(DOCTOR_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1EBFWA INT DEFAULT 0;
    DECLARE MYSQL_VAR_0JKVF2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_C4GDDD INT DEFAULT 0;
    DECLARE MYSQL_VAR_R2SHL6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_RFNFZW INT DEFAULT 0;

    SELECT COALESCE(YEARS_EXPERIENCE, 0), COALESCE(CONSULTATION_FEE, 100)
    INTO MYSQL_VAR_1EBFWA, MYSQL_VAR_0JKVF2
    FROM DOCTORS
    WHERE DOCTOR_ID = DOCTOR_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_C4GDDD
    FROM APPOINTMENTS
    WHERE DOCTOR_ID = DOCTOR_ID_PARAM
      AND MONTH(APPOINTMENT_DATE) = MONTH(CURDATE())
      AND STATUS = 'COMPLETED';

    SET MYSQL_VAR_R2SHL6 = 22;
    SET MYSQL_VAR_RFNFZW = (MYSQL_VAR_C4GDDD * 100) / MYSQL_VAR_R2SHL6;

    IF MYSQL_VAR_1EBFWA > 10 THEN
        SET MYSQL_VAR_RFNFZW = MYSQL_VAR_RFNFZW + 10;
    END IF;

    RETURN LEAST(MYSQL_VAR_RFNFZW, 100);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5JPH02(P_EMP_NO INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_U5X0D5 INT;
    
    SELECT (MYSQL_FUNC_HU4JM8(10) - (0) + COALESCE(AVG(S.SALARY), 0)) INTO MYSQL_VAR_U5X0D5
    FROM TABLE_SVJ7L3 E
    JOIN TABLE_TAKPKM S ON E.EMP_NO = S.EMP_NO
    WHERE E.EMP_NO = P_EMP_NO;
    
    RETURN (MYSQL_FUNC_5K9RQB('test_2_0') - (0) + COALESCE(MYSQL_VAR_U5X0D5, 0));
END//

DELIMITER ;