/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_z6ejol (
    emp_no INT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    birth_date DATE,
    hire_date DATE
);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_KD934Z----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KD934Z(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UGR1O6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_2MH1HH INT DEFAULT 0;
    DECLARE MYSQL_VAR_YRH2P0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_DT7CQM INT DEFAULT 0;

    SELECT COALESCE(SALARY, 50000), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_UGR1O6, MYSQL_VAR_2MH1HH
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COALESCE(IS_REMOTE_FRIENDLY, 0)
    INTO MYSQL_VAR_YRH2P0
    FROM DEPARTMENTS D
    JOIN EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
    WHERE E.EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_DT7CQM = (MYSQL_VAR_2MH1HH * 10) + (MYSQL_VAR_UGR1O6 / 10000 * 5);

    IF MYSQL_VAR_YRH2P0 = 1 THEN
        SET MYSQL_VAR_DT7CQM = MYSQL_VAR_DT7CQM + 15;
    END IF;

    RETURN MYSQL_VAR_DT7CQM;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_12AHDF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_12AHDF(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N0UVY1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_71FVRW INT DEFAULT 1;
    DECLARE MYSQL_VAR_K88SWC INT DEFAULT 0;
    DECLARE MYSQL_VAR_18A8S8 INT DEFAULT 2;

    IF N <= 0 THEN
        RETURN 0;
    END IF;

    IF N = 1 THEN
        RETURN 1;
    END IF;

    WHILE MYSQL_VAR_18A8S8 <= N DO
        SET MYSQL_VAR_K88SWC = MYSQL_VAR_N0UVY1 + MYSQL_VAR_71FVRW;
        SET MYSQL_VAR_N0UVY1 = MYSQL_VAR_71FVRW;
        SET MYSQL_VAR_71FVRW = MYSQL_VAR_K88SWC;
        SET MYSQL_VAR_18A8S8 = MYSQL_VAR_18A8S8 + 1;
    END WHILE;

    RETURN MYSQL_VAR_71FVRW;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YH4JKO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YH4JKO(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TJX3MG INT DEFAULT 0;
    DECLARE MYSQL_VAR_C86EGS INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_TJX3MG
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_C86EGS
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_TJX3MG = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_C86EGS / MYSQL_VAR_TJX3MG;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8GGPTZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8GGPTZ(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WILVVW DECIMAL(3,1) DEFAULT 0.0;

    SELECT MYSQL_FUNC_YH4JKO(20)
    INTO MYSQL_VAR_WILVVW
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_FUNC_12AHDF(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TRL6NY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TRL6NY() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_U7N65F INT DEFAULT 0;
    
    SELECT COUNT(*) INTO MYSQL_VAR_U7N65F 
    FROM TABLE_Z6EJOL 
    LIMIT 1000;
    
    RETURN MYSQL_VAR_U7N65F;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_B1YPAI(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_WWG0WP DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_7ZCVCQ DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_KD934Z(20)
    INTO MYSQL_VAR_WWG0WP, MYSQL_VAR_7ZCVCQ
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
      AND ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY)
      AND STATUS = 'COMPLETED';

    SELECT MYSQL_FUNC_8GGPTZ(20)
    INTO MYSQL_VAR_7ZCVCQ
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
      AND ORDER_DATE < DATE_SUB(CURDATE(), INTERVAL 30 DAY)
      AND STATUS = 'COMPLETED';

    IF MYSQL_VAR_7ZCVCQ = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_TRL6NY();
END//

DELIMITER ;