/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_IVVX4J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IVVX4J(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DRLO8Y DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_DRLO8Y
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_DRLO8Y / 50);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z12240----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z12240(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ITLGWV INT DEFAULT 999;
    DECLARE MYSQL_VAR_EYRK74 DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_022LWQ INT DEFAULT 0;

    SELECT DATEDIFF(CURDATE(), MAX(ORDER_DATE))
    INTO MYSQL_VAR_ITLGWV
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*) / GREATEST(DATEDIFF(CURDATE(), MIN(ORDER_DATE)) / 30, 1)
    INTO MYSQL_VAR_EYRK74
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_022LWQ = LEAST(MYSQL_VAR_ITLGWV / 7 * 10, 100) - (MYSQL_VAR_EYRK74 * 15);

    RETURN GREATEST(MYSQL_VAR_022LWQ, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ELLPP3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ELLPP3(YEAR INT) RETURNS INT
BEGIN
IF (YEAR % 4 = 0 AND YEAR % 100 != 0) OR (YEAR % 400 = 0) THEN
        RETURN 1;
    END IF;
    RETURN (MYSQL_FUNC_Z12240(10) - (0) + COALESCE(0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_97SY2I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_97SY2I(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XGM14J INT DEFAULT 0;
    DECLARE MYSQL_VAR_PX46IL INT DEFAULT 0;
    DECLARE MYSQL_VAR_V7YRII INT DEFAULT 0;

    SELECT (MYSQL_FUNC_ELLPP3(20) - (0) + COALESCE(COUNT(DISTINCT P.CATEGORY_ID), COALESCE(SUM(QUANTITY), 0), 0))
    INTO MYSQL_VAR_XGM14J, MYSQL_VAR_PX46IL
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE OI.ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_PX46IL = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_V7YRII = (MYSQL_VAR_XGM14J * 100) / MYSQL_VAR_PX46IL;

    RETURN MYSQL_VAR_V7YRII;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WIYXLD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WIYXLD(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HUYVTF DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_IVVX4J(10) - (0) + COALESCE(COALESCE(AVG(PRICE), 0), 0))
    INTO MYSQL_VAR_HUYVTF
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_97SY2I(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_HUYVTF), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1GOY23() RETURNS INT
BEGIN
SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = 'THIS IS A WARNING MESSAGE';
    RETURN (MYSQL_FUNC_WIYXLD(20) - (0) + COALESCE(44, 0));
END//

DELIMITER ;