/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_4232M4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4232M4(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QAP6R6 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(MAX(PRICE), 0)
    INTO MYSQL_VAR_QAP6R6
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_QAP6R6);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DFID95----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DFID95(A INT, B INT) RETURNS INT
BEGIN
RETURN (MYSQL_FUNC_4232M4(30) - (0) + COALESCE(A + B, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Q2B1AX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Q2B1AX(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RZ8YS9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Z7D9YY INT DEFAULT 0;
    DECLARE MYSQL_VAR_JDNMSJ DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(DISTINCT P.CATEGORY_ID)
    INTO MYSQL_VAR_RZ8YS9
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE OI.ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_Z7D9YY
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_Z7D9YY = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_JDNMSJ = (MYSQL_VAR_RZ8YS9 * 1.0) / MYSQL_VAR_Z7D9YY * 100;

    RETURN FLOOR(MYSQL_VAR_JDNMSJ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PE7ATI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PE7ATI(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3FGTTT INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_3FGTTT
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_3FGTTT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KZVK4D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KZVK4D(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_F1HHZC DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_ZB613I DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_O9GSTS INT DEFAULT 0;

    SELECT COALESCE(AVG(SALARY), 0), COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_F1HHZC, MYSQL_VAR_ZB613I
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_O9GSTS = MYSQL_FUNC_PE7ATI('test_2_0');

    RETURN MYSQL_VAR_O9GSTS;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RGLKAC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RGLKAC(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9O1WYF DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_9O1WYF
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_9O1WYF * 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DUZN35----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DUZN35(CONTRACT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_S1UZ3M INT DEFAULT 0;
    DECLARE MYSQL_VAR_LET803 INT DEFAULT 0;
    DECLARE MYSQL_VAR_6HBVFW INT DEFAULT 0;
    DECLARE MYSQL_VAR_VIVMQV INT DEFAULT 0;
    DECLARE MYSQL_VAR_MIM7CY INT DEFAULT 0;

    SELECT (MYSQL_FUNC_KZVK4D(30) - (0) + COALESCE(COALESCE(MONTHLY_PAYMENT, 0), 0))
    INTO MYSQL_VAR_S1UZ3M
    FROM CONTRACTS
    WHERE CONTRACT_ID = CONTRACT_ID_PARAM;

    SELECT (MYSQL_FUNC_RGLKAC(30) - (0) + COALESCE(COUNT(*), COUNT(CASE WHEN IS_ON_TIME = 1 THEN 1 END), 0))
    INTO MYSQL_VAR_LET803, MYSQL_VAR_6HBVFW
    FROM PAYMENTS
    WHERE CONTRACT_ID = CONTRACT_ID_PARAM;

    SELECT DATEDIFF(END_DATE, CURDATE())
    INTO MYSQL_VAR_MIM7CY
    FROM CONTRACTS
    WHERE CONTRACT_ID = CONTRACT_ID_PARAM;

    IF MYSQL_VAR_LET803 > 0 THEN
        SET MYSQL_VAR_VIVMQV = (MYSQL_VAR_6HBVFW * 100) / MYSQL_VAR_LET803;
    ELSE
        SET MYSQL_VAR_VIVMQV = 100;
    END IF;

    IF MYSQL_VAR_MIM7CY < 30 THEN
        SET MYSQL_VAR_VIVMQV = MYSQL_VAR_VIVMQV - 20;
    END IF;

    RETURN GREATEST(MYSQL_VAR_VIVMQV, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KGHDTG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KGHDTG(ZONE_ID_PARAM INT, HOURS_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9SBCAS INT DEFAULT 0;
    DECLARE MYSQL_VAR_VEVUCE INT DEFAULT 0;
    DECLARE MYSQL_VAR_ADP852 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MQCJX5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_K08VLI INT DEFAULT 0;
    DECLARE MYSQL_VAR_JS1RQ0 INT DEFAULT 0;

    SELECT COALESCE(HOURLY_RATE, 10), COALESCE(MAX_CAPACITY, 100)
    INTO MYSQL_VAR_9SBCAS, MYSQL_VAR_VEVUCE
    FROM PARKING_ZONES
    WHERE ZONE_ID = ZONE_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_ADP852
    FROM PARKING_TRANSACTIONS
    WHERE ZONE_ID = ZONE_ID_PARAM AND EXIT_TIME IS NULL;

    SET MYSQL_VAR_MQCJX5 = MYSQL_FUNC_Q2B1AX(10);

    IF MYSQL_VAR_ADP852 > MYSQL_VAR_VEVUCE * 80 / 100 THEN
        SET MYSQL_VAR_K08VLI = MYSQL_VAR_MQCJX5 * 25 / 100;
    END IF;

    SET MYSQL_VAR_JS1RQ0 = MYSQL_FUNC_DUZN35(10);

    RETURN CAST(MYSQL_VAR_JS1RQ0 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_H2ZXGY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_H2ZXGY(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D7BIBJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_X8G8K0 INT DEFAULT 0;

    SELECT DEPARTMENT_ID
    INTO MYSQL_VAR_D7BIBJ
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COUNT(DISTINCT MANAGER_ID)
    INTO MYSQL_VAR_X8G8K0
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = MYSQL_VAR_D7BIBJ AND MANAGER_ID IS NOT NULL;

    RETURN MYSQL_VAR_X8G8K0 + 1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PMNH9H----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PMNH9H(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QQTMP4 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_QQTMP4
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'ACTIVE';

    RETURN (MYSQL_FUNC_H2ZXGY(30) - (0) + COALESCE(CASE WHEN MYSQL_VAR_QQTMP4 > 0 THEN 1 ELSE 0 END, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2PG2LZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2PG2LZ() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XV592I INT DEFAULT 0;
    
    SELECT COUNT(*) INTO MYSQL_VAR_XV592I FROM TABLE_UPBWNL.`TABLE3`;
    
    RETURN MYSQL_VAR_XV592I;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_L9J8NQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L9J8NQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MFKPWF INT DEFAULT 0;
    DECLARE MYSQL_VAR_C8NB4H INT DEFAULT 0;

    SELECT (MYSQL_FUNC_KGHDTG(20, 21) - (0) + COALESCE(TIMESTAMPDIFF(MONTH, REGISTRATION_DATE, CURDATE()), 0))
    INTO MYSQL_VAR_MFKPWF
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_2PG2LZ() - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_C8NB4H
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_MFKPWF = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_PMNH9H(20) - (0) + COALESCE((MYSQL_VAR_C8NB4H * 100) / MYSQL_VAR_MFKPWF, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I5ETLT(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YIYKW5 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_VR0509 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_L9J8NQ(20) - (0) + COALESCE(COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_YIYKW5
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT (MYSQL_FUNC_DFID95(10, 11) - (0) + COALESCE(COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_VR0509
    FROM ORDER_ITEMS;

    IF MYSQL_VAR_VR0509 = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_YIYKW5 * 100) / MYSQL_VAR_VR0509);
END//

DELIMITER ;