/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_SJWMS3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SJWMS3(YEAR_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1JU5VV INT DEFAULT 0;

    IF (YEAR_PARAM % 4 = 0 AND YEAR_PARAM % 100 != 0) OR (YEAR_PARAM % 400 = 0) THEN
        SET MYSQL_VAR_1JU5VV = 1;
    END IF;

    IF MYSQL_VAR_1JU5VV = 1 THEN
        RETURN 366;
    END IF;

    RETURN 365;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YA52TQ(CLAIM_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NGFMB0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_CV6PNH INT DEFAULT 0;
    DECLARE MYSQL_VAR_ORVXWK INT DEFAULT 0;
    DECLARE MYSQL_VAR_JI6XEL INT DEFAULT 0;

    SELECT COALESCE(CLAIM_AMOUNT, 0), DATEDIFF(CURDATE(), FILING_DATE)
    INTO MYSQL_VAR_NGFMB0, MYSQL_VAR_CV6PNH
    FROM INSURANCE_CLAIMS
    WHERE CLAIM_ID = CLAIM_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_ORVXWK
    FROM POLICY_TRANSACTIONS
    WHERE POLICY_ID = (SELECT POLICY_ID FROM INSURANCE_CLAIMS WHERE CLAIM_ID = CLAIM_ID_PARAM);

    SET MYSQL_VAR_JI6XEL = MYSQL_FUNC_SJWMS3(20);

    IF MYSQL_VAR_NGFMB0 > 50000 THEN
        SET MYSQL_VAR_JI6XEL = MYSQL_VAR_JI6XEL - 20;
    END IF;

    RETURN CAST(MYSQL_VAR_JI6XEL AS SIGNED);
END//

DELIMITER ;