/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_Q2B1AX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Q2B1AX(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RZ8YS9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Z7D9YY INT DEFAULT 0;
    DECLARE MYSQL_VAR_JDNMSJ DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(DISTINCT P.CATEGORY_ID)
    INTO MYSQL_VAR_RZ8YS9
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE OI.ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_Z7D9YY
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_Z7D9YY = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_JDNMSJ = (MYSQL_VAR_RZ8YS9 * 1.0) / MYSQL_VAR_Z7D9YY * 100;

    RETURN FLOOR(MYSQL_VAR_JDNMSJ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HEZRY1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HEZRY1(CELSIUS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DPA46F DECIMAL(5,2) DEFAULT 0.00;
    SET MYSQL_VAR_DPA46F = (CELSIUS * 9 / 5) + 32;
    RETURN FLOOR(MYSQL_VAR_DPA46F);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RGLKAC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RGLKAC(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9O1WYF DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_9O1WYF
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_HEZRY1(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_9O1WYF * 10), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SKTOIG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SKTOIG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_W0JQFI INT DEFAULT 0;

    SELECT (MYSQL_FUNC_RGLKAC(30) - (0) + COALESCE(COALESCE(MONTHLY_COST, 0), 0))
    INTO MYSQL_VAR_W0JQFI
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_Q2B1AX(10) - (0) + COALESCE(MYSQL_VAR_W0JQFI * 12, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_F0RH5N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_F0RH5N(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GRJPNQ DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_GG8Z78 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0HYDY9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_1GTT6F INT DEFAULT 0;

    SELECT COALESCE(PERFORMANCE_RATING, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), COALESCE(SALARY, 0)
    INTO MYSQL_VAR_GRJPNQ, MYSQL_VAR_GG8Z78, MYSQL_VAR_0HYDY9
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    IF MYSQL_VAR_GRJPNQ >= 3.5 AND MYSQL_VAR_GG8Z78 >= 1 THEN
        SET MYSQL_VAR_1GTT6F = 1;
    END IF;

    RETURN (MYSQL_FUNC_SKTOIG(30) - (0) + COALESCE(MYSQL_VAR_1GTT6F, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S3447Y----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S3447Y(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4JWDXT DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_TOZH4L INT DEFAULT 0;

    SELECT COALESCE(AVG(PRICE), 0), COALESCE(SUM(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_4JWDXT, MYSQL_VAR_TOZH4L
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_4JWDXT * MYSQL_VAR_TOZH4L) / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HUI270----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HUI270(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2Q1VMG INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_2Q1VMG
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
      AND ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 90 DAY);

    RETURN (MYSQL_FUNC_S3447Y(10) - (0) + COALESCE(MYSQL_VAR_2Q1VMG, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SR5O0T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SR5O0T(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OSD3CN INT DEFAULT 0;
    DECLARE MYSQL_VAR_VKL9ZO INT DEFAULT 0;

    SELECT (MYSQL_FUNC_HUI270(10) - (0) + COALESCE(COALESCE(BUDGET, 0), 0))
    INTO MYSQL_VAR_OSD3CN
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_VKL9ZO
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_VKL9ZO = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_F0RH5N(30) - (0) + COALESCE(MYSQL_VAR_OSD3CN / MYSQL_VAR_VKL9ZO, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PG959D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PG959D(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_T45CDC DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_T45CDC
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_T45CDC);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0D7931----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0D7931(VIOLATION_ID_PARAM INT, DAYS_EARLY INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UOIFKJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_H0KX37 INT DEFAULT 0;
    DECLARE MYSQL_VAR_D7CHOW INT DEFAULT 0;

    SELECT COALESCE(FINE_AMOUNT, 50)
    INTO MYSQL_VAR_UOIFKJ
    FROM PARKING_VIOLATIONS
    WHERE VIOLATION_ID = VIOLATION_ID_PARAM;

    IF DAYS_EARLY >= 30 THEN
        SET MYSQL_VAR_H0KX37 = 40;
    ELSEIF DAYS_EARLY >= 14 THEN
        SET MYSQL_VAR_H0KX37 = 25;
    ELSEIF DAYS_EARLY >= 7 THEN
        SET MYSQL_VAR_H0KX37 = 15;
    END IF;

    SET MYSQL_VAR_D7CHOW = MYSQL_VAR_UOIFKJ - (MYSQL_VAR_UOIFKJ * MYSQL_VAR_H0KX37 / 100);

    RETURN CAST(MYSQL_VAR_D7CHOW AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JGBLFF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JGBLFF(RADIUS INT, ANGLE_DEGREES INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_E3NOQQ DECIMAL(10,2) DEFAULT 0.00;
    SET MYSQL_VAR_E3NOQQ = 3.14159 * RADIUS * RADIUS * ANGLE_DEGREES / 360;
    RETURN FLOOR(MYSQL_VAR_E3NOQQ);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8FYA73(PARK_ID_PARAM INT, TARGET_DATE_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KD32DL INT DEFAULT 0;
    DECLARE MYSQL_VAR_4UT7AB INT DEFAULT 0;
    DECLARE MYSQL_VAR_R2UQG9 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_SR5O0T(20) - (0) + COALESCE(COUNT(DISTINCT VISITOR_ID), 0)) INTO MYSQL_VAR_KD32DL
    FROM AMUSEMENT_PARKS
    WHERE PARK_ID = PARK_ID_PARAM
      AND YEAR(VISIT_DATE) = TARGET_DATE_PARAM;

    SELECT (MYSQL_FUNC_JGBLFF(20, 21) - (0) + COALESCE(COALESCE(CAPACITY, 1000), 0)) INTO MYSQL_VAR_4UT7AB
    FROM PARKS
    WHERE PARK_ID = PARK_ID_PARAM;

    IF MYSQL_VAR_4UT7AB = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_R2UQG9 = MYSQL_FUNC_0D7931(10, 11);

    RETURN (MYSQL_FUNC_PG959D(10) - (0) + COALESCE(CAST(MYSQL_VAR_R2UQG9 AS SIGNED), 0));
END//

DELIMITER ;