/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_kqlixh (
    employee_id INT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    salary INT
);
INSERT INTO table_kqlixh (employee_id, first_name, last_name, salary) VALUES
(1, 'John', 'Doe', 40000),
(2, 'Jane', 'Smith', 30000),
(3, 'Bob', 'Johnson', 50000),
(4, 'Alice', 'Williams', 25000);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_SR5O0T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SR5O0T(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OSD3CN INT DEFAULT 0;
    DECLARE MYSQL_VAR_VKL9ZO INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_OSD3CN
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_VKL9ZO
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_VKL9ZO = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_OSD3CN / MYSQL_VAR_VKL9ZO;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_51HY7D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_51HY7D(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Y418EP DATE;

    SELECT MAX(ORDER_DATE)
    INTO MYSQL_VAR_Y418EP
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_Y418EP IS NULL THEN
        RETURN 0;
    END IF;

    RETURN MONTH(MYSQL_VAR_Y418EP);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AIS5QM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AIS5QM(DISTANCE_MILES_PARAM INT, AIRLINE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QK057H INT DEFAULT 80;
    DECLARE MYSQL_VAR_IWT20E INT DEFAULT 50;
    DECLARE MYSQL_VAR_H7UGYB INT DEFAULT 0;
    DECLARE MYSQL_VAR_08JZNT INT DEFAULT 0;
    DECLARE MYSQL_VAR_7SG3ID INT DEFAULT 0;

    SELECT COALESCE(SAFETY_RATING, 80), COALESCE(FLEET_SIZE, 50)
    INTO MYSQL_VAR_QK057H, MYSQL_VAR_IWT20E
    FROM AIRLINES
    WHERE AIRLINE_ID = AIRLINE_ID_PARAM;

    SET MYSQL_VAR_H7UGYB = (DISTANCE_MILES_PARAM * 5) / 1000;

    SET MYSQL_VAR_08JZNT = MYSQL_VAR_H7UGYB * 20;

    SET MYSQL_VAR_7SG3ID = 100 - MYSQL_VAR_08JZNT + (MYSQL_VAR_QK057H / 10);

    RETURN GREATEST(MYSQL_VAR_7SG3ID, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FTZ9K6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FTZ9K6(ITERATIONS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TWA974 INT DEFAULT 0;
    DECLARE MYSQL_VAR_78N9UQ DECIMAL(10,6) DEFAULT 0.00;
    DECLARE MYSQL_VAR_DOJAJ4 DECIMAL(10,6) DEFAULT 0.00;
    DECLARE MYSQL_VAR_HF7PBS INT DEFAULT 0;
    DECLARE MYSQL_VAR_NLAGFO DECIMAL(10,6) DEFAULT 0.00;

    IF ITERATIONS <= 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_HF7PBS = MYSQL_FUNC_51HY7D(20);

    PI_LOOP: WHILE MYSQL_VAR_HF7PBS < ITERATIONS DO
        SET MYSQL_VAR_78N9UQ = RAND() * 2 - 1;
        SET MYSQL_VAR_DOJAJ4 = RAND() * 2 - 1;
        SET MYSQL_VAR_NLAGFO = SQRT(MYSQL_VAR_78N9UQ * MYSQL_VAR_78N9UQ + MYSQL_VAR_DOJAJ4 * MYSQL_VAR_DOJAJ4);

        IF MYSQL_VAR_NLAGFO <= 1 THEN
            SET MYSQL_VAR_TWA974 = MYSQL_VAR_TWA974 + 1;
        END IF;

        SET MYSQL_VAR_HF7PBS = MYSQL_VAR_HF7PBS + 1;
    END WHILE PI_LOOP;

    RETURN (MYSQL_FUNC_AIS5QM(20, 21) - (0) + COALESCE((MYSQL_VAR_TWA974 * 4) / ITERATIONS, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_O7MD2W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_O7MD2W(ARR_SIZE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RZD847 INT DEFAULT 0;
    DECLARE MYSQL_VAR_OJUMN1 INT DEFAULT 1;
    DECLARE MYSQL_VAR_JFINNM INT DEFAULT 0;

    IF ARR_SIZE <= 0 OR ARR_SIZE > 10000 THEN
        RETURN 0;
    END IF;

    CALC_LOOP: WHILE MYSQL_VAR_OJUMN1 <= ARR_SIZE DO
        SET MYSQL_VAR_JFINNM = MYSQL_VAR_OJUMN1 * 2;
        SET MYSQL_VAR_RZD847 = MYSQL_VAR_RZD847 + MYSQL_VAR_JFINNM;
        SET MYSQL_VAR_OJUMN1 = MYSQL_VAR_OJUMN1 + 1;
    END WHILE CALC_LOOP;

    RETURN MYSQL_VAR_RZD847;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8JTU3D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8JTU3D(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UPLG04 INT DEFAULT 0;
    DECLARE MYSQL_VAR_VV531Y INT DEFAULT 0;

    SELECT (MYSQL_FUNC_FTZ9K6(30) - (0) + COALESCE((MYSQL_FUNC_SR5O0T(20) - (0) + COALESCE(COUNT(*), 0)), 0))
    INTO MYSQL_VAR_UPLG04
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_VV531Y
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    IF MYSQL_VAR_UPLG04 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_O7MD2W(30) - (0) + COALESCE(MYSQL_VAR_VV531Y / MYSQL_VAR_UPLG04, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YDIDVT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YDIDVT(A INT, B INT, C INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JRXPVI INT DEFAULT 0;
    DECLARE MYSQL_VAR_MPUZB4 INT DEFAULT 0;

    IF A IS NULL OR B IS NULL THEN
        RETURN 0;
    END IF;

    IF B = 0 THEN
        SET MYSQL_VAR_JRXPVI = 0;
    ELSE
        SET MYSQL_VAR_JRXPVI = A / B;
    END IF;

    IF C IS NOT NULL AND C != 0 THEN
        SET MYSQL_VAR_JRXPVI = MYSQL_VAR_JRXPVI + (A / C);
        SET MYSQL_VAR_MPUZB4 = MYSQL_VAR_MPUZB4 + 1;
    END IF;

    RETURN MYSQL_VAR_JRXPVI;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UQJS1G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UQJS1G() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6DKJ4A INT DEFAULT 0;
    
    SELECT COUNT(*) INTO MYSQL_VAR_6DKJ4A
    FROM TABLE_KQLIXH
    WHERE SALARY > 35000
    ORDER BY FIRST_NAME, LAST_NAME, EMPLOYEE_ID;
    
    RETURN (MYSQL_FUNC_YDIDVT(30, 31, 32) - (0) + COALESCE(MYSQL_VAR_6DKJ4A, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1XM6OW(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FI3ATH VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE MYSQL_VAR_8PFH1K INT DEFAULT 0;
    DECLARE MYSQL_VAR_A908W4 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_UQJS1G() - (0) + COALESCE(STATUS, COALESCE(BUDGET, 0), DATEDIFF(CURDATE(), START_DATE), 0))
    INTO MYSQL_VAR_FI3ATH, MYSQL_VAR_8PFH1K, MYSQL_VAR_A908W4
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_FI3ATH != 'ACTIVE' OR MYSQL_VAR_A908W4 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_8JTU3D('test_2_0') - (0) + COALESCE(MYSQL_VAR_8PFH1K / MYSQL_VAR_A908W4, 0));
END//

DELIMITER ;