/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_RIVVFE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RIVVFE(PET_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JHIQH9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_X7VXNG INT DEFAULT 300;
    DECLARE MYSQL_VAR_G5M6RR INT DEFAULT 1;
    DECLARE MYSQL_VAR_RLT5F1 INT DEFAULT 0;

    SELECT COALESCE(AGE_YEARS, 1) INTO MYSQL_VAR_JHIQH9
    FROM INSURANCE_PET
    WHERE PET_ID = PET_ID_PARAM;

    SELECT COALESCE(B.SIZE_CATEGORY, 1) INTO MYSQL_VAR_G5M6RR
    FROM INSURANCE_PET IP
    JOIN PET_BREEDS B ON IP.BREED = B.BREED_NAME
    WHERE IP.PET_ID = PET_ID_PARAM;

    SET MYSQL_VAR_RLT5F1 = MYSQL_VAR_X7VXNG * MYSQL_VAR_G5M6RR;

    IF MYSQL_VAR_JHIQH9 > 8 THEN
        SET MYSQL_VAR_RLT5F1 = MYSQL_VAR_RLT5F1 + (MYSQL_VAR_RLT5F1 * 25 / 100);
    END IF;

    RETURN CAST(MYSQL_VAR_RLT5F1 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MX5F7P----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MX5F7P(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M17RIT INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_M17RIT
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_VAR_M17RIT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HFG0PO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HFG0PO(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_W6BF3D INT DEFAULT 0;
    DECLARE MYSQL_VAR_G9V8NF INT DEFAULT 0;
    DECLARE MYSQL_VAR_1GDILM INT DEFAULT 0;

    SELECT COUNT(DISTINCT C.CUSTOMER_ID)
    INTO MYSQL_VAR_W6BF3D
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    SELECT COUNT(DISTINCT C.CUSTOMER_ID)
    INTO MYSQL_VAR_G9V8NF
    FROM CUSTOMERS C
    JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM
    GROUP BY C.CUSTOMER_ID
    HAVING COUNT(O.ORDER_ID) > 1;

    IF MYSQL_VAR_W6BF3D = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_1GDILM = (MYSQL_VAR_G9V8NF * 100) / MYSQL_VAR_W6BF3D;

    RETURN MYSQL_FUNC_MX5F7P(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HBXEHS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HBXEHS(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QJBMFR DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_RIVVFE(10)
    INTO MYSQL_VAR_QJBMFR
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_FUNC_HFG0PO('test_2_0');
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JGBLFF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JGBLFF(RADIUS INT, ANGLE_DEGREES INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_E3NOQQ DECIMAL(10,2) DEFAULT 0.00;
    SET MYSQL_VAR_E3NOQQ = 3.14159 * RADIUS * RADIUS * ANGLE_DEGREES / 360;
    RETURN FLOOR(MYSQL_VAR_E3NOQQ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KSZFWV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KSZFWV(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_96U0ZF INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_96U0ZF
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_FUNC_JGBLFF(10, 11);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AFZQCH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AFZQCH(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_C50CYE INT DEFAULT 0;
    DECLARE MYSQL_VAR_I39HA1 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_JMWDSD DECIMAL(10,2) DEFAULT 0.00;

    SELECT COUNT(*), COALESCE(AVG(SALARY), 0),
           COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_C50CYE, MYSQL_VAR_I39HA1, MYSQL_VAR_JMWDSD
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_FUNC_KSZFWV(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TDG4S0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TDG4S0(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DXY9YQ DECIMAL(10,2) DEFAULT 0.00;
    SET MYSQL_VAR_DXY9YQ = SQRT(A * A + B * B);
    RETURN FLOOR(MYSQL_VAR_DXY9YQ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_C1CUWL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_C1CUWL(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_0SES6S INT DEFAULT 0;

    SELECT MYSQL_FUNC_AFZQCH(10)
    INTO MYSQL_VAR_0SES6S
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_FUNC_TDG4S0(20, 21);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_2DP93L----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2DP93L(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RJV8F4 INT DEFAULT 1;
    DECLARE MYSQL_VAR_J3R339 INT DEFAULT 1;

    IF N < 0 THEN
        RETURN -1;
    END IF;

    IF N = 0 OR N = 1 THEN
        RETURN 1;
    END IF;

    COUNTER_LOOP: WHILE MYSQL_VAR_J3R339 <= N DO
        SET MYSQL_VAR_RJV8F4 = MYSQL_VAR_RJV8F4 * MYSQL_VAR_J3R339;
        SET MYSQL_VAR_J3R339 = MYSQL_VAR_J3R339 + 1;
    END WHILE COUNTER_LOOP;

    RETURN MYSQL_VAR_RJV8F4;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_2NQFSW(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PNULD7 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4OHDBR DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_C1CUWL('test_1_0')
    INTO MYSQL_VAR_PNULD7
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT MYSQL_FUNC_HBXEHS(20)
    INTO MYSQL_VAR_4OHDBR
    FROM EMPLOYEES;

    RETURN MYSQL_FUNC_2DP93L(10);
END//

DELIMITER ;