/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_CHGNSC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CHGNSC(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1VSD7N INT DEFAULT 0;

    SELECT WEEK(ORDER_DATE)
    INTO MYSQL_VAR_1VSD7N
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_VAR_1VSD7N;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QHVSQ0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QHVSQ0(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6A7LNI INT DEFAULT 0;
    DECLARE MYSQL_VAR_8ICA4Z INT DEFAULT 0;
    DECLARE MYSQL_VAR_EVLX3A INT DEFAULT 0;
    DECLARE MYSQL_VAR_LO274O INT DEFAULT 0;

    SELECT COALESCE(AVG(RATING), 0), COALESCE(SUM(HELPFUL_COUNT), 0), COUNT(*)
    INTO MYSQL_VAR_6A7LNI, MYSQL_VAR_8ICA4Z, MYSQL_VAR_EVLX3A
    FROM REVIEWS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_EVLX3A = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_LO274O = (MYSQL_VAR_6A7LNI * 20) + (MYSQL_VAR_8ICA4Z / 10) + (MYSQL_VAR_EVLX3A * 2);

    RETURN CAST(MYSQL_VAR_LO274O AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8M56HY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8M56HY(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AJYF9O INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_AJYF9O
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    RETURN LEAST(MYSQL_VAR_AJYF9O, 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_826WIA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_826WIA(EMPLOYEE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PYHM8D INT DEFAULT 0;
    DECLARE MYSQL_VAR_PBCASI DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_MY5U3W INT DEFAULT 0;
    DECLARE MYSQL_VAR_YA38AK INT DEFAULT 0;
    DECLARE MYSQL_VAR_1X8RMZ DECIMAL(3,2) DEFAULT 1.00;

    SELECT COALESCE(SALARY, 0), COALESCE(PERFORMANCE_RATING, 3.00)
    INTO MYSQL_VAR_PYHM8D, MYSQL_VAR_PBCASI
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = EMPLOYEE_ID_PARAM;

    SELECT MYSQL_FUNC_8M56HY(10)
    INTO MYSQL_VAR_MY5U3W
    FROM BONUSES
    WHERE EMPLOYEE_ID = EMPLOYEE_ID_PARAM;

    SET MYSQL_VAR_1X8RMZ = MYSQL_VAR_PBCASI / 3.00;

    SET MYSQL_VAR_YA38AK = MYSQL_FUNC_QHVSQ0(10);

    IF MYSQL_VAR_PBCASI >= 4.5 THEN
        SET MYSQL_VAR_YA38AK = MYSQL_VAR_YA38AK + (MYSQL_VAR_YA38AK * 50 / 100);
    END IF;

    RETURN MYSQL_VAR_YA38AK;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3EWCOM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3EWCOM(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LM8TRL INT DEFAULT 0;
    DECLARE MYSQL_VAR_WXKV68 INT DEFAULT 1;

    SELECT COUNT(*), TIMESTAMPDIFF(MONTH, MIN(O.ORDER_DATE), CURDATE())
    INTO MYSQL_VAR_LM8TRL, MYSQL_VAR_WXKV68
    FROM ORDERS O
    WHERE O.CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_WXKV68 <= 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_LM8TRL * 100) / MYSQL_VAR_WXKV68;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P1HSIB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P1HSIB(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OJXJPF INT;
    DECLARE MYSQL_VAR_89QYHS INT;
    DECLARE MYSQL_VAR_I7EDQR INT;
    DECLARE MYSQL_VAR_J3WERA INT;

    SELECT COALESCE(AVG(PRICE), 0), MIN(PRICE), MAX(PRICE), COUNT(*)
    INTO MYSQL_VAR_OJXJPF, MYSQL_VAR_89QYHS, MYSQL_VAR_I7EDQR, MYSQL_VAR_J3WERA
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_J3WERA = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_OJXJPF;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I10A6J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I10A6J(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7Q8DAD DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_7Q8DAD
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_7Q8DAD);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JR77WN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JR77WN(PET_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_C0QQQD INT DEFAULT 0;
    DECLARE MYSQL_VAR_210VXL INT DEFAULT 0;
    DECLARE MYSQL_VAR_3XAZSF INT DEFAULT 0;
    DECLARE MYSQL_VAR_2RVVIQ INT DEFAULT 50;
    DECLARE MYSQL_VAR_WOOB29 INT DEFAULT 0;

    SELECT COALESCE(AGE_YEARS, 1), COALESCE(WEIGHT_KG, 5)
    INTO MYSQL_VAR_C0QQQD, MYSQL_VAR_210VXL
    FROM VETERINARY_CLINIC
    WHERE PET_ID = PET_ID_PARAM;

    SELECT COALESCE(TREATMENT_COST, 0) INTO MYSQL_VAR_3XAZSF
    FROM VET_VISITS
    WHERE PET_ID = PET_ID_PARAM
    ORDER BY VISIT_DATE DESC LIMIT 1;

    SET MYSQL_VAR_WOOB29 = MYSQL_VAR_2RVVIQ;

    IF MYSQL_VAR_C0QQQD < 1 THEN
        SET MYSQL_VAR_WOOB29 = MYSQL_VAR_WOOB29 + 30;
    END IF;

    IF MYSQL_VAR_210VXL > 50 THEN
        SET MYSQL_VAR_WOOB29 = MYSQL_VAR_WOOB29 + (MYSQL_VAR_210VXL - 50);
    END IF;

    RETURN CAST(MYSQL_VAR_WOOB29 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8OI2O9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8OI2O9(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BFEGSV INT DEFAULT 0;
    DECLARE MYSQL_VAR_WMIU0S INT DEFAULT 0;
    DECLARE MYSQL_VAR_QH6LQ8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_A2YSP8 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_BFEGSV
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_QH6LQ8
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    CASE V_PLAN_TYPE
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_WMIU0S = MYSQL_FUNC_JR77WN(10);
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_WMIU0S = MYSQL_FUNC_826WIA(30);
        WHEN 'BASIC' THEN SET MYSQL_VAR_WMIU0S = MYSQL_FUNC_P1HSIB(20);
        ELSE SET MYSQL_VAR_WMIU0S = MYSQL_FUNC_3EWCOM(20);
    END CASE;

    IF MYSQL_VAR_BFEGSV = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_A2YSP8 = MYSQL_FUNC_I10A6J(30);

    RETURN MYSQL_VAR_A2YSP8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TX4QU9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TX4QU9(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UFWUUW INT DEFAULT 0;
    DECLARE MYSQL_VAR_P6BU22 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_943ZLA DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_SM2J49 INT DEFAULT 0;

    SELECT MONTH(CURDATE())
    INTO MYSQL_VAR_UFWUUW;

    SELECT COALESCE(AVG(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_P6BU22
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
    GROUP BY YEAR(ORDER_DATE), MONTH(ORDER_DATE);

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_943ZLA
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
    AND YEAR(ORDER_DATE) = YEAR(CURDATE())
    AND MONTH(ORDER_DATE) = MYSQL_VAR_UFWUUW;

    IF MYSQL_VAR_P6BU22 = 0 THEN
        RETURN 100;
    END IF;

    SET MYSQL_VAR_SM2J49 = (MYSQL_VAR_943ZLA * 100) / MYSQL_VAR_P6BU22;

    RETURN MYSQL_VAR_SM2J49;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4KDMSH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4KDMSH(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2JDOQA DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_8OI2O9(10)
    INTO MYSQL_VAR_2JDOQA
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN MYSQL_FUNC_TX4QU9(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8S6NUP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8S6NUP(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DXNSKH VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE MYSQL_VAR_VE8DYR INT DEFAULT 0;
    DECLARE MYSQL_VAR_0AJE11 INT DEFAULT 0;
    DECLARE MYSQL_VAR_IA5P4Z INT DEFAULT 0;

    SELECT CHANNEL, COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_DXNSKH, MYSQL_VAR_VE8DYR
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_0AJE11
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_VE8DYR = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_IA5P4Z = ((MYSQL_VAR_0AJE11 - MYSQL_VAR_VE8DYR) * 100) / MYSQL_VAR_VE8DYR;

    RETURN MYSQL_VAR_IA5P4Z;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_88YPMX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_88YPMX(RESTAURANT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UAHBCE INT DEFAULT 0;
    DECLARE MYSQL_VAR_31NF2F INT DEFAULT 0;
    DECLARE MYSQL_VAR_WR6WOT INT DEFAULT 0;
    DECLARE MYSQL_VAR_0CN7CJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_U2CFZD INT DEFAULT 0;

    SELECT COALESCE(AVG(RATING), 0), COALESCE(AVG(FOOD_QUALITY), 0), COALESCE(AVG(SERVICE_SCORE), 0), COUNT(*)
    INTO MYSQL_VAR_UAHBCE, MYSQL_VAR_31NF2F, MYSQL_VAR_WR6WOT, MYSQL_VAR_0CN7CJ
    FROM RESTAURANT_REVIEWS
    WHERE RESTAURANT_ID = RESTAURANT_ID_PARAM;

    IF MYSQL_VAR_0CN7CJ = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_U2CFZD = (MYSQL_VAR_UAHBCE * 40 / 100) + (MYSQL_VAR_31NF2F * 35 / 100) + (MYSQL_VAR_WR6WOT * 25 / 100);

    IF MYSQL_VAR_0CN7CJ > 100 THEN
        SET MYSQL_VAR_U2CFZD = MYSQL_VAR_U2CFZD + 10;
    END IF;

    RETURN CAST(MYSQL_VAR_U2CFZD AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XAAAUE(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JJSDVU DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_NGWEF3 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_EYA8PT INT DEFAULT 0;

    SELECT MYSQL_FUNC_4KDMSH(20)
    INTO MYSQL_VAR_JJSDVU
    FROM ORDER_ITEMS OI
    WHERE OI.PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT MYSQL_FUNC_8S6NUP(20)
    INTO MYSQL_VAR_NGWEF3
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    IF MYSQL_VAR_NGWEF3 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_EYA8PT = MYSQL_FUNC_CHGNSC(30);

    RETURN MYSQL_FUNC_88YPMX(30);
END//

DELIMITER ;