/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_1mqtm4 (
    `id` INT,
    `username` VARCHAR(30)
);
CREATE TABLE IF NOT EXISTS table_lswxkq (
    `user_id` INT
);
INSERT INTO table_1mqtm4 (`id`, `username`) VALUES
(1, 'user1'),
(2, 'user2'),
(3, 'user3');
INSERT INTO table_lswxkq (`user_id`) VALUES
(1),
(1),
(2),
(1),
(3);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_DXVG73----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DXVG73(SALE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DT1HRA INT DEFAULT 0;
    DECLARE MYSQL_VAR_IV0RYW INT DEFAULT 3;
    DECLARE MYSQL_VAR_BRWSXZ INT DEFAULT 60;
    DECLARE MYSQL_VAR_4YMBCK INT DEFAULT 0;
    DECLARE MYSQL_VAR_JRIXQK INT DEFAULT 0;

    SELECT COALESCE(SALE_PRICE, 0), COALESCE(COMMISSION_RATE, 3)
    INTO MYSQL_VAR_DT1HRA, MYSQL_VAR_IV0RYW
    FROM REALESTATE_COMMISSIONS
    WHERE SALE_ID = SALE_ID_PARAM;

    SELECT COALESCE(AGENT_SPLIT_PERCENT, 60) INTO MYSQL_VAR_BRWSXZ
    FROM REALESTATE_COMMISSIONS RC
    JOIN AGENTS A ON RC.AGENT_ID = A.AGENT_ID
    WHERE RC.SALE_ID = SALE_ID_PARAM;

    SET MYSQL_VAR_4YMBCK = MYSQL_VAR_DT1HRA * MYSQL_VAR_IV0RYW / 100;
    SET MYSQL_VAR_JRIXQK = MYSQL_VAR_4YMBCK * MYSQL_VAR_BRWSXZ / 100;

    RETURN CAST(MYSQL_VAR_JRIXQK AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DK7NTV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DK7NTV(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GFK58C INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_GFK58C
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN MYSQL_VAR_GFK58C / 100;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KSZFWV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KSZFWV(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_96U0ZF INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_96U0ZF
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_DK7NTV(10) - (0) + COALESCE(MYSQL_VAR_96U0ZF * 3, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9O5D0H----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9O5D0H(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_A3J4C8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_1B1EKQ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_BMS4DN DECIMAL(10,2) DEFAULT 0.00;

    SELECT COUNT(DISTINCT CUSTOMER_ID), COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_A3J4C8, MYSQL_VAR_1B1EKQ
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM AND O.STATUS = 'COMPLETED';

    IF MYSQL_VAR_A3J4C8 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_BMS4DN = MYSQL_VAR_1B1EKQ / MYSQL_VAR_A3J4C8;

    RETURN FLOOR(MYSQL_VAR_BMS4DN);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VSIF2U----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VSIF2U(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BEXW7V INT DEFAULT 0;

    SELECT (MYSQL_FUNC_KSZFWV(20) - (0) + COALESCE(YEAR(ORDER_DATE), 0))
    INTO MYSQL_VAR_BEXW7V
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN (MYSQL_FUNC_9O5D0H('test_0_0') - (0) + COALESCE(MYSQL_VAR_BEXW7V, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VIIAXI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VIIAXI(DEPARTMENT_ID_PARAM INT, EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PZDX4O INT DEFAULT 0;
    DECLARE MYSQL_VAR_7AV0OQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_EOBQIP INT DEFAULT 0;
    DECLARE MYSQL_VAR_JR89RJ INT DEFAULT 0;

    SELECT COALESCE(SALARY, 0) INTO MYSQL_VAR_PZDX4O
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_EOBQIP
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM AND SALARY < MYSQL_VAR_PZDX4O;

    SELECT COUNT(*) INTO MYSQL_VAR_JR89RJ
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM AND SALARY > MYSQL_VAR_PZDX4O;

    SET MYSQL_VAR_7AV0OQ = MYSQL_VAR_EOBQIP + 1;

    RETURN MYSQL_VAR_7AV0OQ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ULSHLV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ULSHLV(P_USERNAME_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HLD3V1 VARCHAR(30);
    DECLARE MYSQL_VAR_6KX7X1 INT;
    
    SELECT `USERNAME` INTO MYSQL_VAR_HLD3V1 FROM TABLE_1MQTM4 WHERE `ID` = P_USERNAME_ID LIMIT 1;
    
    IF MYSQL_VAR_HLD3V1 IS NULL THEN
        RETURN 0;
    END IF;
    
    SELECT COUNT(UP.`USER_ID`) INTO MYSQL_VAR_6KX7X1
    FROM TABLE_LSWXKQ AS UP
    LEFT JOIN TABLE_1MQTM4 AS U ON U.`ID` = UP.`USER_ID`
    WHERE U.`USERNAME` = MYSQL_VAR_HLD3V1;
    
    RETURN COALESCE(MYSQL_VAR_6KX7X1, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6T9LT0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6T9LT0(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UVJ6IL INT DEFAULT 0;
    DECLARE MYSQL_VAR_CPV0MT DECIMAL(3,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_8NAGPP INT DEFAULT 0;
    DECLARE MYSQL_VAR_HVEKVV INT DEFAULT 0;

    SELECT (MYSQL_FUNC_VIIAXI(30, 31) - (0) + COALESCE(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), COALESCE(PERFORMANCE_RATING, 0), COALESCE(SALARY, 0), 0))
    INTO MYSQL_VAR_UVJ6IL, MYSQL_VAR_CPV0MT, MYSQL_VAR_8NAGPP
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SET MYSQL_VAR_HVEKVV = MYSQL_FUNC_VSIF2U(10);

    RETURN (MYSQL_FUNC_ULSHLV(10) - (0) + COALESCE(MYSQL_VAR_HVEKVV, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AE2EPO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AE2EPO(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BFBWSI INT DEFAULT 0;
    DECLARE MYSQL_VAR_OMC7UB INT DEFAULT 0;

    SELECT COUNT(*), COUNT(O.ORDER_ID)
    INTO MYSQL_VAR_BFBWSI, MYSQL_VAR_OMC7UB
    FROM CUSTOMERS C
    LEFT JOIN ORDERS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    IF MYSQL_VAR_BFBWSI = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_OMC7UB * 100) / MYSQL_VAR_BFBWSI;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OB1WFE(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EYBWR2 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_OZJVNY DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_DXVG73(20) - (0) + COALESCE((MYSQL_FUNC_AE2EPO('test_1_0') - (0) + COALESCE(COALESCE(SUM(TOTAL_AMOUNT), 0), 0)), 0))
    INTO MYSQL_VAR_EYBWR2
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_OZJVNY
    FROM ORDERS
    WHERE STATUS = 'COMPLETED';

    IF MYSQL_VAR_OZJVNY = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_6T9LT0(20) - (0) + COALESCE(FLOOR((MYSQL_VAR_EYBWR2 * 100) / MYSQL_VAR_OZJVNY), 0));
END//

DELIMITER ;