/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_M57IYZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M57IYZ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_X6R8Y0 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_X6R8Y0
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_X6R8Y0 / 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UY9PPR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UY9PPR(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NUYZS7 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_M57IYZ(20) - (0) + COALESCE(COUNT(DISTINCT S.CUSTOMER_ID), 0))
    INTO MYSQL_VAR_NUYZS7
    FROM SUBSCRIPTIONS S
    JOIN CUSTOMERS C ON S.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_NUYZS7;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YJORL9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YJORL9(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RLW962 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_RLW962
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_RLW962 / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S7A9RG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S7A9RG(NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2E76FD INT DEFAULT 0;
    DECLARE MYSQL_VAR_RO6869 INT;
    DECLARE MYSQL_VAR_4VQQRL INT;

    SET MYSQL_VAR_4VQQRL = ABS(NUM);

    SUM_LOOP: WHILE MYSQL_VAR_4VQQRL > 0 DO
        SET MYSQL_VAR_RO6869 = MYSQL_VAR_4VQQRL MOD 10;
        SET MYSQL_VAR_2E76FD = MYSQL_VAR_2E76FD + MYSQL_VAR_RO6869;
        SET MYSQL_VAR_4VQQRL = MYSQL_VAR_4VQQRL DIV 10;
    END WHILE SUM_LOOP;

    RETURN MYSQL_VAR_2E76FD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9NVDOJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9NVDOJ(ANIMAL_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZLWXHR INT DEFAULT 0;
    DECLARE MYSQL_VAR_AVGWJO INT DEFAULT 100;
    DECLARE MYSQL_VAR_FGZVK7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_WO7FT7 INT DEFAULT 0;

    SELECT TIMESTAMPDIFF(MONTH, CURDATE(), CURDATE()) - TIMESTAMPDIFF(MONTH, CURDATE(), CURDATE()),
           COALESCE(ADOPTION_FEE, 100)
    INTO MYSQL_VAR_ZLWXHR, MYSQL_VAR_AVGWJO
    FROM PET_SHELTER_ANIMALS
    WHERE ANIMAL_ID = ANIMAL_ID_PARAM;

    SET MYSQL_VAR_ZLWXHR = 12;

    SELECT COUNT(*) INTO MYSQL_VAR_FGZVK7
    FROM ADOPTION_APPLICATIONS
    WHERE ANIMAL_ID = ANIMAL_ID_PARAM AND STATUS = 'PENDING';

    SET MYSQL_VAR_WO7FT7 = 100 - MYSQL_VAR_ZLWXHR - (MYSQL_VAR_AVGWJO / 10) + (MYSQL_VAR_FGZVK7 * 10);

    RETURN CAST(MYSQL_VAR_WO7FT7 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9KCBSB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9KCBSB(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7U9RGH INT DEFAULT 0;

    SELECT SUPPLIER_ID
    INTO MYSQL_VAR_7U9RGH
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COUNT(DISTINCT CATEGORY_ID)
    INTO @V_CATEGORY_COUNT
    FROM PRODUCTS
    WHERE SUPPLIER_ID = MYSQL_VAR_7U9RGH;

    RETURN @V_CATEGORY_COUNT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TRMH9I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TRMH9I(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8KOQGQ INT DEFAULT 2;
    DECLARE MYSQL_VAR_LA6QNT INT DEFAULT 0;

    IF N <= 1 THEN RETURN 0; END IF;
    IF N <= 3 THEN RETURN 1; END IF;
    IF N % 2 = 0 OR N % 3 = 0 THEN RETURN 0; END IF;

    SET MYSQL_VAR_LA6QNT = MYSQL_FUNC_9KCBSB(20);
    SET MYSQL_VAR_8KOQGQ = MYSQL_FUNC_9NVDOJ(10);

    PRIME_LOOP: WHILE MYSQL_VAR_8KOQGQ <= MYSQL_VAR_LA6QNT DO
        IF N % MYSQL_VAR_8KOQGQ = 0 OR N % (MYSQL_VAR_8KOQGQ + 2) = 0 THEN
            RETURN 0;
        END IF;
        SET MYSQL_VAR_8KOQGQ = MYSQL_VAR_8KOQGQ + 6;
    END WHILE PRIME_LOOP;

    RETURN 1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WWG3XI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WWG3XI(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_P5MVVD INT DEFAULT 0;
    DECLARE MYSQL_VAR_IK1PA3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_2LAFZ2 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_S7A9RG(20) - (0) + COALESCE(COALESCE(RELIABILITY_SCORE, 80), COALESCE(LEAD_TIME_DAYS, 7), 0))
    INTO MYSQL_VAR_P5MVVD, MYSQL_VAR_IK1PA3
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_2LAFZ2 = MYSQL_FUNC_YJORL9(30);

    IF MYSQL_VAR_IK1PA3 > 30 THEN
        SET MYSQL_VAR_2LAFZ2 = MYSQL_VAR_2LAFZ2 + 20;
    ELSEIF MYSQL_VAR_IK1PA3 > 14 THEN
        SET MYSQL_VAR_2LAFZ2 = MYSQL_VAR_2LAFZ2 + 10;
    END IF;

    RETURN (MYSQL_FUNC_TRMH9I(10) - (0) + COALESCE(MYSQL_VAR_2LAFZ2, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TYAU77(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_B24S87 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_YGY7S6 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_V9P6J8 INT DEFAULT 0;

    SELECT COALESCE(SHIPPING_COST, 0), COALESCE(TOTAL_AMOUNT, 1)
    INTO MYSQL_VAR_B24S87, MYSQL_VAR_YGY7S6
    FROM ORDERS O
    LEFT JOIN SHIPMENTS S ON O.ORDER_ID = S.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_V9P6J8 = MYSQL_FUNC_WWG3XI(30);

    RETURN (MYSQL_FUNC_UY9PPR('test_2_0') - (0) + COALESCE(MYSQL_VAR_V9P6J8, 0));
END//

DELIMITER ;