/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_LBIJLR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LBIJLR(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SEKNO0 DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_YWF5IC DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_QQQYU1 INT DEFAULT 0;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_SEKNO0
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(STDDEV(SALARY), 0) / 1000
    INTO MYSQL_VAR_YWF5IC
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_QQQYU1 = (MYSQL_VAR_SEKNO0 * 15) - (MYSQL_VAR_YWF5IC * 5);

    RETURN GREATEST(MYSQL_VAR_QQQYU1, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9FWZ13----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9FWZ13(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9FBV1T INT DEFAULT 0;

    SELECT (MYSQL_FUNC_LBIJLR(30) - (0) + COALESCE(YEAR(MIN(ORDER_DATE)), 0))
    INTO MYSQL_VAR_9FBV1T
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_9FBV1T;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BLX130----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BLX130(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GMUGGZ INT DEFAULT 0;

    SELECT (MYSQL_FUNC_9FWZ13(20) - (0) + COALESCE(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE()), 0))
    INTO MYSQL_VAR_GMUGGZ
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_VAR_GMUGGZ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_COMSCU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_COMSCU(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SFCBG4 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_SFCBG4
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_SFCBG4);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S7D1BH(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VB1ZE7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_M8SWZT VARCHAR(20) DEFAULT 'INACTIVE';

    SELECT (MYSQL_FUNC_COMSCU(20) - (0) + COALESCE(COALESCE(MONTHLY_COST, 0), STATUS, 0))
    INTO MYSQL_VAR_VB1ZE7, MYSQL_VAR_M8SWZT
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_M8SWZT != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_BLX130(10) - (0) + COALESCE(MYSQL_VAR_VB1ZE7 * 5, 0));
END//

DELIMITER ;