/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_YA52TQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YA52TQ(CLAIM_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NGFMB0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_CV6PNH INT DEFAULT 0;
    DECLARE MYSQL_VAR_ORVXWK INT DEFAULT 0;
    DECLARE MYSQL_VAR_JI6XEL INT DEFAULT 0;

    SELECT COALESCE(CLAIM_AMOUNT, 0), DATEDIFF(CURDATE(), FILING_DATE)
    INTO MYSQL_VAR_NGFMB0, MYSQL_VAR_CV6PNH
    FROM INSURANCE_CLAIMS
    WHERE CLAIM_ID = CLAIM_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_ORVXWK
    FROM POLICY_TRANSACTIONS
    WHERE POLICY_ID = (SELECT POLICY_ID FROM INSURANCE_CLAIMS WHERE CLAIM_ID = CLAIM_ID_PARAM);

    SET MYSQL_VAR_JI6XEL = (MYSQL_VAR_ORVXWK * 5) - MYSQL_VAR_CV6PNH;

    IF MYSQL_VAR_NGFMB0 > 50000 THEN
        SET MYSQL_VAR_JI6XEL = MYSQL_VAR_JI6XEL - 20;
    END IF;

    RETURN CAST(MYSQL_VAR_JI6XEL AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AV39HM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AV39HM(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_95XIBT INT DEFAULT 0;
    DECLARE MYSQL_VAR_W7O61A INT DEFAULT 2;
    DECLARE MYSQL_VAR_602S25 INT DEFAULT 0;

    IF N <= 1 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_602S25 = N;
    SET MYSQL_VAR_W7O61A = 2;

    FACTOR_LOOP: WHILE MYSQL_VAR_W7O61A <= MYSQL_VAR_602S25 DO
        IF MYSQL_VAR_602S25 % MYSQL_VAR_W7O61A = 0 THEN
            SET MYSQL_VAR_95XIBT = MYSQL_VAR_95XIBT + 1;
            SET MYSQL_VAR_602S25 = MYSQL_VAR_602S25 / MYSQL_VAR_W7O61A;
        ELSE
            SET MYSQL_VAR_W7O61A = MYSQL_VAR_W7O61A + 1;
        END IF;
    END WHILE FACTOR_LOOP;

    RETURN MYSQL_VAR_95XIBT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4EEBVL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4EEBVL(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D5CYB4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_A08NE3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_K1M7V7 INT DEFAULT 0;

    SELECT MYSQL_FUNC_YA52TQ(20)
    INTO MYSQL_VAR_D5CYB4, MYSQL_VAR_K1M7V7
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    SELECT MYSQL_FUNC_AV39HM(20)
    INTO MYSQL_VAR_A08NE3
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = MYSQL_VAR_K1M7V7 AND SALARY > MYSQL_VAR_D5CYB4;

    RETURN MYSQL_VAR_A08NE3;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AWZ3WR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AWZ3WR(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_I6EX5D INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_I6EX5D
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_I6EX5D / 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ENB4I7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ENB4I7(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3RHDU4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZBDLVQ INT DEFAULT N;
    DECLARE MYSQL_VAR_MAPY5G INT DEFAULT 0;

    WHILE N > 0 DO
        SET MYSQL_VAR_MAPY5G = N % 10;
        SET MYSQL_VAR_3RHDU4 = MYSQL_VAR_3RHDU4 * 10 + MYSQL_VAR_MAPY5G;
        SET N = N / 10;
    END WHILE;

    IF MYSQL_VAR_3RHDU4 = MYSQL_VAR_ZBDLVQ THEN
        RETURN 1;
    END IF;

    RETURN MYSQL_FUNC_AWZ3WR('test_1_0');
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J5135R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J5135R(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XIKD8Q INT DEFAULT 0;

    SELECT MYSQL_FUNC_ENB4I7(20)
    INTO MYSQL_VAR_XIKD8Q
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_XIKD8Q;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7IPX8J() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N6KHOC INT DEFAULT 0;
    
    SELECT MYSQL_FUNC_J5135R(20) INTO MYSQL_VAR_N6KHOC FROM TABLE_9QIJ7M.`TABLE3`;
    
    RETURN MYSQL_FUNC_4EEBVL(20);
END//

DELIMITER ;