/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_XR216L----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XR216L(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3K9U7B INT DEFAULT 0;
    DECLARE MYSQL_VAR_22OM3O INT DEFAULT 0;
    DECLARE MYSQL_VAR_LEZT3U INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_3K9U7B
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_22OM3O
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_22OM3O = 0 THEN
        RETURN MYSQL_VAR_3K9U7B;
    END IF;

    SET MYSQL_VAR_LEZT3U = MYSQL_VAR_3K9U7B / MYSQL_VAR_22OM3O;

    RETURN MYSQL_VAR_LEZT3U;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RD0CHM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RD0CHM(COURSE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FLF17I INT DEFAULT 1;
    DECLARE MYSQL_VAR_KU8LTZ INT DEFAULT 30;
    DECLARE MYSQL_VAR_YZ7EBH INT DEFAULT 0;
    DECLARE MYSQL_VAR_SU3975 DECIMAL(4,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_QD48A0 INT DEFAULT 0;

    SELECT COALESCE(DIFFICULTY_LEVEL, 1), COALESCE(ENROLLMENT_CAPACITY, 30)
    INTO MYSQL_VAR_FLF17I, MYSQL_VAR_KU8LTZ
    FROM COURSES
    WHERE COURSE_ID = COURSE_ID_PARAM;

    SELECT (MYSQL_FUNC_XR216L(30) - (0) + COALESCE(COUNT(*), 0)) INTO MYSQL_VAR_YZ7EBH
    FROM ENROLLMENTS
    WHERE COURSE_ID = COURSE_ID_PARAM;

    SELECT COALESCE(AVG(CASE GRADE WHEN 'F' THEN 1 ELSE 0 END) * 100, 0)
    INTO MYSQL_VAR_SU3975
    FROM ENROLLMENTS
    WHERE COURSE_ID = COURSE_ID_PARAM;

    SET MYSQL_VAR_QD48A0 = (MYSQL_VAR_FLF17I * 20) + ((MYSQL_VAR_YZ7EBH * 100) / MYSQL_VAR_KU8LTZ) + MYSQL_VAR_SU3975;

    RETURN FLOOR(MYSQL_VAR_QD48A0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_K698WX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_K698WX(DISTANCE_MILES_PARAM INT, TRUCK_SIZE_PARAM VARCHAR(20)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BRY2U2 INT DEFAULT 2;
    DECLARE MYSQL_VAR_F0BBJ4 INT DEFAULT 1;
    DECLARE MYSQL_VAR_FY4FTY INT DEFAULT 50;
    DECLARE MYSQL_VAR_W3E78Z INT DEFAULT 0;

    CASE TRUCK_SIZE_PARAM
        WHEN 'SMALL' THEN SET MYSQL_VAR_F0BBJ4 = 1;
        WHEN 'MEDIUM' THEN SET MYSQL_VAR_F0BBJ4 = 2;
        WHEN 'LARGE' THEN SET MYSQL_VAR_F0BBJ4 = 3;
        WHEN 'EXTRA_LARGE' THEN SET MYSQL_VAR_F0BBJ4 = 4;
        ELSE SET MYSQL_VAR_F0BBJ4 = 1;
    END CASE;

    SET MYSQL_VAR_W3E78Z = (DISTANCE_MILES_PARAM * MYSQL_VAR_BRY2U2 * MYSQL_VAR_F0BBJ4) + MYSQL_VAR_FY4FTY;

    IF DISTANCE_MILES_PARAM > 500 THEN
        SET MYSQL_VAR_W3E78Z = MYSQL_VAR_W3E78Z - (MYSQL_VAR_W3E78Z * 10 / 100);
    END IF;

    RETURN CAST(MYSQL_VAR_W3E78Z AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z55XRT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z55XRT(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9E3TAS INT DEFAULT 0;

    SELECT YEAR(HIRE_DATE)
    INTO MYSQL_VAR_9E3TAS
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_VAR_9E3TAS - 2000;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EBADOC(MEMBER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZNSUD8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZSUKQX INT DEFAULT 0;
    DECLARE MYSQL_VAR_1SCJD3 INT DEFAULT 50;
    DECLARE MYSQL_VAR_BOIDEZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_8BS9B2 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_Z55XRT(20) - (0) + COALESCE(COALESCE(MONTHLY_FEE, 0), 0)) INTO MYSQL_VAR_ZNSUD8
    FROM GYM_MEMBERS
    WHERE MEMBER_ID = MEMBER_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_8BS9B2
    FROM TRAINER_SESSIONS
    WHERE MEMBER_ID = MEMBER_ID_PARAM
      AND SESSION_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SET MYSQL_VAR_1SCJD3 = MYSQL_FUNC_K698WX(10, 'test_0_1');
    SET MYSQL_VAR_BOIDEZ = MYSQL_VAR_ZNSUD8 + MYSQL_VAR_1SCJD3;

    RETURN (MYSQL_FUNC_RD0CHM(10) - (0) + COALESCE(MYSQL_VAR_BOIDEZ, 0));
END//

DELIMITER ;