/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_XG7Z1J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XG7Z1J(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JLHTT9 VARCHAR(50) DEFAULT '';
    DECLARE MYSQL_VAR_EUWK5E INT DEFAULT 0;
    DECLARE MYSQL_VAR_EY0BFW INT DEFAULT 0;
    DECLARE MYSQL_VAR_R04DY9 INT DEFAULT 0;

    SELECT COUNTRY
    INTO MYSQL_VAR_JLHTT9
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_EUWK5E
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = MYSQL_VAR_JLHTT9;

    SELECT COUNT(*)
    INTO MYSQL_VAR_EY0BFW
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_EUWK5E = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_R04DY9 = (MYSQL_VAR_EY0BFW * 100) / MYSQL_VAR_EUWK5E;

    RETURN MYSQL_VAR_R04DY9;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_K3EM8Q----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_K3EM8Q(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LT293B INT DEFAULT 1;
    DECLARE MYSQL_VAR_WGLVKP INT DEFAULT 1;

    IF N < 0 THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_WGLVKP <= N DO
        SET MYSQL_VAR_LT293B = MYSQL_VAR_LT293B * MYSQL_VAR_WGLVKP;
        SET MYSQL_VAR_WGLVKP = MYSQL_VAR_WGLVKP + 1;
    END WHILE;

    RETURN MYSQL_VAR_LT293B;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_51HY7D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_51HY7D(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Y418EP DATE;

    SELECT MAX(ORDER_DATE)
    INTO MYSQL_VAR_Y418EP
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_Y418EP IS NULL THEN
        RETURN 0;
    END IF;

    RETURN MONTH(MYSQL_VAR_Y418EP);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_B2YFU2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_B2YFU2(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IKS0UO INT DEFAULT 0;
    DECLARE MYSQL_VAR_VXRLJ0 INT DEFAULT 1;

    SELECT COUNT(*), DATEDIFF(MAX(ORDER_DATE), MIN(ORDER_DATE)) + 1
    INTO MYSQL_VAR_IKS0UO, MYSQL_VAR_VXRLJ0
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_IKS0UO <= 1 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_IKS0UO * 30) / MYSQL_VAR_VXRLJ0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_WTOM4W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WTOM4W(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XVDZJ1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_LSAXX6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_86K3GU INT DEFAULT 0;
    DECLARE MYSQL_VAR_IJVG1M INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0), COALESCE(SPENT_AMOUNT, 0)
    INTO MYSQL_VAR_XVDZJ1, MYSQL_VAR_LSAXX6
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_XVDZJ1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_86K3GU = MYSQL_FUNC_K3EM8Q(20);
    SET MYSQL_VAR_IJVG1M = MYSQL_FUNC_51HY7D(20);

    RETURN MYSQL_FUNC_B2YFU2(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TDYPL2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TDYPL2(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DMUJP9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MLTTH3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MZSUDY DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(*)
    INTO MYSQL_VAR_DMUJP9
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MYSQL_FUNC_XG7Z1J(10)
    INTO MYSQL_VAR_MLTTH3
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_MLTTH3 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_MZSUDY = MYSQL_FUNC_WTOM4W(30);

    RETURN FLOOR(MYSQL_VAR_MZSUDY);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I0MWJF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I0MWJF(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1SBHSI VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_A9AEI9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0R0IRL INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0), TIMESTAMPDIFF(MONTH, START_DATE, CURDATE())
    INTO MYSQL_VAR_1SBHSI, MYSQL_VAR_A9AEI9, MYSQL_VAR_0R0IRL
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_1SBHSI != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_A9AEI9 * MYSQL_VAR_0R0IRL;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KUXEC6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KUXEC6(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IT9BOK DATETIME;
    DECLARE MYSQL_VAR_EBIUBL DATETIME;
    DECLARE MYSQL_VAR_7Y1VGM INT DEFAULT 15;
    DECLARE MYSQL_VAR_EK9J4K INT DEFAULT 0;
    DECLARE MYSQL_VAR_8EPSF2 INT DEFAULT 0;

    SELECT O.ORDER_TIME, O.DELIVERY_TIME
    INTO MYSQL_VAR_IT9BOK, MYSQL_VAR_EBIUBL
    FROM FOOD_ORDERS O
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_IT9BOK IS NULL THEN
        RETURN 0;
    END IF;

    IF MYSQL_VAR_EBIUBL IS NULL THEN
        SET MYSQL_VAR_EBIUBL = NOW();
    END IF;

    SET MYSQL_VAR_EK9J4K = TIMESTAMPDIFF(MINUTE, MYSQL_VAR_IT9BOK, MYSQL_VAR_EBIUBL);

    SET MYSQL_VAR_8EPSF2 = 100 - (MYSQL_VAR_EK9J4K - MYSQL_VAR_7Y1VGM);

    IF MYSQL_VAR_8EPSF2 < 0 THEN
        SET MYSQL_VAR_8EPSF2 = 0;
    END IF;

    RETURN MYSQL_VAR_8EPSF2;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_COMSCU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_COMSCU(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SFCBG4 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_SFCBG4
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_SFCBG4);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I6AKM1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I6AKM1(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D242CV DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_865KIW DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_3K1B51 INT DEFAULT 0;

    SELECT MYSQL_FUNC_I0MWJF(20)
    INTO MYSQL_VAR_D242CV
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT MYSQL_FUNC_COMSCU(20)
    INTO MYSQL_VAR_865KIW
    FROM PRODUCTS
    WHERE CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    SET MYSQL_VAR_3K1B51 = MYSQL_FUNC_KUXEC6(30);

    RETURN MYSQL_VAR_3K1B51;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IAX85K(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VYRDM9 INT DEFAULT 0;

    SELECT MYSQL_FUNC_I6AKM1(10)
    INTO MYSQL_VAR_VYRDM9
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_TDYPL2(10);
END//

DELIMITER ;