/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_6JTA8K----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6JTA8K(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7GOS61 INT DEFAULT 1;
    DECLARE MYSQL_VAR_NUX5VN INT DEFAULT 1;

    IF N < 0 THEN
        RETURN 0;
    END IF;

    IF N > 12 THEN
        SET N = 12;
    END IF;

    WHILE MYSQL_VAR_NUX5VN <= N DO
        SET MYSQL_VAR_7GOS61 = MYSQL_VAR_7GOS61 * MYSQL_VAR_NUX5VN;
        SET MYSQL_VAR_NUX5VN = MYSQL_VAR_NUX5VN + 1;
    END WHILE;

    RETURN MYSQL_VAR_7GOS61;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1K7PC8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1K7PC8(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LEBMVS INT DEFAULT 0;
    DECLARE MYSQL_VAR_AQXI8Y INT DEFAULT 0;
    DECLARE MYSQL_VAR_TKVGWP INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO MYSQL_VAR_LEBMVS
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_AQXI8Y
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_TKVGWP = MYSQL_VAR_LEBMVS - MYSQL_VAR_AQXI8Y;

    RETURN MYSQL_VAR_TKVGWP;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_M57IYZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M57IYZ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_X6R8Y0 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_X6R8Y0
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_X6R8Y0 / 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1GOY23----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1GOY23() RETURNS INT
BEGIN
SIGNAL SQLSTATE '01000' SET MESSAGE_TEXT = 'THIS IS A WARNING MESSAGE';
    RETURN 44;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GONYUZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GONYUZ(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5HBUUS DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_5HBUUS
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN FLOOR(MYSQL_VAR_5HBUUS);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DQ097Y----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DQ097Y(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TMAABX INT DEFAULT 0;
    DECLARE MYSQL_VAR_W6OHUE INT DEFAULT 0;

    SELECT COALESCE(DATEDIFF(CURDATE(), MAX(ORDER_DATE)), 999)
    INTO MYSQL_VAR_TMAABX
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_W6OHUE = 100 - LEAST(MYSQL_VAR_TMAABX, 100);

    RETURN MYSQL_VAR_W6OHUE;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FIZG0X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FIZG0X(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XXPA8S DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_B7ALZK INT DEFAULT 0;
    DECLARE MYSQL_VAR_BNMH6W DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_LZC97F INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_XXPA8S
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*), COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_B7ALZK, MYSQL_VAR_BNMH6W
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_LZC97F = (MYSQL_VAR_XXPA8S * 20) + (MYSQL_VAR_B7ALZK * 5) + (MYSQL_VAR_BNMH6W / 10);

    RETURN MYSQL_VAR_LZC97F;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XO4DVP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XO4DVP(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PFGPB3 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_FIZG0X(20) - (0) + COALESCE(COALESCE(TOTAL_AMOUNT, 0), 0))
    INTO MYSQL_VAR_PFGPB3
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_PFGPB3);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RVJPST----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RVJPST(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YHJ82J INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_YHJ82J
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_YHJ82J;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J4Q2FX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J4Q2FX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EWK5IY VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_2X1Z17 INT DEFAULT 0;
    DECLARE MYSQL_VAR_6JYUCS VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_N684PH INT DEFAULT 0;

    SELECT PLAN_TYPE, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_EWK5IY, MYSQL_VAR_2X1Z17
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT TIER_LEVEL
    INTO MYSQL_VAR_6JYUCS
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    CASE MYSQL_VAR_EWK5IY
        WHEN 'BASIC' THEN SET MYSQL_VAR_N684PH = MYSQL_FUNC_DQ097Y(30);
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_N684PH = 40;
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_N684PH = MYSQL_FUNC_XO4DVP(10);
        ELSE SET MYSQL_VAR_N684PH = MYSQL_FUNC_1GOY23();
    END CASE;

    CASE MYSQL_VAR_6JYUCS
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_N684PH = MYSQL_FUNC_GONYUZ('test_0_0');
        WHEN 'GOLD' THEN SET MYSQL_VAR_N684PH = MYSQL_FUNC_RVJPST('test_1_0');
    END CASE;

    RETURN MYSQL_VAR_N684PH;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1763N7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1763N7(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_O8T928 INT DEFAULT 0;
    DECLARE MYSQL_VAR_OLEMTX DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_FM4R36 DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_VQL8BF INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_O8T928
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_OLEMTX
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COALESCE(STDDEV(SALARY), 0)
    INTO MYSQL_VAR_FM4R36
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SET MYSQL_VAR_VQL8BF = (MYSQL_VAR_O8T928 * 5) + (MYSQL_VAR_OLEMTX * 10) - (MYSQL_VAR_FM4R36 / 1000);

    RETURN MYSQL_VAR_VQL8BF;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I5ETLT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I5ETLT(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YIYKW5 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_VR0509 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_J4Q2FX(30) - (0) + COALESCE(COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_YIYKW5
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT (MYSQL_FUNC_1763N7(20) - (0) + COALESCE(COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), 0))
    INTO MYSQL_VAR_VR0509
    FROM ORDER_ITEMS;

    IF MYSQL_VAR_VR0509 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_M57IYZ(20) - (0) + COALESCE(FLOOR((MYSQL_VAR_YIYKW5 * 100) / MYSQL_VAR_VR0509), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7S090X(POLICY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ACCDAT INT DEFAULT 0;
    DECLARE MYSQL_VAR_TEQSK8 INT DEFAULT 500;
    DECLARE MYSQL_VAR_YPSIKA INT DEFAULT 0;
    DECLARE MYSQL_VAR_R2WH4N INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZFNLSX INT DEFAULT 0;

    SELECT (MYSQL_FUNC_I5ETLT(20) - (0) + COALESCE(COALESCE(BIKE_VALUE, 10000), COALESCE(ANNUAL_PREMIUM, 500), COALESCE(DEDUCTIBLE_AMOUNT, 500), 0))
    INTO MYSQL_VAR_ACCDAT, MYSQL_VAR_TEQSK8, MYSQL_VAR_YPSIKA
    FROM MOTORCYCLE_POLICIES
    WHERE POLICY_ID = POLICY_ID_PARAM;

    SET MYSQL_VAR_R2WH4N = MYSQL_FUNC_1K7PC8(20);
    SET MYSQL_VAR_ZFNLSX = MYSQL_VAR_TEQSK8 + MYSQL_VAR_R2WH4N * 10;

    IF MYSQL_VAR_YPSIKA > 1000 THEN
        SET MYSQL_VAR_ZFNLSX = MYSQL_VAR_ZFNLSX - (MYSQL_VAR_ZFNLSX * 15 / 100);
    END IF;

    RETURN (MYSQL_FUNC_6JTA8K(20) - (0) + COALESCE(CAST(MYSQL_VAR_ZFNLSX AS SIGNED), 0));
END//

DELIMITER ;