/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_FG6CYO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FG6CYO(CS_ID INT, CLUSTER_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3QAN2L BIGINT UNSIGNED DEFAULT 1;
    DECLARE MYSQL_VAR_3O4UJH VARCHAR(36);
    DECLARE MYSQL_VAR_YIVDB9 VARCHAR(36);
    
    SET MYSQL_VAR_3O4UJH = CONCAT('CS', CS_ID);
    SET MYSQL_VAR_YIVDB9 = CONCAT('CLUSTER', CLUSTER_ID);
    
    DELETE FROM MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS
    WHERE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTERSET_ID = MYSQL_VAR_3O4UJH
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTER_ID = MYSQL_VAR_YIVDB9
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.VIEW_ID = MYSQL_VAR_3QAN2L;

    UPDATE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERS C
    SET C.CLUSTERSET_ID = NULL
    WHERE C.CLUSTER_ID = MYSQL_VAR_YIVDB9;

    RETURN 1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RD0CHM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RD0CHM(COURSE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FLF17I INT DEFAULT 1;
    DECLARE MYSQL_VAR_KU8LTZ INT DEFAULT 30;
    DECLARE MYSQL_VAR_YZ7EBH INT DEFAULT 0;
    DECLARE MYSQL_VAR_SU3975 DECIMAL(4,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_QD48A0 INT DEFAULT 0;

    SELECT COALESCE(DIFFICULTY_LEVEL, 1), COALESCE(ENROLLMENT_CAPACITY, 30)
    INTO MYSQL_VAR_FLF17I, MYSQL_VAR_KU8LTZ
    FROM COURSES
    WHERE COURSE_ID = COURSE_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_YZ7EBH
    FROM ENROLLMENTS
    WHERE COURSE_ID = COURSE_ID_PARAM;

    SELECT COALESCE(AVG(CASE GRADE WHEN 'F' THEN 1 ELSE 0 END) * 100, 0)
    INTO MYSQL_VAR_SU3975
    FROM ENROLLMENTS
    WHERE COURSE_ID = COURSE_ID_PARAM;

    SET MYSQL_VAR_QD48A0 = (MYSQL_VAR_FLF17I * 20) + ((MYSQL_VAR_YZ7EBH * 100) / MYSQL_VAR_KU8LTZ) + MYSQL_VAR_SU3975;

    RETURN FLOOR(MYSQL_VAR_QD48A0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_26NRTF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_26NRTF(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QZIAQG INT DEFAULT 0;
    DECLARE MYSQL_VAR_GUFGWB INT DEFAULT 1;

    SELECT MYSQL_FUNC_RD0CHM(20)
    INTO MYSQL_VAR_QZIAQG, MYSQL_VAR_GUFGWB
    FROM CUSTOMERS C
    LEFT JOIN SUBSCRIPTIONS S ON C.CUSTOMER_ID = S.CUSTOMER_ID AND S.STATUS = 'ACTIVE'
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_FUNC_FG6CYO(20, 21);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GY2NI0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GY2NI0(EVENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z04RYO INT DEFAULT 0;
    DECLARE MYSQL_VAR_3WXAGL INT DEFAULT 0;
    DECLARE MYSQL_VAR_VGPIM4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_EV7OP1 INT DEFAULT 0;

    SELECT COUNT(*), COALESCE(E.TOTAL_CAPACITY, 1000), COALESCE(AVG(T.PRICE), 0)
    INTO MYSQL_VAR_Z04RYO, MYSQL_VAR_3WXAGL, MYSQL_VAR_VGPIM4
    FROM EVENT_TICKETS T
    JOIN EVENTS E ON T.EVENT_ID = E.EVENT_ID
    WHERE T.EVENT_ID = EVENT_ID_PARAM
    GROUP BY T.EVENT_ID;

    IF MYSQL_VAR_3WXAGL = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_EV7OP1 = ((MYSQL_VAR_Z04RYO * 100) / MYSQL_VAR_3WXAGL) + (MYSQL_VAR_VGPIM4 / 10);

    RETURN CAST(MYSQL_VAR_EV7OP1 AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_COMSCU(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SFCBG4 DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_GY2NI0(30)
    INTO MYSQL_VAR_SFCBG4
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN MYSQL_FUNC_26NRTF('test_0_0');
END//

DELIMITER ;