/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_rx9vg2 (
    category_id INT AUTO_INCREMENT PRIMARY KEY,
    category_name VARCHAR(255)
);
INSERT INTO table_rx9vg2 (category_id, category_name) VALUES (1, 'TestCategory');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_S464W9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S464W9(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_APOBPO INT DEFAULT 0;

    SELECT COALESCE(SUM(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_APOBPO
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN LEAST(MYSQL_VAR_APOBPO, 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GV5T1Q----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GV5T1Q(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_18WJ20 DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_2JRGQX INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_18WJ20, MYSQL_VAR_2JRGQX
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_S464W9(20) - (0) + COALESCE((MYSQL_VAR_18WJ20 * 10) + (30 - MYSQL_VAR_2JRGQX), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZUXKFE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZUXKFE(CATEGORY_NAME_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MW2AQ7 INT;
    
    INSERT INTO TABLE_RX9VG2 (CATEGORY_ID, CATEGORY_NAME)
    VALUES (DEFAULT, CAST(CATEGORY_NAME_PARAM AS CHAR));
    
    SET MYSQL_VAR_MW2AQ7 = LAST_INSERT_ID();
    
    RETURN MYSQL_VAR_MW2AQ7;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RF2DE7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RF2DE7(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QB6O72 VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_BZ5M3D INT DEFAULT 0;
    DECLARE MYSQL_VAR_RN2BWD INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0), TIMESTAMPDIFF(MONTH, START_DATE, CURDATE())
    INTO MYSQL_VAR_QB6O72, MYSQL_VAR_BZ5M3D, MYSQL_VAR_RN2BWD
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_QB6O72 != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_BZ5M3D * MYSQL_VAR_RN2BWD) / 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4TOOXN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4TOOXN(PROPERTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XPKFHS INT DEFAULT 0;
    DECLARE MYSQL_VAR_XOYC9B INT DEFAULT 0;
    DECLARE MYSQL_VAR_UTJHWH INT DEFAULT 0;
    DECLARE MYSQL_VAR_4W3RR6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_8S3J4L INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_RENT, 0), COALESCE(NUM_UNITS, 1)
    INTO MYSQL_VAR_XPKFHS, MYSQL_VAR_XOYC9B
    FROM RENTAL_PROPERTIES
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM;

    SELECT (MYSQL_FUNC_RF2DE7(30) - (0) + COALESCE(COUNT(*), 0)) INTO MYSQL_VAR_UTJHWH
    FROM LEASE_AGREEMENTS
    WHERE PROPERTY_ID = PROPERTY_ID_PARAM
      AND END_DATE > CURDATE();

    IF MYSQL_VAR_XOYC9B = 0 THEN
        RETURN 100;
    END IF;

    SET MYSQL_VAR_4W3RR6 = MYSQL_FUNC_GV5T1Q(20);
    SET MYSQL_VAR_8S3J4L = MYSQL_FUNC_ZUXKFE(10);

    IF MYSQL_VAR_XPKFHS > 5000 THEN
        SET MYSQL_VAR_8S3J4L = MYSQL_VAR_8S3J4L + 10;
    END IF;

    RETURN CAST(MYSQL_VAR_8S3J4L AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Q3W7R4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Q3W7R4(OPPORTUNITY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V8RG3N INT DEFAULT 0;
    DECLARE MYSQL_VAR_2A1AQB INT DEFAULT 0;
    DECLARE MYSQL_VAR_VH1MHV INT DEFAULT 0;
    DECLARE MYSQL_VAR_F8XRKT INT DEFAULT 0;

    SELECT (MYSQL_FUNC_4TOOXN(20) - (0) + COALESCE(COALESCE(PROBABILITY_PERCENT, 0), COALESCE(DEAL_VALUE, 0), DATEDIFF(CLOSE_DATE, CURDATE()), 0))
    INTO MYSQL_VAR_V8RG3N, MYSQL_VAR_2A1AQB, MYSQL_VAR_VH1MHV
    FROM CRM_OPPORTUNITIES
    WHERE OPPORTUNITY_ID = OPPORTUNITY_ID_PARAM;

    SET MYSQL_VAR_F8XRKT = (MYSQL_VAR_2A1AQB * MYSQL_VAR_V8RG3N) / 100;

    IF MYSQL_VAR_VH1MHV < 0 THEN
        SET MYSQL_VAR_F8XRKT = MYSQL_VAR_F8XRKT - 50;
    END IF;

    RETURN CAST(MYSQL_VAR_F8XRKT AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_12AHDF(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N0UVY1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_71FVRW INT DEFAULT 1;
    DECLARE MYSQL_VAR_K88SWC INT DEFAULT 0;
    DECLARE MYSQL_VAR_18A8S8 INT DEFAULT 2;

    IF N <= 0 THEN
        RETURN 0;
    END IF;

    IF N = 1 THEN
        RETURN 1;
    END IF;

    WHILE MYSQL_VAR_18A8S8 <= N DO
        SET MYSQL_VAR_K88SWC = MYSQL_VAR_N0UVY1 + MYSQL_VAR_71FVRW;
        SET MYSQL_VAR_N0UVY1 = MYSQL_VAR_71FVRW;
        SET MYSQL_VAR_71FVRW = MYSQL_VAR_K88SWC;
        SET MYSQL_VAR_18A8S8 = MYSQL_VAR_18A8S8 + 1;
    END WHILE;

    RETURN (MYSQL_FUNC_Q3W7R4(30) - (0) + COALESCE(MYSQL_VAR_71FVRW, 0));
END//

DELIMITER ;