/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_L1EC92----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L1EC92(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3ICN4M INT DEFAULT 3;
    DECLARE MYSQL_VAR_7KI3RG INT DEFAULT 1;
    DECLARE MYSQL_VAR_1GWVZS INT DEFAULT 0;

    IF N <= 2 OR N % 2 != 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_3ICN4M = 3;

    OUTER_LOOP: WHILE MYSQL_VAR_3ICN4M <= N / 2 DO
        SET MYSQL_VAR_7KI3RG = 1;
        SET MYSQL_VAR_1GWVZS = 2;

        INNER_LOOP: WHILE MYSQL_VAR_1GWVZS * MYSQL_VAR_1GWVZS <= MYSQL_VAR_3ICN4M DO
            IF MYSQL_VAR_3ICN4M % MYSQL_VAR_1GWVZS = 0 THEN
                SET MYSQL_VAR_7KI3RG = 0;
                LEAVE INNER_LOOP;
            END IF;
            SET MYSQL_VAR_1GWVZS = MYSQL_VAR_1GWVZS + 1;
        END WHILE INNER_LOOP;

        IF MYSQL_VAR_7KI3RG = 1 THEN
            SET MYSQL_VAR_1GWVZS = N - MYSQL_VAR_3ICN4M;
            SET MYSQL_VAR_7KI3RG = 1;
            SET MYSQL_VAR_1GWVZS = 2;

            CHECK_LOOP: WHILE MYSQL_VAR_1GWVZS * MYSQL_VAR_1GWVZS <= MYSQL_VAR_1GWVZS DO
                IF MYSQL_VAR_1GWVZS % MYSQL_VAR_1GWVZS = 0 THEN
                    SET MYSQL_VAR_7KI3RG = 0;
                    LEAVE CHECK_LOOP;
                END IF;
                SET MYSQL_VAR_1GWVZS = MYSQL_VAR_1GWVZS + 1;
            END WHILE CHECK_LOOP;

            IF MYSQL_VAR_7KI3RG = 1 THEN
                RETURN MYSQL_VAR_3ICN4M;
            END IF;
        END IF;

        SET MYSQL_VAR_3ICN4M = MYSQL_VAR_3ICN4M + 1;
    END WHILE OUTER_LOOP;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Q2B1AX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Q2B1AX(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RZ8YS9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Z7D9YY INT DEFAULT 0;
    DECLARE MYSQL_VAR_JDNMSJ DECIMAL(5,2) DEFAULT 0.00;

    SELECT COUNT(DISTINCT P.CATEGORY_ID)
    INTO MYSQL_VAR_RZ8YS9
    FROM ORDER_ITEMS OI
    JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
    WHERE OI.ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_Z7D9YY
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_Z7D9YY = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_JDNMSJ = (MYSQL_VAR_RZ8YS9 * 1.0) / MYSQL_VAR_Z7D9YY * 100;

    RETURN (MYSQL_FUNC_L1EC92(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_JDNMSJ), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4QGORF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4QGORF(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZBGL9O DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_H17HUH INT DEFAULT 0;
    DECLARE MYSQL_VAR_XTXRQD INT DEFAULT 0;

    SELECT COALESCE(AVG(PRICE), 0), COALESCE(MAX(PRICE), 0)
    INTO MYSQL_VAR_ZBGL9O, MYSQL_VAR_H17HUH
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_H17HUH = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_XTXRQD = (MYSQL_VAR_ZBGL9O * 100) / MYSQL_VAR_H17HUH;

    RETURN MYSQL_VAR_XTXRQD;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PRB376----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PRB376(INPUT_STR VARCHAR(100)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RLBIV8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_E7EY3D INT DEFAULT 1;
    DECLARE MYSQL_VAR_LVCBEI VARCHAR(1);
    DECLARE MYSQL_VAR_93QD0D INT DEFAULT 0;

    SET MYSQL_VAR_93QD0D = CHAR_LENGTH(INPUT_STR);

    WHILE MYSQL_VAR_E7EY3D <= MYSQL_VAR_93QD0D DO
        SET MYSQL_VAR_LVCBEI = SUBSTRING(INPUT_STR, MYSQL_VAR_E7EY3D, 1);

        IF MYSQL_VAR_LVCBEI IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') THEN
            SET MYSQL_VAR_RLBIV8 = MYSQL_VAR_RLBIV8 * 10 + CAST(MYSQL_VAR_LVCBEI AS SIGNED);
        END IF;

        SET MYSQL_VAR_E7EY3D = MYSQL_VAR_E7EY3D + 1;
    END WHILE;

    RETURN MYSQL_VAR_RLBIV8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9TIY8F----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9TIY8F(TARGET_DATE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_KS8YXV INT DEFAULT 0;
    DECLARE MYSQL_VAR_YSGQMZ INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COUNT(*)
    INTO MYSQL_VAR_KS8YXV, MYSQL_VAR_YSGQMZ
    FROM SALES
    WHERE YEAR(SALE_DATE) = TARGET_DATE;

    IF MYSQL_VAR_YSGQMZ = 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_KS8YXV;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UJK0I8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UJK0I8(ACCOUNT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_YUV9L3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_6WTXRO INT DEFAULT 0;
    DECLARE MYSQL_VAR_SQTGNA INT DEFAULT 0;

    SELECT COALESCE(ANNUAL_CONTRIBUTION, 0), COALESCE(EMPLOYER_MATCH_PERCENT, 0)
    INTO MYSQL_VAR_YUV9L3, MYSQL_VAR_6WTXRO
    FROM RETIREMENT_ACCOUNTS
    WHERE ACCOUNT_ID = ACCOUNT_ID_PARAM;

    SET MYSQL_VAR_6WTXRO = (MYSQL_VAR_YUV9L3 * MYSQL_VAR_6WTXRO) / 100;
    SET MYSQL_VAR_SQTGNA = MYSQL_VAR_YUV9L3 + MYSQL_VAR_6WTXRO;

    RETURN CAST(MYSQL_VAR_SQTGNA AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6X5KKC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6X5KKC(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TIJ7BM DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_LPJR0Z DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_4XLGE1 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_UJK0I8(10) - (0) + COALESCE(COALESCE(PRICE, 0), COALESCE(COST, 0), 0))
    INTO MYSQL_VAR_TIJ7BM, MYSQL_VAR_LPJR0Z
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_TIJ7BM = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_4XLGE1 = MYSQL_FUNC_PRB376('test_0_0');

    RETURN (MYSQL_FUNC_9TIY8F(10) - (0) + COALESCE(MYSQL_VAR_4XLGE1, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GYRWLW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PYIAN7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_WJ4AQ4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_A9YT2Y INT DEFAULT 0;
    DECLARE MYSQL_VAR_E8JT5J VARCHAR(20) DEFAULT 'BRONZE';
    DECLARE MYSQL_VAR_5SAM09 INT DEFAULT 1;
    DECLARE MYSQL_VAR_JKMGYJ INT DEFAULT 0;

    SELECT (MYSQL_FUNC_6X5KKC(30) - (0) + COALESCE(COALESCE(COUNT(*), 0), COALESCE(SUM(TOTAL_AMOUNT), 0), 0))
    INTO MYSQL_VAR_WJ4AQ4, MYSQL_VAR_PYIAN7
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT (MYSQL_FUNC_4QGORF(10) - (0) + COALESCE(CUSTOMER_TIER, 0)) INTO MYSQL_VAR_E8JT5J
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_5SAM09 = CASE MYSQL_VAR_E8JT5J
        WHEN 'PLATINUM' THEN 4
        WHEN 'GOLD' THEN 3
        WHEN 'SILVER' THEN 2
        ELSE 1
    END;

    IF MYSQL_VAR_WJ4AQ4 > 0 THEN
        SET MYSQL_VAR_A9YT2Y = MYSQL_VAR_PYIAN7 / MYSQL_VAR_WJ4AQ4;
        SET MYSQL_VAR_JKMGYJ = MYSQL_VAR_A9YT2Y * MYSQL_VAR_WJ4AQ4 * MYSQL_VAR_5SAM09;
    END IF;

    RETURN (MYSQL_FUNC_Q2B1AX(30) - (0) + COALESCE(MYSQL_VAR_JKMGYJ, 0));
END//

DELIMITER ;