/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Seed Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WLXCUB(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1XMNKQ INT DEFAULT 0;
    DECLARE MYSQL_VAR_EDWSE8 INT DEFAULT 1;

    SELECT COUNT(*), GREATEST(TIMESTAMPDIFF(DAY, MIN(ORDER_DATE), CURDATE()), 1)
    INTO MYSQL_VAR_1XMNKQ, MYSQL_VAR_EDWSE8
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_VAR_1XMNKQ * 100) / MYSQL_VAR_EDWSE8;
END//

DELIMITER ;