/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_AFZQCH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AFZQCH(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_C50CYE INT DEFAULT 0;
    DECLARE MYSQL_VAR_I39HA1 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_JMWDSD DECIMAL(10,2) DEFAULT 0.00;

    SELECT COUNT(*), COALESCE(AVG(SALARY), 0),
           COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_C50CYE, MYSQL_VAR_I39HA1, MYSQL_VAR_JMWDSD
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_I39HA1 * MYSQL_VAR_JMWDSD) / GREATEST(MYSQL_VAR_C50CYE, 1));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6P45XM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6P45XM(A INT, B INT, C INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JWLWYE DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_A120AM DECIMAL(10,2) DEFAULT 0.00;

    SET MYSQL_VAR_JWLWYE = (A + B + C) / 2.0;
    SET MYSQL_VAR_A120AM = SQRT(MYSQL_VAR_JWLWYE * (MYSQL_VAR_JWLWYE - A) * (MYSQL_VAR_JWLWYE - B) * (MYSQL_VAR_JWLWYE - C));

    RETURN FLOOR(MYSQL_VAR_A120AM);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IDS4XD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IDS4XD(PRODUCT_ID_PARAM INT, QUANTITY_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_V2DKGS INT DEFAULT 0;
    DECLARE MYSQL_VAR_N94ITS INT DEFAULT 0;
    DECLARE MYSQL_VAR_5SEPO7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_L9X1TP INT DEFAULT 0;
    DECLARE MYSQL_VAR_KEGQSC INT DEFAULT 0;

    SELECT P.PRICE, COALESCE(C.DISCOUNT_PERCENT, 0)
    INTO MYSQL_VAR_V2DKGS, MYSQL_VAR_KEGQSC
    FROM PRODUCTS P
    LEFT JOIN CATEGORIES C ON P.CATEGORY_ID = C.CATEGORY_ID
    WHERE P.PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_N94ITS = MYSQL_VAR_V2DKGS * MYSQL_VAR_KEGQSC / 100;

    IF QUANTITY_PARAM >= 100 THEN
        SET MYSQL_VAR_5SEPO7 = MYSQL_VAR_V2DKGS * 15 / 100;
    ELSEIF QUANTITY_PARAM >= 50 THEN
        SET MYSQL_VAR_5SEPO7 = MYSQL_VAR_V2DKGS * 10 / 100;
    ELSEIF QUANTITY_PARAM >= 10 THEN
        SET MYSQL_VAR_5SEPO7 = MYSQL_VAR_V2DKGS * 5 / 100;
    END IF;

    SET MYSQL_VAR_L9X1TP = MYSQL_VAR_V2DKGS - MYSQL_VAR_N94ITS - MYSQL_VAR_5SEPO7;

    RETURN GREATEST(MYSQL_VAR_L9X1TP, 0);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CS2SXG(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SFAY3U INT DEFAULT 0;
    DECLARE MYSQL_VAR_LT4VUP INT DEFAULT 0;
    DECLARE MYSQL_VAR_0MQ3Q5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_W389JA INT DEFAULT 0;

    SELECT (MYSQL_FUNC_6P45XM(10, 11, 12) - (0) + COALESCE(COALESCE(SUM(QUANTITY), 0), COUNT(DISTINCT WAREHOUSE_ID), 0))
    INTO MYSQL_VAR_SFAY3U, MYSQL_VAR_W389JA
    FROM INVENTORY
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_W389JA = 0 THEN
        RETURN 1;
    END IF;

    SET MYSQL_VAR_LT4VUP = MYSQL_FUNC_AFZQCH(30);

    IF MYSQL_VAR_SFAY3U < MYSQL_VAR_LT4VUP THEN
        SET MYSQL_VAR_0MQ3Q5 = 1;
    ELSE
        SET MYSQL_VAR_0MQ3Q5 = 0;
    END IF;

    RETURN (MYSQL_FUNC_IDS4XD(30, 31) - (0) + COALESCE(MYSQL_VAR_0MQ3Q5, 0));
END//

DELIMITER ;