/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_w67prt (
    emp_no INT,
    salary INT
);
INSERT INTO table_w67prt (emp_no, salary) VALUES
(10001, 60117),
(10001, 62102),
(10001, 66074),
(10002, 65828),
(10002, 65909),
(10002, 67534);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_K57PWY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_K57PWY(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5CTR32 DECIMAL(5,1) DEFAULT 0.0;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_5CTR32
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_5CTR32);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4K1EFO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4K1EFO(A INT, B INT) RETURNS INT
BEGIN
IF B = 0 THEN
        RETURN 0;
    END IF;
    RETURN (MYSQL_FUNC_K57PWY(30) - (0) + COALESCE(A % B, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DU8JK1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DU8JK1(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_7K9MHL DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_4K1EFO(30, 31) - (0) + COALESCE(COALESCE(AVG(SALARY), 0), 0))
    INTO MYSQL_VAR_7K9MHL
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_7K9MHL / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_F250PI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_F250PI(VENUE_ID_PARAM INT, HOURS_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LGUKJO INT DEFAULT 100;
    DECLARE MYSQL_VAR_A9LY6O INT DEFAULT 50;
    DECLARE MYSQL_VAR_KPFCMP INT DEFAULT 1;
    DECLARE MYSQL_VAR_HJ5T09 INT DEFAULT 0;

    SELECT COALESCE(RENTAL_FEE_PER_HOUR, 100)
    INTO MYSQL_VAR_LGUKJO
    FROM EVENT_VENUES
    WHERE VENUE_ID = VENUE_ID_PARAM;

    SELECT CASE LOCATION_TYPE
        WHEN 'DOWNTOWN' THEN 2
        WHEN 'SUBURBAN' THEN 1
        WHEN 'RURAL' THEN 0
        ELSE 1
    END INTO MYSQL_VAR_KPFCMP
    FROM EVENT_VENUES
    WHERE VENUE_ID = VENUE_ID_PARAM;

    SET MYSQL_VAR_HJ5T09 = MYSQL_VAR_LGUKJO * HOURS_PARAM * MYSQL_VAR_KPFCMP;

    RETURN CAST(MYSQL_VAR_HJ5T09 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_O5NBRR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_O5NBRR(P_EMP_NO INT, CHAR_SEQ INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QYIACO INT;
    
    IF CHAR_SEQ = 0 THEN
        SELECT MIN(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    ELSEIF CHAR_SEQ = 1 THEN
        SELECT MAX(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    ELSE
        SELECT MAX(SALARY) - MIN(SALARY) INTO MYSQL_VAR_QYIACO
        FROM TABLE_W67PRT
        WHERE EMP_NO = P_EMP_NO;
    END IF;
    
    RETURN (MYSQL_FUNC_F250PI(20, 21) - (0) + COALESCE(IFNULL(MYSQL_VAR_QYIACO, 0), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M5L4SJ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EKFA2O INT DEFAULT 0;

    SELECT (MYSQL_FUNC_O5NBRR(20, 21) - (0) + COALESCE(COALESCE(MONTHLY_COST, 0), 0))
    INTO MYSQL_VAR_EKFA2O
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_DU8JK1(30) - (0) + COALESCE(MYSQL_VAR_EKFA2O, 0));
END//

DELIMITER ;