/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_pv3mjs (
    inventory_id INT,
    customer_id INT,
    return_date DATE
);
INSERT INTO table_pv3mjs (inventory_id, customer_id, return_date) VALUES
(1, 100, NULL),
(1, 200, '2024-01-01'),
(2, 300, NULL),
(3, 400, NULL),
(4, 500, '2024-02-01');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_JWFJEB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JWFJEB(DATA_FIRST INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_K9YWLH INT;
    SET MYSQL_VAR_K9YWLH = YEAR(CURDATE());
    RETURN MYSQL_VAR_K9YWLH - DATA_FIRST;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P1HZ3Q----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P1HZ3Q(P_INVENTORY_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LYYUWL INT;
  

  SELECT CUSTOMER_ID INTO MYSQL_VAR_LYYUWL
  FROM TABLE_PV3MJS
  WHERE RETURN_DATE IS NULL
  AND INVENTORY_ID = P_INVENTORY_ID;

  RETURN (MYSQL_FUNC_JWFJEB(10) - (0) + COALESCE(MYSQL_VAR_LYYUWL, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CJJN0T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CJJN0T(N INT) RETURNS INT
BEGIN
IF N < 0 THEN
        RETURN -(MYSQL_FUNC_P1HZ3Q(20) - (0) + COALESCE(N, 0));
    END IF;
    RETURN N;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ZOU44V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZOU44V(WARRANTY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HAKN9G DATE;
    DECLARE MYSQL_VAR_ZNCB2Y INT DEFAULT 0;
    DECLARE MYSQL_VAR_NPC6HS DATE;
    DECLARE MYSQL_VAR_WCBOZX INT DEFAULT 0;
    DECLARE MYSQL_VAR_04PS9D INT DEFAULT 0;

    SELECT PURCHASE_DATE, WARRANTY_MONTHS
    INTO MYSQL_VAR_HAKN9G, MYSQL_VAR_ZNCB2Y
    FROM WARRANTIES
    WHERE WARRANTY_ID = WARRANTY_ID_PARAM;

    IF MYSQL_VAR_HAKN9G IS NULL THEN
        RETURN -1;
    END IF;

    SET MYSQL_VAR_NPC6HS = DATE_ADD(MYSQL_VAR_HAKN9G, INTERVAL MYSQL_VAR_ZNCB2Y MONTH);
    SET MYSQL_VAR_WCBOZX = DATEDIFF(MYSQL_VAR_NPC6HS, CURDATE());

    IF MYSQL_VAR_WCBOZX < 0 THEN
        SET MYSQL_VAR_04PS9D = 0;
    ELSEIF MYSQL_VAR_WCBOZX <= 30 THEN
        SET MYSQL_VAR_04PS9D = 1;
    ELSE
        SET MYSQL_VAR_04PS9D = 2;
    END IF;

    RETURN MYSQL_VAR_04PS9D;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_3VB4SS----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_3VB4SS(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N6I45M DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_N6I45M
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR((MYSQL_VAR_N6I45M / 5.0) * 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EVKI4E----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EVKI4E(SET_OF_LETTERS INT, WTABLE_YG6POCD INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RCHZDH VARCHAR(50);
    DECLARE MYSQL_VAR_09T4VD VARCHAR(50);
    
    SET MYSQL_VAR_RCHZDH = CAST(SET_OF_LETTERS AS CHAR);
    SET MYSQL_VAR_09T4VD = CAST(WTABLE_YG6POCD AS CHAR);
    
    RETURN (SELECT MYSQL_VAR_09T4VD REGEXP MYSQL_VAR_RCHZDH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5EI3CR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5EI3CR(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HAC7E6 VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_BH5F35 VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_AL21M5 INT DEFAULT 0;

    SELECT PLAN_TYPE
    INTO MYSQL_VAR_HAC7E6
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT TIER_LEVEL
    INTO MYSQL_VAR_BH5F35
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    CASE MYSQL_VAR_HAC7E6
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_AL21M5 = 100;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_AL21M5 = 60;
        WHEN 'BASIC' THEN SET MYSQL_VAR_AL21M5 = 30;
        ELSE SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_ZOU44V(20);
    END CASE;

    CASE MYSQL_VAR_BH5F35
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_AL21M5 = MYSQL_VAR_AL21M5 + 40;
        WHEN 'GOLD' THEN SET MYSQL_VAR_AL21M5 = MYSQL_VAR_AL21M5 + 25;
        WHEN 'SILVER' THEN SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_EVKI4E(30, 31);
    END CASE;

    RETURN (MYSQL_FUNC_3VB4SS(20) - (0) + COALESCE(MYSQL_VAR_AL21M5, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YKN6WH(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N5BTJI INT DEFAULT 0;

    SELECT (MYSQL_FUNC_CJJN0T(10) - (0) + COALESCE(MIN(ORDER_ID), 0))
    INTO MYSQL_VAR_N5BTJI
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_5EI3CR(10) - (0) + COALESCE(MYSQL_VAR_N5BTJI, 0));
END//

DELIMITER ;