/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_5R9UPI----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5R9UPI(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JLMB6O INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZQPOL1 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_JLMB6O
    FROM EMPLOYEES
    WHERE MANAGER_ID = EMP_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_ZQPOL1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = (SELECT DEPARTMENT_ID FROM EMPLOYEES WHERE EMP_ID = EMP_ID_PARAM);

    IF MYSQL_VAR_ZQPOL1 = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_JLMB6O * 100) / MYSQL_VAR_ZQPOL1;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QX56X5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QX56X5(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8RVGVF DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_7D7IY5 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_8RVGVF
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(AVG(PRICE), 1)
    INTO MYSQL_VAR_7D7IY5
    FROM PRODUCTS;

    RETURN FLOOR((MYSQL_VAR_8RVGVF * 100) / MYSQL_VAR_7D7IY5);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_R9H81C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_R9H81C(N INT, LEVELS INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RYRLA0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7EUULB INT DEFAULT 1;

    IF LEVELS <= 0 OR N <= 0 THEN
        RETURN 0;
    END IF;

    OUTER_LOOP: WHILE MYSQL_VAR_7EUULB <= N DO
        SET MYSQL_VAR_RYRLA0 = MYSQL_VAR_RYRLA0 + MYSQL_VAR_7EUULB;

        IF LEVELS > 1 AND MYSQL_VAR_7EUULB > 1 THEN
            SET MYSQL_VAR_RYRLA0 = MYSQL_VAR_RYRLA0 + MYSQL_FUNC_R9H81C(MYSQL_VAR_7EUULB - 1, LEVELS - 1);
        END IF;

        SET MYSQL_VAR_7EUULB = MYSQL_VAR_7EUULB + 1;
    END WHILE OUTER_LOOP;

    RETURN MYSQL_VAR_RYRLA0;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PQ73OH(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZWSA0K INT DEFAULT 0;
    DECLARE MYSQL_VAR_OSAD0B INT DEFAULT 0;
    DECLARE MYSQL_VAR_X0861X INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_ZWSA0K
    FROM REFUNDS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT (MYSQL_FUNC_R9H81C(20, 21) - (0) + COALESCE(COALESCE(TOTAL_AMOUNT, 1), 0))
    INTO MYSQL_VAR_OSAD0B
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_X0861X = MYSQL_FUNC_QX56X5(10);

    RETURN (MYSQL_FUNC_5R9UPI(10) - (0) + COALESCE(MYSQL_VAR_X0861X, 0));
END//

DELIMITER ;