/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_3y0d8a (
    produto_id INT,
    Quantidade_produto INT
);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (1, 10);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (2, 5);
INSERT INTO table_3y0d8a (produto_id, Quantidade_produto) VALUES (3, 0);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_42MJ5R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_42MJ5R(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EF5R5F INT DEFAULT 0;
    DECLARE MYSQL_VAR_0M9MR1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0QOMES INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_EF5R5F
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM
    AND YEAR(HIRE_DATE) = YEAR(CURDATE());

    SELECT COUNT(*)
    INTO MYSQL_VAR_0M9MR1
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    IF MYSQL_VAR_0M9MR1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_0QOMES = (MYSQL_VAR_EF5R5F * 100) / MYSQL_VAR_0M9MR1;

    RETURN MYSQL_VAR_0QOMES;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AXWHLP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AXWHLP(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UV4KG2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_W78DPI INT DEFAULT 0;
    DECLARE MYSQL_VAR_2O4Y46 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JRYPI9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_DT752D INT DEFAULT 0;

    SELECT COALESCE(BUDGET_ALLOCATED, 0), COALESCE(LEADS_GENERATED, 0), COALESCE(CONVERSIONS, 0)
    INTO MYSQL_VAR_UV4KG2, MYSQL_VAR_W78DPI, MYSQL_VAR_2O4Y46
    FROM MARKETING_CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT_SPENT), 0) INTO MYSQL_VAR_JRYPI9
    FROM CAMPAIGN_SPEND
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_UV4KG2 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_DT752D = ((MYSQL_VAR_2O4Y46 * 100) - MYSQL_VAR_JRYPI9) * 100 / MYSQL_VAR_UV4KG2;

    RETURN CAST(MYSQL_VAR_DT752D AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4G9A5W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4G9A5W(PROD_ID INT, QTDE_COMPRADA INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4MCEPB INT;
    DECLARE MYSQL_VAR_ZAJVJ3 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_AXWHLP(10) - (0) + COALESCE(COUNT(*), 0)) INTO MYSQL_VAR_4MCEPB FROM TABLE_3Y0D8A WHERE PRODUTO_ID = PROD_ID;

    IF MYSQL_VAR_4MCEPB > 0 THEN
        UPDATE TABLE_3Y0D8A SET QUANTIDADE_PRODUTO = QUANTIDADE_PRODUTO + QTDE_COMPRADA
        WHERE PRODUTO_ID = PROD_ID;
        SET MYSQL_VAR_ZAJVJ3 = ROW_COUNT();
    ELSE
        INSERT INTO TABLE_3Y0D8A (PRODUTO_ID, QUANTIDADE_PRODUTO) VALUES (1, NULL);
        SET MYSQL_VAR_ZAJVJ3 = 1;
    END IF;

    RETURN MYSQL_VAR_ZAJVJ3;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ARETGO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ARETGO(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6SG0YZ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_Z5XWLF INT DEFAULT 0;
    DECLARE MYSQL_VAR_1HLST2 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(PRICE, 0), COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_6SG0YZ, MYSQL_VAR_Z5XWLF
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_1HLST2 = MYSQL_FUNC_4G9A5W(30, 31);

    RETURN FLOOR(MYSQL_VAR_1HLST2 / 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BMH86N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BMH86N(CARD_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_R9NW9R INT DEFAULT 0;
    DECLARE MYSQL_VAR_BOQ37V VARCHAR(20) DEFAULT 'STANDARD';
    DECLARE MYSQL_VAR_08LRZZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_YXTFAX INT DEFAULT 100;
    DECLARE MYSQL_VAR_QK7WPT INT DEFAULT 0;
    DECLARE MYSQL_VAR_D0KZCQ INT DEFAULT 0;

    SELECT COALESCE(BALANCE, 0), CARD_TYPE
    INTO MYSQL_VAR_R9NW9R, MYSQL_VAR_BOQ37V
    FROM PUBLIC_TRANSIT_CARDS
    WHERE CARD_ID = CARD_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_08LRZZ
    FROM TRANSIT_TRIPS
    WHERE CARD_ID = CARD_ID_PARAM
      AND TRIP_DATE >= CURDATE();

    IF MYSQL_VAR_BOQ37V = 'SENIOR' THEN
        SET MYSQL_VAR_QK7WPT = 50;
    ELSEIF MYSQL_VAR_BOQ37V = 'STUDENT' THEN
        SET MYSQL_VAR_QK7WPT = 30;
    END IF;

    IF MYSQL_VAR_08LRZZ >= 5 THEN
        SET MYSQL_VAR_QK7WPT = MYSQL_VAR_QK7WPT + 20;
    END IF;

    SET MYSQL_VAR_D0KZCQ = 25 - (25 * MYSQL_VAR_QK7WPT / 100);

    RETURN CAST(MYSQL_VAR_D0KZCQ AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KM8M2T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KM8M2T(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VT475G VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_2IX7BK INT DEFAULT 0;
    DECLARE MYSQL_VAR_JXK3NC INT DEFAULT 0;

    SELECT PLAN_TYPE, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_VT475G, MYSQL_VAR_2IX7BK
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    CASE MYSQL_VAR_VT475G
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_JXK3NC = MYSQL_VAR_2IX7BK / 5;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_JXK3NC = MYSQL_VAR_2IX7BK / 3;
        WHEN 'BASIC' THEN SET MYSQL_VAR_JXK3NC = MYSQL_VAR_2IX7BK / 2;
        ELSE SET MYSQL_VAR_JXK3NC = MYSQL_VAR_2IX7BK;
    END CASE;

    RETURN MYSQL_VAR_JXK3NC;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BHC0I8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BHC0I8(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LL5I67 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_KM8M2T(30) - (0) + COALESCE(COALESCE(SALARY, 0), 0))
    INTO MYSQL_VAR_LL5I67
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_LL5I67);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_79SFE3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_79SFE3(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IR23E8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_36EK8V INT DEFAULT 0;

    SELECT COALESCE(MAX(SALARY), 0), COALESCE(MIN(SALARY), 0)
    INTO MYSQL_VAR_IR23E8, MYSQL_VAR_36EK8V
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_VAR_IR23E8 - MYSQL_VAR_36EK8V;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AIS5QM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AIS5QM(DISTANCE_MILES_PARAM INT, AIRLINE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QK057H INT DEFAULT 80;
    DECLARE MYSQL_VAR_IWT20E INT DEFAULT 50;
    DECLARE MYSQL_VAR_H7UGYB INT DEFAULT 0;
    DECLARE MYSQL_VAR_08JZNT INT DEFAULT 0;
    DECLARE MYSQL_VAR_7SG3ID INT DEFAULT 0;

    SELECT (MYSQL_FUNC_BMH86N(20) - (0) + COALESCE(COALESCE(SAFETY_RATING, 80), COALESCE(FLEET_SIZE, 50), 0))
    INTO MYSQL_VAR_QK057H, MYSQL_VAR_IWT20E
    FROM AIRLINES
    WHERE AIRLINE_ID = AIRLINE_ID_PARAM;

    SET MYSQL_VAR_H7UGYB = MYSQL_FUNC_79SFE3(10);

    SET MYSQL_VAR_08JZNT = MYSQL_FUNC_42MJ5R(20);

    SET MYSQL_VAR_7SG3ID = MYSQL_FUNC_ARETGO(10);

    RETURN (MYSQL_FUNC_BHC0I8(30) - (0) + COALESCE(GREATEST(MYSQL_VAR_7SG3ID, 0), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_L9F2TJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L9F2TJ(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1XE8TM INT DEFAULT 0;
    DECLARE MYSQL_VAR_IBAADE INT DEFAULT 0;
    DECLARE MYSQL_VAR_RV3GEJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_G16D3Z INT;
    DECLARE MYSQL_VAR_P3B2N8 INT;

    SET MYSQL_VAR_G16D3Z = YEAR(CURDATE());

    SELECT COUNT(*), COALESCE(AVG(MYSQL_VAR_G16D3Z - YEAR(HIRE_DATE)), 0)
    INTO MYSQL_VAR_RV3GEJ, MYSQL_VAR_1XE8TM
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    IF MYSQL_VAR_RV3GEJ = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_IBAADE = CAST(MYSQL_VAR_1XE8TM * 100 AS UNSIGNED);

    RETURN MYSQL_VAR_IBAADE;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0VZMS1(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_74U5XL DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_L9F2TJ(30) - (0) + COALESCE(COALESCE(AVG(PRICE), 0), 0))
    INTO MYSQL_VAR_74U5XL
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_AIS5QM(10, 11) - (0) + COALESCE(FLOOR(MYSQL_VAR_74U5XL / 10), 0));
END//

DELIMITER ;