/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_352AVK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_352AVK(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_F8B2VP INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_F8B2VP
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_F8B2VP;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NHMD6G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NHMD6G(A INT, B INT) RETURNS INT
BEGIN
RETURN MYSQL_FUNC_352AVK(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BHC0I8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BHC0I8(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LL5I67 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_LL5I67
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_LL5I67);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_A7S5Z7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_A7S5Z7(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JL3OPZ DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_BHC0I8(30)
    INTO MYSQL_VAR_JL3OPZ
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_JL3OPZ);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J1RJ2X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J1RJ2X(INVOICE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NXUDJL DATE;
    DECLARE MYSQL_VAR_7KUGZW INT DEFAULT 0;
    DECLARE MYSQL_VAR_GR7U6F INT DEFAULT 0;
    DECLARE MYSQL_VAR_6GZA4F INT DEFAULT 0;
    DECLARE MYSQL_VAR_7VQ3MM INT DEFAULT 0;

    SELECT COALESCE(TOTAL_AMOUNT, 0), DUE_DATE
    INTO MYSQL_VAR_7KUGZW, MYSQL_VAR_NXUDJL
    FROM INVOICES
    WHERE INVOICE_ID = INVOICE_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT_PAID), 0)
    INTO MYSQL_VAR_GR7U6F
    FROM PAYMENTS
    WHERE INVOICE_ID = INVOICE_ID_PARAM;

    SET MYSQL_VAR_6GZA4F = MYSQL_VAR_7KUGZW - MYSQL_VAR_GR7U6F;

    IF MYSQL_VAR_6GZA4F <= 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_7VQ3MM = DATEDIFF(CURDATE(), MYSQL_VAR_NXUDJL);

    IF MYSQL_VAR_7VQ3MM < 0 THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_7VQ3MM;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7RW84V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7RW84V(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DPXTF4 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(SALARY), 0)
    INTO MYSQL_VAR_DPXTF4
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_DPXTF4 / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1UM166----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1UM166() RETURNS INT
BEGIN
RETURN MYSQL_FUNC_7RW84V(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_W17KCR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_W17KCR(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LD9OWF INT DEFAULT 0;
    DECLARE MYSQL_VAR_GM52J9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_AXKPZ4 DECIMAL(5,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_KK7YPQ INT DEFAULT 0;

    SELECT MYSQL_FUNC_1UM166()
    INTO MYSQL_VAR_LD9OWF, MYSQL_VAR_GM52J9
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    IF MYSQL_VAR_GM52J9 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_AXKPZ4 = MYSQL_VAR_LD9OWF / MYSQL_VAR_GM52J9;

    SET MYSQL_VAR_KK7YPQ = MYSQL_VAR_AXKPZ4 / 10;

    RETURN MYSQL_FUNC_J1RJ2X(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_NMV4W2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_NMV4W2(APPT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OGXLEB INT DEFAULT 0;
    DECLARE MYSQL_VAR_O7I7IW INT DEFAULT 0;
    DECLARE MYSQL_VAR_YE93EU INT DEFAULT 0;

    SELECT MYSQL_FUNC_W17KCR(10)
    INTO MYSQL_VAR_OGXLEB, MYSQL_VAR_O7I7IW
    FROM APPOINTMENTS
    WHERE APPT_ID = APPT_ID_PARAM;

    IF MYSQL_VAR_OGXLEB = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_YE93EU = MYSQL_VAR_OGXLEB + MYSQL_VAR_O7I7IW;

    RETURN MYSQL_FUNC_A7S5Z7(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JN2VW6----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JN2VW6(LISTING_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DO71XW INT DEFAULT 0;
    DECLARE MYSQL_VAR_UAX86F INT DEFAULT 0;
    DECLARE MYSQL_VAR_46OXPO INT DEFAULT 0;
    DECLARE MYSQL_VAR_HP5AQV INT DEFAULT 0;

    SELECT COALESCE(LIST_PRICE, 0), COALESCE(DAYS_ON_MARKET, 0), COALESCE(SHOWINGS_COUNT, 0)
    INTO MYSQL_VAR_DO71XW, MYSQL_VAR_UAX86F, MYSQL_VAR_46OXPO
    FROM PROPERTY_LISTINGS
    WHERE LISTING_ID = LISTING_ID_PARAM;

    SET MYSQL_VAR_HP5AQV = (MYSQL_VAR_46OXPO * 10) - (MYSQL_VAR_UAX86F * 2);

    IF MYSQL_VAR_DO71XW > 500000 THEN
        SET MYSQL_VAR_HP5AQV = MYSQL_VAR_HP5AQV + 20;
    END IF;

    IF MYSQL_VAR_UAX86F > 90 THEN
        SET MYSQL_VAR_HP5AQV = MYSQL_VAR_HP5AQV - 30;
    END IF;

    RETURN CAST(MYSQL_VAR_HP5AQV AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GQH2SH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GQH2SH(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QHFK20 INT DEFAULT 0;

    SELECT TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_QHFK20
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_JN2VW6(30);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GIUQ1E(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JKDB56 INT DEFAULT 0;
    DECLARE MYSQL_VAR_FF9TH7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_T4J0XG DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_GQH2SH(30)
    INTO MYSQL_VAR_JKDB56
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT MYSQL_FUNC_NMV4W2(30)
    INTO MYSQL_VAR_FF9TH7
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_FF9TH7 > 365 THEN
        SET MYSQL_VAR_T4J0XG = (MYSQL_VAR_JKDB56 * 365.0) / MYSQL_VAR_FF9TH7 * 3;
    ELSE
        SET MYSQL_VAR_T4J0XG = MYSQL_VAR_JKDB56;
    END IF;

    RETURN MYSQL_FUNC_NHMD6G(10, 11);
END//

DELIMITER ;