/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_JXKVEV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JXKVEV(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N20351 DATE;
    DECLARE MYSQL_VAR_8KI07H DATE;
    DECLARE MYSQL_VAR_T1SYMY INT DEFAULT 0;

    SELECT REGISTRATION_DATE
    INTO MYSQL_VAR_8KI07H
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MIN(ORDER_DATE)
    INTO MYSQL_VAR_N20351
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_N20351 IS NOT NULL THEN
        SET MYSQL_VAR_T1SYMY = DATEDIFF(MYSQL_VAR_N20351, MYSQL_VAR_8KI07H);
    END IF;

    RETURN MYSQL_VAR_T1SYMY;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BE7ASW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BE7ASW(N INT) RETURNS INT
BEGIN
RETURN (MYSQL_FUNC_JXKVEV(20) - (0) + COALESCE(N * N, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PL0847----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PL0847(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_LLLEM9 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_LLLEM9
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_LLLEM9;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CJJN0T----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CJJN0T(N INT) RETURNS INT
BEGIN
IF N < 0 THEN
        RETURN -(MYSQL_FUNC_PL0847(10) - (0) + COALESCE(N, 0));
    END IF;
    RETURN N;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CC5T7F(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GIJYV1 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_VV1ERB INT DEFAULT 0;

    SELECT (MYSQL_FUNC_CJJN0T(10) - (0) + COALESCE(COALESCE(AVG(PRICE), 0), COALESCE(SUM(STOCK_QUANTITY), 0), 0))
    INTO MYSQL_VAR_GIJYV1, MYSQL_VAR_VV1ERB
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_BE7ASW(30) - (0) + COALESCE(FLOOR((MYSQL_VAR_GIJYV1 * MYSQL_VAR_VV1ERB) / 100), 0));
END//

DELIMITER ;