/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_GRHCIN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GRHCIN(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QSJXA8 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_CWAXLU DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_QSJXA8
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_CWAXLU
    FROM ORDERS;

    IF MYSQL_VAR_CWAXLU = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_QSJXA8 * 100) / MYSQL_VAR_CWAXLU);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6SSNLE----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6SSNLE(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UK703B INT DEFAULT 0;
    DECLARE MYSQL_VAR_8J2N81 DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_GL9CWR INT DEFAULT 0;

    SELECT COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_UK703B
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(AVG(STOCK_QUANTITY), 0)
    INTO MYSQL_VAR_8J2N81
    FROM PRODUCTS
    WHERE CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    IF MYSQL_VAR_UK703B < MYSQL_VAR_8J2N81 * 0.5 THEN
        SET MYSQL_VAR_GL9CWR = 100;
    ELSEIF MYSQL_VAR_UK703B > MYSQL_VAR_8J2N81 * 1.5 THEN
        SET MYSQL_VAR_GL9CWR = 50;
    ELSE
        SET MYSQL_VAR_GL9CWR = 25;
    END IF;

    RETURN MYSQL_VAR_GL9CWR;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AUY523----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AUY523(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GKH7OL INT DEFAULT 0;
    DECLARE MYSQL_VAR_3YYJG6 DECIMAL(5,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_6SSNLE(10) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_GKH7OL
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_3YYJG6
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM
    AND ORDER_ID IN (SELECT ORDER_ID FROM ORDERS WHERE ORDER_DATE >= DATE_SUB(CURDATE(), INTERVAL 7 DAY));

    IF MYSQL_VAR_GKH7OL = 0 THEN
        RETURN 999;
    END IF;

    RETURN (MYSQL_FUNC_GRHCIN(20) - (0) + COALESCE(FLOOR((MYSQL_VAR_3YYJG6 / MYSQL_VAR_GKH7OL) * 100), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IUCCJL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IUCCJL(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_017YWK INT DEFAULT 0;
    DECLARE MYSQL_VAR_FJD9Z9 INT DEFAULT 95;
    DECLARE MYSQL_VAR_RGJ616 INT DEFAULT 7;
    DECLARE MYSQL_VAR_A645MI DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_2J2A1J INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZGWCO2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_X6WYXF INT DEFAULT 0;

    SELECT COALESCE(QUALITY_CERTIFIED, 0), COALESCE(ON_TIME_DELIVERY_RATE, 95)
    INTO MYSQL_VAR_017YWK, MYSQL_VAR_FJD9Z9
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SELECT COUNT(*), COUNT(CASE WHEN ACTUAL_DELIVERY_DATE > EXPECTED_DELIVERY_DATE THEN 1 END)
    INTO MYSQL_VAR_X6WYXF, MYSQL_VAR_ZGWCO2
    FROM PURCHASE_ORDERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    IF MYSQL_VAR_X6WYXF > 0 THEN
        SET MYSQL_VAR_A645MI = (MYSQL_VAR_ZGWCO2 * 100.0) / MYSQL_VAR_X6WYXF;
    END IF;

    SET MYSQL_VAR_2J2A1J = (MYSQL_VAR_017YWK * 30) + (MYSQL_VAR_FJD9Z9 / 2) - (MYSQL_VAR_A645MI * 5);

    RETURN GREATEST(MYSQL_VAR_2J2A1J, 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_L3XHPT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L3XHPT(N INT, DEPTH INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_64EB3A INT DEFAULT 0;
    DECLARE MYSQL_VAR_AVL70V INT DEFAULT 1;

    IF DEPTH <= 0 OR N <= 0 THEN
        RETURN 0;
    END IF;

    CALC_LOOP: WHILE MYSQL_VAR_AVL70V <= N DO
        SET MYSQL_VAR_64EB3A = MYSQL_VAR_64EB3A + MYSQL_VAR_AVL70V;
        SET MYSQL_VAR_AVL70V = MYSQL_VAR_AVL70V + 1;
    END WHILE CALC_LOOP;

    IF DEPTH > 1 THEN
        SET MYSQL_VAR_64EB3A = MYSQL_VAR_64EB3A + MYSQL_FUNC_L3XHPT(N - 1, DEPTH - 1);
    END IF;

    RETURN MYSQL_VAR_64EB3A;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5V5EP8(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HUFK5L INT DEFAULT 0;
    DECLARE MYSQL_VAR_3CDP3J INT DEFAULT 0;
    DECLARE MYSQL_VAR_IW9GNP INT DEFAULT 0;
    DECLARE MYSQL_VAR_HPYZUO INT DEFAULT 0;
    DECLARE MYSQL_VAR_4RNJXH INT DEFAULT 0;

    SET MYSQL_VAR_IW9GNP = MYSQL_FUNC_L3XHPT(30, 31);
    SET MYSQL_VAR_HPYZUO = B;

    GCD_LOOP: WHILE MYSQL_VAR_HPYZUO != 0 DO
        SET MYSQL_VAR_4RNJXH = MYSQL_VAR_IW9GNP % MYSQL_VAR_HPYZUO;
        SET MYSQL_VAR_IW9GNP = MYSQL_VAR_HPYZUO;
        SET MYSQL_VAR_HPYZUO = MYSQL_VAR_4RNJXH;
    END WHILE GCD_LOOP;

    SET MYSQL_VAR_HUFK5L = MYSQL_VAR_IW9GNP;

    IF MYSQL_VAR_HUFK5L = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_3CDP3J = MYSQL_FUNC_IUCCJL(30);

    RETURN (MYSQL_FUNC_AUY523(10) - (0) + COALESCE(MYSQL_VAR_3CDP3J, 0));
END//

DELIMITER ;