/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS table_dubmq9 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100)
);
INSERT INTO table_dubmq9 (name) VALUES 
    ('Product A'),
    ('Product B'),
    ('Product C'),
    ('Product D'),
    ('Product E'),
    ('Product F'),
    ('Product G');

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_XS82MK----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XS82MK(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4DHPT0 INT DEFAULT 0;
    DECLARE MYSQL_VAR_TRA3SS INT DEFAULT 1;
    DECLARE MYSQL_VAR_MHR2TL INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y5BOTZ INT DEFAULT 2;

    IF N = 0 THEN
        RETURN 0;
    END IF;
    IF N = 1 THEN
        RETURN 1;
    END IF;

    WHILE MYSQL_VAR_Y5BOTZ <= N DO
        SET MYSQL_VAR_MHR2TL = MYSQL_VAR_4DHPT0 + MYSQL_VAR_TRA3SS;
        SET MYSQL_VAR_4DHPT0 = MYSQL_VAR_TRA3SS;
        SET MYSQL_VAR_TRA3SS = MYSQL_VAR_MHR2TL;
        SET MYSQL_VAR_Y5BOTZ = MYSQL_VAR_Y5BOTZ + 1;
    END WHILE;

    RETURN MYSQL_VAR_TRA3SS;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6L3S50----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6L3S50() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GZHRQ9 INT;
    DECLARE MYSQL_VAR_P4S7HI INT DEFAULT 0;

    SELECT COUNT(*) INTO MYSQL_VAR_GZHRQ9 FROM TABLE_DUBMQ9;

    IF MYSQL_VAR_GZHRQ9 >= 7 THEN
        SET MYSQL_VAR_P4S7HI = 1;
    ELSE
        SET MYSQL_VAR_P4S7HI = 0;
    END IF;

    RETURN MYSQL_VAR_P4S7HI;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VXNR84(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FBS4GA DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_6L3S50()
    INTO MYSQL_VAR_FBS4GA
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_XS82MK(10);
END//

DELIMITER ;