/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_D56L6L----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_D56L6L(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4PX3B7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_P3N4N9 DATE;
    DECLARE MYSQL_VAR_69WVNB DATE;

    SELECT COUNT(*), MIN(ORDER_DATE), MAX(ORDER_DATE)
    INTO MYSQL_VAR_4PX3B7, MYSQL_VAR_P3N4N9, MYSQL_VAR_69WVNB
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_4PX3B7 < 2 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR(DATEDIFF(MYSQL_VAR_69WVNB, MYSQL_VAR_P3N4N9) / (MYSQL_VAR_4PX3B7 - 1));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JRP5H5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JRP5H5(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MQ93S6 INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_MQ93S6
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN 30 - MYSQL_VAR_MQ93S6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_IK4G9R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_IK4G9R(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OE9SLC DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0)
    INTO MYSQL_VAR_OE9SLC
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_OE9SLC * 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PYMD0R----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PYMD0R(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ELXOQY INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_ELXOQY
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN 30 - MYSQL_VAR_ELXOQY;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_132U2S----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_132U2S(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_97WTCU INT DEFAULT 0;
    DECLARE MYSQL_VAR_N6LG4S INT DEFAULT 0;
    DECLARE MYSQL_VAR_06JK7G INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_97WTCU
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(CONVERSION_VALUE), 0)
    INTO MYSQL_VAR_N6LG4S
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_97WTCU = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_06JK7G = MYSQL_FUNC_IK4G9R(30);

    RETURN MYSQL_FUNC_PYMD0R(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ILACKF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ILACKF(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_22RI5E DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_JRP5H5(10)
    INTO MYSQL_VAR_22RI5E
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_FUNC_132U2S(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S110UQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S110UQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_SEVR7B INT DEFAULT 0;

    SELECT MYSQL_FUNC_D56L6L(30)
    INTO MYSQL_VAR_SEVR7B
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'ACTIVE';

    RETURN MYSQL_FUNC_ILACKF(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WTOM4W(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_XVDZJ1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_LSAXX6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_86K3GU INT DEFAULT 0;
    DECLARE MYSQL_VAR_IJVG1M INT DEFAULT 0;

    SELECT COALESCE(BUDGET, 0), COALESCE(SPENT_AMOUNT, 0)
    INTO MYSQL_VAR_XVDZJ1, MYSQL_VAR_LSAXX6
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_XVDZJ1 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_86K3GU = MYSQL_VAR_XVDZJ1 - MYSQL_VAR_LSAXX6;
    SET MYSQL_VAR_IJVG1M = MYSQL_FUNC_S110UQ(10);

    RETURN CAST(MYSQL_VAR_IJVG1M AS SIGNED);
END//

DELIMITER ;