/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_Z73713----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z73713(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_E9L4BW INT DEFAULT 0;
    DECLARE MYSQL_VAR_GHB3AO INT DEFAULT 0;
    DECLARE MYSQL_VAR_WB4TQB INT DEFAULT 0;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COUNT(*)
    INTO MYSQL_VAR_E9L4BW, MYSQL_VAR_GHB3AO
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_WB4TQB = (MYSQL_VAR_E9L4BW / 100) + (MYSQL_VAR_GHB3AO * 5);

    RETURN MYSQL_VAR_WB4TQB;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_RF2DE7----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_RF2DE7(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QB6O72 VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_BZ5M3D INT DEFAULT 0;
    DECLARE MYSQL_VAR_RN2BWD INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0), TIMESTAMPDIFF(MONTH, START_DATE, CURDATE())
    INTO MYSQL_VAR_QB6O72, MYSQL_VAR_BZ5M3D, MYSQL_VAR_RN2BWD
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_QB6O72 != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_VAR_BZ5M3D * MYSQL_VAR_RN2BWD) / 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BE7ASW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BE7ASW(N INT) RETURNS INT
BEGIN
RETURN N * N;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5DZW0D----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5DZW0D(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_J6SI5A INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_J6SI5A
    FROM CUSTOMERS
    WHERE COUNTRY = COUNTRY_PARAM;

    RETURN MYSQL_VAR_J6SI5A;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z9E7PH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z9E7PH(HOTEL_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FH60E6 INT DEFAULT 3;
    DECLARE MYSQL_VAR_RU284G INT DEFAULT 100;
    DECLARE MYSQL_VAR_FNXZAZ INT DEFAULT 70;
    DECLARE MYSQL_VAR_5KIMTH INT DEFAULT 50;
    DECLARE MYSQL_VAR_UCG39K INT DEFAULT 0;
    DECLARE MYSQL_VAR_7FHPEK INT DEFAULT 0;

    SELECT COALESCE(STAR_RATING, 3), COALESCE(AVERAGE_DAILY_RATE, 100), COALESCE(OCCUPANCY_RATE, 70)
    INTO MYSQL_VAR_FH60E6, MYSQL_VAR_RU284G, MYSQL_VAR_FNXZAZ
    FROM HOTELS
    WHERE HOTEL_ID = HOTEL_ID_PARAM;

    SET MYSQL_VAR_UCG39K = MYSQL_VAR_5KIMTH * MYSQL_VAR_RU284G * MYSQL_VAR_FH60E6 / 3;
    SET MYSQL_VAR_7FHPEK = (MYSQL_VAR_UCG39K * 365 * MYSQL_VAR_FNXZAZ) / 100;

    RETURN FLOOR(MYSQL_VAR_7FHPEK);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1ENVDN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1ENVDN(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GUQNF5 INT DEFAULT 0;

    SELECT MONTH(START_DATE)
    INTO MYSQL_VAR_GUQNF5
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN MYSQL_VAR_GUQNF5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XN9NC8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XN9NC8(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2MU5F0 INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_2MU5F0
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN GREATEST(100 - (MYSQL_VAR_2MU5F0 * 5), 0);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VXNR84----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VXNR84(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FBS4GA DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_FBS4GA
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN (MYSQL_FUNC_XN9NC8(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_FBS4GA / 12), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_A8R587----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_A8R587(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8U91KY INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y7FX0F DECIMAL(5,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_Z7KX9J INT DEFAULT 0;

    SELECT (MYSQL_FUNC_1ENVDN(10) - (0) + COALESCE(COALESCE(STOCK_QUANTITY, 0), 0))
    INTO MYSQL_VAR_8U91KY
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT (MYSQL_FUNC_VXNR84(20) - (0) + COALESCE(COALESCE(AVG(QUANTITY), 0) / 30, 0))
    INTO MYSQL_VAR_Y7FX0F
    FROM ORDER_ITEMS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SET MYSQL_VAR_Z7KX9J = MYSQL_FUNC_Z9E7PH(20);

    IF MYSQL_VAR_8U91KY < MYSQL_VAR_Z7KX9J THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JLTUWZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JLTUWZ(CALL_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_0PFVJJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_EVTVEZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_DW14L9 INT DEFAULT 75;
    DECLARE MYSQL_VAR_TSZ3HY INT DEFAULT 50;
    DECLARE MYSQL_VAR_TSNUXL INT DEFAULT 0;

    SELECT (MYSQL_FUNC_A8R587(20) - (0) + COALESCE(COALESCE(LABOR_HOURS, 0), COALESCE(PARTS_COST, 0), 0))
    INTO MYSQL_VAR_0PFVJJ, MYSQL_VAR_EVTVEZ
    FROM PLUMBING_SERVICE_CALLS
    WHERE CALL_ID = CALL_ID_PARAM;

    SELECT (MYSQL_FUNC_5DZW0D('test_0_0') - (0) + COALESCE(COALESCE(HOURLY_RATE, 75), 0))
    INTO MYSQL_VAR_DW14L9
    FROM PLUMBING_SERVICE_CALLS PC
    JOIN PLUMBERS P ON PC.PLUMBER_ID = P.PLUMBER_ID
    WHERE PC.CALL_ID = CALL_ID_PARAM;

    SET MYSQL_VAR_TSNUXL = MYSQL_FUNC_RF2DE7(20);

    RETURN (MYSQL_FUNC_BE7ASW(10) - (0) + COALESCE(CAST(MYSQL_VAR_TSNUXL AS SIGNED), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FIPA22----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FIPA22(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D8BAXM DATE;

    SELECT (MYSQL_FUNC_JLTUWZ(10) - (0) + COALESCE(END_DATE, 0))
    INTO MYSQL_VAR_D8BAXM
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_D8BAXM IS NULL THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_Z73713(30) - (0) + COALESCE(GREATEST(DATEDIFF(MYSQL_VAR_D8BAXM, CURDATE()), 0), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6XKQMX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6XKQMX(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QVD59I INT DEFAULT 0;

    SELECT TIMESTAMPDIFF(DAY, REGISTRATION_DATE, CURDATE())
    INTO MYSQL_VAR_QVD59I
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_QVD59I;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KJUMFU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KJUMFU(RENTAL_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BKV555 INT DEFAULT 4;
    DECLARE MYSQL_VAR_GM684T INT DEFAULT 200;
    DECLARE MYSQL_VAR_4PMHBD INT DEFAULT 150;
    DECLARE MYSQL_VAR_BW4MJD INT DEFAULT 0;
    DECLARE MYSQL_VAR_53SGYN INT DEFAULT 0;

    SELECT COALESCE(RENTAL_HOURS, 4), COALESCE(HOURLY_RATE, 200), COALESCE(CAPTAIN_REQUIRED, 0)
    INTO MYSQL_VAR_BKV555, MYSQL_VAR_GM684T, MYSQL_VAR_4PMHBD
    FROM BOAT_RENTALS
    WHERE RENTAL_ID = RENTAL_ID_PARAM;

    SELECT LENGTH_FEET * 5 INTO MYSQL_VAR_BW4MJD
    FROM BOAT_RENTALS BR
    JOIN BOATS B ON BR.BOAT_ID = B.BOAT_ID
    WHERE BR.RENTAL_ID = RENTAL_ID_PARAM AND FUEL_INCLUDED = 0;

    SET MYSQL_VAR_53SGYN = MYSQL_FUNC_FIPA22(20);

    IF MYSQL_VAR_4PMHBD > 0 THEN
        SET MYSQL_VAR_53SGYN = MYSQL_VAR_53SGYN + MYSQL_VAR_4PMHBD;
    END IF;

    RETURN (MYSQL_FUNC_6XKQMX(10) - (0) + COALESCE(CAST(MYSQL_VAR_53SGYN AS SIGNED), 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GJQFPZ(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OX7OHA DECIMAL(3,1) DEFAULT 0.0;
    DECLARE MYSQL_VAR_6JYFPG INT DEFAULT 0;
    DECLARE MYSQL_VAR_5LQYKD INT DEFAULT 0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0), COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_OX7OHA, MYSQL_VAR_6JYFPG
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    SET MYSQL_VAR_5LQYKD = MYSQL_FUNC_KJUMFU(30);

    RETURN MYSQL_VAR_5LQYKD;
END//

DELIMITER ;