/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_X0RVNT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_X0RVNT(STORE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MP9E8F INT DEFAULT 0;
    DECLARE MYSQL_VAR_SRCYN7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_U9HJFL INT DEFAULT 0;
    DECLARE MYSQL_VAR_VRQEAV INT DEFAULT 0;

    SELECT COALESCE(SALES_TARGET, 0), COALESCE(SALES_ACTUAL, 0)
    INTO MYSQL_VAR_MP9E8F, MYSQL_VAR_SRCYN7
    FROM RETAIL_STORES
    WHERE STORE_ID = STORE_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_U9HJFL
    FROM STORE_EMPLOYEES
    WHERE STORE_ID = STORE_ID_PARAM;

    IF MYSQL_VAR_MP9E8F = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_VRQEAV = ((MYSQL_VAR_SRCYN7 - MYSQL_VAR_MP9E8F) * 100) / MYSQL_VAR_MP9E8F;

    IF MYSQL_VAR_U9HJFL > 10 THEN
        SET MYSQL_VAR_VRQEAV = MYSQL_VAR_VRQEAV - 5;
    END IF;

    RETURN CAST(MYSQL_VAR_VRQEAV AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4LRZ21----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4LRZ21(SALESPERSON_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PXA8SS INT DEFAULT 0;
    DECLARE MYSQL_VAR_LO5500 INT DEFAULT 0;
    DECLARE MYSQL_VAR_N4R6NC INT DEFAULT 0;
    DECLARE MYSQL_VAR_KWIT01 INT DEFAULT 5;
    DECLARE MYSQL_VAR_XVEOPC INT DEFAULT 0;

    SELECT COUNT(*), SUM(QUANTITY * UNIT_PRICE)
    INTO MYSQL_VAR_LO5500, MYSQL_VAR_PXA8SS
    FROM SALES
    WHERE SALESPERSON_ID = SALESPERSON_ID_PARAM
      AND SALE_DATE >= DATE_SUB(CURDATE(), INTERVAL 1 YEAR);

    IF MYSQL_VAR_LO5500 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_N4R6NC = MYSQL_VAR_PXA8SS / MYSQL_VAR_LO5500;

    CASE
        WHEN MYSQL_VAR_N4R6NC > 5000 THEN SET MYSQL_VAR_KWIT01 = 12;
        WHEN MYSQL_VAR_N4R6NC > 2000 THEN SET MYSQL_VAR_KWIT01 = 8;
        WHEN MYSQL_VAR_N4R6NC > 1000 THEN SET MYSQL_VAR_KWIT01 = 6;
        ELSE SET MYSQL_VAR_KWIT01 = 4;
    END CASE;

    SET MYSQL_VAR_XVEOPC = MYSQL_VAR_PXA8SS * MYSQL_VAR_KWIT01 / 100;

    RETURN MYSQL_VAR_XVEOPC;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6HYJG5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6HYJG5(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FX0IE6 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_FX0IE6
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN MYSQL_VAR_FX0IE6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BASEBM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BASEBM(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1LZMNB INT DEFAULT 0;

    SELECT MYSQL_FUNC_4LRZ21(10)
    INTO MYSQL_VAR_1LZMNB
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_6HYJG5(20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_N5QMBU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_N5QMBU(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RPGYN8 DATE;

    SELECT START_DATE
    INTO MYSQL_VAR_RPGYN8
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_RPGYN8 IS NULL THEN
        RETURN 0;
    END IF;

    RETURN DATEDIFF(CURDATE(), MYSQL_VAR_RPGYN8);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KKOU8N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KKOU8N(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AQMN6O INT DEFAULT 0;

    SELECT MYSQL_FUNC_N5QMBU(30)
    INTO MYSQL_VAR_AQMN6O
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_AQMN6O / 1000);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KHTKEG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KHTKEG(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_VKZ3I7 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SALARY, 0)
    INTO MYSQL_VAR_VKZ3I7
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_VKZ3I7);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EBADOC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EBADOC(MEMBER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ZNSUD8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZSUKQX INT DEFAULT 0;
    DECLARE MYSQL_VAR_1SCJD3 INT DEFAULT 50;
    DECLARE MYSQL_VAR_BOIDEZ INT DEFAULT 0;
    DECLARE MYSQL_VAR_8BS9B2 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_FEE, 0) INTO MYSQL_VAR_ZNSUD8
    FROM GYM_MEMBERS
    WHERE MEMBER_ID = MEMBER_ID_PARAM;

    SELECT MYSQL_FUNC_KKOU8N(10) INTO MYSQL_VAR_8BS9B2
    FROM TRAINER_SESSIONS
    WHERE MEMBER_ID = MEMBER_ID_PARAM
      AND SESSION_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SET MYSQL_VAR_1SCJD3 = MYSQL_FUNC_X0RVNT(10);
    SET MYSQL_VAR_BOIDEZ = MYSQL_FUNC_KHTKEG(20);

    RETURN MYSQL_FUNC_BASEBM(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_9ULDSZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_9ULDSZ(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_K65Q98 DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_K65Q98
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_K65Q98 * 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P6DCN0----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P6DCN0(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2JCURD INT DEFAULT 0;
    SET MYSQL_VAR_2JCURD = MYSQL_FUNC_9ULDSZ(20);
    RETURN MYSQL_VAR_2JCURD;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WE29AV(P_NUM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GLPNQJ INT;
    DECLARE MYSQL_VAR_OFA815 INT;
    DECLARE MYSQL_VAR_04HYOU INT;
    DECLARE MYSQL_VAR_NCJ7TR INT;
    DECLARE MYSQL_VAR_GAGLZU INT DEFAULT 1000;

    SET MYSQL_VAR_GLPNQJ = MYSQL_FUNC_P6DCN0(30, 31);

    SEARCH_LOOP: WHILE MYSQL_VAR_GLPNQJ <= P_NUM + MYSQL_VAR_GAGLZU DO
        SET MYSQL_VAR_04HYOU = 1;

        IF MYSQL_VAR_GLPNQJ <= 1 THEN
            SET MYSQL_VAR_04HYOU = 0;
        ELSEIF MYSQL_VAR_GLPNQJ = 2 THEN
            SET MYSQL_VAR_04HYOU = 1;
        ELSEIF MYSQL_VAR_GLPNQJ % 2 = 0 THEN
            SET MYSQL_VAR_04HYOU = 0;
        ELSE
            SET MYSQL_VAR_NCJ7TR = CAST(SQRT(MYSQL_VAR_GLPNQJ) AS UNSIGNED);
            SET MYSQL_VAR_OFA815 = 3;
            INNER_LOOP: WHILE MYSQL_VAR_OFA815 <= MYSQL_VAR_NCJ7TR DO
                IF MYSQL_VAR_GLPNQJ % MYSQL_VAR_OFA815 = 0 THEN
                    SET MYSQL_VAR_04HYOU = 0;
                    LEAVE INNER_LOOP;
                END IF;
                SET MYSQL_VAR_OFA815 = MYSQL_VAR_OFA815 + 2;
            END WHILE INNER_LOOP;
        END IF;

        IF MYSQL_VAR_04HYOU = 1 THEN
            RETURN MYSQL_VAR_GLPNQJ;
        END IF;

        SET MYSQL_VAR_GLPNQJ = MYSQL_VAR_GLPNQJ + 1;
    END WHILE SEARCH_LOOP;

    RETURN MYSQL_FUNC_EBADOC(30);
END//

DELIMITER ;