/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_N79RUF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_N79RUF(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BKNFEK INT DEFAULT 0;
    DECLARE MYSQL_VAR_G32R82 INT DEFAULT 0;

    SELECT COALESCE(MAX(PRICE), 0), COALESCE(MIN(PRICE), 1)
    INTO MYSQL_VAR_BKNFEK, MYSQL_VAR_G32R82
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN MYSQL_VAR_BKNFEK - MYSQL_VAR_G32R82;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AXWHLP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AXWHLP(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UV4KG2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_W78DPI INT DEFAULT 0;
    DECLARE MYSQL_VAR_2O4Y46 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JRYPI9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_DT752D INT DEFAULT 0;

    SELECT COALESCE(BUDGET_ALLOCATED, 0), COALESCE(LEADS_GENERATED, 0), COALESCE(CONVERSIONS, 0)
    INTO MYSQL_VAR_UV4KG2, MYSQL_VAR_W78DPI, MYSQL_VAR_2O4Y46
    FROM MARKETING_CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(AMOUNT_SPENT), 0) INTO MYSQL_VAR_JRYPI9
    FROM CAMPAIGN_SPEND
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_UV4KG2 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_DT752D = ((MYSQL_VAR_2O4Y46 * 100) - MYSQL_VAR_JRYPI9) * 100 / MYSQL_VAR_UV4KG2;

    RETURN CAST(MYSQL_VAR_DT752D AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BAYQDF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BAYQDF(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8X6W62 DATE;
    DECLARE MYSQL_VAR_HX0C9B VARCHAR(20) DEFAULT 'INACTIVE';

    SELECT START_DATE, STATUS
    INTO MYSQL_VAR_8X6W62, MYSQL_VAR_HX0C9B
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_HX0C9B != 'ACTIVE' OR MYSQL_VAR_8X6W62 IS NULL THEN
        RETURN 0;
    END IF;

    RETURN TIMESTAMPDIFF(MONTH, MYSQL_VAR_8X6W62, CURDATE());
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LTOQJN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LTOQJN(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FB62FT DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_FB62FT
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_FB62FT);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4HE4M3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4HE4M3(VEHICLE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BYW6I3 INT DEFAULT 0;
    DECLARE MYSQL_VAR_1YNYG8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_HB5T31 INT DEFAULT 5000;
    DECLARE MYSQL_VAR_U9T9NO INT DEFAULT 0;
    DECLARE MYSQL_VAR_YQ1LMT INT DEFAULT 0;

    SELECT MYSQL_FUNC_BAYQDF(20) INTO MYSQL_VAR_BYW6I3
    FROM VEHICLES
    WHERE VEHICLE_ID = VEHICLE_ID_PARAM;

    SELECT COALESCE(MILEAGE, 0) INTO MYSQL_VAR_1YNYG8
    FROM SERVICE_RECORDS
    WHERE VEHICLE_ID = VEHICLE_ID_PARAM
    ORDER BY SERVICE_DATE DESC LIMIT 1;

    SET MYSQL_VAR_U9T9NO = MYSQL_VAR_1YNYG8 + MYSQL_VAR_HB5T31;
    SET MYSQL_VAR_YQ1LMT = MYSQL_FUNC_AXWHLP(20);

    IF MYSQL_VAR_YQ1LMT > 0 THEN
        RETURN 0 - MYSQL_VAR_YQ1LMT;
    END IF;

    RETURN MYSQL_FUNC_LTOQJN(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HV4PYL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HV4PYL(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_NHL7DG INT DEFAULT 0;
    DECLARE MYSQL_VAR_GXGAJ8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Q1A0RI INT DEFAULT 0;
    DECLARE MYSQL_VAR_693FDO INT DEFAULT 0;

    SELECT MYSQL_FUNC_4HE4M3(30)
    INTO MYSQL_VAR_NHL7DG, MYSQL_VAR_GXGAJ8, MYSQL_VAR_Q1A0RI
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_693FDO = (MYSQL_VAR_NHL7DG * 2) + (MYSQL_VAR_GXGAJ8 * 3) + (MYSQL_VAR_Q1A0RI / 5);

    RETURN MYSQL_FUNC_N79RUF(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z1IBA4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z1IBA4(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3Z6QKM INT DEFAULT 0;
    DECLARE MYSQL_VAR_68U8XF INT DEFAULT 0;
    DECLARE MYSQL_VAR_D3F97E INT DEFAULT 0;
    DECLARE MYSQL_VAR_H41G35 INT DEFAULT 0;
    DECLARE MYSQL_VAR_MOA6U1 VARCHAR(50) DEFAULT '';

    SELECT REFERRAL_CODE
    INTO MYSQL_VAR_MOA6U1
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_3Z6QKM
    FROM CUSTOMERS
    WHERE REFERRED_BY = MYSQL_VAR_MOA6U1;

    SELECT COALESCE(SUM(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_68U8XF
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.REFERRED_BY = MYSQL_VAR_MOA6U1;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_D3F97E
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_D3F97E = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_H41G35 = ((MYSQL_VAR_68U8XF - MYSQL_VAR_D3F97E) * 100) / MYSQL_VAR_D3F97E;

    RETURN MYSQL_VAR_H41G35;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VNMVHB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VNMVHB(SIDE INT) RETURNS INT
BEGIN
RETURN SIDE * 4;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AN6XUB----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AN6XUB(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5LECCX DECIMAL(10,2) DEFAULT 0.00;

    SELECT MYSQL_FUNC_Z1IBA4(30)
    INTO MYSQL_VAR_5LECCX
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_FUNC_VNMVHB(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_01PZD0() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IUY7VZ INT DEFAULT 0;
    
    SELECT MYSQL_FUNC_AN6XUB(10) INTO MYSQL_VAR_IUY7VZ FROM TABLE_TL7J49.`TABLE3`;
    
    RETURN MYSQL_FUNC_HV4PYL(30);
END//

DELIMITER ;