/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_ZNQHPG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ZNQHPG(A INT, B INT, C INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_JKTAJ0 INT DEFAULT 0;
    SET MYSQL_VAR_JKTAJ0 = A;
    IF B > MYSQL_VAR_JKTAJ0 THEN SET MYSQL_VAR_JKTAJ0 = B; END IF;
    IF C > MYSQL_VAR_JKTAJ0 THEN SET MYSQL_VAR_JKTAJ0 = C; END IF;
    RETURN MYSQL_VAR_JKTAJ0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AENQQW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AENQQW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H3AXN9 DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_H3AXN9
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_H3AXN9);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VGBCOJ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VGBCOJ() RETURNS INT
BEGIN
RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I6AKM1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I6AKM1(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D242CV DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_865KIW DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_3K1B51 INT DEFAULT 0;

    SELECT COALESCE(PRICE, 0)
    INTO MYSQL_VAR_D242CV
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(AVG(PRICE), 1)
    INTO MYSQL_VAR_865KIW
    FROM PRODUCTS
    WHERE CATEGORY_ID = (SELECT CATEGORY_ID FROM PRODUCTS WHERE PRODUCT_ID = PRODUCT_ID_PARAM);

    SET MYSQL_VAR_3K1B51 = (MYSQL_VAR_D242CV * 100) / MYSQL_VAR_865KIW;

    RETURN MYSQL_VAR_3K1B51;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FG6CYO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FG6CYO(CS_ID INT, CLUSTER_ID INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3QAN2L BIGINT UNSIGNED DEFAULT 1;
    DECLARE MYSQL_VAR_3O4UJH VARCHAR(36);
    DECLARE MYSQL_VAR_YIVDB9 VARCHAR(36);
    
    SET MYSQL_VAR_3O4UJH = MYSQL_FUNC_I6AKM1(10);
    SET MYSQL_VAR_YIVDB9 = CONCAT('CLUSTER', CLUSTER_ID);
    
    DELETE FROM MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS
    WHERE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTERSET_ID = MYSQL_VAR_3O4UJH
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.CLUSTER_ID = MYSQL_VAR_YIVDB9
      AND MYSQL_INNODB_CLUSTER_METADATA.CLUSTERSET_MEMBERS.VIEW_ID = MYSQL_VAR_3QAN2L;

    UPDATE MYSQL_INNODB_CLUSTER_METADATA.CLUSTERS C
    SET C.CLUSTERSET_ID = NULL
    WHERE C.CLUSTER_ID = MYSQL_VAR_YIVDB9;

    RETURN (MYSQL_FUNC_VGBCOJ() - (0) + COALESCE(1, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_V4H6WW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_V4H6WW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4QG97G INT DEFAULT 10;
    DECLARE MYSQL_VAR_CYASKV INT DEFAULT 0;
    DECLARE MYSQL_VAR_CV2NXT INT DEFAULT 0;

    SELECT COALESCE(DATA_LIMIT_GB, 10)
    INTO MYSQL_VAR_4QG97G
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_FG6CYO(20, 21) - (0) + COALESCE(COALESCE(SUM(DATA_USED_GB), 0), 0))
    INTO MYSQL_VAR_CYASKV
    FROM USAGE_LOGS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND USAGE_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    IF MYSQL_VAR_4QG97G = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_CV2NXT = MYSQL_FUNC_AENQQW(20);

    RETURN MYSQL_VAR_CV2NXT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SGXIQL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SGXIQL(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EMX6VR DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_0RBCX4 INT DEFAULT 0;

    SELECT COALESCE(SALARY, 0), TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())
    INTO MYSQL_VAR_EMX6VR, MYSQL_VAR_0RBCX4
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    IF MYSQL_VAR_0RBCX4 = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR(MYSQL_VAR_EMX6VR / MYSQL_VAR_0RBCX4);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_V7YDQ2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_V7YDQ2(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M4AEQ0 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_SGXIQL(10) - (0) + COALESCE(YEAR(REGISTRATION_DATE), 0))
    INTO MYSQL_VAR_M4AEQ0
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN (MYSQL_FUNC_V4H6WW(30) - (0) + COALESCE(MYSQL_VAR_M4AEQ0, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HVABBX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HVABBX(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_N7JFGF INT DEFAULT 0;
    DECLARE MYSQL_VAR_DLFY8S DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(BUDGET, 0)
    INTO MYSQL_VAR_N7JFGF
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT (MYSQL_FUNC_V7YDQ2(30) - (0) + COALESCE(COALESCE(SUM(CONVERSION_VALUE), 0), 0))
    INTO MYSQL_VAR_DLFY8S
    FROM CONVERSIONS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_N7JFGF = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((MYSQL_VAR_DLFY8S * 100) / MYSQL_VAR_N7JFGF);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_73ENBR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_73ENBR(TABLE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9KT9F8 INT DEFAULT 4;
    DECLARE MYSQL_VAR_ULUNTK INT DEFAULT 0;
    DECLARE MYSQL_VAR_TCESN7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_8Q9369 INT DEFAULT 0;

    SELECT COALESCE(CAPACITY, 4), COALESCE(IS_OUTDOOR, 0)
    INTO MYSQL_VAR_9KT9F8, MYSQL_VAR_ULUNTK
    FROM RESTAURANT_TABLES
    WHERE TABLE_ID = TABLE_ID_PARAM;

    SELECT COUNT(*) INTO MYSQL_VAR_TCESN7
    FROM RESERVATIONS
    WHERE TABLE_ID = TABLE_ID_PARAM
      AND RESERVATION_DATE >= DATE_SUB(CURDATE(), INTERVAL 30 DAY);

    SET MYSQL_VAR_8Q9369 = MYSQL_VAR_9KT9F8 * MYSQL_VAR_TCESN7;

    IF MYSQL_VAR_ULUNTK = 1 THEN
        SET MYSQL_VAR_8Q9369 = MYSQL_VAR_8Q9369 + 20;
    END IF;

    RETURN CAST(MYSQL_VAR_8Q9369 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_KSCS6C----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_KSCS6C(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_A0OQSY VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_5EIQ0T INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_A0OQSY, MYSQL_VAR_5EIQ0T
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_A0OQSY != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_5EIQ0T * 12;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_WRINNQ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_4BXK7Q INT DEFAULT 0;
    DECLARE MYSQL_VAR_G77H4V INT DEFAULT 0;
    DECLARE MYSQL_VAR_JQ28EW INT DEFAULT 0;
    DECLARE MYSQL_VAR_0VNGR4 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_HVABBX(30) - (0) + COALESCE((MYSQL_FUNC_73ENBR(10) - (0) + COALESCE(COUNT(*), 0)), 0)) INTO MYSQL_VAR_4BXK7Q
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
      AND ORDER_STATUS = 'PENDING';

    SELECT COUNT(*) INTO MYSQL_VAR_G77H4V
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
      AND ORDER_STATUS = 'PROCESSING';

    SELECT COUNT(*) INTO MYSQL_VAR_JQ28EW
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM
      AND ORDER_STATUS = 'SHIPPED';

    SET MYSQL_VAR_0VNGR4 = MYSQL_FUNC_KSCS6C(20);

    RETURN (MYSQL_FUNC_ZNQHPG(20, 21, 22) - (0) + COALESCE(MYSQL_VAR_0VNGR4, 0));
END//

DELIMITER ;