/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_1DT1O5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1DT1O5(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_3D6A5F INT DEFAULT 0;
    DECLARE MYSQL_VAR_BYAQNP INT DEFAULT 0;
    DECLARE MYSQL_VAR_2IA9YW INT DEFAULT 0;
    DECLARE MYSQL_VAR_YY0A8U INT DEFAULT 0;

    SET MYSQL_VAR_BYAQNP = N;
    SET MYSQL_VAR_2IA9YW = LENGTH(CAST(N AS CHAR));

    WHILE MYSQL_VAR_BYAQNP > 0 DO
        SET MYSQL_VAR_YY0A8U = MYSQL_VAR_BYAQNP % 10;
        SET MYSQL_VAR_3D6A5F = MYSQL_VAR_3D6A5F + POW(MYSQL_VAR_YY0A8U, MYSQL_VAR_2IA9YW);
        SET MYSQL_VAR_BYAQNP = MYSQL_VAR_BYAQNP / 10;
    END WHILE;

    IF MYSQL_VAR_3D6A5F = N THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HU4JM8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HU4JM8(DOCTOR_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1EBFWA INT DEFAULT 0;
    DECLARE MYSQL_VAR_0JKVF2 INT DEFAULT 0;
    DECLARE MYSQL_VAR_C4GDDD INT DEFAULT 0;
    DECLARE MYSQL_VAR_R2SHL6 INT DEFAULT 0;
    DECLARE MYSQL_VAR_RFNFZW INT DEFAULT 0;

    SELECT COALESCE(YEARS_EXPERIENCE, 0), COALESCE(CONSULTATION_FEE, 100)
    INTO MYSQL_VAR_1EBFWA, MYSQL_VAR_0JKVF2
    FROM DOCTORS
    WHERE DOCTOR_ID = DOCTOR_ID_PARAM;

    SELECT COUNT(*)
    INTO MYSQL_VAR_C4GDDD
    FROM APPOINTMENTS
    WHERE DOCTOR_ID = DOCTOR_ID_PARAM
      AND MONTH(APPOINTMENT_DATE) = MONTH(CURDATE())
      AND STATUS = 'COMPLETED';

    SET MYSQL_VAR_R2SHL6 = 22;
    SET MYSQL_VAR_RFNFZW = (MYSQL_VAR_C4GDDD * 100) / MYSQL_VAR_R2SHL6;

    IF MYSQL_VAR_1EBFWA > 10 THEN
        SET MYSQL_VAR_RFNFZW = MYSQL_VAR_RFNFZW + 10;
    END IF;

    RETURN LEAST(MYSQL_VAR_RFNFZW, 100);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_79SFE3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_79SFE3(DEPARTMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IR23E8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_36EK8V INT DEFAULT 0;

    SELECT (MYSQL_FUNC_1DT1O5(10) - (0) + COALESCE(COALESCE(MAX(SALARY), 0), COALESCE(MIN(SALARY), 0), 0))
    INTO MYSQL_VAR_IR23E8, MYSQL_VAR_36EK8V
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN (MYSQL_FUNC_HU4JM8(20) - (0) + COALESCE(MYSQL_VAR_IR23E8 - MYSQL_VAR_36EK8V, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0VZMS1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0VZMS1(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_74U5XL DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(PRICE), 0)
    INTO MYSQL_VAR_74U5XL
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_74U5XL / 10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_I0MWJF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I0MWJF(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_1SBHSI VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_A9AEI9 INT DEFAULT 0;
    DECLARE MYSQL_VAR_0R0IRL INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0), TIMESTAMPDIFF(MONTH, START_DATE, CURDATE())
    INTO MYSQL_VAR_1SBHSI, MYSQL_VAR_A9AEI9, MYSQL_VAR_0R0IRL
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_1SBHSI != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_A9AEI9 * MYSQL_VAR_0R0IRL;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_003BTV----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_003BTV(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_FDUWBF INT DEFAULT 3;
    DECLARE MYSQL_VAR_LOKHLJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_N1Z61X INT DEFAULT 0;

    SELECT DATEDIFF(DELIVERY_DATE, ORDER_DATE)
    INTO MYSQL_VAR_LOKHLJ
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_LOKHLJ <= MYSQL_VAR_FDUWBF THEN
        SET MYSQL_VAR_N1Z61X = 100 - (MYSQL_VAR_LOKHLJ * 10);
    ELSE
        SET MYSQL_VAR_N1Z61X = 100 - ((MYSQL_VAR_LOKHLJ - MYSQL_VAR_FDUWBF) * 20);
    END IF;

    RETURN (MYSQL_FUNC_I0MWJF(30) - (0) + COALESCE(GREATEST(MYSQL_VAR_N1Z61X, 0), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_VSIF2U----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_VSIF2U(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BEXW7V INT DEFAULT 0;

    SELECT (MYSQL_FUNC_003BTV(30) - (0) + COALESCE(YEAR(ORDER_DATE), 0))
    INTO MYSQL_VAR_BEXW7V
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN (MYSQL_FUNC_0VZMS1(20) - (0) + COALESCE(MYSQL_VAR_BEXW7V, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_6PT9ZH----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_6PT9ZH(PET_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_S1XYPE INT DEFAULT 0;
    DECLARE MYSQL_VAR_NPXD63 INT DEFAULT 0;
    DECLARE MYSQL_VAR_Z1BGPS INT DEFAULT 0;
    DECLARE MYSQL_VAR_GYT0EK INT DEFAULT 0;
    DECLARE MYSQL_VAR_Y8BS91 INT DEFAULT 0;

    SELECT COALESCE(COUNT(*), 0), COALESCE(SUM(COST), 0)
    INTO MYSQL_VAR_S1XYPE, MYSQL_VAR_NPXD63
    FROM PET_SERVICES
    WHERE PET_ID = PET_ID_PARAM;

    SELECT COALESCE(AGE_MONTHS, 0), COALESCE(WEIGHT_KG, 0)
    INTO MYSQL_VAR_Z1BGPS, MYSQL_VAR_GYT0EK
    FROM PETS
    WHERE PET_ID = PET_ID_PARAM;

    SET MYSQL_VAR_Y8BS91 = (MYSQL_VAR_NPXD63 / 100) + (MYSQL_VAR_S1XYPE * 5);

    IF MYSQL_VAR_Z1BGPS < 12 THEN
        SET MYSQL_VAR_Y8BS91 = MYSQL_VAR_Y8BS91 + 20;
    END IF;

    IF MYSQL_VAR_GYT0EK > 30 THEN
        SET MYSQL_VAR_Y8BS91 = MYSQL_VAR_Y8BS91 + (MYSQL_VAR_GYT0EK - 30);
    END IF;

    RETURN CAST(MYSQL_VAR_Y8BS91 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_0GV05Z----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_0GV05Z(METER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5WBLZD INT DEFAULT 0;
    DECLARE MYSQL_VAR_2R29OX INT DEFAULT 0;
    DECLARE MYSQL_VAR_N50OFW INT DEFAULT 0;
    DECLARE MYSQL_VAR_SA8JZX INT DEFAULT 25;
    DECLARE MYSQL_VAR_AA3USZ INT DEFAULT 0;

    SELECT COALESCE(CURRENT_READING, 0), COALESCE(PREVIOUS_READING, 0)
    INTO MYSQL_VAR_5WBLZD, MYSQL_VAR_2R29OX
    FROM UTILITY_METERS
    WHERE METER_ID = METER_ID_PARAM;

    SET MYSQL_VAR_N50OFW = MYSQL_VAR_5WBLZD - MYSQL_VAR_2R29OX;

    IF MYSQL_VAR_N50OFW < 0 THEN
        SET MYSQL_VAR_N50OFW = 0;
    END IF;

    SET MYSQL_VAR_AA3USZ = MYSQL_VAR_SA8JZX + (MYSQL_VAR_N50OFW * 3);

    IF MYSQL_VAR_N50OFW > 100 THEN
        SET MYSQL_VAR_AA3USZ = MYSQL_VAR_AA3USZ + ((MYSQL_VAR_N50OFW - 100) * 5);
    END IF;

    RETURN CAST(MYSQL_VAR_AA3USZ AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_1PVB2M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_1PVB2M(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_B8NFQT INT DEFAULT 0;
    DECLARE MYSQL_VAR_W4LXBD INT DEFAULT 1;

    IF N <= 0 THEN
        RETURN 0;
    END IF;

    MY_LOOP: WHILE MYSQL_VAR_W4LXBD <= N DO
        SET MYSQL_VAR_B8NFQT = MYSQL_VAR_B8NFQT * 2;
        SET MYSQL_VAR_B8NFQT = MYSQL_VAR_B8NFQT + 1;
        SET MYSQL_VAR_W4LXBD = MYSQL_VAR_W4LXBD + 1;
    END WHILE MY_LOOP;

    RETURN MYSQL_VAR_B8NFQT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OHV87J----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OHV87J(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6Q5OEG DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_6Q5OEG
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_6Q5OEG);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_J2SZP5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_J2SZP5(BOOKING_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_G1YAW1 INT DEFAULT 0;
    DECLARE MYSQL_VAR_2QMCP5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_JCFG8K INT DEFAULT 1;
    DECLARE MYSQL_VAR_RSIT1W INT DEFAULT 0;

    SELECT COALESCE(TOTAL_COST, 0), COALESCE(DISCOUNT_PERCENT, 0)
    INTO MYSQL_VAR_G1YAW1, MYSQL_VAR_2QMCP5
    FROM TRAVEL_BOOKINGS
    WHERE BOOKING_ID = BOOKING_ID_PARAM;

    SELECT COALESCE(SEASON_MULTIPLIER, 1) INTO MYSQL_VAR_JCFG8K
    FROM TRAVEL_PACKAGES TP
    JOIN TRAVEL_BOOKINGS TB ON TP.DESTINATION = TB.DESTINATION
    WHERE TB.BOOKING_ID = BOOKING_ID_PARAM;

    SET MYSQL_VAR_G1YAW1 = MYSQL_VAR_G1YAW1 * MYSQL_VAR_JCFG8K;
    SET MYSQL_VAR_G1YAW1 = MYSQL_VAR_G1YAW1 - (MYSQL_VAR_G1YAW1 * MYSQL_VAR_2QMCP5 / 100);

    RETURN CAST(MYSQL_VAR_G1YAW1 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_N5QMBU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_N5QMBU(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RPGYN8 DATE;

    SELECT START_DATE
    INTO MYSQL_VAR_RPGYN8
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_RPGYN8 IS NULL THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_J2SZP5(20) - (0) + COALESCE(DATEDIFF(CURDATE(), MYSQL_VAR_RPGYN8), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_E88JTA----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_E88JTA(CARD_NUMBER VARCHAR(20)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BOCJUR INT DEFAULT 0;
    DECLARE MYSQL_VAR_NFICDY INT DEFAULT 1;
    DECLARE MYSQL_VAR_NZJWR7 VARCHAR(1);
    DECLARE MYSQL_VAR_4ZPJ25 INT DEFAULT 0;

    IF CARD_NUMBER IS NULL THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_NFICDY <= CHAR_LENGTH(CARD_NUMBER) DO
        SET MYSQL_VAR_NZJWR7 = SUBSTRING(CARD_NUMBER, MYSQL_VAR_NFICDY, 1);

        IF MYSQL_VAR_NZJWR7 IN ('0', '1', '2', '3', '4', '5', '6', '7', '8', '9') THEN
            SET MYSQL_VAR_4ZPJ25 = MYSQL_VAR_4ZPJ25 + 1;
        END IF;

        SET MYSQL_VAR_NFICDY = MYSQL_VAR_NFICDY + 1;
    END WHILE;

    IF MYSQL_VAR_4ZPJ25 >= 13 AND MYSQL_VAR_4ZPJ25 <= 19 THEN
        SET MYSQL_VAR_BOCJUR = 1;
    END IF;

    RETURN MYSQL_VAR_BOCJUR;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5TNCFY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5TNCFY(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MUOQWZ DECIMAL(10,2) DEFAULT 0.00;
    DECLARE MYSQL_VAR_IKP0TF INT DEFAULT 0;
    DECLARE MYSQL_VAR_1H9MLF DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SHIPPING_COST, 0)
    INTO MYSQL_VAR_MUOQWZ
    FROM SHIPMENTS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_IKP0TF
    FROM ORDER_ITEMS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_IKP0TF = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_1H9MLF = MYSQL_VAR_MUOQWZ / MYSQL_VAR_IKP0TF;

    RETURN FLOOR(MYSQL_VAR_1H9MLF);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CQ08ZQ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CQ08ZQ(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_D2CCLH DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_D2CCLH
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM AND O.STATUS = 'COMPLETED';

    RETURN FLOOR(MYSQL_VAR_D2CCLH);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_5EI3CR----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_5EI3CR(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HAC7E6 VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_BH5F35 VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_AL21M5 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_OHV87J(20) - (0) + COALESCE(PLAN_TYPE, 0))
    INTO MYSQL_VAR_HAC7E6
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_N5QMBU(30) - (0) + COALESCE(TIER_LEVEL, 0))
    INTO MYSQL_VAR_BH5F35
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    CASE MYSQL_VAR_HAC7E6
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_AL21M5 = 100;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_AL21M5 = 60;
        WHEN 'BASIC' THEN SET MYSQL_VAR_AL21M5 = 30;
        ELSE SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_CQ08ZQ('test_1_0');
    END CASE;

    CASE MYSQL_VAR_BH5F35
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_AL21M5 = MYSQL_FUNC_E88JTA('test_0_0');
        WHEN 'GOLD' THEN SET MYSQL_VAR_AL21M5 = MYSQL_VAR_AL21M5 + 25;
        WHEN 'SILVER' THEN SET MYSQL_VAR_AL21M5 = MYSQL_VAR_AL21M5 + 10;
    END CASE;

    RETURN (MYSQL_FUNC_5TNCFY(10) - (0) + COALESCE(MYSQL_VAR_AL21M5, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XUM2XW----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XUM2XW(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_02DXBE DATE;
    DECLARE MYSQL_VAR_E4ZHQP DATE;

    SELECT MIN(ORDER_DATE), MAX(ORDER_DATE)
    INTO MYSQL_VAR_02DXBE, MYSQL_VAR_E4ZHQP
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_02DXBE IS NULL THEN
        RETURN 0;
    END IF;

    RETURN DATEDIFF(MYSQL_VAR_E4ZHQP, MYSQL_VAR_02DXBE);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_55YXPD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_55YXPD(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AQ7TMG VARCHAR(50) DEFAULT '';
    DECLARE MYSQL_VAR_T7I488 INT DEFAULT 0;
    DECLARE MYSQL_VAR_478WRH INT DEFAULT 0;

    SELECT COUNTRY
    INTO MYSQL_VAR_AQ7TMG
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT (MYSQL_FUNC_XUM2XW(30) - (0) + COALESCE(COALESCE(AVG(TOTAL_AMOUNT), 0), 0))
    INTO MYSQL_VAR_T7I488
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    SELECT COALESCE(AVG(O.TOTAL_AMOUNT), 0)
    INTO MYSQL_VAR_478WRH
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = MYSQL_VAR_AQ7TMG AND O.STATUS = 'COMPLETED';

    IF MYSQL_VAR_478WRH = 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_5EI3CR(10) - (0) + COALESCE(FLOOR((MYSQL_VAR_T7I488 * 100) / MYSQL_VAR_478WRH), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_QF75ZL----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_QF75ZL(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IIZ3PU INT DEFAULT 0;
    DECLARE MYSQL_VAR_5M479K INT DEFAULT 0;
    DECLARE MYSQL_VAR_16INTN INT DEFAULT 0;
    DECLARE MYSQL_VAR_877EWB INT DEFAULT 0;
    DECLARE MYSQL_VAR_LW4AXJ INT DEFAULT 0;
    DECLARE MYSQL_VAR_HZ13VI INT DEFAULT 0;

    SELECT (MYSQL_FUNC_1PVB2M(30) - (0) + COALESCE(COALESCE(SUM(QUANTITY * UNIT_PRICE), 0), COALESCE(DISCOUNT_PERCENT, 0), COALESCE(SHIPPING_COST, 0), 0))
    INTO MYSQL_VAR_IIZ3PU, MYSQL_VAR_5M479K, MYSQL_VAR_16INTN
    FROM ORDER_ITEMS OI
    JOIN ORDERS O ON OI.ORDER_ID = O.ORDER_ID
    WHERE O.ORDER_ID = ORDER_ID_PARAM;

    SET MYSQL_VAR_5M479K = COALESCE(
        (SELECT DISCOUNT_PERCENT FROM ORDERS WHERE ORDER_ID = ORDER_ID_PARAM), 0
    );

    SET MYSQL_VAR_877EWB = MYSQL_FUNC_VSIF2U(30);

    SELECT (MYSQL_FUNC_55YXPD(10) - (0) + COALESCE(COALESCE(TOTAL_AMOUNT, 0) - MYSQL_VAR_877EWB, 0))
    INTO MYSQL_VAR_LW4AXJ
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_877EWB = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_HZ13VI = MYSQL_FUNC_0GV05Z(10);

    RETURN (MYSQL_FUNC_6PT9ZH(20) - (0) + COALESCE(MYSQL_VAR_HZ13VI, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EP80U1(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TUVF36 DECIMAL(10,2) DEFAULT 0.00;

    SELECT (MYSQL_FUNC_QF75ZL(30) - (0) + COALESCE(COALESCE(TOTAL_AMOUNT, 0), 0))
    INTO MYSQL_VAR_TUVF36
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN (MYSQL_FUNC_79SFE3(20) - (0) + COALESCE(FLOOR(MYSQL_VAR_TUVF36 * 0.1), 0));
END//

DELIMITER ;