/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_GCMS42----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GCMS42(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_F1G5XQ VARCHAR(20) DEFAULT 'DRAFT';

    SELECT STATUS
    INTO MYSQL_VAR_F1G5XQ
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN CASE WHEN MYSQL_VAR_F1G5XQ = 'ACTIVE' THEN 1 ELSE 0 END;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ISMQR5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ISMQR5(SESSION_TYPE_PARAM VARCHAR(50), HOURS_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PRFKA8 INT DEFAULT 200;
    DECLARE MYSQL_VAR_U0EBQ0 INT DEFAULT 1;
    DECLARE MYSQL_VAR_HRIJCK INT DEFAULT 0;

    CASE SESSION_TYPE_PARAM
        WHEN 'WEDDING' THEN SET MYSQL_VAR_PRFKA8 = 500;
        WHEN 'PORTRAIT' THEN SET MYSQL_VAR_PRFKA8 = 150;
        WHEN 'EVENT' THEN SET MYSQL_VAR_PRFKA8 = 300;
        WHEN 'PRODUCT' THEN SET MYSQL_VAR_PRFKA8 = 250;
        ELSE SET MYSQL_VAR_PRFKA8 = 200;
    END CASE;

    SET MYSQL_VAR_HRIJCK = MYSQL_VAR_PRFKA8 * HOURS_PARAM;

    RETURN CAST(MYSQL_VAR_HRIJCK AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SKTOIG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SKTOIG(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_W0JQFI INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_W0JQFI
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_W0JQFI * 12;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DQ097Y----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DQ097Y(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_TMAABX INT DEFAULT 0;
    DECLARE MYSQL_VAR_W6OHUE INT DEFAULT 0;

    SELECT COALESCE(DATEDIFF(CURDATE(), MAX(ORDER_DATE)), 999)
    INTO MYSQL_VAR_TMAABX
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET MYSQL_VAR_W6OHUE = 100 - LEAST(MYSQL_VAR_TMAABX, 100);

    RETURN MYSQL_VAR_W6OHUE;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_LE8BQC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_LE8BQC(A1 INT, R INT, N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PTI1Z0 INT DEFAULT 0;
    SET MYSQL_VAR_PTI1Z0 = A1 * POW(R, N - 1);
    RETURN MYSQL_VAR_PTI1Z0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_O7MD2W----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_O7MD2W(ARR_SIZE INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RZD847 INT DEFAULT 0;
    DECLARE MYSQL_VAR_OJUMN1 INT DEFAULT 1;
    DECLARE MYSQL_VAR_JFINNM INT DEFAULT 0;

    IF ARR_SIZE <= 0 OR ARR_SIZE > 10000 THEN
        RETURN 0;
    END IF;

    CALC_LOOP: WHILE MYSQL_VAR_OJUMN1 <= ARR_SIZE DO
        SET MYSQL_VAR_JFINNM = MYSQL_VAR_OJUMN1 * 2;
        SET MYSQL_VAR_RZD847 = MYSQL_VAR_RZD847 + MYSQL_VAR_JFINNM;
        SET MYSQL_VAR_OJUMN1 = MYSQL_VAR_OJUMN1 + 1;
    END WHILE CALC_LOOP;

    RETURN MYSQL_VAR_RZD847;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_8OI2O9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8OI2O9(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BFEGSV INT DEFAULT 0;
    DECLARE MYSQL_VAR_WMIU0S INT DEFAULT 0;
    DECLARE MYSQL_VAR_QH6LQ8 INT DEFAULT 0;
    DECLARE MYSQL_VAR_A2YSP8 INT DEFAULT 0;

    SELECT MYSQL_FUNC_GCMS42(10)
    INTO MYSQL_VAR_BFEGSV
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT MYSQL_FUNC_ISMQR5('test_0_0', 11)
    INTO MYSQL_VAR_QH6LQ8
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM AND STATUS = 'COMPLETED';

    CASE V_PLAN_TYPE
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_WMIU0S = MYSQL_FUNC_O7MD2W(10);
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_WMIU0S = MYSQL_FUNC_DQ097Y(10);
        WHEN 'BASIC' THEN SET MYSQL_VAR_WMIU0S = 30;
        ELSE SET MYSQL_VAR_WMIU0S = MYSQL_FUNC_LE8BQC(30, 31, 32);
    END CASE;

    IF MYSQL_VAR_BFEGSV = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_A2YSP8 = MYSQL_FUNC_SKTOIG(30);

    RETURN MYSQL_VAR_A2YSP8;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TI507I----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TI507I(TREATMENT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_14HUKU INT DEFAULT 0;
    DECLARE MYSQL_VAR_4W27HJ INT DEFAULT 50;
    DECLARE MYSQL_VAR_SM1334 INT DEFAULT 1500;
    DECLARE MYSQL_VAR_EUMM51 INT DEFAULT 0;
    DECLARE MYSQL_VAR_CJF5N2 INT DEFAULT 0;

    SELECT COALESCE(COST, 0)
    INTO MYSQL_VAR_14HUKU
    FROM DENTAL_TREATMENTS
    WHERE TREATMENT_ID = TREATMENT_ID_PARAM;

    SELECT DP.COVERAGE_PERCENT, DP.ANNUAL_MAX
    INTO MYSQL_VAR_4W27HJ, MYSQL_VAR_SM1334
    FROM DENTAL_TREATMENTS DT
    JOIN DENTAL_PLANS DP ON DT.PATIENT_ID = DP.PATIENT_ID
    WHERE DT.TREATMENT_ID = TREATMENT_ID_PARAM;

    SELECT COALESCE(SUM(COST), 0) INTO MYSQL_VAR_EUMM51
    FROM DENTAL_TREATMENTS
    WHERE PATIENT_ID = (SELECT PATIENT_ID FROM DENTAL_TREATMENTS WHERE TREATMENT_ID = TREATMENT_ID_PARAM);

    SET MYSQL_VAR_CJF5N2 = MYSQL_VAR_14HUKU * MYSQL_VAR_4W27HJ / 100;

    IF MYSQL_VAR_EUMM51 > MYSQL_VAR_SM1334 THEN
        SET MYSQL_VAR_CJF5N2 = 0;
    END IF;

    RETURN CAST(MYSQL_VAR_CJF5N2 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_UEQBWY----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_UEQBWY(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_6DIF83 INT DEFAULT 0;
    DECLARE MYSQL_VAR_U42Q90 INT DEFAULT 2;
    DECLARE MYSQL_VAR_RPSKZL INT DEFAULT 2;
    DECLARE MYSQL_VAR_Q60PSU INT DEFAULT 1;

    OUTER_LOOP: WHILE MYSQL_VAR_U42Q90 <= N DO
        SET MYSQL_VAR_Q60PSU = 1;
        SET MYSQL_VAR_RPSKZL = 2;

        INNER_LOOP: WHILE MYSQL_VAR_RPSKZL < MYSQL_VAR_U42Q90 DO
            IF MYSQL_VAR_U42Q90 % MYSQL_VAR_RPSKZL = 0 THEN
                SET MYSQL_VAR_Q60PSU = 0;
                ITERATE INNER_LOOP;
            END IF;
            SET MYSQL_VAR_RPSKZL = MYSQL_VAR_RPSKZL + 1;
        END WHILE INNER_LOOP;

        IF MYSQL_VAR_Q60PSU = 1 THEN
            SET MYSQL_VAR_6DIF83 = MYSQL_VAR_6DIF83 + 1;
        END IF;

        SET MYSQL_VAR_U42Q90 = MYSQL_VAR_U42Q90 + 1;
    END WHILE OUTER_LOOP;

    RETURN MYSQL_VAR_6DIF83;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_AV39HM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AV39HM(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_95XIBT INT DEFAULT 0;
    DECLARE MYSQL_VAR_W7O61A INT DEFAULT 2;
    DECLARE MYSQL_VAR_602S25 INT DEFAULT 0;

    IF N <= 1 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_602S25 = N;
    SET MYSQL_VAR_W7O61A = MYSQL_FUNC_UEQBWY(10);

    FACTOR_LOOP: WHILE MYSQL_VAR_W7O61A <= MYSQL_VAR_602S25 DO
        IF MYSQL_VAR_602S25 % MYSQL_VAR_W7O61A = 0 THEN
            SET MYSQL_VAR_95XIBT = MYSQL_VAR_95XIBT + 1;
            SET MYSQL_VAR_602S25 = MYSQL_VAR_602S25 / MYSQL_VAR_W7O61A;
        ELSE
            SET MYSQL_VAR_W7O61A = MYSQL_VAR_W7O61A + 1;
        END IF;
    END WHILE FACTOR_LOOP;

    RETURN MYSQL_FUNC_TI507I(30);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_L2R0N9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L2R0N9(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Z2FZP9 INT DEFAULT 0;

    SELECT MYSQL_FUNC_AV39HM(30)
    INTO MYSQL_VAR_Z2FZP9
    FROM ORDERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_FUNC_8OI2O9(10);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BRQHOO----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BRQHOO(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_HBU1L7 INT DEFAULT 0;

    SELECT MYSQL_FUNC_L2R0N9(10)
    INTO MYSQL_VAR_HBU1L7
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_VAR_HBU1L7 * 5;
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_R8K8RL(INPUT_STRING VARCHAR(255)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_Q5M2YQ INT DEFAULT 0;
    SET MYSQL_VAR_Q5M2YQ = CHAR_LENGTH(INPUT_STRING);
    RETURN MYSQL_FUNC_BRQHOO(20);
END//

DELIMITER ;