/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_I4J4SU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_I4J4SU(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_29FYU6 VARCHAR(20) DEFAULT 'INACTIVE';
    DECLARE MYSQL_VAR_377OE9 INT DEFAULT 0;

    SELECT STATUS, COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_29FYU6, MYSQL_VAR_377OE9
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_29FYU6 != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_VAR_377OE9 * 5;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_YKYV36----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_YKYV36(COURSE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GI1OHH INT DEFAULT 0;
    DECLARE MYSQL_VAR_LLAG8E INT DEFAULT 0;
    DECLARE MYSQL_VAR_LHDI1E INT DEFAULT 0;
    DECLARE MYSQL_VAR_CD74JB INT DEFAULT 0;

    SELECT COUNT(*), COUNT(CASE WHEN GRADE >= 60 THEN 1 END), COALESCE(AVG(GRADE), 0)
    INTO MYSQL_VAR_GI1OHH, MYSQL_VAR_LLAG8E, MYSQL_VAR_LHDI1E
    FROM ENROLLMENTS
    WHERE COURSE_ID = COURSE_ID_PARAM;

    IF MYSQL_VAR_GI1OHH = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_CD74JB = (MYSQL_VAR_LLAG8E * 100) / MYSQL_VAR_GI1OHH;

    IF MYSQL_VAR_LHDI1E >= 90 THEN
        SET MYSQL_VAR_CD74JB = MYSQL_VAR_CD74JB + 5;
    END IF;

    RETURN CAST(MYSQL_VAR_CD74JB AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4FO6UN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4FO6UN(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_K2BRZ1 INT DEFAULT 1;
    DECLARE MYSQL_VAR_1DUASY INT DEFAULT 2;

    IF N <= 1 THEN
        RETURN 0;
    END IF;

    WHILE MYSQL_VAR_1DUASY * MYSQL_VAR_1DUASY <= N DO
        IF N % MYSQL_VAR_1DUASY = 0 THEN
            SET MYSQL_VAR_K2BRZ1 = MYSQL_VAR_K2BRZ1 + MYSQL_VAR_1DUASY;
            IF MYSQL_VAR_1DUASY != N / MYSQL_VAR_1DUASY THEN
                SET MYSQL_VAR_K2BRZ1 = MYSQL_VAR_K2BRZ1 + (N / MYSQL_VAR_1DUASY);
            END IF;
        END IF;
        SET MYSQL_VAR_1DUASY = MYSQL_VAR_1DUASY + 1;
    END WHILE;

    IF MYSQL_VAR_K2BRZ1 = N THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_GOS6GU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_GOS6GU(PRODUCT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MMV3PH INT DEFAULT 0;
    DECLARE MYSQL_VAR_8VHH7V INT DEFAULT 0;
    DECLARE MYSQL_VAR_3D3NCA INT DEFAULT 0;
    DECLARE MYSQL_VAR_ISMP8C INT DEFAULT 0;
    DECLARE MYSQL_VAR_BBC1HI INT DEFAULT 0;
    DECLARE MYSQL_VAR_PZMJ3C INT DEFAULT 0;
    DECLARE MYSQL_VAR_V1G8TZ INT DEFAULT 0;

    SELECT COALESCE(UNIT_COST, 0), COALESCE(UNIT_PRICE, 0), COALESCE(STOCK_QUANTITY, 0)
    INTO MYSQL_VAR_MMV3PH, MYSQL_VAR_8VHH7V, MYSQL_VAR_3D3NCA
    FROM PRODUCTS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY), 0)
    INTO MYSQL_VAR_PZMJ3C
    FROM ORDERS
    WHERE PRODUCT_ID = PRODUCT_ID_PARAM;

    IF MYSQL_VAR_8VHH7V = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_BBC1HI = ((MYSQL_VAR_8VHH7V - MYSQL_VAR_MMV3PH) * 100) / MYSQL_VAR_8VHH7V;

    SET MYSQL_VAR_V1G8TZ = (MYSQL_VAR_BBC1HI * MYSQL_VAR_PZMJ3C) / GREATEST(MYSQL_VAR_3D3NCA, 1);

    RETURN MYSQL_VAR_V1G8TZ;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_ISMQR5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_ISMQR5(SESSION_TYPE_PARAM VARCHAR(50), HOURS_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PRFKA8 INT DEFAULT 200;
    DECLARE MYSQL_VAR_U0EBQ0 INT DEFAULT 1;
    DECLARE MYSQL_VAR_HRIJCK INT DEFAULT 0;

    CASE SESSION_TYPE_PARAM
        WHEN 'WEDDING' THEN SET MYSQL_VAR_PRFKA8 = MYSQL_FUNC_YKYV36(30);
        WHEN 'PORTRAIT' THEN SET MYSQL_VAR_PRFKA8 = MYSQL_FUNC_I4J4SU(10);
        WHEN 'EVENT' THEN SET MYSQL_VAR_PRFKA8 = MYSQL_FUNC_GOS6GU(10);
        WHEN 'PRODUCT' THEN SET MYSQL_VAR_PRFKA8 = 250;
        ELSE SET MYSQL_VAR_PRFKA8 = MYSQL_FUNC_4FO6UN(10);
    END CASE;

    SET MYSQL_VAR_HRIJCK = MYSQL_VAR_PRFKA8 * HOURS_PARAM;

    RETURN CAST(MYSQL_VAR_HRIJCK AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_JRP5H5----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_JRP5H5(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_MQ93S6 INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_MQ93S6
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN 30 - MYSQL_VAR_MQ93S6;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_M85E1G----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M85E1G(SERVICE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_PQ3Z5J INT DEFAULT 15000;
    DECLARE MYSQL_VAR_H67J0V INT DEFAULT 0;
    DECLARE MYSQL_VAR_ODFHIF INT DEFAULT 0;
    DECLARE MYSQL_VAR_T91L29 INT DEFAULT 0;
    DECLARE MYSQL_VAR_27B6S8 INT DEFAULT 0;

    SELECT (MYSQL_FUNC_JRP5H5(30) - (0) + COALESCE(COALESCE(POOL_VOLUME_GALLONS, 15000), COALESCE(LABOR_HOURS, 2), COALESCE(CHEMICAL_COST, 50), 0))
    INTO MYSQL_VAR_PQ3Z5J, MYSQL_VAR_H67J0V, MYSQL_VAR_ODFHIF
    FROM SWIMMING_POOL_SERVICE
    WHERE SERVICE_ID = SERVICE_ID_PARAM;

    SELECT COALESCE(SUM(REPLACEMENT_COST), 0) INTO MYSQL_VAR_T91L29
    FROM SWIMMING_POOL_SERVICE SS
    JOIN POOL_EQUIPMENT PE ON SS.SERVICE_ID = PE.SERVICE_ID
    WHERE SS.SERVICE_ID = SERVICE_ID_PARAM;

    SET MYSQL_VAR_27B6S8 = MYSQL_FUNC_ISMQR5('test_2_0', 31);

    IF MYSQL_VAR_PQ3Z5J > 30000 THEN
        SET MYSQL_VAR_27B6S8 = MYSQL_VAR_27B6S8 + 50;
    END IF;

    RETURN CAST(MYSQL_VAR_27B6S8 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7LBCM1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7LBCM1(EMPLOYEE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_BQOTMX INT DEFAULT 0;
    DECLARE MYSQL_VAR_GWOAFS INT DEFAULT 0;
    DECLARE MYSQL_VAR_6UQ887 INT DEFAULT 0;
    DECLARE MYSQL_VAR_T5PFUF INT DEFAULT 0;
    DECLARE MYSQL_VAR_B446RF INT DEFAULT 0;

    SELECT COALESCE(IS_REMOTE, 0), COALESCE(SALARY, 50000)
    INTO MYSQL_VAR_BQOTMX, MYSQL_VAR_GWOAFS
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID = EMPLOYEE_ID_PARAM;

    SELECT COUNT(*), COUNT(CASE WHEN STATUS = 'COMPLETED' THEN 1 END)
    INTO MYSQL_VAR_6UQ887, MYSQL_VAR_T5PFUF
    FROM PROJECTS
    WHERE TEAM_LEAD_ID = EMPLOYEE_ID_PARAM;

    IF MYSQL_VAR_BQOTMX = 1 THEN
        SET MYSQL_VAR_B446RF = 80 + (MYSQL_VAR_T5PFUF * 5) - (MYSQL_VAR_GWOAFS / 10000);
    ELSE
        SET MYSQL_VAR_B446RF = 70 + (MYSQL_VAR_T5PFUF * 3);
    END IF;

    RETURN MYSQL_VAR_B446RF;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_OXVO2M----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_OXVO2M(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_ESVUSH VARCHAR(20) DEFAULT 'BASIC';
    DECLARE MYSQL_VAR_DKMFOV VARCHAR(20) DEFAULT 'REGULAR';
    DECLARE MYSQL_VAR_ALM7ET INT DEFAULT 0;

    SELECT PLAN_TYPE
    INTO MYSQL_VAR_ESVUSH
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT TIER_LEVEL
    INTO MYSQL_VAR_DKMFOV
    FROM CUSTOMERS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    CASE MYSQL_VAR_ESVUSH
        WHEN 'ENTERPRISE' THEN SET MYSQL_VAR_ALM7ET = 100;
        WHEN 'PREMIUM' THEN SET MYSQL_VAR_ALM7ET = 50;
        WHEN 'BASIC' THEN SET MYSQL_VAR_ALM7ET = 20;
        ELSE SET MYSQL_VAR_ALM7ET = 5;
    END CASE;

    CASE MYSQL_VAR_DKMFOV
        WHEN 'PLATINUM' THEN SET MYSQL_VAR_ALM7ET = MYSQL_VAR_ALM7ET + 30;
        WHEN 'GOLD' THEN SET MYSQL_VAR_ALM7ET = MYSQL_VAR_ALM7ET + 15;
        WHEN 'SILVER' THEN SET MYSQL_VAR_ALM7ET = MYSQL_VAR_ALM7ET + 5;
    END CASE;

    RETURN MYSQL_VAR_ALM7ET;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_4MLORP----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_4MLORP(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QQX0ZX INT DEFAULT 0;

    SELECT (MYSQL_FUNC_7LBCM1(20) - (0) + COALESCE(COUNT(*), 0))
    INTO MYSQL_VAR_QQX0ZX
    FROM PRODUCTS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN (MYSQL_FUNC_OXVO2M(20) - (0) + COALESCE(MYSQL_VAR_QQX0ZX, 0));
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_AZY9GD(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GGZIPF INT DEFAULT 0;
    DECLARE MYSQL_VAR_9JMK91 INT DEFAULT 1;

    SELECT (MYSQL_FUNC_4MLORP(30) - (0) + COALESCE(COALESCE(BUDGET, 0), DATEDIFF(END_DATE, START_DATE) + 1, 0))
    INTO MYSQL_VAR_GGZIPF, MYSQL_VAR_9JMK91
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    IF MYSQL_VAR_9JMK91 <= 0 THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_M85E1G(30) - (0) + COALESCE(MYSQL_VAR_GGZIPF / MYSQL_VAR_9JMK91, 0));
END//

DELIMITER ;