/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_98WDW1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_98WDW1(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_H8Q2WK INT DEFAULT 0;
    DECLARE MYSQL_VAR_EXT8O4 INT DEFAULT 0;
    DECLARE MYSQL_VAR_XGWD19 INT DEFAULT 0;

    SELECT COUNT(*)
    INTO MYSQL_VAR_H8Q2WK
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM
    AND YEAR(O.ORDER_DATE) = YEAR(CURDATE());

    SELECT COUNT(*)
    INTO MYSQL_VAR_EXT8O4
    FROM ORDERS O
    JOIN CUSTOMERS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
    WHERE C.COUNTRY = COUNTRY_PARAM
    AND YEAR(O.ORDER_DATE) = YEAR(CURDATE()) - 1;

    IF MYSQL_VAR_EXT8O4 = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_XGWD19 = ((MYSQL_VAR_H8Q2WK - MYSQL_VAR_EXT8O4) * 100) / MYSQL_VAR_EXT8O4;

    RETURN MYSQL_VAR_XGWD19;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EDMHXC----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EDMHXC(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OHSN01 INT DEFAULT 1;
    DECLARE MYSQL_VAR_8BGXVC INT DEFAULT 1;

    IF N < 0 THEN
        RETURN 0;
    END IF;

    IF N > 12 THEN
        SET N = 12;
    END IF;

    FACT_LOOP: WHILE MYSQL_VAR_8BGXVC <= N DO
        SET MYSQL_VAR_OHSN01 = MYSQL_VAR_OHSN01 * MYSQL_VAR_8BGXVC;
        SET MYSQL_VAR_8BGXVC = MYSQL_VAR_8BGXVC + 1;
    END WHILE FACT_LOOP;

    RETURN MYSQL_FUNC_98WDW1('test_2_0');
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_MX5F7P----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_MX5F7P(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_M17RIT INT DEFAULT 0;

    SELECT COALESCE(LEAD_TIME_DAYS, 7)
    INTO MYSQL_VAR_M17RIT
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_VAR_M17RIT;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EM0BQD----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EM0BQD(CASE_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_GRRPEA INT DEFAULT 0;
    DECLARE MYSQL_VAR_FK8309 INT DEFAULT 0;
    DECLARE MYSQL_VAR_EBKNY7 INT DEFAULT 0;
    DECLARE MYSQL_VAR_7UKWS5 INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZMLIX0 INT DEFAULT 0;

    SELECT COALESCE(ESTIMATED_VALUE, 0)
    INTO MYSQL_VAR_GRRPEA
    FROM LEGAL_CASES
    WHERE CASE_ID = CASE_ID_PARAM;

    SELECT COALESCE(SUM(HOURS_BILLED * HOURLY_RATE), 0), COALESCE(SUM(HOURS_BILLED), 0)
    INTO MYSQL_VAR_7UKWS5, MYSQL_VAR_FK8309
    FROM LEGAL_TASKS
    WHERE CASE_ID = CASE_ID_PARAM;

    IF MYSQL_VAR_GRRPEA = 0 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_ZMLIX0 = MYSQL_VAR_GRRPEA - MYSQL_VAR_7UKWS5;

    IF MYSQL_VAR_FK8309 > 100 THEN
        SET MYSQL_VAR_ZMLIX0 = MYSQL_VAR_ZMLIX0 - (MYSQL_VAR_FK8309 - 100) * 10;
    END IF;

    RETURN CAST(MYSQL_VAR_ZMLIX0 AS SIGNED);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_XN9NC8----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XN9NC8(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_2MU5F0 INT DEFAULT 0;

    SELECT MYSQL_FUNC_MX5F7P(30)
    INTO MYSQL_VAR_2MU5F0
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN MYSQL_FUNC_EM0BQD(20);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HHMQJV() RETURNS INT
BEGIN
DECLARE MYSQL_VAR_THXPVL INT DEFAULT 0;
    SELECT MYSQL_FUNC_XN9NC8(10) INTO MYSQL_VAR_THXPVL FROM TABLE_7UF0YV.`TABLE3` LIMIT 1;
    RETURN MYSQL_FUNC_EDMHXC(30);
END//

DELIMITER ;