/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_XY1NEG----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_XY1NEG(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_UZ44GM DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(TOTAL_AMOUNT, 0)
    INTO MYSQL_VAR_UZ44GM
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_UZ44GM);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_26NRTF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_26NRTF(COUNTRY_PARAM VARCHAR(50)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_QZIAQG INT DEFAULT 0;
    DECLARE MYSQL_VAR_GUFGWB INT DEFAULT 1;

    SELECT COUNT(DISTINCT S.CUSTOMER_ID), COUNT(*)
    INTO MYSQL_VAR_QZIAQG, MYSQL_VAR_GUFGWB
    FROM CUSTOMERS C
    LEFT JOIN SUBSCRIPTIONS S ON C.CUSTOMER_ID = S.CUSTOMER_ID AND S.STATUS = 'ACTIVE'
    WHERE C.COUNTRY = COUNTRY_PARAM;

    RETURN (MYSQL_VAR_QZIAQG * 100) / MYSQL_VAR_GUFGWB;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_BAYQDF----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_BAYQDF(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8X6W62 DATE;
    DECLARE MYSQL_VAR_HX0C9B VARCHAR(20) DEFAULT 'INACTIVE';

    SELECT START_DATE, STATUS
    INTO MYSQL_VAR_8X6W62, MYSQL_VAR_HX0C9B
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_HX0C9B != 'ACTIVE' OR MYSQL_VAR_8X6W62 IS NULL THEN
        RETURN 0;
    END IF;

    RETURN MYSQL_FUNC_26NRTF('test_1_0');
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_8H2GPE(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_DB4FPM DATE;
    DECLARE MYSQL_VAR_4V9VFB DATE;
    DECLARE MYSQL_VAR_3O8CMI INT DEFAULT 0;

    SELECT MYSQL_FUNC_BAYQDF(10)
    INTO MYSQL_VAR_DB4FPM, MYSQL_VAR_4V9VFB
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    IF MYSQL_VAR_DB4FPM IS NULL THEN
        RETURN -1;
    END IF;

    IF MYSQL_VAR_4V9VFB IS NULL THEN
        SET MYSQL_VAR_4V9VFB = CURDATE();
    END IF;

    SET MYSQL_VAR_3O8CMI = DATEDIFF(MYSQL_VAR_4V9VFB, MYSQL_VAR_DB4FPM);

    IF MYSQL_VAR_3O8CMI < 0 THEN
        SET MYSQL_VAR_3O8CMI = 0;
    END IF;

    RETURN MYSQL_FUNC_XY1NEG(10);
END//

DELIMITER ;