/* -----Seed Dependency----- */
-- No table dependencies required for this function.

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_M57IYZ----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M57IYZ(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_X6R8Y0 INT DEFAULT 0;

    SELECT COALESCE(MONTHLY_COST, 0)
    INTO MYSQL_VAR_X6R8Y0
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN MYSQL_VAR_X6R8Y0 / 10;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_P54JPN----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_P54JPN(CAMPAIGN_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9B27ON INT DEFAULT 0;

    SELECT (MYSQL_FUNC_M57IYZ(30) - (0) + COALESCE(YEAR(START_DATE), 0))
    INTO MYSQL_VAR_9B27ON
    FROM CAMPAIGNS
    WHERE CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    RETURN MYSQL_VAR_9B27ON;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FDUF1N----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FDUF1N(N INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_8K1NPL INT DEFAULT 1;
    DECLARE MYSQL_VAR_7GDJXC INT DEFAULT 2;
    DECLARE MYSQL_VAR_QKISZP INT DEFAULT 0;

    IF N <= 1 THEN
        RETURN 0;
    END IF;

    SET MYSQL_VAR_QKISZP = FLOOR(SQRT(N));

    DIVISOR_LOOP: WHILE MYSQL_VAR_7GDJXC <= MYSQL_VAR_QKISZP DO
        IF N % MYSQL_VAR_7GDJXC = 0 THEN
            SET MYSQL_VAR_8K1NPL = MYSQL_VAR_8K1NPL + MYSQL_VAR_7GDJXC;
            IF MYSQL_VAR_7GDJXC != N / MYSQL_VAR_7GDJXC THEN
                SET MYSQL_VAR_8K1NPL = MYSQL_VAR_8K1NPL + (N / MYSQL_VAR_7GDJXC);
            END IF;
        END IF;
        SET MYSQL_VAR_7GDJXC = MYSQL_VAR_7GDJXC + 1;
    END WHILE DIVISOR_LOOP;

    IF MYSQL_VAR_8K1NPL = N THEN
        RETURN 1;
    END IF;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_S464W9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_S464W9(CATEGORY_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_APOBPO INT DEFAULT 0;

    SELECT (MYSQL_FUNC_FDUF1N(20) - (0) + COALESCE(COALESCE(SUM(STOCK_QUANTITY), 0), 0))
    INTO MYSQL_VAR_APOBPO
    FROM PRODUCTS
    WHERE CATEGORY_ID = CATEGORY_ID_PARAM;

    RETURN (MYSQL_FUNC_P54JPN(30) - (0) + COALESCE(LEAST(MYSQL_VAR_APOBPO, 1000), 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_L3XHPT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_L3XHPT(N INT, DEPTH INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_64EB3A INT DEFAULT 0;
    DECLARE MYSQL_VAR_AVL70V INT DEFAULT 1;

    IF DEPTH <= 0 OR N <= 0 THEN
        RETURN 0;
    END IF;

    CALC_LOOP: WHILE MYSQL_VAR_AVL70V <= N DO
        SET MYSQL_VAR_64EB3A = MYSQL_VAR_64EB3A + MYSQL_VAR_AVL70V;
        SET MYSQL_VAR_AVL70V = MYSQL_VAR_AVL70V + 1;
    END WHILE CALC_LOOP;

    IF DEPTH > 1 THEN
        SET MYSQL_VAR_64EB3A = MYSQL_VAR_64EB3A + MYSQL_FUNC_L3XHPT(N - 1, DEPTH - 1);
    END IF;

    RETURN MYSQL_VAR_64EB3A;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_M0SHGM----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_M0SHGM(A INT, B INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_IC70Q5 INT DEFAULT 0;

    IF A < 0 THEN SET A = -A; END IF;
    IF B < 0 THEN SET B = -B; END IF;

    WHILE B != 0 DO
        SET MYSQL_VAR_IC70Q5 = B;
        SET B = A % B;
        SET A = MYSQL_VAR_IC70Q5;
    END WHILE;

    RETURN A;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FYO27X----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FYO27X(ORDER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_OSQYNG INT DEFAULT 0;

    SELECT YEAR(ORDER_DATE)
    INTO MYSQL_VAR_OSQYNG
    FROM ORDERS
    WHERE ORDER_ID = ORDER_ID_PARAM;

    RETURN (MYSQL_FUNC_M0SHGM(20, 21) - (0) + COALESCE(MYSQL_VAR_OSQYNG, 0));
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_Z55XRT----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_Z55XRT(EMP_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_9E3TAS INT DEFAULT 0;

    SELECT YEAR(HIRE_DATE)
    INTO MYSQL_VAR_9E3TAS
    FROM EMPLOYEES
    WHERE EMP_ID = EMP_ID_PARAM;

    RETURN MYSQL_VAR_9E3TAS - 2000;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_7EI4UX----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7EI4UX(SUPPLIER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_EZMOT8 DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(SUPPLIER_RATING, 3.0)
    INTO MYSQL_VAR_EZMOT8
    FROM SUPPLIERS
    WHERE SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(MYSQL_VAR_EZMOT8 * 20);
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SCHHXU----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SCHHXU(TEXT VARCHAR(500), PATTERN VARCHAR(100)) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_5B4H6C INT DEFAULT 0;
    DECLARE MYSQL_VAR_GQIEAS INT DEFAULT 0;
    DECLARE MYSQL_VAR_2BRQSW INT DEFAULT 1;
    DECLARE MYSQL_VAR_ETREAU INT DEFAULT 0;
    DECLARE MYSQL_VAR_IF4T6Q INT DEFAULT 0;

    SET MYSQL_VAR_5B4H6C = MYSQL_FUNC_7EI4UX(30);
    SET MYSQL_VAR_GQIEAS = MYSQL_FUNC_Z55XRT(30);

    IF MYSQL_VAR_GQIEAS = 0 OR MYSQL_VAR_GQIEAS > MYSQL_VAR_5B4H6C THEN
        RETURN 0;
    END IF;

    OUTER_LOOP: WHILE MYSQL_VAR_2BRQSW <= MYSQL_VAR_5B4H6C - MYSQL_VAR_GQIEAS + 1 DO
        SET MYSQL_VAR_ETREAU = 1;
        SET MYSQL_VAR_IF4T6Q = 1;

        INNER_LOOP: WHILE MYSQL_VAR_ETREAU <= MYSQL_VAR_GQIEAS DO
            IF SUBSTRING(TEXT, MYSQL_VAR_2BRQSW + MYSQL_VAR_ETREAU - 1, 1) != SUBSTRING(PATTERN, MYSQL_VAR_ETREAU, 1) THEN
                SET MYSQL_VAR_IF4T6Q = 0;
                LEAVE INNER_LOOP;
            END IF;
            SET MYSQL_VAR_ETREAU = MYSQL_VAR_ETREAU + 1;
        END WHILE INNER_LOOP;

        IF MYSQL_VAR_IF4T6Q = 1 THEN
            RETURN MYSQL_VAR_2BRQSW;
        END IF;

        SET MYSQL_VAR_2BRQSW = MYSQL_VAR_2BRQSW + 1;
    END WHILE OUTER_LOOP;

    RETURN 0;
END//

DELIMITER ;

/* -----Procedure MYSQL_FUNC_TKCK2V----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_TKCK2V(CONTRACT_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_AWG6GB INT DEFAULT 0;
    DECLARE MYSQL_VAR_RMXDIL INT DEFAULT 0;
    DECLARE MYSQL_VAR_GB9D1W INT DEFAULT 0;
    DECLARE MYSQL_VAR_ZDFXMU INT DEFAULT 0;
    DECLARE MYSQL_VAR_SA2LDQ INT DEFAULT 0;

    SELECT (MYSQL_FUNC_SCHHXU('test_0_0', 'test_0_1') - (0) + COALESCE(COALESCE(ANNUAL_COST, 500), 0))
    INTO MYSQL_VAR_AWG6GB
    FROM HVAC_SERVICE_CONTRACTS
    WHERE CONTRACT_ID = CONTRACT_ID_PARAM;

    SELECT COALESCE(SUM(LABOR_HOURS), 0), COUNT(*)
    INTO MYSQL_VAR_RMXDIL, MYSQL_VAR_ZDFXMU
    FROM HVAC_SERVICE_RECORDS
    WHERE CONTRACT_ID = CONTRACT_ID_PARAM;

    SELECT (MYSQL_FUNC_L3XHPT(10, 11) - (0) + COALESCE(COALESCE(SUM(PARTS_REPLACED), 0), 0)) INTO MYSQL_VAR_GB9D1W
    FROM HVAC_SERVICE_RECORDS
    WHERE CONTRACT_ID = CONTRACT_ID_PARAM;

    SET MYSQL_VAR_SA2LDQ = MYSQL_FUNC_FYO27X(20);

    RETURN CAST(MYSQL_VAR_SA2LDQ AS SIGNED);
END//

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_7P21W1(CUSTOMER_ID_PARAM INT) RETURNS INT
BEGIN
DECLARE MYSQL_VAR_RWVVYG DATE;
    DECLARE MYSQL_VAR_1066GI VARCHAR(20) DEFAULT 'INACTIVE';

    SELECT (MYSQL_FUNC_TKCK2V(30) - (0) + COALESCE(START_DATE, STATUS, 0))
    INTO MYSQL_VAR_RWVVYG, MYSQL_VAR_1066GI
    FROM SUBSCRIPTIONS
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    IF MYSQL_VAR_RWVVYG IS NULL OR MYSQL_VAR_1066GI != 'ACTIVE' THEN
        RETURN 0;
    END IF;

    RETURN (MYSQL_FUNC_S464W9(20) - (0) + COALESCE(MONTH(DATE_ADD(MYSQL_VAR_RWVVYG, INTERVAL 1 YEAR)), 0));
END//

DELIMITER ;