/* -----Seed Dependency----- */
CREATE TABLE IF NOT EXISTS `table_3yc615` (
    `table_3yc615_campaign_id` INT,
    `table_3yc615_status` VARCHAR(50)
);

INSERT INTO `table_3yc615` (`table_3yc615_campaign_id`, `table_3yc615_status`) VALUES (1, 'test');

/* -----Seed Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_CAMPAIGN_HEALTH_INDEX_j30o7f(CAMPAIGN_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_STATUS VARCHAR(20) DEFAULT 'DRAFT';
    DECLARE V_CONVERSION_COUNT INT DEFAULT 0;

    SELECT TABLE_3YC615_STATUS, COUNT(CV.CONVERSION_ID)
    INTO V_STATUS, V_CONVERSION_COUNT
    FROM TABLE_3YC615 C
    LEFT JOIN CONVERSIONS CV ON TABLE_3YC615_CAMPAIGN_ID = CV.CAMPAIGN_ID
    WHERE TABLE_3YC615_CAMPAIGN_ID = CAMPAIGN_ID_PARAM
    GROUP BY TABLE_3YC615_CAMPAIGN_ID;

    CASE V_STATUS
        WHEN 'ACTIVE' THEN RETURN 100 + (V_CONVERSION_COUNT * 5);
        WHEN 'PAUSED' THEN RETURN 50 + (V_CONVERSION_COUNT * 3);
        WHEN 'COMPLETED' THEN RETURN 75 + (V_CONVERSION_COUNT * 4);
        ELSE RETURN 25 + V_CONVERSION_COUNT;
    END CASE;
END //

DELIMITER ;