/* -----Seed Dependency----- */
CREATE TABLE IF NOT EXISTS `table_5d48sg` (
    `table_5d48sg_project_id` INT,
    `table_5d48sg_team_lead_id` INT,
    `table_5d48sg_start_date` DATE,
    `table_5d48sg_deadline` INT,
    `table_5d48sg_budget` INT,
    `table_5d48sg_status` VARCHAR(50)
);

INSERT INTO `table_5d48sg` (`table_5d48sg_project_id`, `table_5d48sg_team_lead_id`, `table_5d48sg_start_date`, `table_5d48sg_deadline`, `table_5d48sg_budget`, `table_5d48sg_status`) VALUES (1, 1, '2024-01-01', 1, 1, '2024-01-01');

/* -----Seed Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_PROJECT_HEALTH_SCORE_9vv0o6(PROJECT_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_BUDGET INT DEFAULT 0;
    DECLARE V_DAYS_REMAINING INT DEFAULT 0;
    DECLARE V_TOTAL_DAYS INT DEFAULT 0;
    DECLARE V_STATUS VARCHAR(20) DEFAULT '';
    DECLARE V_HEALTH_SCORE INT DEFAULT 50;

    SELECT TABLE_5D48SG_BUDGET, DATEDIFF(TABLE_5D48SG_DEADLINE, CURDATE()), TABLE_5D48SG_STATUS
    INTO V_BUDGET, V_DAYS_REMAINING, V_STATUS
    FROM TABLE_5D48SG
    WHERE TABLE_5D48SG_PROJECT_ID = PROJECT_ID_PARAM;

    SELECT DATEDIFF(TABLE_5D48SG_DEADLINE, TABLE_5D48SG_START_DATE)
    INTO V_TOTAL_DAYS
    FROM TABLE_5D48SG
    WHERE TABLE_5D48SG_PROJECT_ID = PROJECT_ID_PARAM;

    CASE V_STATUS
        WHEN 'COMPLETED' THEN SET V_HEALTH_SCORE = 100;
        WHEN 'IN_PROGRESS' THEN
            IF V_DAYS_REMAINING < 0 THEN
                SET V_HEALTH_SCORE = 10;
            ELSEIF V_DAYS_REMAINING < V_TOTAL_DAYS * 0.2 THEN
                SET V_HEALTH_SCORE = 40;
            ELSEIF V_DAYS_REMAINING > V_TOTAL_DAYS * 0.5 THEN
                SET V_HEALTH_SCORE = 80;
            END IF;
        WHEN 'ON_HOLD' THEN SET V_HEALTH_SCORE = 30;
        WHEN 'CANCELLED' THEN SET V_HEALTH_SCORE = 0;
        ELSE SET V_HEALTH_SCORE = 50;
    END CASE;

    RETURN V_HEALTH_SCORE;
END //

DELIMITER ;