/* -----Seed Dependency----- */
CREATE TABLE IF NOT EXISTS `table_0ku296` (
    `table_0ku296_emp_id` INT,
    `table_0ku296_department_id` INT,
    `table_0ku296_salary` INT
);

INSERT INTO `table_0ku296` (`table_0ku296_emp_id`, `table_0ku296_department_id`, `table_0ku296_salary`) VALUES (1, 1, 1);

/* -----Seed Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_DEPARTMENT_RETENTION_INDEX_pf1hmm(DEPARTMENT_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_AVG_TENURE DECIMAL(10,2) DEFAULT 0.00;
    DECLARE V_AVG_SALARY DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(TIMESTAMPDIFF(YEAR, HIRE_DATE, CURDATE())), 0),
           COALESCE(AVG(TABLE_0KU296_SALARY), 0)
    INTO V_AVG_TENURE, V_AVG_SALARY
    FROM TABLE_0KU296
    WHERE TABLE_0KU296_DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN FLOOR((V_AVG_TENURE * 1000) + (V_AVG_SALARY / 1000));
END //

DELIMITER ;