/* -----Seed Dependency----- */
CREATE TABLE IF NOT EXISTS `mysql_tbl_6ok4qo` (
    `mysql_tbl_6ok4qo_campaign_id` INT,
    `mysql_tbl_6ok4qo_channel` INT,
    `mysql_tbl_6ok4qo_budget` INT,
    `mysql_tbl_6ok4qo_start_date` DATE,
    `mysql_tbl_6ok4qo_end_date` DATE
);

CREATE TABLE IF NOT EXISTS `mysql_tbl_3u7xox` (
    `mysql_tbl_3u7xox_conversion_id` INT,
    `mysql_tbl_3u7xox_campaign_id` INT,
    `mysql_tbl_3u7xox_conversion_value` INT
);

INSERT INTO `mysql_tbl_6ok4qo` (`mysql_tbl_6ok4qo_campaign_id`, `mysql_tbl_6ok4qo_channel`, `mysql_tbl_6ok4qo_budget`, `mysql_tbl_6ok4qo_start_date`, `mysql_tbl_6ok4qo_end_date`) VALUES (1, 1, 1, '2024-01-01', '2024-01-01');

INSERT INTO `mysql_tbl_3u7xox` (`mysql_tbl_3u7xox_conversion_id`, `mysql_tbl_3u7xox_campaign_id`, `mysql_tbl_3u7xox_conversion_value`) VALUES (1, 2, 3);

/* -----Table Dependencies----- */
CREATE TABLE IF NOT EXISTS `mysql_tbl_9mmx9u` (
    `mysql_tbl_9mmx9u_customer_id` INT,
    `mysql_tbl_9mmx9u_country` INT
);

INSERT INTO `mysql_tbl_9mmx9u` (`mysql_tbl_9mmx9u_customer_id`, `mysql_tbl_9mmx9u_country`) VALUES (1, 1);

CREATE TABLE IF NOT EXISTS `mysql_tbl_gw4545` (
    mysql_tbl_gw4545_emp_no INT,
    mysql_tbl_gw4545_first_name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS `mysql_tbl_ipo9dq` (
    mysql_tbl_ipo9dq_emp_no INT,
    mysql_tbl_ipo9dq_salary DECIMAL(10,2)
);

INSERT INTO `mysql_tbl_gw4545` (`mysql_tbl_gw4545_emp_no`, `mysql_tbl_gw4545_first_name`) VALUES (10001, 'Georgi');

INSERT INTO `mysql_tbl_ipo9dq` (`mysql_tbl_ipo9dq_emp_no`, `mysql_tbl_ipo9dq_salary`) VALUES (10001, 60117);

INSERT INTO `mysql_tbl_ipo9dq` (`mysql_tbl_ipo9dq_emp_no`, `mysql_tbl_ipo9dq_salary`) VALUES (10001, 62102);

INSERT INTO `mysql_tbl_ipo9dq` (`mysql_tbl_ipo9dq_emp_no`, `mysql_tbl_ipo9dq_salary`) VALUES (10001, 66074);

CREATE TABLE IF NOT EXISTS `mysql_tbl_o4nvxj` (
    `mysql_tbl_o4nvxj_customer_id` INT,
    `mysql_tbl_o4nvxj_plan_type` VARCHAR(50),
    `mysql_tbl_o4nvxj_monthly_cost` DECIMAL(10,2),
    `mysql_tbl_o4nvxj_start_date` DATE,
    `mysql_tbl_o4nvxj_status` VARCHAR(50)
);

INSERT INTO `mysql_tbl_o4nvxj` (`mysql_tbl_o4nvxj_customer_id`, `mysql_tbl_o4nvxj_plan_type`, `mysql_tbl_o4nvxj_monthly_cost`, `mysql_tbl_o4nvxj_start_date`, `mysql_tbl_o4nvxj_status`) VALUES (1, 'test', 1.0, '2024-01-01', 'test');

CREATE TABLE IF NOT EXISTS `mysql_tbl_gqhw7p` (
    `mysql_tbl_gqhw7p_department_id` INT,
    `mysql_tbl_gqhw7p_salary` INT
);

INSERT INTO `mysql_tbl_gqhw7p` (`mysql_tbl_gqhw7p_department_id`, `mysql_tbl_gqhw7p_salary`) VALUES (1, 1);

CREATE TABLE IF NOT EXISTS `mysql_tbl_yn4fo7` (
    `mysql_tbl_yn4fo7_customer_id` INT,
    `mysql_tbl_yn4fo7_status` VARCHAR(50)
);

INSERT INTO `mysql_tbl_yn4fo7` (`mysql_tbl_yn4fo7_customer_id`, `mysql_tbl_yn4fo7_status`) VALUES (1, 'test');

CREATE TABLE IF NOT EXISTS `mysql_tbl_aufz3y` (mysql_tbl_aufz3y_id INT, mysql_tbl_aufz3y_name VARCHAR(100), mysql_tbl_aufz3y_email VARCHAR(100));

CREATE TABLE IF NOT EXISTS `mysql_tbl_u2o1dk` (
    `mysql_tbl_u2o1dk_country` INT
);

INSERT INTO `mysql_tbl_u2o1dk` (`mysql_tbl_u2o1dk_country`) VALUES (1);

CREATE TABLE IF NOT EXISTS `mysql_tbl_aolj2w` (
    `mysql_tbl_aolj2w_supplier_id` INT,
    `mysql_tbl_aolj2w_supplier_rating` DECIMAL(3,1)
);

INSERT INTO `mysql_tbl_aolj2w` (`mysql_tbl_aolj2w_supplier_id`, `mysql_tbl_aolj2w_supplier_rating`) VALUES (1, 1.0);

CREATE TABLE IF NOT EXISTS `mysql_tbl_e3wklg` (
    `mysql_tbl_e3wklg_product_id` INT,
    `mysql_tbl_e3wklg_category_id` INT,
    `mysql_tbl_e3wklg_price` DECIMAL(10,2)
);

INSERT INTO `mysql_tbl_e3wklg` (`mysql_tbl_e3wklg_product_id`, `mysql_tbl_e3wklg_category_id`, `mysql_tbl_e3wklg_price`) VALUES (1, 2, 1.0);

CREATE TABLE IF NOT EXISTS `mysql_tbl_4vk36o` (
    `mysql_tbl_4vk36o_supplier_id` INT,
    `mysql_tbl_4vk36o_supplier_rating` DECIMAL(3,1)
);

INSERT INTO `mysql_tbl_4vk36o` (`mysql_tbl_4vk36o_supplier_id`, `mysql_tbl_4vk36o_supplier_rating`) VALUES (1, 1.0);

CREATE TABLE IF NOT EXISTS `mysql_tbl_q6h3oj` (
    `mysql_tbl_q6h3oj_policy_id` INT,
    `mysql_tbl_q6h3oj_customer_id` INT,
    `mysql_tbl_q6h3oj_policy_type` VARCHAR(50),
    `mysql_tbl_q6h3oj_premium_annual` INT,
    `mysql_tbl_q6h3oj_coverage_amount` DECIMAL(10,2),
    `mysql_tbl_q6h3oj_claim_count` INT
);

CREATE TABLE IF NOT EXISTS `mysql_tbl_10xng6` (
    `mysql_tbl_10xng6_claim_id` INT,
    `mysql_tbl_10xng6_policy_id` INT,
    `mysql_tbl_10xng6_claim_date` DATE,
    `mysql_tbl_10xng6_claim_amount` DECIMAL(10,2),
    `mysql_tbl_10xng6_status` VARCHAR(50)
);

INSERT INTO `mysql_tbl_q6h3oj` (`mysql_tbl_q6h3oj_policy_id`, `mysql_tbl_q6h3oj_customer_id`, `mysql_tbl_q6h3oj_policy_type`, `mysql_tbl_q6h3oj_premium_annual`, `mysql_tbl_q6h3oj_coverage_amount`, `mysql_tbl_q6h3oj_claim_count`) VALUES (1, 2, 'test', 4, 1.0, 6);

INSERT INTO `mysql_tbl_10xng6` (`mysql_tbl_10xng6_claim_id`, `mysql_tbl_10xng6_policy_id`, `mysql_tbl_10xng6_claim_date`, `mysql_tbl_10xng6_claim_amount`, `mysql_tbl_10xng6_status`) VALUES (1, 2, '2024-01-01', 1.0, 'test');

CREATE TABLE IF NOT EXISTS `mysql_tbl_t3y59r` (
    `mysql_tbl_t3y59r_monthly_cost` DECIMAL(10,2)
);

INSERT INTO `mysql_tbl_t3y59r` (`mysql_tbl_t3y59r_monthly_cost`) VALUES (1.0);

CREATE TABLE IF NOT EXISTS `mysql_tbl_v606go` (
    `mysql_tbl_v606go_emp_id` INT,
    `mysql_tbl_v606go_department_id` INT
);

INSERT INTO `mysql_tbl_v606go` (`mysql_tbl_v606go_emp_id`, `mysql_tbl_v606go_department_id`) VALUES (1, 1);

CREATE TABLE IF NOT EXISTS `mysql_tbl_5bu7gq` (
    `mysql_tbl_5bu7gq_product_id` INT,
    `mysql_tbl_5bu7gq_category_id` INT,
    `mysql_tbl_5bu7gq_price` DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS `mysql_tbl_jk3ngq` (
    `mysql_tbl_jk3ngq_category_id` INT,
    `mysql_tbl_jk3ngq_name` VARCHAR(50)
);

INSERT INTO `mysql_tbl_5bu7gq` (`mysql_tbl_5bu7gq_product_id`, `mysql_tbl_5bu7gq_category_id`, `mysql_tbl_5bu7gq_price`) VALUES (1, 2, 1.0);

INSERT INTO `mysql_tbl_jk3ngq` (`mysql_tbl_jk3ngq_category_id`, `mysql_tbl_jk3ngq_name`) VALUES (1, 'test');

CREATE TABLE IF NOT EXISTS `mysql_tbl_eppqhm` (
    `mysql_tbl_eppqhm_order_id` INT,
    `mysql_tbl_eppqhm_customer_id` INT,
    `mysql_tbl_eppqhm_total_amount` DECIMAL(10,2)
);

INSERT INTO `mysql_tbl_eppqhm` (`mysql_tbl_eppqhm_order_id`, `mysql_tbl_eppqhm_customer_id`, `mysql_tbl_eppqhm_total_amount`) VALUES (1, 2, 1.0);

CREATE TABLE IF NOT EXISTS `mysql_tbl_gub1v2` (
    `mysql_tbl_gub1v2_cdecimal` DECIMAL(10,0)
);

INSERT INTO `mysql_tbl_gub1v2` (`mysql_tbl_gub1v2_cdecimal`) VALUES (42);

/* -----Procedure Dependencies----- */
/* -----Procedure MYSQL_FUNC_CALCULATE_PRICE_COMPETITIVENESS_INDEX_1ybrx2----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_PRICE_COMPETITIVENESS_INDEX_1ybrx2(PRODUCT_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_PRICE DECIMAL(10,2) DEFAULT 0.00;
    DECLARE V_CATEGORY_AVG DECIMAL(10,2) DEFAULT 0.00;
    DECLARE V_COMPETITIVENESS INT DEFAULT 0;

    SELECT COALESCE(mysql_tbl_5bu7gq_PRICE, 0)
    INTO V_PRICE
    FROM `mysql_tbl_5bu7gq`
    WHERE mysql_tbl_5bu7gq_PRODUCT_ID = PRODUCT_ID_PARAM;

    SELECT COALESCE(AVG(mysql_tbl_5bu7gq_PRICE), 1)
    INTO V_CATEGORY_AVG
    FROM `mysql_tbl_5bu7gq`
    WHERE mysql_tbl_5bu7gq_CATEGORY_ID = (SELECT mysql_tbl_5bu7gq_CATEGORY_ID FROM `mysql_tbl_5bu7gq` WHERE mysql_tbl_5bu7gq_PRODUCT_ID = PRODUCT_ID_PARAM);

    SET V_COMPETITIVENESS = (V_CATEGORY_AVG * 100) / V_PRICE;

    RETURN FLOOR(V_COMPETITIVENESS);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_DEPARTMENT_CONCENTRATION_SCORE_qdkbxy----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_DEPARTMENT_CONCENTRATION_SCORE_qdkbxy(DEPARTMENT_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_DEPT_COUNT INT DEFAULT 0;
    DECLARE V_TOTAL_COUNT INT DEFAULT 0;

    SELECT COUNT(*)
    INTO V_DEPT_COUNT
    FROM `mysql_tbl_v606go`
    WHERE mysql_tbl_v606go_DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    SELECT COUNT(*)
    INTO V_TOTAL_COUNT
    FROM `mysql_tbl_v606go`;

    IF V_TOTAL_COUNT = 0 THEN
        RETURN 0;
    END IF;

    RETURN (V_DEPT_COUNT * 100) / V_TOTAL_COUNT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SANITIZE_INPUT_1v2j5i----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SANITIZE_INPUT_1v2j5i(INPUT_STRING INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_RESULT INT DEFAULT 0;
    DECLARE V_CHAR_POS INT DEFAULT 1;
    DECLARE V_CHAR_VAL INT;
    DECLARE V_INPUT_LEN INT DEFAULT 0;
    DECLARE V_DANGER_COUNT INT DEFAULT 0;
    DECLARE V_DANGEROUS_CHARS VARCHAR(10) DEFAULT '''"'';--';

    SET V_INPUT_LEN = CHAR_LENGTH(INPUT_STRING);

    WHILE V_CHAR_POS <= V_INPUT_LEN DO
        SET V_CHAR_VAL = ASCII(SUBSTRING(INPUT_STRING, V_CHAR_POS, 1));

        IF V_CHAR_VAL IN (39, 34, 59, 45, 45) THEN
            SET V_DANGER_COUNT = V_DANGER_COUNT + 1;
        END IF;

        IF V_CHAR_VAL < 32 OR V_CHAR_VAL > 126 THEN
            SET V_DANGER_COUNT = V_DANGER_COUNT + 1;
        END IF;

        SET V_CHAR_POS = V_CHAR_POS + 1;
    END WHILE;

    RETURN V_DANGER_COUNT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FUNC_172_SELECT_DISTINCTROW_t851hi----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FUNC_172_SELECT_DISTINCTROW_t851hi() RETURNS INT DETERMINISTIC
BEGIN
    DECLARE SEL_COUNT INT DEFAULT 0;
    
    SELECT DISTINCTROW STATUS INTO @mysql_synth_dummy FROM `mysql_tbl_vxwz6y`;
    SET SEL_COUNT = SEL_COUNT + 1;
    
    SELECT DISTINCT STATUS, CREATED_AT INTO @mysql_synth_dummy FROM `mysql_tbl_vxwz6y`;
    SET SEL_COUNT = SEL_COUNT + 1;
    
    RETURN SEL_COUNT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_HANDLER_FUNC_AVG_TWO_mydyy1----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_HANDLER_FUNC_AVG_TWO_mydyy1(P_A INT, P_B INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_RESULT INT;
    DECLARE V_ERROR INT DEFAULT 0;

    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET V_ERROR = 1;

    SET V_RESULT = (P_A + P_B) / 2;

    IF V_ERROR = 1 THEN
        RETURN -1;
    END IF;

    RETURN V_RESULT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_TRIANGLE_AREA_6lastw----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_TRIANGLE_AREA_6lastw(A INT, B INT, C INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_S DECIMAL(10,2) DEFAULT 0.00;
    DECLARE V_AREA DECIMAL(10,2) DEFAULT 0.00;

    IF A + B <= C OR B + C <= A OR A + C <= B THEN
        RETURN ((MYSQL_FUNC_CALCULATE_PRICE_COMPETITIVENESS_INDEX_1ybrx2(-70)) - (0) + 0);
    END IF;

    SET V_S = MYSQL_FUNC_CALCULATE_DEPARTMENT_CONCENTRATION_SCORE_qdkbxy(-34);
    SET V_AREA = MYSQL_FUNC_HANDLER_FUNC_AVG_TWO_mydyy1(13, -15);

    RETURN ((MYSQL_FUNC_SANITIZE_INPUT_1v2j5i(6)) - (0) + (((MYSQL_FUNC_FUNC_172_SELECT_DISTINCTROW_t851hi()) - (0) + (FLOOR(V_AREA)))));
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_DEPARTMENT_AVG_SALARY_3l80bl----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_DEPARTMENT_AVG_SALARY_3l80bl(DEPARTMENT_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_AVG DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(AVG(mysql_tbl_gqhw7p_SALARY), 0)
    INTO V_AVG
    FROM `mysql_tbl_gqhw7p`
    WHERE mysql_tbl_gqhw7p_DEPARTMENT_ID = DEPARTMENT_ID_PARAM;

    RETURN ((MYSQL_FUNC_CALCULATE_TRIANGLE_AREA_6lastw(90, 8, -37)) - (0) + (FLOOR(V_AVG)));
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_INSURANCE_RISK_SCORE_kuk7lq----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_INSURANCE_RISK_SCORE_kuk7lq(POLICY_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_PREMIUM_ANNUAL INT DEFAULT 0;
    DECLARE V_COVERAGE_AMOUNT INT DEFAULT 0;
    DECLARE V_CLAIM_COUNT INT DEFAULT 0;
    DECLARE V_TOTAL_CLAIMS_AMOUNT INT DEFAULT 0;
    DECLARE V_CLAIMS_TO_PREMIUM_RATIO DECIMAL(5,2) DEFAULT 0.00;
    DECLARE V_RISK_SCORE INT DEFAULT 0;

    SELECT COALESCE(mysql_tbl_q6h3oj_PREMIUM_ANNUAL, 0), COALESCE(mysql_tbl_q6h3oj_COVERAGE_AMOUNT, 0), COUNT(*)
    INTO V_PREMIUM_ANNUAL, V_COVERAGE_AMOUNT, V_CLAIM_COUNT
    FROM `mysql_tbl_q6h3oj` P
    LEFT JOIN `mysql_tbl_10xng6` C ON mysql_tbl_q6h3oj_POLICY_ID = mysql_tbl_10xng6_POLICY_ID AND mysql_tbl_10xng6_STATUS = 'APPROVED'
    WHERE mysql_tbl_q6h3oj_POLICY_ID = POLICY_ID_PARAM
    GROUP BY mysql_tbl_q6h3oj_POLICY_ID;

    SELECT COALESCE(SUM(mysql_tbl_10xng6_CLAIM_AMOUNT), 0)
    INTO V_TOTAL_CLAIMS_AMOUNT
    FROM `mysql_tbl_10xng6`
    WHERE mysql_tbl_10xng6_POLICY_ID = POLICY_ID_PARAM AND mysql_tbl_10xng6_STATUS = 'APPROVED';

    IF V_PREMIUM_ANNUAL > 0 THEN
        SET V_CLAIMS_TO_PREMIUM_RATIO = (V_TOTAL_CLAIMS_AMOUNT * 1.0) / V_PREMIUM_ANNUAL;
    END IF;

    SET V_RISK_SCORE = (V_CLAIM_COUNT * 20) + (V_CLAIMS_TO_PREMIUM_RATIO * 50);

    IF V_COVERAGE_AMOUNT > 1000000 THEN
        SET V_RISK_SCORE = V_RISK_SCORE + 15;
    END IF;

    RETURN LEAST(V_RISK_SCORE, 100);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FUNC_134_CREATE_TABLE_od9xcd----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FUNC_134_CREATE_TABLE_od9xcd() RETURNS INT DETERMINISTIC
BEGIN
    DECLARE TBL_COUNT INT DEFAULT 0;
    
    CREATE TABLE IF NOT EXISTS `mysql_tbl_6dj92q` (mysql_tbl_6dj92q_ID INT PRIMARY KEY, mysql_tbl_6dj92q_NAME VARCHAR(50));
    SET TBL_COUNT = TBL_COUNT + 1;
    
    CREATE TABLE IF NOT EXISTS `mysql_tbl_zcud00` (mysql_tbl_zcud00_ID INT);
    SET TBL_COUNT = TBL_COUNT + 1;
    
    CREATE TEMPORARY TABLE TEMP_TABLE (DATA VARCHAR(100));
    SET TBL_COUNT = TBL_COUNT + 1;
    
    RETURN TBL_COUNT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FUNC_012_DATE_EXTRACT_q5mm31----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FUNC_012_DATE_EXTRACT_q5mm31() RETURNS INT DETERMINISTIC
BEGIN
    DECLARE EXTRACT_COUNT INT DEFAULT 0;
    
    SELECT MONTH(NOW());
    SET EXTRACT_COUNT = EXTRACT_COUNT + 1;
    
    SELECT DAY(NOW());
    SET EXTRACT_COUNT = EXTRACT_COUNT + 1;
    
    SELECT HOUR(NOW());
    SET EXTRACT_COUNT = EXTRACT_COUNT + 1;
    
    SELECT MINUTE(NOW());
    SET EXTRACT_COUNT = EXTRACT_COUNT + 1;
    
    SELECT SECOND(NOW());
    SET EXTRACT_COUNT = EXTRACT_COUNT + 1;
    
    RETURN EXTRACT_COUNT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_SUPPLIER_STAR_RATING_sepavs----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_SUPPLIER_STAR_RATING_sepavs(SUPPLIER_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_RATING DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(mysql_tbl_4vk36o_SUPPLIER_RATING, 3.0)
    INTO V_RATING
    FROM `mysql_tbl_4vk36o`
    WHERE mysql_tbl_4vk36o_SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(V_RATING);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_COST_jcd9pn----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_COST_jcd9pn(CUSTOMER_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_COST INT DEFAULT 0;

    SELECT COALESCE(mysql_tbl_t3y59r_MONTHLY_COST, 0)
    INTO V_COST
    FROM `mysql_tbl_t3y59r`
    WHERE CUSTOMER_ID = CUSTOMER_ID_PARAM;

    RETURN V_COST;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_SUBSCRIPTION_HEALTH_SCORE_f4iv4x----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_SUBSCRIPTION_HEALTH_SCORE_f4iv4x(CUSTOMER_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_PLAN_TYPE VARCHAR(20) DEFAULT 'BASIC';
    DECLARE V_MONTHLY_COST INT DEFAULT 0;
    DECLARE V_TENURE_MONTHS INT DEFAULT 0;
    DECLARE V_HEALTH_SCORE INT DEFAULT 0;

    SELECT mysql_tbl_o4nvxj_PLAN_TYPE, COALESCE(mysql_tbl_o4nvxj_MONTHLY_COST, 0), TIMESTAMPDIFF(MONTH, mysql_tbl_o4nvxj_START_DATE, CURDATE())
    INTO V_PLAN_TYPE, V_MONTHLY_COST, V_TENURE_MONTHS
    FROM `mysql_tbl_o4nvxj`
    WHERE mysql_tbl_o4nvxj_CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SET V_HEALTH_SCORE = (MYSQL_FUNC_CALCULATE_SUPPLIER_STAR_RATING_sepavs(47));

    CASE V_PLAN_TYPE
        WHEN 'ENTERPRISE' THEN SET V_HEALTH_SCORE = MYSQL_FUNC_FUNC_134_CREATE_TABLE_od9xcd();
        WHEN 'PREMIUM' THEN SET V_HEALTH_SCORE = MYSQL_FUNC_FUNC_012_DATE_EXTRACT_q5mm31();
        WHEN 'BASIC' THEN SET V_HEALTH_SCORE = V_HEALTH_SCORE + 10;
    END CASE;

    RETURN ((MYSQL_FUNC_CALCULATE_INSURANCE_RISK_SCORE_kuk7lq(-1)) - (0) + ((MYSQL_FUNC_CALCULATE_COST_jcd9pn(3)) - (0) + V_HEALTH_SCORE));
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_SIGNAL_PROC_INSERT_USER_ixieiy----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_SIGNAL_PROC_INSERT_USER_ixieiy(USER_NAME INT, mysql_tbl_aufz3y_EMAIL INT) RETURNS INT DETERMINISTIC
BEGIN
    IF USER_NAME IS NULL OR USER_NAME = '' THEN
        SIGNAL SQLSTATE '23000' SET MESSAGE_TEXT = 'USERNAME IS REQUIRED';
    END IF;
    IF mysql_tbl_aufz3y_EMAIL IS NULL OR mysql_tbl_aufz3y_EMAIL = '' THEN
        SIGNAL SQLSTATE '23000' SET MESSAGE_TEXT = 'mysql_tbl_aufz3y_EMAIL IS REQUIRED';
    END IF;
    INSERT INTO `mysql_tbl_aufz3y` (`mysql_tbl_aufz3y_NAME`, `mysql_tbl_aufz3y_EMAIL`) VALUES (USER_NAME, mysql_tbl_aufz3y_EMAIL);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_SUBSCRIPTION_ACTIVE_CHECK_9rsk67----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_SUBSCRIPTION_ACTIVE_CHECK_9rsk67(CUSTOMER_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_COUNT INT DEFAULT 0;

    SELECT COUNT(*)
    INTO V_COUNT
    FROM `mysql_tbl_yn4fo7`
    WHERE mysql_tbl_yn4fo7_CUSTOMER_ID = CUSTOMER_ID_PARAM AND mysql_tbl_yn4fo7_STATUS = 'ACTIVE';

    RETURN CASE WHEN V_COUNT > 0 THEN 1 ELSE 0 END;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_POWER_y2j5yj----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_POWER_y2j5yj(BASE INT, EXPONENT INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_RESULT INT DEFAULT 1;
    DECLARE V_COUNTER INT DEFAULT 0;

    IF EXPONENT < 0 THEN
        RETURN 0;
    END IF;

    POWER_LOOP: WHILE V_COUNTER < EXPONENT DO
        SET V_RESULT = MYSQL_FUNC_CALCULATE_SUBSCRIPTION_ACTIVE_CHECK_9rsk67(56);
        SET V_COUNTER = MYSQL_FUNC_SIGNAL_PROC_INSERT_USER_ixieiy(-15, 84);
    END WHILE POWER_LOOP;

    RETURN V_RESULT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FLOW_CONTROL_FUNC_CASE_NULL_CHECK_s92jh9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FLOW_CONTROL_FUNC_CASE_NULL_CHECK_s92jh9(VAL INT) RETURNS VARCHAR(20) DETERMINISTIC
BEGIN
    CASE
        WHEN VAL IS NULL THEN RETURN MYSQL_FUNC_CALCULATE_POWER_y2j5yj(-51, -39);
        WHEN VAL = 0 THEN RETURN MYSQL_FUNC_CALCULATE_DEPARTMENT_AVG_SALARY_3l80bl(89);
        WHEN VAL > 0 THEN RETURN 'POSITIVE';
        WHEN VAL < 0 THEN RETURN MYSQL_FUNC_CALCULATE_SUBSCRIPTION_HEALTH_SCORE_f4iv4x(5);
    END CASE;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_SUPPLIER_QUALITY_INDEX_doj4wl----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_SUPPLIER_QUALITY_INDEX_doj4wl(SUPPLIER_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_RATING DECIMAL(3,1) DEFAULT 0.0;

    SELECT COALESCE(mysql_tbl_aolj2w_SUPPLIER_RATING, 3.0)
    INTO V_RATING
    FROM `mysql_tbl_aolj2w`
    WHERE mysql_tbl_aolj2w_SUPPLIER_ID = SUPPLIER_ID_PARAM;

    RETURN FLOOR(V_RATING * 20);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_COUNTRY_SUBSCRIPTION_INDEX_pr8gj9----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_COUNTRY_SUBSCRIPTION_INDEX_pr8gj9(COUNTRY_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_SUBSCRIBED INT DEFAULT 0;

    SELECT COUNT(DISTINCT S.CUSTOMER_ID)
    INTO V_SUBSCRIBED
    FROM SUBSCRIPTIONS S
    JOIN `mysql_tbl_9mmx9u` C ON S.CUSTOMER_ID = mysql_tbl_9mmx9u_CUSTOMER_ID
    WHERE mysql_tbl_9mmx9u_COUNTRY = COUNTRY_PARAM;

    RETURN ((MYSQL_FUNC_CALCULATE_SUPPLIER_QUALITY_INDEX_doj4wl(1)) - (0) + V_SUBSCRIBED);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_FUNC_031_DATE_MAKE_2p04w3----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_FUNC_031_DATE_MAKE_2p04w3() RETURNS INT DETERMINISTIC
BEGIN
    DECLARE DATE_COUNT INT DEFAULT 0;
    
    SELECT MAKEDATE(2024, 100);
    SET DATE_COUNT = DATE_COUNT + 1;
    
    SELECT MAKETIME(12, 30, 45);
    SET DATE_COUNT = DATE_COUNT + 1;
    
    SELECT MICROSECOND(NOW(6));
    SET DATE_COUNT = DATE_COUNT + 1;
    
    SELECT PERIOD_ADD(202401, 1);
    SET DATE_COUNT = DATE_COUNT + 1;
    
    SELECT PERIOD_DIFF(202402, 202401);
    SET DATE_COUNT = DATE_COUNT + 1;
    
    RETURN DATE_COUNT;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_PROC_DECIMAL_zozmya----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_PROC_DECIMAL_zozmya() RETURNS INT DETERMINISTIC
BEGIN
    DECLARE RESULT INT;
    SELECT CAST(mysql_tbl_gub1v2_CDECIMAL AS SIGNED) INTO RESULT FROM `mysql_tbl_gub1v2` LIMIT 1;
    RETURN COALESCE(RESULT, 0);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_CUSTOMER_REVENUE_SHARE_u7vfyi----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_CUSTOMER_REVENUE_SHARE_u7vfyi(CUSTOMER_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_CUSTOMER_REVENUE DECIMAL(10,2) DEFAULT 0.00;
    DECLARE V_TOTAL_REVENUE DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(mysql_tbl_eppqhm_TOTAL_AMOUNT), 0)
    INTO V_CUSTOMER_REVENUE
    FROM `mysql_tbl_eppqhm`
    WHERE mysql_tbl_eppqhm_CUSTOMER_ID = CUSTOMER_ID_PARAM;

    SELECT COALESCE(SUM(mysql_tbl_eppqhm_TOTAL_AMOUNT), 0)
    INTO V_TOTAL_REVENUE
    FROM `mysql_tbl_eppqhm`;

    IF V_TOTAL_REVENUE = 0 THEN
        RETURN 0;
    END IF;

    RETURN FLOOR((V_CUSTOMER_REVENUE * 100) / V_TOTAL_REVENUE);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_DISCOUNT_rxl9cd----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_DISCOUNT_rxl9cd(AGE INT) RETURNS INT DETERMINISTIC
BEGIN
  IF AGE < 15 THEN RETURN 0;
  ELSEIF AGE < 30 THEN RETURN 10;
  ELSEIF AGE < 50 THEN RETURN 20;
  ELSE RETURN 30;
  END IF;
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_CATEGORY_REVENUE_SHARE_5yg16j----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_CATEGORY_REVENUE_SHARE_5yg16j(CATEGORY_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_CATEGORY_REVENUE DECIMAL(10,2) DEFAULT 0.00;
    DECLARE V_TOTAL_REVENUE DECIMAL(10,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(OI.QUANTITY * OI.UNIT_PRICE), 0)
    INTO V_CATEGORY_REVENUE
    FROM `mysql_tbl_ydk8ku` OI
    JOIN `mysql_tbl_e3wklg` P ON OI.PRODUCT_ID = mysql_tbl_e3wklg_PRODUCT_ID
    WHERE mysql_tbl_e3wklg_CATEGORY_ID = CATEGORY_ID_PARAM;

    SELECT COALESCE(SUM(QUANTITY * UNIT_PRICE), 0)
    INTO V_TOTAL_REVENUE
    FROM `mysql_tbl_ydk8ku`;

    IF V_TOTAL_REVENUE = 0 THEN
        RETURN ((MYSQL_FUNC_CALCULATE_CUSTOMER_REVENUE_SHARE_u7vfyi(-49)) - (((MYSQL_FUNC_PROC_DECIMAL_zozmya()) - (0) + 0)) + 0);
    END IF;

    RETURN ((MYSQL_FUNC_DISCOUNT_rxl9cd(78)) - (0) + (FLOOR((V_CATEGORY_REVENUE * 100) / V_TOTAL_REVENUE)));
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_CALCULATE_COUNTRY_SCORE_f2t6li----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_COUNTRY_SCORE_f2t6li(COUNTRY_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_COUNT INT DEFAULT 0;

    SELECT COUNT(*)
    INTO V_COUNT
    FROM `mysql_tbl_u2o1dk`
    WHERE mysql_tbl_u2o1dk_COUNTRY = COUNTRY_PARAM;

    RETURN ((MYSQL_FUNC_CALCULATE_CATEGORY_REVENUE_SHARE_5yg16j(49)) - (0) + V_COUNT);
END //

DELIMITER ;

/* -----Procedure MYSQL_FUNC_EMP_AVG_SALARY_5keii4----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_EMP_AVG_SALARY_5keii4(P_EMP_NO INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE AVG_SALARY INT;
    
    SELECT CAST(AVG(mysql_tbl_ipo9dq_SALARY) AS UNSIGNED) INTO AVG_SALARY
    FROM `mysql_tbl_gw4545` E 
    JOIN `mysql_tbl_ipo9dq` S ON mysql_tbl_gw4545_EMP_NO = mysql_tbl_ipo9dq_EMP_NO
    WHERE mysql_tbl_gw4545_EMP_NO = P_EMP_NO;
    
    RETURN ((MYSQL_FUNC_CALCULATE_COUNTRY_SCORE_f2t6li(-76)) - (0) + ((MYSQL_FUNC_FUNC_031_DATE_MAKE_2p04w3()) - (0) + AVG_SALARY));
END //

DELIMITER ;

/* -----Synthesized Procedure----- */
DELIMITER //

CREATE FUNCTION MYSQL_FUNC_CALCULATE_MARKETING_MIX_SCORE_laxoeq(CAMPAIGN_ID_PARAM INT) RETURNS INT DETERMINISTIC
BEGIN
    DECLARE V_CHANNEL VARCHAR(20) DEFAULT 'ORGANIC';
    DECLARE V_BUDGET INT DEFAULT 0;
    DECLARE V_REVENUE INT DEFAULT 0;
    DECLARE V_MIX_SCORE INT DEFAULT 0;

    SELECT mysql_tbl_6ok4qo_CHANNEL, COALESCE(mysql_tbl_6ok4qo_BUDGET, 0)
    INTO V_CHANNEL, V_BUDGET
    FROM `mysql_tbl_6ok4qo`
    WHERE mysql_tbl_6ok4qo_CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    SELECT COALESCE(SUM(mysql_tbl_3u7xox_CONVERSION_VALUE), 0)
    INTO V_REVENUE
    FROM `mysql_tbl_3u7xox`
    WHERE mysql_tbl_3u7xox_CAMPAIGN_ID = CAMPAIGN_ID_PARAM;

    CASE V_CHANNEL
        WHEN 'PAID' THEN SET V_MIX_SCORE = (MYSQL_FUNC_FLOW_CONTROL_FUNC_CASE_NULL_CHECK_s92jh9(9));
        WHEN 'ORGANIC' THEN SET V_MIX_SCORE = MYSQL_FUNC_CALCULATE_COUNTRY_SUBSCRIPTION_INDEX_pr8gj9(59) * 3;
        WHEN 'SOCIAL' THEN SET V_MIX_SCORE = (V_REVENUE * 150) / GREATEST(V_BUDGET, 1);
        ELSE SET V_MIX_SCORE = V_REVENUE;
    END CASE;

    RETURN ((MYSQL_FUNC_EMP_AVG_SALARY_5keii4(-89)) - (0) + V_MIX_SCORE);
END //

DELIMITER ;

/* -----Call Statement----- */
SELECT MYSQL_FUNC_CALCULATE_MARKETING_MIX_SCORE_laxoeq(1);